### ISSUE TITLE
warrior mace spec bug

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#1000]
**Description:**
the talent for warrior mace specialisation isn't giving rage on proc

**Current behaviour:**
mace spec procs and stuns target, no rage gen
**Expected behaviour:**
mace spec procs and generates 7 rage

**Steps to reproduce the problem:**
hit a target with a mace till it procs, you will see no rage generation on your rage bar or as a popup when you have show energy gains as status text, or in the combat log

**Comment by plutonium447** [comment]
OJ, you need to include a screencap to give this issue a little more context. Go out and replicate the issue and screencap it, then post it here. There we can see what conditions are causing the issue in a little more detail.

Include a link to the specific talent you are refering to, from http://db.hellfire-tbc.com/ or https://www.wowdb.com/ , just as examples.

And finally include the revision number of the server at the time the issue occured.
This can be done by typing:

.server info

into your chat in-game. Then just copy + paste what you get.

**Comment by oj449** [comment]
http://db.hellfire-tbc.com/?spell=12704
the spell, although it's saying 70 when it should be 7 for some reason there.
the video attached shows me using slam, which costs 15 rage, to hit the target and my rage goes from 19 to 4 as mace spec procs, so i should have generated 7 rage and hit 11 rage.
[2019-04-04 21-14-12.zip](https://github.com/thebarrensissues/Issues/files/3043165/2019-04-04.21-14-12.zip)

**Comment by kelno** [comment]
Fixed with 11379
