### ISSUE TITLE
executes seem to be eaten with nothing shown in log

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#1002]
**Description:**
executes sometimes show nothing happening after use, and is consumed
**Current behaviour:**
execute a mob, sometimes it will work correctly sometimes nothing will occur for damage or failed damage, and nothing will show in the combat log for that execute, and the mob will take no damage.
**Expected behaviour:**
execute a mob, shows something, ie damage or failed attack floating text, as well as showing up in the combat log
**Steps to reproduce the problem:**
execute a few times, 20+ and watch for the combat log and damage text, it should show sometimes to not seem to work.

**Comment by plutonium447** [comment]
OJ, you need to include a screencap of the combat log showing that executes are not being correctly applied.
Include a link to the specific rank of Execute you are using, from http://db.hellfire-tbc.com/ or https://www.wowdb.com/ for instance.
And finally, include the revision number.

**Comment by kelno** [comment]
Maybe this happens when the ability fail to hit, could be a combat log problem

**Comment by oj449** [comment]
rank 7 execute :
http://db.hellfire-tbc.com/?spell=25236
what should happen if execute fails to hit, is that the base rage cost of execute is used, 15, and not the excess rage that would be used on a successful hit. usually that is what happens when execute is dodged and such, however sometimes what happens is execute seems to disappear and eat all your rage, as shown in the video
[execute eaten.zip](https://github.com/thebarrensissues/Issues/files/3043195/execute.eaten.zip)

**Comment by kelno** [comment]
Nice, thanks for the details

**Comment by oj449** [comment]
i think this bug might have something to do with how execute is being coded currently, as i have noticed recently that when you use bloodthirst which gives a buff that gives you 30 hp per melee hit with 5 stacks, and then use execute, you will gain 30x2 hp and use 2 stacks of the buff, so it seems execute is being coded as 2 hits somehow, perhaps due to how it has the base rage cost and excess rage cost, so maybe those are 2 seperate hits pushed into 1, and if say the base rage part hits the target but the excess part misses hiddenly, then execute fails to perform correctly and eats all your rage with nothing happening?

**Comment by kelno** [comment]
Tested now, it happens when the spell miss, but no message is shown. This is a combat log issue.

**Comment by kelno** [comment]
Fixed with 11385

**Comment by kelno** [comment]
Apparently wasn't completely fixed, 
Updated with 11428
