### ISSUE TITLE
[NPC] - G'eras missing from Shattrath

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1003]
**Description:**

G'eras is missing from his spot around the middle ring in Shattrath (Badge of justice Vendor)

**Current behaviour:**

G'eras is missing from his spot around the middle ring in Shattrath (Badge of justice Vendor)

**Expected behaviour:**

https://www.wowhead.com/npc=18525/geras

![image](https://user-images.githubusercontent.com/38281939/55513436-62e6be00-56b1-11e9-9a4d-0a84cf443c91.png)

![image](https://user-images.githubusercontent.com/38281939/55513467-7b56d880-56b1-11e9-8c0f-257ee819080d.png)

**Steps to reproduce the problem:**

CHANGEME
1. Go to where he should be in karazhan

![image](https://user-images.githubusercontent.com/38281939/55513508-99bcd400-56b1-11e9-986a-0ade0ed67723.png)

**Comment by Jerrythemagicdog** [comment]
He's added in patch 2.2
https://www.wowhead.com/npc=18525/geras
The Barrens are running patch 2.0

**Comment by hufsa** [comment]
I really think he was added earlier than 2.2 even though that's what Wowhead says. I'm pretty sure he used to be on the "main floor" until a later time (im not sure when he's moved "upstairs"). But I'm very sure he should be there from day one. I'll try to find some sources on this.

**Comment by Cheelout** [comment]
Jerry already verified and pushed fix for this :) Thanks though Hufsa!

**Comment by hufsa** [comment]
"Previously G'eras was located in front of the western alcove in the central dome, but was moved to the walkway above it in Patch 2.4.0"

https://wowwiki.fandom.com/wiki/G%27eras

**Comment by hufsa** [comment]
Didn't read the edit lul. Okay, good.
