### ISSUE TITLE
Shattered Halls incorrect reputation

### ISSUE THREAD

**Issue by Gredsta** [thebarrensissues/Issues#1004]
**Description:**

Slime mobs in the tunnel before first boss incorrectly give 55 reputation per kill.

**Current behaviour:**

Both the Creeping Ooze id 17356, and the Creeping Oozeling id 17357 located in the sewer tunnel immediately before first boss in Shattered Halls Normal reward 55 Honor Hold reputation per kill. Unsure of the true value however 55 is far too high. In addtion, the Oozelings will respawn on a 4 minute time, without the larger Ooze also doing so. This makes them easily farmable by a single player for approximately 2.5k rep per 4 minutes.

**Expected behaviour:**

Both mobs should reward less reputation and not respawn as frequently.

**Steps to reproduce the problem:**

Step 1. Enter Shattered Halls, clear to the slime tunnel.
Step 2. Clear the tunnel, note reputation gained.
Step 3. Wait 4 minutes for 17357 to respawn, clear again and note rep gained.
Step 4. Step 3 infinitely repeatable.

**rev. hash/commit:** 

Rev 10850 (f4bd229634c7+)

**Comment by Jerrythemagicdog** [comment]
Fixed in 10851
