### ISSUE TITLE
Door after chest event is closeable then unable to be reopened

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#1006]
**Description:**

The door which is the exit for chess event is clickable after it opens when event is successfully completed

**Current behaviour:**

Door to exit the chess event is able to be clicked and closes permanently once clicked

**Expected behaviour:**

Door should open and stay open once chess event is complete. It should not be clickable.

**Steps to reproduce the problem:**

CHANGEME
1. Complete chess event successfully
2. Watch exit door open
3. Click exit door
4. Door will remain closed

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/55532751-95ff7080-56f6-11e9-964a-7d509f43e485.png)

**Comment by kelno** [comment]
Fixed in 11528 (4b0972c7b46737fff79adf7c0ef13aad0bbe4e59)
