### ISSUE TITLE
Unable to master loot items - Too far away from that corpse

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1008]
**Description:**

When master loot is used, you cannot loot, it gives you Too far way from that corpse
Changing to another loot system does not resolve after Master loot is used, have to keep on group loot to loot items.

**Current behaviour:**

When master loot is used, you cannot loot, it gives you Too far way from that corpse
Changing to another loot system does not resolve after Master loot is used, have to keep on group loot to loot items.

**Expected behaviour:**

Should be able to loot items to anyone in the group with master loot

**Steps to reproduce the problem:**

CHANGEME
1. Create raid
2. Set to ML
3. Try and loot

![image](https://user-images.githubusercontent.com/38281939/55551103-abd85a00-5725-11e9-9454-5ed804793721.png)

**Comment by kelno** [comment]
Fixed with 10889
