### ISSUE TITLE
[Heroics] Last boss loot

### ISSUE THREAD

**Issue by artieau** [thebarrensissues/Issues#1012]
**Description:**

The last boss of a Heroic dungeon should drop 2 items and 1 Primal Nether.

**Current behaviour:**

The last boss of a heroic is dropping only 1 item and 1 Nether

**Expected behaviour:**

The last boss should drop 2 x item and 1 x Primal Nether.
One of the 2 x item rolls has a chance to be from the Epic item table (this feature is Patch appropriate while the 2 items is TBC whole time)
See from 1:35
https://youtu.be/WBZWQlPi5fg?t=95

**Steps to reproduce the problem:**

CHANGEME
1. Kill last boss of a Heroic dungeon such as The Black Stalk - NPC 17882
2. Only 1 Blue item drop and 1 Primal Nether
3. cri

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/55555449-075c1500-5731-11e9-8566-f8ce431e7a41.png)

**Comment by Cheelout** [comment]
wip

**Comment by Cheelout** [comment]
Fixed in next update.
