### ISSUE TITLE
[paladin] Retribution Aura scaling with spellpower

### ISSUE THREAD

**Issue by plutonium447** [thebarrensissues/Issues#1015]
**Description:**
Retribution aura damage is multiple times higher than it should be, hitting for several hundreds of damage instead of the base described in the spell tooltip text.
This may be caused by the spell scaling its damage with spellpower.

**Current behaviour:**
Retribution aura damage is incorrect because it is scaling with spellpower.

![Screenshot from 2019-04-05 07-36-04](https://user-images.githubusercontent.com/40911527/55591086-000c2a00-5778-11e9-850a-bef56e124a0c.png)

![Screenshot from 2019-04-05 07-36-16](https://user-images.githubusercontent.com/40911527/55591097-03071a80-5778-11e9-8cb5-d53f03276c2c.png)

**Expected behaviour:**
Retribution aura should not scale with any stat at all.

**Steps to reproduce the problem:**

1. Be paladin
2. Cast Retirbution aura
3. Attack a melee type mob
4. get hit by the mob
5. notice incorrect retribution aura damage

**rev. hash/commit:**
10866

**id's**
[spell] Retribution Aura (27150) http://db.hellfire-tbc.com/?spell=27150

**Comment by Jerrythemagicdog** [comment]
Fixed in 10902
