### ISSUE TITLE
Arcane Vortex - Zapthrottle Mote Extractor

### ISSUE THREAD

**Issue by Paralol** [thebarrensissues/Issues#1017]
**Description:**

Zapthrottle mote extractor doesn't work on the Arcane Vortex in Netherstorm.

**Current behaviour:**

Arcane Vortex (17408) are spawning and you can channel on them using the Zapthrottle Mote Extractor however it does not despawn or give motes of mana.

**Expected behaviour:**

At the end of the channel you should get around 3-5 motes of mana and the Arcane Vortex despawns.

**Steps to reproduce the problem:**

1. Find Arcane Vortex in Netherstorm. 1 spawns in the middle of Area 52
2. Use Zapthrottle Mote Extractor on it.
3. Watch channel complete with no motes given at the end.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/4516769/55599795-b3871580-579c-11e9-8bfc-0d263da855b0.png)

**Comment by giveusmezpls** [comment]
hello yes i can also no slurp these, need slurp for primal mana

please fix for slurp

**Comment by pewpewlaserz** [comment]
Can confirm no workey.

**Comment by artieau** [comment]
@kelno .replay play Nobugs

**Comment by kelno** [comment]
Fixed with 11197

**Comment by Harrock1** [comment]
Broken again, as is Felmist (SMV), Windy Clound (Nagrand) and Swamp Gas (Zangamarsh)

Sunstrider rev. 11530 (36f875f830b3+)

**Comment by kelno** [comment]
Indeed that's a recent regression from 5 days ago.
Fixed again in 11547.
