### ISSUE TITLE
[WARLOCK] Felguard will not move to attack NPC

### ISSUE THREAD

**Issue by cursedbitcoin** [thebarrensissues/Issues#1019]
**Description:**

Warlock pet Felguard will not move to attack NPCs when ordered to, unless intercept is off cooldown (it will only move to intercept and run back to the warlock).

**Current behaviour:**

Warlock commands attack, Felguard will not move unless intercept is off cooldown. It will be aggressive and attack NPC but only when it is near the warlock or after having intercepted.
To get the felguard to move you have to press follow command.

**Expected behaviour:**

Felguard should run to attack the NPC when commanded to even when intercept is off cooldown. It should also not stand idly in place when warlock is moving unless it is attacking an NPC OR when commanded to stay.

**Steps to reproduce the problem:**

Felguard - NPC #17252
![revhash2](https://user-images.githubusercontent.com/48847635/55600752-3615d200-57a9-11e9-8e7c-16de152b6808.png)

**rev. hash/commit:**

**Comment by Cheelout** [comment]
Not occuring for other players.

**Comment by cursedbitcoin** [comment]
it's occurring for 2 other locks in my guild, still a problem for me, could you help me fix it please?

**Comment by Cheelout** [comment]
Message me on discord - Mode
