### ISSUE TITLE
Gift of the wild rank3

### ISSUE THREAD

**Issue by Davethedruid** [thebarrensissues/Issues#1030]
**Description:**

Gift of the wild rank 3 stacks with any lower level gift of the wild for full benefit of both as long as lower spell cast first.

**Current behaviour:**

Can get gift of wild rank 2 and 3 stacked by casting 2 first. Both benefits stack

**Expected behaviour:**

only one gift of the wild should be able to be currently applied

**Steps to reproduce the problem:**

CHANGEME
1. Step 1 Cast gift of wild rank 2
2. Step 2 cast gift of wild rank 3
3. Step 3 You have both buffs and stacked benefits of both.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by kelno** [comment]
Fixed with 10893
