### ISSUE TITLE
[Druid] Natural Shapeshifter does not provide permanent shapeshifting mana cost reductions.

### ISSUE THREAD

**Issue by Zeuaireus** [thebarrensissues/Issues#1031]
Description:

Natural Shapeshifter does not provide permanent shapeshifting mana cost reductions for rank 2 and 3.

Current behaviour:

Natural Shapeshifter does not provide permanent shapeshifting mana cost reductions for rank of 2 and 3. (10/20/30% based on allocated talent points) If you apply the talent points, you will immediately see the reductions being applied to Bear Form and Cat Form.

However, roughly 8 to 10 seconds later, after allocation points to rank 2 or rank 3, the mana cost reduction is gone and the cost of shapeshifting has been returned to the full cost. Being that my character is level 70, the cost of shapeshifting in to Dire Bear form is 829 without and talent points allocated.

Expected behaviour:

Reduces the mana cost of all shapeshifting by x% of allocated point. (10/20/30% based on allocated talent points) This effect should be permanent for all ranks with the correct points allocated.

Assuming you are level 70 and without any points allocated; Dire Bear Form mana cost will be 829.
	- Assuming you are level 70 and with One point allocated, Dire Bear Form mana cost will be 746.
	- Assuming you are level 70 and with Two points allocated, Dire Bear Form mana cost will be 663.
	- Assuming you are level 70 and with Three points allocated, Dire Bear Form mana cost will be 580.

Steps to reproduce the problem:

   - Be a Druid and talent into Natural Shapeshifter located in the Restoration Tree. 
	- Check to see changes after each point is applied.
	- Wait 8 to 10 seconds and then check to see if the cost mana reduction is still applied to shapeshifting forms by mousing over the shapeshifting spell on your hotbar after allocating points. (ie Dire Bear Form, Cat Form.) 

	Additional Notes.
	Character was and was not wearing any armour at the time of testing issue in Darnassus. 
	
	The original issues was discovered after logging out and then logging back in by another member in the guild.
	
	However, after further testing the issue, I have discovered the issue happens only seconds after talent points have been allocated. But it does correctly work with Rank 1.
	An in-game timer was also used to check the timing of mana cost changes for each rank to confirm issue.

	Talent Details.
	http://db.hellfire-tbc.com/?spell=16833		Natural Shapeshifter Rank 1
	http://db.hellfire-tbc.com/?spell=16834		Natural Shapeshifter Rank 2	(Duration should be the same as Rank 1.)
	http://db.hellfire-tbc.com/?spell=16835		Natural Shapeshifter Rank 3	(Duration should be the same as Rank 1.)

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/49328610/55664388-56a06380-585f-11e9-92f3-309768bd7df0.png)

**Comment by kelno** [comment]
Good catch

**Comment by kelno** [comment]
Fixed with 10894
