### ISSUE TITLE
[Item] Assassination Armor (2) set procing incorrectly

### ISSUE THREAD

**Issue by giveusmez** [thebarrensissues/Issues#1032]
**Description:**

Level 70 rogue dungeon set; Assassination Armor (2) set is procing far more than intended. This is a big problem because these abilities are not intended to be usable in most raids, and are able to be used for an insane damage boost rogues should not have access to.

**Current behaviour:**

Assassination Armor (2) set is procing off many rogue abilities as opposed to just kidney shot and cheap shot.

**Expected behaviour:**

Assassination Armor (2) set should proc only off of kidney shot and cheap shot.

**Steps to reproduce the problem:**

Equip any (2) pieces of Assassination Armor on a rogue and use rogue abilities,

**rev. hash/commit:** 

ID: 28414 helm https://db.excalibur.ws/?item=28414
ID: 27776 shoulders https://db.excalibur.ws/?item=27776
ID: 28204 chest https://db.excalibur.ws/?item=28204
ID: 27509 gloves https://db.excalibur.ws/?item=27509
ID: 27908 legs https://db.excalibur.ws/?item=27908

![hashblabla](https://user-images.githubusercontent.com/49213988/55666537-072c5880-589c-11e9-9d79-fdb31c0f02cd.png)

**Comment by kelno** [comment]
Fixed with 10888

**Comment by kelno** [comment]
89b39efc86cd84ffffdc6200bc6b0308a4238a7d
