### ISSUE TITLE
Leveling Cooking

### ISSUE THREAD

**Issue by Veshoi** [thebarrensissues/Issues#1034]
**Description:**

Cooking skill, all recipes are grey at 275/300 skill level. 

**Current behaviour:**

 All recipes options within Cooking profession are grey.

**Expected behaviour:**

According to all research I have done (leveling guides etc) at least 3 recipes should be yellow or green and be able to level.

**Steps to reproduce the problem:**

CHANGEME
1. Click on Cooking (Artisan) profession  
2. Look at recipes
3. Step 3

![Cooking](https://user-images.githubusercontent.com/49338610/55668423-a148cc80-58ad-11e9-9287-f5ceb8a68169.PNG)

**Comment by Cheelout** [comment]
Yes you generally have to get recipes from a quest / random drop to get to 300 cooking.
