### ISSUE TITLE
[dungeon] Arcatraz last boss incorrect start trigger

### ISSUE THREAD

**Issue by plutonium447** [thebarrensissues/Issues#1036]
**Description:**
The last boss of the Arcatraz dungeon has the wrong encounter trigger, which causes the fight to start when players come within ~40 yards of the NPC. The fight should instead start when a player directly attacks the NPC.

https://youtu.be/vyh208QHxbs?t=1143
reference video-^

**Current behaviour:**
Combat with Warden Mellichar will begin when players come within ~40 yards of the boss.

![Screenshot from 2019-04-06 22-13-12](https://user-images.githubusercontent.com/40911527/55669933-ac592800-58c0-11e9-9401-aa1278d02300.png)
_players were about 40 yards away from the boss, and did not attack it at all_

**Expected behaviour:**
Combat should only start with the boss when players directly attack the NPC.

**Steps to reproduce the problem:**

1. Go the Arcatraz
2. Complete the instance except for the last boss
3. Approach the last boss
4. Notice that the fight begins immediately, without needing to attack him.

**rev. hash/commit:** 
**10884**

**id's**
[npc] Warden Mellichar (20904) http://db.hellfire-tbc.com/?npc=20904

**Comment by Jerrythemagicdog** [comment]
The source you provided is from a private server (Excalibur-wow.) The behavior implemented now is similar / the same to retail (we went there to check.)
