### ISSUE TITLE
Heroism and Besital Wrath Invalid target (Server wide)

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#1038]
**Description:**

Attempting to cast Heroism or Bestial Wrath results in 'Invalid target'. This is server wide

**Current behaviour:**

Attempting to cast Heroism or Bestial Wrath fails and simply says 'Invalid Target'

**Expected behaviour:**

Both spells should cast without issue.

**Steps to reproduce the problem:**

CHANGEME
1. Log on to The barrens and attempt to cast either spell Heroism or Bestial Wrath.
2. Invalid target will appear and fail to cast the spells

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/35262513/55676871-85304400-591c-11e9-8ec8-3fb954babfe8.png)

**Comment by kelno** [comment]
Fixed with 10902
