### ISSUE TITLE
Felguard and Succbus not going into melee.

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#1039]
**Description:**

Felguard is currently not going close enough to begin attacking and just stands around 20 yards away from the mob, never engaging it.

**Current behaviour:**

Attacking with felguard results in the pet simply standing around 20 yards away never attacking.

**Expected behaviour:**

Felguard should run closer to the mob until it is able to attack.

**Steps to reproduce the problem:**

CHANGEME
1. Summon felguard
2. Attack mob without intercept on autocast
3. felguard will just look at the mob without engaging

Note that I have turned autocast intercept off because when it is on it will engage the mob, however it still backs out afterwards. In addition intercept has a cd of 30 secs and is not viable to wait for it every time simply to get the pet to work.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/55676926-4484fa80-591d-11e9-9e6a-4c728a4eebf6.png)

**Comment by nuitari-barrens** [comment]
I'm having this issue as well.
I've tried clearing cache and WDB, disabled all addons etc.
Noticed it will **sometimes** reset to working properly when mounting and dismounting, but after riding some more it will bug again.
Have tried it with and without intercept enabled, pet stance doesn't affect it either.

Probably unrelated: Felguard is also not showing a weapon, still hits as normal. Re-equipping spellpower weapon doesn't fix.

**Comment by qoth** [comment]
Updated to note that this is affecting Succubs as well, but no other pets.

**Comment by qoth** [comment]
To reproduce on fresh server restart and fresh login.

1. summon felguard, attack mob. Results = attacks mob normally
2. Mount up, run a small distance and dismount
3. attack with felguard, will see it stands and looks at mob around 20 yrds away

**Comment by kelno** [comment]
Fixed with Fixed with 10903
