### ISSUE TITLE
Boat from Auberdine to Exodar not working

### ISSUE THREAD

**Issue by Desparto** [thebarrensissues/Issues#1041]
**Description:**
Boat from Auberdine to Exodar does not appear at dock

**Current behaviour:**

The boat pulls into view but before it gets to the dock it completely disappears and doesn't allow you to board.

**Expected behaviour:**

Boat should appear allowing you to travel to Exodar

**Steps to reproduce the problem:**

Stand on the dock. 
Wait infinitely.

**rev. hash/commit:** 
10898

**Comment by kelno** [comment]
Same as https://github.com/thebarrensissues/Issues/issues/445
I'll close this one but thanks for this specific instance, it will probably help
