### ISSUE TITLE
[Buff] Scrolls stacking with class abilities

### ISSUE THREAD

**Issue by LoshyFirestorm** [thebarrensissues/Issues#1043]
**Description:**

Scrolls of Spirit, Stamina, Int etc are stacking with class buffs.

**Current behaviour:**

Scrolls are stacking with class buffs, for example below:

Scroll of Intellect V stacks with Arcane Intellect Rank 6.

**Expected behaviour:**

Arcane Intellect (and other class buffs) should overwrite the scroll buff if the class buff provides more.

**Steps to reproduce the problem:**

CHANGEME
1. Cast Arcane Intellect Rank 6 on a person
2. Cast Scroll of Intellect V on the same person

**rev. hash/commit:** 

![ServerInfo70419](https://user-images.githubusercontent.com/43313533/55681197-b5043980-5966-11e9-815a-d2304a7c9228.png)

**Comment by kelno** [comment]
Fixed
