### ISSUE TITLE
Retribution Aura

### ISSUE THREAD

**Issue by Kazrid** [thebarrensissues/Issues#1044]
**Description:**

Retribution aura does not work if you block and it does not work if the mob uses a special ability, i.e backstab, heroic strike, mortal strike. Basically, it only works if the mob hits you with it's auto attack.

**Current behaviour:**

Read above
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

Retribution aura should deal damage EVERY time a mob strikes you physically, whether you block or not. Not just on auto attacks, but on all attacks.

**Steps to reproduce the problem:**

1. Be a paladin
2. Apply retribution aura
3. Slap on a shield and find a mob with multiple attacks to whack you for a while.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

![Screenshot_5](https://user-images.githubusercontent.com/26983073/55686769-4e195d00-5933-11e9-8a17-6757744c9287.png)
![Screenshot_6](https://user-images.githubusercontent.com/26983073/55686776-5bcee280-5933-11e9-88c5-1f07aec59947.png)
Notice the mob does not take damage when they backstab me and when I block, only when they auto attack.

**Comment by kelno** [comment]
Currently it will not return damage on full block.
Can you provide a source telling it should?

**Comment by Kazrid** [comment]
Did some looking into it, doesn't seem like it works on full blocks, my bad.

**Comment by kelno** [comment]
Thanks!
