### ISSUE TITLE
[Mage] Molten Fury does not correctly increase damage of all spells against targets with less than 20% health.

### ISSUE THREAD

**Issue by Zeuaireus** [thebarrensissues/Issues#1045]
**Description:**

Molten Fury does not correctly increase damage of all spells against targets with less than 20% health.

**Current behaviour:**

Molten Fury does not correctly increase damage of all spells against targets with less than 20% health. (10/20% based on allocated talent points) 
Currently it appears to reduce the damage of spells and slightly increases the damage on some spells. It also doesn't give the full bonus % amount of damage stated in the talents description.

**Expected behaviour:**

Molten Fury increases damage of all spells against targets with less than 20% health by 10/20% based on allocated talent points. 

**Steps to reproduce the problem:**

- Be a mage and talent into Molten Fury located in the Fire Tree. 
	- Check to see damage changes after each point is applied, both before and after with a npc below 20% HP. (For all Spell Classes)
	

**Additional Notes:**

    - Character was level 54, no buffs, and was and was not wearing any armour at the time of testing issue in Stormwind and in Blasted Lands. 
    - The target was a Target Dummy in Stormwind to begin with. Further extended testing was done with level 54 Orges located in Blasted lands.
    - No damage increase talents were used during all testing, excluding Improved Scorch. 
    - It has also been confirmed that having improved Scorch does increase damage like it is supposed to for fire spells. But once you allocate point into Molten Fury, no further damage increase is applied.
    - The issue was also discovered by a mage member in the guild.

    - Character damage with no gear, no talents allocated into Molten Fury and using only Scorch: 271 Highest Non-crit. Test 1
    - Character damage with no gear, no talents allocated into Molten Fury and using only Scorch: 271 Highest Non-crit. Test 2

    - Character damage with no gear, one talent point allocated into Molten Fury and using only Scorch: 271 Highest Non-crit. Test 1
    - Character damage with no gear, one talent point allocated into Molten Fury and using only Scorch: 272 Highest Non-crit. Test 2

    - Character damage with no gear, one talent point allocated into Molten Fury and using only Arcane Missile: 85 (Flat Damage). Test 1
    - Character damage with no gear, one talent point allocated into Molten Fury and using only Arcane missile: 85 (Flat Damage). Test 2

    - Character damage with no gear, two talent points allocated into Molten Fury and using only Arcane Missile: 85 (Flat Damage). Test 1
    - Character damage with no gear, two talent points allocated into Molten Fury and using only Arcane Missile: 85 (Flat Damage). Test 2

    - Character damage with no gear, two talent points allocated into Molten Fury and using only Scorch: 278 Highest Non-crit. Test 1
    - Character damage with no gear, two talent points allocated into Molten Fury and using only Scorch: 276 (261/276/270) Highest Non-crit. Test 2

    - Character damage with gear, two talent points allocated into Molten Fury and using only Fireball: 689 Highest Non-crit. (705 without Molten Fury) Test 1
    - Character damage with gear, two talent points allocated into Molten Fury and using only Fireball: 625 Highest Non-crit. (718 without Molten Fury) Test 2.
 
	It has also been confirmed that having improved Scorch does increase damage, but once you allocate point into Molten Fury, no damage increase is applied.

  - **Talent Details.**
http://db.hellfire-tbc.com/?spell=31679		Molten Fury Rank 1
http://db.hellfire-tbc.com/?spell=31680		Molten Fury Rank 2	

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/49328610/55688770-25cf4400-59af-11e9-98a7-17bca875e307.png)

**Comment by Jerrythemagicdog** [comment]
thanks for all the research and numbers here.

**Comment by giveusmezpls** [comment]
Also this spell appears to proc Clearcasting upon taking damage ....

**Comment by kelno** [comment]
Fixed with 11242
