### ISSUE TITLE
NPC Boulderfist Mage has no spell/magic abilities

### ISSUE THREAD

**Issue by mrqiksta** [thebarrensissues/Issues#1047]
**Description:**
NPC https://wotlk.evowow.com/?npc=17137 Boulderfist mage in Nagrand has no ranged/spell abilities

**Current behaviour:**

NPC will run to player and melee attack only

**Expected behaviour:**

Should use the following spells:
9672
20795
6742

**Steps to reproduce issue**

1. Step 1 Aggro NPC
2. Step 2 Observe it run to player and melee attack

**rev. hash/commit:** 

10910

**Comment by Jerrythemagicdog** [comment]
Fixed in 10916
