### ISSUE TITLE
Manticron cubes - Magtheridon

### ISSUE THREAD

**Issue by Desparto** [thebarrensissues/Issues#1049]
**Description:**
One of the manticron cubes during the Magtheridon encounter stopped working last night. It worked fine for the first few pulls but halfway through our second to last pull could no longer be clicked causing the raid to wipe for that attempt and our final pull. The cube still retained a golden cog showing it was clickable but clicking on it did nothing. This cube was first on your left as you walk through the door into Magtheridons room. The wipe prior to the cube breaking, this same cube was not clicked during a Blast Wave while all other four were. I'm not sure if this is related as the cube was still clickable for the first two blast waves of the next attempt and broke before the third blast wave but it is possible, or could simply be a coincidence. 

**Current behaviour:**

Cube stops being clickable, due to some unknown reason meaning blast wave cannot be interrupted on Magtheridon.

**Expected behaviour:**

All five cubes should be clickable allowing blast wave to be stopped. 

**Steps to reproduce the problem:**

CHANGEME
1. Complete pulls on Magtheridon and at some stage the cube(s?) will stop working. May be related to clicking all other cubes except this one during blast wave on previous pulls but may also not be.

**Comment by Cheelout** [comment]
This has not reoccured since @kelno

**Comment by kelno** [comment]
Nothing changed here so I expect there might still be an issue
