### ISSUE TITLE
[Item] Drakefist Hammer/Dragonmaw/Dragonstrike procrate/ICD

### ISSUE THREAD

**Issue by giveusmez** [thebarrensissues/Issues#1051]
**Description:**

[28437] Drakefist Hammer and its upgrade chain's (Dragonmaw/Dragonstrike) haste proc; 
[Chance on Hit: Increase your haste rating by 212 for 10 sec.]
is behaving incorrectly as well as having an incorrect slot restriction of main hand and unique before 2.4.2.

**Current behaviour:**

[28437] Drakefist Hammer and its upgrade chain's proc currently have no internal cooldown and an extremely high proc rate, leading to the proc being up the vast majority of the duration of combat
while being the one handed variant from 2.4.2.

**Expected behaviour:**

[28437] Drakefist Hammer should either have a high proc rate and a high internal cooldown, or
a low proc rate and no internal cooldown if it follows almost any other proc related burning
crusade weapon. Also not one handed. 

This post;
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/1045 talks about 
the main hand requirement and quotes Elitist jerks and models the procs per minute at 1.4 
with no internal cooldown.

**Steps to reproduce the problem:**

Item: https://db.excalibur.ws/?item=28437
Step 1: Equip 2 drakefist hammers
Step 2: Swing 2 drakefist hammers (preferably on a rogue/warrior/class that can abuse many swings)
Step 3: Observe insane irreplaceable weapon

**rev. hash/commit:** 

![serverinfoblabla2](https://user-images.githubusercontent.com/49213988/55720915-4f3aaf00-5a45-11e9-8922-dbe13b8034ad.png)

**Comment by Jerrythemagicdog** [comment]
Fixed in 10916
Changed it to 1.4ppm as per sources provided and 
https://docs.google.com/spreadsheets/d/11E1k1Di_enrJHOvH992EKBqCoAU7IQPpba6tQJkkQ9M/edit#gid=115069182
