### ISSUE TITLE
[Druid] Aquatic Form Breaks When Jumping

### ISSUE THREAD

**Issue by zemfi** [thebarrensissues/Issues#1052]
**Description:**

As the title suggests

**Current behaviour:**

Be in aquatic form, then 'jump' (spacebar) brings you out of form back to caster; while underwater

**Expected behaviour:**

Should not breakform, until you reach the surface.

**Steps to reproduce the problem:**

CHANGEME
1. Be in aquatic form deep underwater
2. Jump
3. Suddenly out of form?!

**rev. hash/commit:** 

.rev 10910

**Comment by kelno** [comment]
Related to last changes about water detection

**Comment by kelno** [comment]
Fixed with 10924
