### ISSUE TITLE
[dungeon] naga distiller can be interrupted

### ISSUE THREAD

**Issue by plutonium447** [thebarrensissues/Issues#1053]
**Description:**
The Naga Distiller object/npc can be interrupted, preventing its cast of Warlord's Rage

**Current behaviour:**
Players are able to interrupt the Naga Distiller object/npc.

**Expected behaviour:**
The Warlord's Rage spell cast by the Naga Distiller object/npc should be un-interruptable.

**Steps to reproduce the problem:**

CHANGEME
1. Go the Heroic Steamvaults
2. Engage the last boss, Warlod Kalithresh
3. Pull him over to one of the naga distillers
4. When the naga distiller casts Warlord's Rage, use an ability like; Cheap Shot, Counterspell, Hammer of Justice.
5. Notice that the naga distiller's spell is interrupted

I was not able to find a reliable source for this mechanic, but i am reasonable certain that having a major boss mechanic be trivialised is not not intended.

This bug has only been seen on the Heroic mode version of Steamvaults.

**rev. hash/commit:** 
**10913**

**id's**
[npc] Naga Distiller (20631) http://db.hellfire-tbc.com/?npc=20631
[npc] Warlord Kalithresh (20633) http://db.hellfire-tbc.com/?npc=20633
[spell] Warlord's Rage (31543) http://db.hellfire-tbc.com/?spell=31543

**Comment by kelno** [comment]
Fixed
