### ISSUE TITLE
[dungeon] coilfang scale-healer's holy nova spell hits players many times per second

### ISSUE THREAD

**Issue by plutonium447** [thebarrensissues/Issues#1057]
**Description:**
When fighting Coilfang Scale-Healer mobs, it will sometimes cast Holy Nova and strike players multiple times per cast.

**Current behaviour:**
Coilfang Scale-Healer's Holy Nova hits player multiple times per cast.

![Screenshot from 2019-04-09 08-17-10](https://user-images.githubusercontent.com/40911527/55765873-26520280-5ab5-11e9-8dc4-b0013162d30e.png)

**Expected behaviour:**
Coilfang Scale-Healer's Holy Nova should only hit players once per cast.

**Steps to reproduce the problem:**

1. Go to Heroic The Slave Pens
2. Find a Coilfang Scale-Healer mob
3. Attack the mob
4. Wait for it to cast Holy Nova.
5. Notice you have been hit multiple times per cast.

This issue has only been seen in the Heroic mode verison of The Slave Pens.

**rev. hash/commit:** 
**10913**

**id's**
[npc] Coilfang Scale-Healer (21842) http://db.hellfire-tbc.com/?npc=21842
[spell] Holy Nova (37669) http://db.hellfire-tbc.com/?spell=37669

**Comment by Jerrythemagicdog** [comment]
Fixed in 10915
