### ISSUE TITLE
Refreshing Power Word: Shield does not Refresh the Damage Absorption Remaining

### ISSUE THREAD

**Issue by priestly1** [thebarrensissues/Issues#1060]
**Description:**

Power World: Shield in TBC does not refresh correctly when re-cast upon yourself before the initial shield has faded/expired/broken through.

**Current behaviour:**
I have re-created this dozens upon dozens of times, reliably repeatable - occurs every time.

1. Cast PW:S on yourself (1000 Damage available to be absorbed)
2. Take 700 of damage (300 Damage remaining to be absorbed)
3. Finish killing Mob A
4. Re-cast PW:S on yourself before it expires (ie. refresh the shield)
5. Start fighting Mob B
6. Note that your freshly refreshed PW:S will BREAK after taking only 300 damage

Video demonstrating issue (excuse the jittery recording)
https://youtu.be/WLTLB__lPK4

**Expected behaviour:**
Re-casting PW:S on yourself before it expires should renew the damage absorption amount too.

CHANGEME
1. http://db.hellfire-tbc.com/?spell=10901

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
Sunstrider rev.10913 (b0a6d889bac1) 2019-04-08 16:22:30 +0200 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by imtrollingu** [comment]
I can vouch for this it happens to me all the time.

**Comment by priestly1** [comment]
Has this issue been assigned a development roadmap or ETA?

**Comment by imtrollingu** [comment]
No idea

**Comment by kelno** [comment]
Fixed with 11038
