### ISSUE TITLE
Magtheridon Quake/blast wave

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#1061]
**Description:**

Magtheridon is currently casting quake whilst casting blast wave. Any quake that is active should be cancelled by a blast wave cast.

**Current behaviour:**

On the 4th blast wave Magtheridon is casting a quake right after beginning his blast wave.

**Expected behaviour:**

Blast wave should prevent any quakes being cast until after it has finished, and it should cancel any active quakes.

Source: https://wowwiki.fandom.com/wiki/Magtheridon_(tactics) 
Under Manticron Cubes -  'after three or four cycles, they happen at nearly the same time (fortunately Blast Wave cancels any active Quake)'

**Steps to reproduce the problem:**

CHANGEME
1. Engage magtheridon
2. Last until the 4th time the cubes need to be clicked
3. Mag will start casting blast wave and 0.5sec after he starts casting he will cast quake.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/55795470-03e8d500-5b07-11e9-8ace-bb7d04118f50.png)

**Comment by hufsa** [comment]
Fixed in scripts repo, 4f669ec

**Comment by Jerrythemagicdog** [comment]
Fixed in 10916
commit https://github.com/kelno/sunstrider-scripts/commit/4f669ec08d33be7fef337120d4c109774b51abb1
