### ISSUE TITLE
[Dungeon] Old Hillsbrad - Lieutenant Drake Heroic

### ISSUE THREAD

**Issue by Paralol** [thebarrensissues/Issues#1064]
**Description:**

Lieutenant Drake hits excessively hard on heroic.

**Current behaviour:**

Damage done to the tank by Lieutenant Drake is excessive. A tank in part T4 is getting killed in seconds.

**Expected behaviour:**

Should be tankable and healable in mid level heroic gear.

**Steps to reproduce the problem:**

1. Enter Old Hillsbrad on heroic
2. Do the Incendiary boxes and which spawns Lieutenant Drake.
3. Fight Lieutenant Drake and get dumpstered.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/4516769/55802580-dc503780-5b1b-11e9-8b3f-cabe0d1ce558.png)

**Comment by Jerrythemagicdog** [comment]
Fixed in 10916
