### ISSUE TITLE
Scryer to Aldor Rep bug

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#1065]
**Description:**
When changing faction from scryer to aldor with rep hand-ins, i become neutral to aldor but stuck on 'at war' in my rep tab, and cant talk to any of the npcs and can attack them.

**Current behaviour:**
I am unable to talk to any aldor npcs and am at war with them in my rep tab, despite being disliked by scryer and neutral with aldor.

**Expected behaviour:**

I should be able to talk to aldor npcs to hand in rep items and not at war with them.

**Steps to reproduce the problem:**

1. Become loyal to scryers in city of light quest.
2. hand in dreadfang venom sacs for rep with aldor until neutral.
3. rep tab shows at war with aldor despite being neutral
4. unable to talk to any aldor npcs.
 
**rev. hash/commit:** 

![WoWScrnShot_040919_234457](https://user-images.githubusercontent.com/47015256/55806562-d9f1db80-5b23-11e9-9c70-b83a417c7655.jpg)

**Comment by Cheelout** [comment]
Fixed with SQL Update.

**Comment by Cheelout** [comment]
UPDATE character_reputation SET flags=83 WHERE  faction IN (932,934) AND standing < 0;
UPDATE character_reputation SET flags=81 WHERE  faction IN (932,934) AND standing > 0;
