### ISSUE TITLE
Magtheridon moving while channelling Quake

### ISSUE THREAD

**Issue by Harrock1** [thebarrensissues/Issues#1066]
**Description:**

Magtheridon is moving when channelling quake

**Current behaviour:**

Magtheridon moves and attacks the highest threat when quake is cast

See: 
[https://clips.twitch.tv/HappyDeliciousPuppyRuleFive](https://clips.twitch.tv/HappyDeliciousPuppyRuleFive)

**Expected behaviour:**

Magtheridon should channel quake ability, then seek the highest theat target on his hate list.

See:
[Curse vs Magtheridon](https://youtu.be/A5Ma8G8ZScc?t=528)

**Steps to reproduce the problem:**

1. Fite giant demon
2. Live past phase 1
3. Get punted while being gut punched

**rev. hash/commit:** 

.rev 10913

**Comment by hufsa** [comment]
Fixed in scripts 4f669ec

**Comment by Jerrythemagicdog** [comment]
Fixed in 10916
commit https://github.com/kelno/sunstrider-scripts/commit/4f669ec08d33be7fef337120d4c109774b51abb1
