### ISSUE TITLE
weapon skill affecting multiple weapons

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#1067]
**Description:**
weapon skill is affecting more than what the type it lists
**Current behaviour:**
certain skill ratings for weapons, such as swords, are also affecting other weapon skill rating, swords affects maces etc

**Expected behaviour:**
swords skill rating and others should only affect the one they list
**Steps to reproduce the problem:**
equip weapon skill rating item, look at stats changing in weapon skill

**Comment by Cheelout** [comment]
Will be resolved when we go to 2.4.3 item stats.
