### ISSUE TITLE
Trainers do not hae many engineering skills that should be available.

### ISSUE THREAD

**Issue by xanthorrea** [thebarrensissues/Issues#1068]
**Description:**

Many crafts that should be available to engineers are not at the trainers or vendors.

**Current behaviour:**

None of the engineer trainers I visited had various crafts I wished to learn.

All engineering trainers in outlands should have various crafts available.  Some are:  The Bigger One (this is required to make the Area52 Dimensional Ripper).  Icy Blasting Primers (this is required to make other items and would have been good to help level eng).   Frost Grenades.  Super Sapper Charge.  Goblin Rocket Launcher.  Flying Machine(!!!  This is a major problem)  Turbo Charged Flying Machine (hmmm, is there an escalation level higher than major problem?)

Also Vendors Viggz Shinesparked (Shattrath) and Yatheon (horde Silvermoon) should have schematics available - Adamantite Rifle, Adamantite Shell Machine that are not available.

Tell us what should happen instead.

These patterns should be available/visible to all engineers.

**Comment by Cheelout** [comment]
You have provided NO source to your claims, a simple google search has netted the following:

The Bigger One - Patch 2.0
Super Sapper Charge - Patch 2.0
Goblin Rocket Launcher - Patch 2.0

Schematic: Adamantite Rifle - Patch 2.1
Icy Blasting Primers - Patch 2.1
Frost Grenade - Patch 2.1

Flying Machine - Patch 2.3
Turbo-Charged Flying Machine - Patch 2.3
Adamantite Shell Machine - Patch 2.3

So really there are 3 crafts - The Bigger One / Super Sapper Charge / Goblin Rocket Launcher that are missing.

For Kelno / Jerry or whichever Dev is looking at this. 

https://www.wowhead.com/item=23827/super-sapper-charge#created-by-spell
https://www.wowhead.com/spell=30558/the-bigger-one
https://www.wowhead.com/spell=30563/goblin-rocket-launcher

**Comment by Paralol** [comment]
Those crafts (The Bigger One / Super Sapper Charge / Goblin Rocket Launcher) are available at the goblin engineering trainer in Gadgetzan.
