### ISSUE TITLE
Haste potions have no effect

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#1069]
**Description:**

Haste potions do nothing when consumed

**Expected behaviour:**

Haste potions should apply haste causing spells to be cast faster

**Steps to reproduce the problem:**

CHANGEME
1. Consume a haste potion and note spell cast time doesnt change 22838 item id for potion

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by Paralol** [comment]
Haste was only melee during TBC.

Wrath of the Lich King Patch 3.0.2 (2008-10-14): Haste Rating now modifies both melee attacks and spells.

**Comment by Jerrythemagicdog** [comment]
it's melee haste, not spell haste.
