### ISSUE TITLE
[NPC] (Heroic) Avatar of the Martyred not dropping loot

### ISSUE THREAD

**Issue by giveusmez** [thebarrensissues/Issues#1075]
**Description:**

ID: 20303 (Heroic) Avatar of the Martyred https://db.excalibur.ws/?npc=20303 from 
Heroic Auchenai Crypts' last boss encounter cannot/does not always(?) access group 1 of his drop table, meaning he cannot/does not drop anything.

**Current behaviour:**

ID: 20303 (Heroic) Avatar of the Martyred does not (always?) drop an item from group 1 of his
loot table. We killed him before killing Exarch Maladaar.

**Expected behaviour:**

ID: 20303 (Heroic) Avatar of the Martyred can access group 1 of his loot table and drops 1 of 6 items.

**Steps to reproduce the problem:**

Step 1: Start Exarch Maladaar encounter in Auchenai Crypts
Step 2: Get Exarch Maladaar to 20%(?) health, so he summons Avatar of the Martyred
Step 3: Kill Avatar of the Martyred and observe (no) loot
Step 4: If he drops loot repeat until no loot

**rev. hash/commit:** 

![serverinfoblabla3](https://user-images.githubusercontent.com/49213988/55956631-be174280-5ca7-11e9-92fe-5a70cb8e83ac.png)
`

**Comment by giveusmezpls** [comment]
This issue should be considered important as he drops pre-bis items for content progression.

**Comment by giveusmezpls** [comment]
is it possible this mob is not lootable because he is a summon? he does act like a summon in that he despawns as soon as the boss dies.
if he is marked as a summon i imagine he is also not lootable due to the nature of the summon tag.... ?

**Comment by kelno** [comment]
His loot table is wrong currently, we're looking into that.

**Comment by Jerrythemagicdog** [comment]
Fixed in 11054
