### ISSUE TITLE
[Heroics] Rep Keys not Required under 70

### ISSUE THREAD

**Issue by Azytheoneandonly** [thebarrensissues/Issues#1079]
**Description:**

So apparently you can zone into heroics without the rep key under 70.

**Current behaviour:**

Currently you do not need the key to zone into heroics under 70. assuming the that it does not check if you are under 70.
Tested 3 instances but assume will work with them all.
Cleared Sethekk Halls and did Mana Tombs first boss.

https://cdn.discordapp.com/attachments/506142909322625034/565919749066850314/unknown.png

**Expected behaviour:**

Rep Key should be required at all times.

**Steps to reproduce the problem:**

1. Go do Sethekk normal  @ lvl 66 for quest xp and leader forgot to change it off heroic
2. for shits and giggles clear it.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/37324574/56015813-aa1e2000-5d3d-11e9-8740-e29df4900ed4.png)

**Comment by kelno** [comment]
On my lvl 58 characters:
https://i.imgur.com/rQLgvTW.png
https://i.imgur.com/TYFUO8u.png

**Comment by Azytheoneandonly** [comment]
I tried again yesterday and it failed to let me in. so i'm not sure.

**Comment by artieau** [comment]
Closing unless someone can share reproduce steps, NailonCore
