### ISSUE TITLE
Implement proper Ritual of Summoning mechanics

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#108]
"Ritual of Summoning": Spell is usable but visuals are wrong. Other players should be casting and wait until the summoning started. Need more details.

Meeting stone as well?

**Comment by Jerrythemagicdog** [comment]
The spell ID for Ritual of Summoning is 46546 which spawns gobject 36727 around 3-5 yards in front of the caster and requires two people to click it to complete the summon. Here's how it looks: https://www.twitch.tv/videos/356410434?t=16m57s
Meeting stones seem to be using the same mechanic but it requires two people - one person clicking the stone (being the summoner) and the other person clicking the portal that spawns on top of the summoner.

**Comment by kelno** [comment]
Thanks!

**Comment by Nqsty** [comment]
From retail: https://www.youtube.com/watch?v=pUS3MOzxRd0

**Comment by Harrock1** [comment]
https://github.com/ValorenWoW/sunstrider-issues/issues/830

Currently how its reacting on production server
