### ISSUE TITLE
Braxxis Staff of Slumber (or maybe all weapons) not providing correct armor to feral druids

### ISSUE THREAD

**Issue by dylbarrenstbc** [thebarrensissues/Issues#1081]
**Description:**

Braxxis Staff of Slumber (item=31186) is only providing 550 armor in dire bear form (spell=9634). As dire bear form receives "400% armor contribution from items" I would expect the armor provided in bear form from this item to be 2200 or more, depending on talents. 

**Steps to reproduce the problem:**

1. Note current armor value in bear form
2. Equip Braxxis Staff of Slumber (item=31186)
3. Note new armor in bear form - it will have increased by 550
![image](https://user-images.githubusercontent.com/47657717/56031932-23c90480-5d64-11e9-9ceb-4f51c73df8de.png)

**Comment by Kaziner** [comment]
#1100 Further info on this ticket (closed due to duplicate)

**Comment by Orcfootstool** [comment]
Violet Signet tank ring also does not contribute the correct amount of armour.

**Comment by kelno** [comment]
Fixed with 11039
