### ISSUE TITLE
Successful Auctions not displaying any information

### ISSUE THREAD

**Issue by zemfi** [thebarrensissues/Issues#1082]
**Description:**

Having a Successful Auction go through, and when you go to recieve the coin from the mail, all the relevant information isnt there.

**Current behaviour:**

As Above

**Expected behaviour:**

The mail you received should have the relevant information (who bought it, prices etc, **even** if xfaction is enabled)

**Steps to reproduce the problem:**

CHANGEME
1. Set An Auction 
2. Have someone else buy it (both on your faction and apposing)
3. No information when you receive the mail :(

Had this now with 5+ successful auctions.

![auction](https://user-images.githubusercontent.com/46832429/56040293-6a752980-5d79-11e9-88c1-0401041c6aec.png)

**rev. hash/commit:** 

.rev 10931

**Comment by kelno** [comment]
Fixed with 11131
