### ISSUE TITLE
[Buff] Hellfire Superiority - Not Showing Flying In

### ISSUE THREAD

**Issue by zemfi** [thebarrensissues/Issues#1083]
**Description:**

Noticed this numerous times now, heres the report. If your side has the 3 required nodes captured, a zone wide buff (#32071) is applied to your faction.

**Current behaviour:**

When you **fly** into Hellfire Peninsula and your side already has the 3 nodes required, you **dont** get the buff. If you walk in/out of the zone, you get the buff.

**Expected behaviour:**

Flying into the zone you should automatically have the buff applied to you.

**Steps to reproduce the problem:**

1. Your side has 3/3 nodes captured in Hellfire gives you a zone wide buff (#32071)
2. Fly into Honor Hold from Shattrath City
3. Notice you have no buff :(
3.1 Further testing i ran out of the zone+back in again and had the buff applied.
3.2 Couldnt test if a relog would work since the server crashed :(

_Furthermore would be recommended to test the other zone wide buffs in Tekkora Forest+Nagrand for this same issue. id's n/a._

**rev. hash/commit:** 

.rev 10931

**Comment by kelno** [comment]
Probably the same issue with other zone buffs yeah.
Relog should work.

**Comment by kelno** [comment]
Fixed with 11051
