### ISSUE TITLE
[Quest] Escape from the Staging Grounds [ID: 10425]

### ISSUE THREAD

**Issue by Septimush** [thebarrensissues/Issues#1084]
**Description:**
Upon accepting the quest and killing nearby mobs, the NPC does not lead an escort path towards quest completion.

**Current behaviour:**

Questgiver Captured Protectorate Vanguard (https://db.excalibur.ws/?npc=20763) will attack nearby mobs as standard with escort quests but once cleared he just paths in a circle where he spawns instead of leading your towards quest hand in NPC. https://i.imgur.com/WLS7Pyb.jpg https://i.imgur.com/yVh9m9U.jpg

I waited for respawn and tried this a 2nd time taking advice from the wowhead comments (https://www.wowhead.com/quest=10425/escape-from-the-staging-grounds) mentioning to kill a mob he fights Etheruem Gladiator (https://db.excalibur.ws/?npc=20854) first before accepting the quest, however this still resulted in him walking in circles.

**Expected behaviour:**

On killing mobs, accepting quest, NPC should head towards quest hand in at Commander Ameer (https://db.excalibur.ws/?npc=20448)

**Steps to reproduce the problem:**

1. Kill mobs attacking Captured Protectorate Vanguard
2. Accept escort quest 'Escape from the Staging Grounds'
3. Kill nearby mobs that attack him

**rev. hash/commit:** 

https://i.imgur.com/EGDjG0v.png

**Comment by kelno** [comment]
Fixed with 11145 (by woiwoz)
