### ISSUE TITLE
Scarab of the infinite cycle

### ISSUE THREAD

**Issue by Desparto** [thebarrensissues/Issues#1085]
**Description:**

This item should proc off only healing spells but currently procs off all spells including buffs.

**Current behaviour:**

As above

**Expected behaviour:**

Should only proc off healing spells

**Steps to reproduce the problem:**

CHANGEME
1. Step 1 Equip
2. Step 2 Cast non healing spells
3. Step 3 See trinket proc

**rev. hash/commit:** 10931

**Comment by plutonium447** [comment]
[item] Scarab of the Infinite Cycle (28190) http://db.hellfire-tbc.com/?item=28190

Also i have experienced this trinket proccing off almost any spell that affects the player, such as:
Eating
Drinking
Creating a healthstone from a soulwell
Being teleported
Casting buffs
Drinking potions

**Comment by Jerrythemagicdog** [comment]
Fixed in 10932
