### ISSUE TITLE
Spinesever

### ISSUE THREAD

**Issue by Desparto** [thebarrensissues/Issues#1086]
**Description:**
This item appears to not be in the game currently (not queryable via Atlasloot)

**Current behaviour:**

Item appears to not be in game

**Expected behaviour:**

Item should be in game - was added patch 2.0.3
https://wow.gamepedia.com/Spinesever_(weapon)

**rev. hash/commit:** 10931

**Comment by Jerrythemagicdog** [comment]
Fixed in 10932
