### ISSUE TITLE
Telaar Inn - Intermittent Resting, inc outside

### ISSUE THREAD

**Issue by zemfi** [thebarrensissues/Issues#1088]
**Description:**

Telaar Inn (54,74) 'Rested' is not working properly (gain exp/instalog)

**Current behaviour:**

Entering/Exiting Telaar Inn randomly sets you as rested, and most of the time doesnt work (ie No rested at all). A few more times i was actually being set way outside the Inn.

**Expected behaviour:**

While you are inside the Inn, you should always get rested.

**Steps to reproduce the problem:**

1. Enter & Exit Telaar Inn, notice that sometimes you will be set as rested, most of the time not. re-logging aswell does nothing.
2. Running around outside your able to find areas where you can get rested, clearly out of the Inn.

![rested](https://user-images.githubusercontent.com/46832429/56073556-93cd9e00-5de9-11e9-8a69-ce5b84e31260.jpg)

Probably related to these aswell: #423 #411 

**rev. hash/commit:** 

.rev 10931

**Comment by kelno** [comment]
Fixed with 11048
