### ISSUE TITLE
Creature damage is too low in many cases

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#1089]
**Description:**
Creature damage is too low in many cases, compared to retail sources (and other servers).
It seems that sometimes the damage modifier is wrong (0.5) (http://tbc.cavernoftime.com/npc=18135) but in other cases it seems to be correct, yet the damage they do to players (tested on a level 62 Rogue with ~2k armor 22.4%) is very low (http://tbc.cavernoftime.com/npc=18131) - these are level 63 creatures that the 62 rogue was able to pull and fight two at a time losing roughly 300 hp (he did not dodge that much).

**Expected behaviour:**
Creature damage should be a bit higher and seems incorrect in many cases, maybe entire world - see examples above.

rev. 10935

**Comment by Jerrythemagicdog** [comment]
Some more examples:
https://db.excalibur.ws/?npc=19852 hits for ~30ish for us (thanks Swidge!)

**Comment by kelno** [comment]
Fixed

**Comment by giveusmezpls** [comment]
Hello friends, is it possible this has affected dungeon mob damage? some feedback the mobs in Durnholde/BlackMorass seem to be doing additional damage which could be related to this change.

**Comment by kelno** [comment]
Yes all creatures will make additional damage with this, they're back to their previous values before a recent change.
Those mobs in Cavern of Times probably need some individual tweaks (rather than a global change like this one)
