### ISSUE TITLE
[Heroic Dungeon] Old Hillsbrad Ending / Level 1 Guards / Friendly mobs (VIDEO)

### ISSUE THREAD

**Issue by HueHueTBCTheBarrens** [thebarrensissues/Issues#1091]
Issues are for problem only, NOT for asking questions.
---> 

**Description:**
Level 1 mobs, Green guards (Script can't continue because guards can't die) 

CHANGEME Description of the problem or issue here.
As above
https://www.youtube.com/watch?v=BcfhmVGMaJU&feature=youtu.be

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**
The mobs not be level 1, they aren't friendly guards in tarren mill (We're humans during the quest), the dragons be red (hostile) not green, the waves spawn 
CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**
1.Run OHB Heroic
2. Get to the 2nd part of the dungeon (after rescuing Thrall, going to Tarren mill)
3. Play through the 2nd half of dungeon
4. look at guard levels, friendly script NPC's (meant to be hostiles) 
5. Video shows it all. 

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`
![image](https://user-images.githubusercontent.com/29525708/56086625-0dbf5f00-5e9e-11e9-96d2-e0944cdb735a.png)

**Comment by kelno** [comment]
Thanks for the video!

**Comment by kelno** [comment]
Fixed!
I'm still working on this instance right now.

**Comment by HueHueTBCTheBarrens** [comment]
Guerrero dead following Don, when the battle starts, the dead body runs towards you then despawns instantly when getting to you. 
![image](https://user-images.githubusercontent.com/29525708/56842602-4c134000-68da-11e9-879e-b793b5b3867b.png)

![image](https://user-images.githubusercontent.com/29525708/56842627-a0b6bb00-68da-11e9-874d-b8abd1325d19.png)

**Comment by HueHueTBCTheBarrens** [comment]
You can re-talk to thrall over and over from his part near the trees, and it restarts his RP
Each RP he does, you have to re-talk to him to continue his script also, see second screenshot
![image](https://user-images.githubusercontent.com/29525708/56842668-2d617900-68db-11e9-86a8-91027390cf23.png)


![image](https://user-images.githubusercontent.com/29525708/56842685-64378f00-68db-11e9-9cce-e4c56113fb71.png)
