### ISSUE TITLE
warrior incorrect crit values

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#1093]
**Description:**
warriors are not getting a base 5% crit chance from their agility of 93 at lvl 70

**Current behaviour:**
174 agility on a warrior is giving 6.41% agility.(93 base + 81 from other)

**Expected behaviour:**
174 agility should give 7.4545*% crit chance, as the base crit of all classes should give 5% agility, and then warriors get 1% crit per 33 agility.
![visual](https://user-images.githubusercontent.com/47352954/56086913-fc795100-5ea3-11e9-9728-f554e0a9e782.png)

**Comment by Jerrythemagicdog** [comment]
Could you provide a source for that? The only mention about base 5% I find is in:
https://wowwiki.fandom.com/wiki/Critical_strike
from Warlords of Draenor. 
Thanks!

**Comment by oj449** [comment]
i can't find anything, looks like i was wrong.
