### ISSUE TITLE
Medallion of Horde/Alliance trinket

### ISSUE THREAD

**Issue by vicholdan** [thebarrensissues/Issues#1094]
Medallion of the Horde/Alliance (2min CD 70 version) Still has the same effect as the 1.12 version of the games insignia's (5min CD) where it would only remove certain types of spells/effects for different classes. Where since patch 2.0 all pvp trinkets should remove all loss of control effects. Oddly enough, the insignia of horde/alliance has the correct tooltip and effect as tested, medallion has been tested and is still having the effects of the old pvp trinkets. This will be a big deal if this is not fixed once arena season is out, thanks.

**Comment by Cheelout** [comment]
Please go and get more detail, like Item ID's.

**Comment by artieau** [comment]
Was a 2.1 change
https://wow.gamepedia.com/Patch_2.1.2

**Comment by vicholdan** [comment]
artieau if this was a 2.1 change then as said before the original insignia of the alliance/horde is doing the remove of all effects, and shouldnt be doing it at all.

**Comment by artieau** [comment]
Level 60 trinket should be at 2.0 effect = class specific removals

**Comment by artieau** [comment]
Item ID 18845
Item ID 18856

**Comment by Tamosheik** [comment]
**Insignia of The Horde (Pre 2.1)**
Item ID, Effect, (Spell ID)
18834, Dispels all Immobilizing, Slowing and Stun effects. (5579)
18845, Dispels all Immobilizing, Slowing and Stun effects. (5579)
18846, Dispels all Immobilizing, Slowing and Stun effects. (5579)
18849, Dispels all Charm, Fear and Polymorph effects. (23273)
18850, Dispels all Fear, Polymorph and Slowing effects. (23274)
18851, Dispels all Fear, Polymorph and Stun effects. (23276)
18852, Dispels all Charm, Fear and Polymorph effects. (23273)
18853, Dispels all Charm, Fear and Stun effects. (23277)
29592, Dispels all Fear, Polymorph and Stun effects. (23276) * *Assumed *

**Insignia of The Alliance (Pre 2.1)**
Item ID | Effect
18854, Dispels all Immobilizing, Slowing and Stun effects. (5579)
18856, Dispels all Immobilizing, Slowing and Stun effects. (5579)
18857, Dispels all Charm, Fear and Polymorph effects. (23273)
18858, Dispels all Charm, Fear and Polymorph effects. (23273)
18859, Dispels all Fear, Polymorph and Slowing effects. (23274)
18862, Dispels all Fear, Polymorph and Stun effects. (23276)
18863, Dispels all Charm, Fear and Stun effects. (23277)
18864, Dispels all Fear, Polymorph and Stun effects. (23276)
29593,  Dispels all Immobilizing, Slowing and Stun effects. (5579) * *Assumed*

**Comment by artieau** [comment]
Items are updated but still not working correctly @Tamosheik
