### ISSUE TITLE
warriors are getting extra crit from nowhere

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#1095]
**Description:**
changing stances as a warrior gives you extra crit, more than what you should have
**Current behaviour:**
after equipping an item and swapping to berserker stance, you seem to get the 3% crit chance from berserker stance, but then also get excess, maybe it is also multiplying your total crit chance by 3% as well - eg 23.69% crit chance>swap to berserker = 27.25% crit chance
**Expected behaviour:**
23.69% crit chance in battle stance>26.39% crit chance in berserker stance

**Steps to reproduce the problem:**

1.equip and unequip an item that modifies critical strike chance
2. watch your critical strike chance lower if you have been in berserker stance since modifying your critical strike chance
3. use berserker stance and the excess critical strike chance comes back until you modify critical strike chance again
[2019-04-14_11-09-03.zip](https://github.com/thebarrensissues/Issues/files/3076902/2019-04-14_11-09-03.zip)
![visual](https://user-images.githubusercontent.com/47352954/56087014-f97f6000-5ea5-11e9-9837-c2e2aef412e9.png)

**Comment by Cheelout** [comment]
Tested on warrior. Only getting 3% CRIt. Not matter what I did
Hoochx is the same

**Comment by oj449** [comment]
nvm it's a bug related to weapon skill then, excess weapon skill giving 0.04 per is applied after stance swapping to zerker it seems, had a fair amount of excess from stuff
