### ISSUE TITLE
[Druid] Feral Instinct talent doesn't appear to be working. (Threat Related)

### ISSUE THREAD

**Issue by Zeuaireus** [thebarrensissues/Issues#1096]
**Description:**

Feral Instinct talent doesn't appear to be working correctly; both with increasing threat caused in Bear and Dire Bear Form by x%, and reducing the chance enemies have to detect you while Prowling.

**Current behaviour:**

Feral Instinct isn't applying any additional threat generation and the necessary stealth detection reductions with prowling.

**Expected behaviour:**

Feral Instinct Increases threat caused in Bear and Dire Bear Form by 5/10/15% and reduces the chance enemies have to detect you while Prowling.

**Steps to reproduce the problem:**

- Be a Druid and talent into Feral Instinct located in the Feral Tree. What you should see is you being able to hold threat much easier than what is currently happening. 
	- A threat meter, such as Omean 2 will be required. 
	- A group will also be required.
	
**Additional Notes:**

As this issues isn't something you can visually see or check normally, a threat meter is required for long term testing. During my own testing, Omen2 was used. I have also been told about warriors having similar issues to holding with threat, so this talent may not be the only issue. The threat issue could be a global issue for druids and warriors.

	- Character is a Level 70 Druid, geared in accordance to a BiS (Best in Slot) list and crit capped for Heroic Dungeons. 
	- 5 man Dungeons was the main source of testing.
	- Abilities used were Mangle, Maul, Swipe, and Lacerate. Things such as Growl and Challenging Roar have been excluded.
	
	Base on the current data collected from testing these abilites and in combos; without critical strikes, Omen was indicating TPS (Threat Per Second) to be around 100-150 to begin with, then ramping up to 300-400 with critical, with a burst of around 700 before turning to the 300-400 mark. 
	Unlike other classes, mainly Paladins, Druid tanking is at level which is unsustainable with current threat generation. 
	Classes such as Mages, Warlocks, Shadow Priests even Balance Druids are pulling over 700 TPS. One attack from one of these class was enough to rip threat from the tank, where taunt was required to bring the target back. Even with Taunting, gaining threat back wasnt always possible and ended up with the healer or DPS dying.
	
	Bear Form is the Druid tanking form.
	Bear Form has an innate threat multiplier of +30%. This means that every time the druid does 100 damage he generates 130 threat.
	Several druid abilities in Bear Form further increases the threat generated making the druid able to hold aggro from DPS and healers.

	The Bear Form +30% modifier is adjustable with the talent Feral Instinct, granting up to +15% threat. The talents stacks additively, which means that if you spec 3 points into the talent you will gain +45% threat (+30% threat from bear + 15% from the talent). The talent does NOT stack multiplicatively for druids, it does however for warriors (e.g. +30% * 1.15 = +49.5%).
	This effect (Bear Form) was not changed in TBC, so the additional threat should have carried over from Vanilla into TBC. A question as to if this is working has been raised.	

	Mangle (Bear): Damage done * 1.3
	Example: Mangle crits for 1000 damage. 1000 * 1.3 * 1.3 = 1690 threat (1885 for 3/3 Feral Instinct).
	Based on testing, Mangle is not getting Bear Form additional Threat. And because Feral Instinct is also not working correctly, additional threat is not being applied overall. So as it stands, Mangle only give threat based on the damage it does.
	
	Swipe additional threat was removed in Patch 2.0.3 ("Swipe" has had its threat bonus multiplier removed.) 

	Maul, based on testing seems to be correct. "Maul" has had its threat bonus multiplier changed to a flat value similar in threat per time to "Heroic Strike". However, with Feral Instincts not appearing to be working correctly, testing results for this skill have been hindered.

  - **Talent Details.**
http://db.hellfire-tbc.com/?spell=16947		Feral Instinct	Rank 1
http://db.hellfire-tbc.com/?spell=16948		Feral Instinct	Rank 2
http://db.hellfire-tbc.com/?spell=16949		Feral Instinct	Rank 3

http://db.hellfire-tbc.com/?spell=9634		Dire Bear Form
http://db.hellfire-tbc.com/?spell=9635		Dire Bear Form (Passive)

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/49328610/56086972-60941900-5e94-11e9-81fd-3ce69f0ab4b5.png)

**Comment by Kaziner** [comment]
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/129748-guide-druid-tanking.html

Good resource above that details alot of specifics of threat gen

Key things to check:
Mangle may not be applying its 30% threat bonus
Lacerate may not be applying its flat 280ish base threat bonus
Swipe's cone may be too small; may not be scaling correctly with AP (unsure)

**Comment by SUN-Leekie** [comment]
Fixed in 11293.

Thanks for the sources!
Fixes:

* Lacerate having a modifier of 0.2 instead of 1.2
* Swipe having a modifier of 1.5 instead of 1

Other spells had the right flat/percentage modifiers and Feral Instinct works properly.
