### ISSUE TITLE
Druid - Armor from weapon's doesnt get amplified by druid's bear form

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#1100]
**Description:**

Druid - Armor from weapon's doesnt get amplified by druid's bear form

**Expected behaviour:**

The bonus armor from druid's bear form and talents should boost the armor from druid's weapons

**Steps to reproduce the problem:**

CHANGEME
1. Go into normal form
2. Equip a weapon with armor (eg Braxxis staff of slumber)
3. Note your base armor go up by 550.
4. Take it off go into bear form
5. Equip the weapon again; note the armor only goes up by 550 not 2k+ like it should

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by LoshyFirestorm** [comment]
This is something that was changed in patch 3.0.8 (https://www.wowhead.com/patchnotes=3.0.8) referred to as Bonus Armor and is as follows:

Bonus Armor: The mechanics for items with bonus armor on them has changed (any cloth, leather, mail, or plate items with extra armor, or any other items with any armor). Bonus armor beyond the base armor of an item will no longer be multiplied by any talents or by the bonuses of  Bear Form, (Spell #9634), or  Veteran of the Third War.

**Comment by Kaziner** [comment]
closed due to duplicate

**Comment by kelno** [comment]
Fixed with 11039
