### ISSUE TITLE
Thrall in OHFH's shield block has no cooldown

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#1101]
**Description:**

Thrall in OHFH's shield block has no cooldown - spams in several times a second throughout the entire instance

**Expected behaviour:**

Shouldn't be using it so often

**Steps to reproduce the problem:**

CHANGEME
1. Do OHFH, watch thrall

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by giveusmezpls** [comment]
Thrall of OHB has the NPC ID of 17876 and his shield block has Spell ID 12169

**Comment by kelno** [comment]
I think it's fixed now though
