### ISSUE TITLE
[Quest] The Cipher of Damnation

### ISSUE THREAD

**Issue by DotDotGoose** [thebarrensissues/Issues#1105]
**Description:**
Cyruhk The Fire Lord kill.

**Current behaviour:**
Kill the mob, incomplete slain quest.

**Expected behaviour:**
When mob is killed should complete the quest
also friendly helper Npcs do not attack him

**Steps to reproduce the problem:**
-use cipher of damnation to summon Cyruhk
-kill Cyruhk
-incomplete quest

Quest NPC-  #21181

![cihper](https://user-images.githubusercontent.com/46829458/56099705-9fd56f00-5f53-11e9-90d9-ed3e2c2747c5.jpg)
![cyruk](https://user-images.githubusercontent.com/46829458/56099716-d27f6780-5f53-11e9-8c2d-a8c90ea513a5.jpg)

**Comment by Tamosheik** [comment]
Quest ID#10588

**Comment by dinkletron** [comment]
We completed this quest tonight (even though it is not meant to be available until later in the chain), and received credit.

**Comment by giveusmezpls** [comment]
dinkleton confirmed cheater

**Comment by Cheelout** [comment]
Confirmed this is working.

**Comment by Jerrythemagicdog** [comment]
Probably related to https://github.com/thebarrensissues/Issues/issues/973 if some people are not getting the credit.
