### ISSUE TITLE
[Quest] Overlord missing from Force Commander Danath Trollbane

### ISSUE THREAD

**Issue by giveusmezpls** [thebarrensissues/Issues#1106]
**Description:**

The quest Overlord (QuestID: 10400) should be available from the NPC Force Commander Danath Trollbane (NPC: 16819) in the central building of Honor Hold from level 58 after the pre-quest (QuestID: 10395) which drops from item id 29588 is completed.

**Current behaviour:**

The NPC does not have the quest available to start after completion of the pre-quest.

**Expected behaviour:**

The NPC should have the quest available to start after completion of the pre-quest.

**Steps to reproduce the problem:**

1. Do the pre-quest
2. Check the NPC
3. Type /cry
4. Go to the cupboard and get some scotch
5. Drink till you are happy.
6. Blame Swidge.

**rev. hash/commit:** 

Do a `.server info` in game and copy/screenshot the first line.  
![image](https://user-images.githubusercontent.com/49624667/56101075-c69ba180-5f63-11e9-8a5a-51e74599cef0.png)

**Comment by Jerrythemagicdog** [comment]
Fixed in 11062 in https://github.com/kelno/sunstrider/commit/f1cb2d4fefab25e95259ef3824af578938ea4ae4
