### ISSUE TITLE
[Quest] Auchindoun... - D'ore Does Not Spawn

### ISSUE THREAD

**Issue by lagunac** [thebarrensissues/Issues#1107]
Description: (Quest) [Auchindon...]

The NPC named D'ore does not spawn after killing Exarch Maladaar

Tell us what happens: He is supposed to spawn and he does not.

Expected behaviour: He is supposed to spawn.

Steps to reproduce the problem:

Step 1: Enter Auchenai Crypts with the Quest [Auchindon...]
Step 2: Kill Exarch Maladaar

CHANGEME

Step 1 [Auchindon...] & followups.

![image](https://user-images.githubusercontent.com/49626510/56103503-98738d00-5f76-11e9-9585-d6ad7e588d62.png)

**Comment by Tamosheik** [comment]
Please provide NPC/Quest ID's in future reports. Check out the pinned messages in the #game-issues discord channel for more info.

QUEST ID#10167
D'ore - NPC ID#19412

**Comment by kelno** [comment]
Fixed with 11040
