### ISSUE TITLE
Quest -[Who are they?]

### ISSUE THREAD

**Issue by lagunac** [thebarrensissues/Issues#1108]
Quest -[Who are they?] isn't working as the NPC's you talk to do not provide quest accreditation to complete the quest.

Current behaviour: Talking to said NPC's will not give creditation toward quest.

Expected behaviour: Talking to the NPC's should give credit to the quest.

Steps to reproduce the problem:
Step 1: Obtain Quest [Who are they?]
Step 2: Talk to NPC's in quest requirements
Step 3: Notice they don't provide credits.

1. Step 1 :http://db.hellfire-tbc.com/?quest=10041

![image](https://user-images.githubusercontent.com/49626510/56103487-7aa62800-5f76-11e9-9588-0176eff442e5.png)

**Comment by zemfi** [comment]
another dupe #938
