### ISSUE TITLE
 [The Skettis Offensive] bugged

### ISSUE THREAD

**Issue by lagunac** [thebarrensissues/Issues#1109]
Description of the problem or issue here.
[The Skettis Offensive] bugged, have completed the quest creditation but the whole quest is incomplete and unable to turn in.

Current behaviour:
Quest is able to follow through as per normal, you obtain the quest creditation (Attack Thwarted 1/1) but the quest itself does not state complete, in turn you cannot hand it in.

Expected behaviour:
Quest should say it is completed as a whole after attack is thwarted.

Steps to reproduce the problem:
Step 1: Accept Quest
Step 2: Thwart the attack and kill NPC's
Step 3: Obtain Quest creditation
Step 4: You'll notice quest is not complete.

http://db.hellfire-tbc.com/?quest=10879

![image](https://user-images.githubusercontent.com/49626510/56103648-44b57380-5f77-11e9-8365-6748f5ac4ee4.png)

**Comment by zemfi** [comment]
duplicate, less than 12 hours ago #1104
