### ISSUE TITLE
Steamvault Heroic first boss post-damage adjustment

### ISSUE THREAD

**Issue by giveusmezpls** [thebarrensissues/Issues#1113]
**Description:**

Some monster damage has increased and cool downs decreased after recent changes.

**Current behaviour:**

It's difficult to say, a good test would be Steamvaults on Heroic mode first boss.

**Expected behaviour:**

Previously the first boss had cooldowns which made the content more do-able.

**Steps to reproduce the problem:**

We did wipe on the first pull due to higher than expected cloud damage with lung burst on 3 people, it seemed after this that more clouds spawned than expected (over 15 at one point shortly after pull).

**rev. hash/commit:**

**Comment by zemfi** [comment]
beautiful/10
