### ISSUE TITLE
Mage Spells Slowing effects (frost) higher then normal

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#1117]
**Description:**

Mage spells seems to have exceedingly high slow effects.

**Current behaviour:**

When casting a spell with a chill/slow effect (cone of cold, frostbolt, or target effected by Ice Armor) The affected target is slowed for more then intended.

Cone of Cold - 85% slow
Frostbolt - 72% slow
Ice Armor - 40% slow

**Expected behaviour:**

The slow effect from these spells should be:
Cone of Cold : 50%
Frostbolt - 40%
Ice Armor - 30%

**Steps to reproduce the problem:**

1. Step 1 Cast Cone of Cold, Frostbolt on a target or have a melee proc your ice armour chill effect.
2. Step 2 They are now slowed for more then they should be, also visible in debuff tooltips.
3. Step 3 Report on github so you don't get destroyed in arena on your rogue.

(Max ranks were tested of this only. Mage did not have Imp blizzard in his spec.)

 **rev. hash/commit:** 	

rev. 10989 (f824c7a15ce6+)

Cone of Cold - spell=27087
Frostbolt - spell=27072
Ice Armor - spell=27124

**Comment by Jerrythemagicdog** [comment]
The bug here is a tooltip bug with Permafrost (check with Cone of Cold and Permafrost talented and without). It has no effect on the amount of slow.
They're not active at the same time. The stronger effect only is always active. 
Related issue: https://github.com/thebarrensissues/Issues/issues/687

**Comment by kelno** [comment]
I'm 80% sure it's a clientside bug that can't be fixed. Closed until proven otherwise.
