### ISSUE TITLE
Baron Geddon dies on pull

### ISSUE THREAD

**Issue by giveusmezpls** [thebarrensissues/Issues#1119]
**Description:**

Baron Geddon dies on pull. (NPCID=12056)

**Current behaviour:**

Baron Geddon dies on pull, you engage combat and he deflates like a popped balloon.

**Expected behaviour:**

Baron Geddon does not die on pull.

**Steps to reproduce the problem:**

1. Go to Molten Core (why would you do this to yourself AGAIN).
2. Clear mobs.
3. Pull Baron Geddon.
4. Be sad, he gone.

![image](https://user-images.githubusercontent.com/49624667/56267463-3c556800-6132-11e9-988e-424bf054a15f.png)

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/49624667/56267482-48412a00-6132-11e9-880e-b57f8c5e4d99.png)

**Comment by Harrock1** [comment]
Last week it was rocket laucher, this week was bow. Hes very weak
