### ISSUE TITLE
[Quest] Shattering the Veil - minions not spawning

### ISSUE THREAD

**Issue by heyquestbroke** [thebarrensissues/Issues#1120]
Quest: Shattering the Veil

Nagrand

Slay 30 Minion of Gurok

![rock](https://user-images.githubusercontent.com/49708053/56275261-be01c180-6143-11e9-98a5-76c279328cf2.PNG)

Use "Gordawg's Boulder" on "Shattering Rumbler" to spawn minions

Problem: Minions don't spawn properly after Boulder is used on Shattering Rumbler, they appear for a second then instantly disappear, cannot be targeted

Once boulder is used, the Rumbler is killed and several minions are suppose to spawn to be attacked and killed. 

https://www.wowhead.com/quest=9849/shattering-the-veil

here's video, click on "View raw"

://github.com/heyquestbroke/yo/blob/master/World%20Of%20Warcraft%202019.04.17%20-%2016.54.31.06.mp4

**Comment by zemfi** [comment]
I completed it a few days ago fine, something broke in the newest rev? should include that in your report ^

**Comment by heyquestbroke** [comment]
@zemfi  where can i find that ID info? first time using this/reporting a problem sorry.  i was able to finish the quest, i eventually found a spot where the minions were randomly spawning at on the ground near Telaar. did that link for the video work?

**Comment by Tamosheik** [comment]
Video didn't work, try uploading to youtube and posting the link here.

An explanation of quest/npc/item/spell ids is pinned in the #game-issues channel on discord. Hit me up if you need help.

**Comment by heyquestbroke** [comment]
copy link n click "View raw" and it downloads the video, just worked fine on me phone

**Comment by zemfi** [comment]
Confirmed broken by ign: weezy. Probably a regression bug.

.rev 11082

**Comment by Orcfootstool** [comment]
Still broken.
rev. 11262

**Comment by SUN-Leekie** [comment]
Fixed in 11308.
