### ISSUE TITLE
Nethermancer Sepethrea - Mechanar Heroic

### ISSUE THREAD

**Issue by giveusmezpls** [thebarrensissues/Issues#1122]
**Description:**

The Heroic Mechanar and potential normal mechanar are plagued with issues which can increase the difficulty artificially.

**Current behaviour:**

On the second boss:
The 3 adds which spawn move faster than the players instead of around 80% of player movement speed. The damage dealt by both the fire trail and the hellfire effect is signicantly higher than what looks correct in the video below.
The mobs are target able (instead of untargettable) and melee attack instead of just mindlessly follow. The hellfire can be forced by moving into melee whereas instead it should occur on a timer when they are changing targets.

**Expected behaviour:**

https://www.youtube.com/watch?v=6B518EQiyiI

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/49624667/56286158-5c018600-615c-11e9-8663-f4b71f6f9d71.png)

**Comment by SUN-Leekie** [comment]
What is fixed:

* Raging Flames are now unselectable, unattackable and pacified
* Raging Flames speed

The rest seems to add challenge to the fight so I won't change it.

**Comment by SUN-Leekie** [comment]
After @Jerrythemagicdog DM and another close look at the vide linked in the issue, I will be reverting the first bullet point as it is intended and can be seen in the video...
