### ISSUE TITLE
[Mage] Invisibility doesn't prevent to see other non-invisible creature/players

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#1126]
**Description:**

Invisibility (spell 66) doesn't correctly phase out the mage. When invisible the mage should only see other invisible targets and those whom can see invisible (tooltip).
Currently the mage can see all targets.

**Steps to reproduce the problem:**

1. .learn 66
2. .cast 66
3. we're in Stealth.

 **rev. hash/commit:** 	

10993

**Comment by kelno** [comment]
Fixed with 11030
