### ISSUE TITLE
Creatures don't idle in combat properly

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#1128]
**Description:**
This is an issue in the entire world, not sure how to reproduce but happens very often. Creatures seem to randomly lose their combat animation. When fighting they go idle and then swing and go back to idle again.

**Current behaviour:**
Here's an example video with Bonechewer Devastator (16772)  (happens on other mobs too.):
https://streamable.com/od4ah

**Expected behaviour:**

They should have their combat stance while fighting.

**Steps to reproduce the problem:**

1. Pull a mob
2. Fight for a bit
3. Observe they lose their combat animation.

 **rev. hash/commit:** 	

10993

**Comment by SUN-Leekie** [comment]
Fixed in 11107.
