### ISSUE TITLE
[Rogue] Deadly Throw can proc Ruthlessness

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#1129]
**Description:**
Deadly Throw (26679) can proc Ruthlessness talent (14161) which can lead to endless Deadly Throw. It should not be able to proc Ruthlessness. 

**Expected behaviour:**

Deadly Throw shouldn't have a chance to proc Ruthlessness.
Source: https://wowwiki.fandom.com/wiki/Ruthlessness_(rogue_talent)
Not very related but slightly relevant: https://github.com/thebarrensissues/Issues/issues/498

**rev. hash/commit:** 	

10993

**Comment by cryptochiefy** [comment]
Br0ken pllz fix

**Comment by SUN-Leekie** [comment]
Fixed in 11247.

**Comment by cryptochiefy** [comment]
its not fixed yet

**Comment by kelno** [comment]
Seems to be for us, can you tell us how to reproduce?
