### ISSUE TITLE
Creatures have spells that shouldn't be usable while CM

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#1130]
I'd like to compile a list of some npc spells that should be usable from a MC'ed creature.

1. 34809 (https://www.wowhead.com/spell=34809/holy-fury#comments and https://www.wowhead.com/npc=19633/bloodwarder-mender#comments)
2. 15123 was until some point, maybe still has flag (https://www.wowhead.com/npc=9098/scarshield-spellbinder#abilities)
3. 17175 (https://www.wowhead.com/npc=10605/scarlet-medic#comments)
4. 31598 (https://wowwiki.fandom.com/wiki/List_of_mind_controllable_mobs Bleeding Hollow Darkcaster and https://www.wowhead.com/npc=17269/bleeding-hollow-darkcaster#comments)
5. 35265(https://www.wowhead.com/npc=19168/sunseeker-astromage#comments:id=52728 and https://wowwiki.fandom.com/wiki/List_of_mind_controllable_mobs Sunseeker Astromage)

Those are just some examples, more on wowwiki, would appreciate more sources.

**Comment by giveusmezpls** [comment]
Interesting topic, i think the three major faults at the moment regarding to mind control are (in no specific order):

1. Mobs have no Cooldown on spells MOST of the time.
2. Mobs had some spells which are not correct.
3. Many mobs have no scaling on spells when MC leading to them doing 80-105 damage in most cases even on higher level elite mobs for example. (This is **MOST** mobs).

Further to this bug type 3, spell reflected spells on mobs also appear affected in these instances (i.e. reflecting these spells leads to little damage being created).
w
A lot of mobs also have issues in using summoning spells I assume this s related to:
https://github.com/TrinityCore/TrinityCore/issues/7653

There are also some mobs hard coded to be immune for no reason, I think being immune should be considered abnormal behavior as most mobs were in general mind control excluding those with immunities (i.e. boss behavior) if you examine Blackrock Depths the mobs are immune to Mind Control however this was not the case in retail ( can dig up a source if required ) but in Dire Maul the mobs are Mind controllable which is correct however they have no CD on spell leading to a Priest being able to solo the dungeon (incorrect).

**Comment by giveusmezpls** [comment]
https://tbc-twinhead.twinstar.cz/?npc=16772
![image](https://user-images.githubusercontent.com/49624667/56327122-4a4fcb00-61bc-11e9-95ea-182e121dbe3e.png)
dual wield ...

**Comment by kelno** [comment]
Nice. The reason I want to make a list is to compare some stuff on them and see if I can create a general rule out of them.
I've discussed a bit what was wrong with other developers and indeed the data we currently have is wildly incorrect (which explains your points 1 and 2).
For 3. however I don't know of any scaling that's supposed to happen, can you give detail on that?

As for the last point there is no good source that I know of on what creature should be immune and what shouldn't, we're still operating on a per case basis there.

**Comment by kelno** [comment]
https://www.youtube.com/watch?v=4QyqMICxtiQ

**Comment by kelno** [comment]
Updated with ce1fa6ff550cd87b6ed13a27345651e12f192a75

**Comment by kelno** [comment]
Updated again in 2e06e96300ae43e792c49665b1a39bad37179803 
All of this will be applied with 11030

I'll close it for now, but feel free to add spells that shouldn't be there.
