### ISSUE TITLE
Mass Dispel is removing stealth from Rogues

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1131]
**Description:**

Mass Dispel is removing stealth from Rogues

**Current behaviour:**

When casting Mass Dispel [SpellID=32375], The rogue is being put into combat correctly but stealth is being removed.

Stealth Spell ID's by Rank
spell=1785
spell=1786
spell=1787

**Expected behaviour:**

Rogue and Priest should be put in combat but stealth should remain active

**Steps to reproduce the problem:**

1. Be Rogue in stealth
2. Have priest MD the area you are stealthed
3. Cri erytym

(Literal tears, Swidge was crying in Arena last night because of this)
Revision: 11015

**Comment by Kaziner** [comment]
https://wowwiki.fandom.com/wiki/Patch_2.2.0

Mass Dispel: The portion of this spell that removes immunity effects (Blessing of Protection, Ice Block, etc.), now has a chance to be resisted, and will display correctly to the combat log. It will no longer cause Rogues and Druids in Cat Form to lose stealth.

Supporting evidence; changed in 2.2 to no longer remove stealth

**Comment by HueHueTBCTheBarrens** [comment]
if we're using 2.4.3 spells, mass dispel was fixed in 2.2 because of a bug that it was removing stealth

**Comment by kelno** [comment]
Fixed with 11047

**Comment by cryptochiefy** [comment]
wHAT BOUT MAGES HOPE IT DOESNT POP MI OUT
