### ISSUE TITLE
Captain Skarlocc on Heroic dropping wrong SOME loot table.

### ISSUE THREAD

**Issue by giveusmezpls** [thebarrensissues/Issues#1134]
**Description:**

Captain Skarlocc (NPCID=17862) in Heroic Old Hillsbrad drops from the non-heroic loot table instead of the heroic loot table.

**Current behaviour:**

This is per the description.

**Expected behaviour:**

Instead i would prefer if he dropped the heroic loot table!

**Steps to reproduce the problem:**

1. Go into the dungeon on normal and then heroic
2. see the mob drops the same items (or at least some shared items)
3. Don't get the item you want, be sad.

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/49624667/56353514-e0afdb00-6214-11e9-8fce-4426b23e9af0.png)

**Comment by giveusmezpls** [comment]
killed today and dropped the Heroic resilience neck.

Perhaps just some of the loot table is wrong?

**Comment by Cheelout** [comment]
Fixed with SQL Update
DELETE FROM `creature_loot_template` where `entry`=20521 AND `Item` IN(27424,27428,27430)
