### ISSUE TITLE
[Quest] Mark V is Alive! Failing to complete for multiple players at once.

### ISSUE THREAD

**Issue by Azytheoneandonly** [thebarrensissues/Issues#1135]
**Description:**

Mark V is Alive! escort quest gives credit for person who starts quest but not for group members.

**Current behaviour:**

Mark V is Alive! escort quest completes for person who starts quest but not for group members.

**Expected behaviour:**

For the Quest to complete for group members if done in a group.

**Steps to reproduce the problem:**

1. Start quest and group members accept it.
2. Complete quest and Person who starts quest gets credit and other members do not.

Quest: http://db.hellfire-tbc.com/?quest=10191
Video Accepting Quest on 3 Toons: https://streamable.com/kfug1 
Video At of Quest Credit: https://streamable.com/qtnj6
 **rev. hash/commit:** 	
![image](https://user-images.githubusercontent.com/37324574/56360716-d0a1f680-6228-11e9-8c4a-9c1130b6d4c9.png)

**Comment by SUN-Leekie** [comment]
Fixed in 11316.
