### ISSUE TITLE
Normal and Heroic Murmur issues

### ISSUE THREAD

**Issue by kakarotkaruma** [thebarrensissues/Issues#1137]
**Description:**

Issues with Normal and Heroic Murmur (npc=18708).
Murmur in both Normal and Heroic should start at approx. half health (I believe it's 49%). This occurs in Normal mode, however, if you wipe on the boss, he resets to 100% health. This should not happen.
In Heroic mode, Murmur starts at 100% health (approx 650k hp), again, this should not be the case. Additionally, Murmur should only cast resonance (spell=33657) if there is nobody in melee range. This is not happening and the boss seems to be spamming the ability on cooldown (5 seconds).

**Current behaviour:**

Normal Shadow Labs: Murmur resetting to 100% health when wiped on.

Heroic Shadow Labs: Murmur starting at 100% HP. Using Resonance even with targets in melee range.

**Expected behaviour:**

Murmur should start on 49% HP (or there about) for both encounters, and should reset to that same level if wiped on. 

Heroic Murmur: Should only cast Resonance when there are no players in melee range.

**Steps to reproduce the problem:**

1. Enter Normal Shadow Labs
2. See Murmur at half HP
3. Wipe to Murmur
4. See Murmur reset to 100% HP

1. Enter Heroic Shadow Labs
2. See Murmur at 100% HP
3. Stand in melee range and have Resonance cast on you

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**Comment by giveusmezpls** [comment]
In Addition Murmur should not use spell=3365 unless no player is in melee range with some time delay between the cast of Sonic Boom (spell=33666) and the melee proximity check.

**Comment by kelno** [comment]
2681ff7decdd77a131b06141609be6b02b1beb47

**Comment by kelno** [comment]
Fixed with 11376

**Comment by kelno** [comment]
7d19c543851099dd22e6718b972fe1ca8c133f68
