### ISSUE TITLE
The Lightning Capacitor version

### ISSUE THREAD

**Issue by artieau** [thebarrensissues/Issues#1138]
**Description:**

Item/patch state of the item The Lightning Capacitor is per 2.4.3 but should be per 2.0
Item ID 28785

**Current behaviour:**

Current item version is per 2.4.3 with 2.5second cooldown per charge.
![image](https://user-images.githubusercontent.com/40563134/56409456-85d1be80-62bc-11e9-8ac3-5f31dc743065.png)

**Expected behaviour:**

Trinket should have no internal cooldown until patch 2.3
SpellPower coefficient of the proc should be 1:1

**Steps to reproduce the problem:**

1. Equip trinket
2. Cast spells which crit
3. ONly gain charge every 2.5 sec

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/40563134/56409576-ff69ac80-62bc-11e9-96e5-300767c327d6.png)

**Comment by artieau** [comment]
Probably has to be action by Mode from item template @Cheelout

**Comment by Cheelout** [comment]
Please provide both spell ids

**Comment by artieau** [comment]
Spell ID # 37657
Unable to find if any earlier version exists.
If there is not, requires a new spell to be created or this one adjusted server side.

**Comment by Cheelout** [comment]
Ill handle this one Nolin and Kelno

**Comment by Cheelout** [comment]
https://github.com/Atlantiss/NetherwingBugtracker/issues/3136

**Comment by Cheelout** [comment]
Same problem exists for example DST has the 20 second ICD that was added in patch 2.2. But there is no spell in game for prenerf. These issues most likely wont be fixed and the items would stay in a 2.4 state

**Comment by Cheelout** [comment]
Team has decided these items will stay with 2.4.3 procs much like netherwing. These procs were broken and nerfed to balance the trinket.

**Comment by artieau** [comment]
Does not need a new spell -
You need to remove the cooldown in spell_proc table
UPDATE spell_proc SET cooldown = 0 WHERE SpellId = 37657;
Same can be done for DST and any other items found moving forward
