### ISSUE TITLE
Epic gems in Heroics

### ISSUE THREAD

**Issue by artieau** [thebarrensissues/Issues#1140]
**Description:**

All bosses in a heroic dungeon should have a chance to drop an epic gem.
This is a separate roll to the other item/s that boss should drop.

**Current behaviour:**

No epic gems drop from any boss currently.
Example is Item ID # 30603 from NPC ID # 19893
https://wow.gamepedia.com/Royal_Tanzanite

**Expected behaviour:**

All bosses in a heroic dungeon should have a chance to drop an epic gem.
This is a separate roll to the other item/s that boss should drop.

**Steps to reproduce the problem:**

1. Kill a heroic boss, any
2. No gems drop
3. no drop EVER

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/40563134/56419221-dd802200-62dc-11e9-9a2d-d83cb3b96ffa.png)

**Comment by giveusmezpls** [comment]
confirmed i have not seen any epic gems.

**Comment by giveusmezpls** [comment]
![image](https://user-images.githubusercontent.com/49624667/56456872-bba69e00-63b5-11e9-9e7a-aefa4a55afcd.png)
where is item
Heroic Grand Warlock Netherkurse
