### ISSUE TITLE
Insignia of the horde = broken

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#1141]
**Description:**

Insignia of the horde seems to be broken. Does not initiate the spell to remove cc nor put trinket on cd.

**Current behaviour:**

When you /use your insignia of the horde, it casts the animation on your character and makes the sound but does not use the trinket or trigger the remove cc spell effect. When you use the trinket, is does not go on cooldown either.

(deleting WDB Cache folder did not fix this issue)

**Expected behaviour:**

The trinket should proc a spell that removes cc and be put on cooldown.

**Steps to reproduce the problem:**

1. Have Insignia of the Horde on and off cooldown.
2. Be CC'd or not.
3. /use the insignia of the horde.
4. Nothing happens.

Tested the trinkets below, both are broken:

item=18850 (Mage trinket)
item=18849 (rogue trinket)

![WoWScrnShot_041919_212610](https://user-images.githubusercontent.com/47015256/56422249-cac01a00-62e9-11e9-859a-a4e9d47d4c41.jpg)

**Comment by emorelix** [comment]
Equiping the trinket also does not put it on cooldown.

**Comment by kelno** [comment]
Very probably related to item progression

**Comment by Cheelout** [comment]
Yep will handle it when i return

**Comment by Tamosheik** [comment]
Please confirm that after waiting the full (5 minute) cooldown you are still unable to use the item.

**Comment by emorelix** [comment]
> Please confirm that after waiting the full (5 minute) cooldown you are still unable to use the item.

the item never enters a cooldown state when you use it, i have had it equipped and tried to use it multiple times in the same battleground without taking it off. So even if there was a 5 minute cooldown i can't see, i cannot use the trinket after it is off cooldown either.
