### ISSUE TITLE
Guild bank allows users to split stacks / move stacks without withdraw permissions

### ISSUE THREAD

**Issue by giveusmezpls** [thebarrensissues/Issues#1143]
**Description:**

Guild bank allows users to split stacks / move stacks without withdraw permissions

**Current behaviour:**

Guild bank allows users to split stacks / move stacks without withdraw permissions

**Expected behaviour:**

Not that.

**Steps to reproduce the problem:**

Guild bank allows users to split stacks / move stacks without withdraw permissions

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/49624667/56447617-c24cfb00-634c-11e9-9112-07d1cbdcfb24.png)

**Comment by giveusmezpls** [comment]
let me know when you need me to test it again it annoys Modelol so happy to help.

**Comment by kelno** [comment]
I can reproduce it only when I add deposit rights. I guess you have them.
What's supposed to happen here? If you deposit an item you do not have the right to move it afterwards if you don't have withdraw rights?

**Comment by giveusmezpls** [comment]
Correct if you try to interact with an item when you are not depositing the response from server should be 'you do not have permission' you cannot pick up to move or split stacks due to this.

**Comment by kelno** [comment]
I'm not 100% convinced this is blizzlike buuut, why not, this makes sense to me.
Fixed with 11050
