### ISSUE TITLE
Food overhealing

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#1144]
**Description:**

Food currently overheals when consumed.

**Current behaviour:**

example:
When i eat clefthoof ribs, it is meant to heal 7500 hp over 30 seconds. Instead i heal 7500hp over more like 15 seconds. *my hp5 is only at 25*

So food is healing 2-3 time the normal rate it should. It is almost faster to use food than to bandage atm.

**Expected behaviour:**

Food is only meant to heal the tool-tipped amount.

**Steps to reproduce the problem:**

CHANGEME
1. Be on low health.
2. Eat some food (ie clefthoof ribs)
3. heal for 2-3 times the normal rate.

 **rev. hash/commit:** 	

Tested this on 55-70 food brackets.
clefthoof ribs : item=29451

![WoWScrnShot_042019_131942](https://user-images.githubusercontent.com/47015256/56451434-fafdcc00-636e-11e9-8cda-4f5fb90e15eb.jpg)

**Comment by kelno** [comment]
Thanks!

**Comment by kelno** [comment]
Fixed with 11041
