### ISSUE TITLE
[Druid] Dire Bear form not increasing armour

### ISSUE THREAD

**Issue by LoshyFirestorm** [thebarrensissues/Issues#1145]
**Description:**

Dire Bear form is currently giving no increase to armour.  The stamina increase appears to be working correctly.

**Current behaviour:**

Dire Bear form should increase armour from equipment by 400%

**Expected behaviour:**

Dire Bear form increases armour from equipment by 400% while in the form.

**Steps to reproduce the problem:**

CHANGEME
1. Equip items
2. Note armour
3. Shapeshift into Dire Bear form
4. Note no change to armour

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/43313533/56451975-a60f8500-6371-11e9-9f40-924e8ea73f34.png)

**Comment by Cheelout** [comment]
Fix is ready to go on next maint.

**Comment by Cheelout** [comment]
@Kelno

**Comment by kelno** [comment]
That was broken yesterday.
Fixed with 11043
