### ISSUE TITLE
Prayer of Spirit (Rank 2) Usable In Non-DS Specs

### ISSUE THREAD

**Issue by nafsepz** [thebarrensissues/Issues#1147]
**Description:**

Priest trainer teaches priests "Prayer of Spirit (Rank 2)" as a skill, which remains in spellbook even after respec to a non Divine Spirit spec.

**Current behaviour:**

If a priest prior to hitting level 60 learns "Prayer of Spirit (Rank 1)" and attends the trainer at level 70 in a non Divine Spirit spec, the trainer teaches Rank2 as a skill anyway. The skill is usable to the priest even when the Divine Spirit talent has not been selected (non-improved version). 

**Expected behaviour:**

Prayer of Spirit should only be available to be trained at 70 after selecting a Divine Spirit based spec. Upon talent reset, all ranks of individual and group spirit buffs should be removed from the spellbook.

**Steps to reproduce the problem:**

1. Learn Prayer of Spirit (Rank 1) before lvl 70
2. Respec to non-DS spec
3. Hit 70
4. Attend trainer in non-DS spec and learn all skills
5. Start haxxoring with Prayer of Spirit R2 :/

 **rev. hash/commit:** 	
"Sunstrider rev. 11053 (e907c86a319f+) 2019-04-21 01:25:25 +0200 (master branch) (Unix, RelWithDebInfo, Static)"

For reference, the in-game character is "Sepz" (70 Human Priest)

**Comment by giveusmezpls** [comment]
Tested, every-time you unlearn talent points it does not unlearn Prayer of Divine Spirit (Rank 2) [SPELLIID=32999] but it does unlearn Prayer of Divine Spirit (Rank 1) [SPELLID=27681] and it the non group ranks (SPELLIDs=14752, 14818, 14819, 27841, 25312).

**Comment by kelno** [comment]
Fixed with 11129
