### ISSUE TITLE
Mind Flay interrupts, Shadow weaving not stacking w/ multiple shadow priests

### ISSUE THREAD

**Issue by nafsepz** [thebarrensissues/Issues#1148]
**Description:**

Priest mind-flay is interrupted/not cast-able and shadow weaving is overwritten if 2 shadow priests are present.

**Current behaviour:**

If 2 Shadow priests are present only 1 can mind-flay at a time. The priest with the higher spell power (SP) interrupts the mind-flay of the other priest, even mid cast. If the higher SP priest is casting, the lower SP priest receives a message "A more powerful spell is already active" and is unable to cast. Severely gimping the DPS of the second priest.

When these and other spells are cast, the shadow weaving buff does not stack together, instead they remove the existing stack and re-stack at 2%. For example, Priest 1 obtains 5 stack weaving 10% debuff on a target, priest 2 hits target with a shadow spell, the 10% disappears and the target now has a 2% debuff from the second priest.

**Expected behaviour:**

Both priests should be able to cast mind-flay upon the target at the same time, so that the target has 2 debuffs. Shadow weaving should stack from multiple priests.

**Steps to reproduce the problem:**

CHANGEME
1. Obtain two shadow priests (we used Seth halls)
2. Target same mob, cast Mind Flay (or any shadow spell for the weaving issue)

 **rev. hash/commit:** 	

"Sunstrider rev. 11053 (e907c86a319f+) 2019-04-21 01:25:25 +0200 (master branch) (Unix, RelWithDebInfo, Static)"

**Comment by Jerrythemagicdog** [comment]
Fixed in 11054
