### ISSUE TITLE
pvp combat debuff bug

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#1149]
**Description:**
players will enter combat from debuffs ticking rather than only the intial application
**Current behaviour:**
players will reenter combat from the ticking of debuffs
**Expected behaviour:**
players will only enter combat from intial debuff applications
**Steps to reproduce the problem:**
this is more noticable in a bg scenario and on rogues trying to restealth
1. enter a bg with 2 players to test
2. player 1 debuffs player 2
3. player 1 is killed quickly before their debuffs wear off player 2
4. player 1 respawns before their debuffs wear off player 2, and their debuffs tick on player 2, causing combat for player 1, not sure if player 2 is also getting combat from this
![visual](https://user-images.githubusercontent.com/47352954/56464813-ab81d380-6434-11e9-92a8-c3885f018c3f.png)

**Comment by Jerrythemagicdog** [comment]
maybe related: https://github.com/thebarrensissues/Issues/issues/1142

**Comment by kelno** [comment]
We couldn't reproduce this

**Comment by kelno** [comment]
Going to assume it's fixed

**Comment by oj449** [comment]
More like no one bgs anymore to see it lol
