### ISSUE TITLE
Arena Team Ratings Broken (for losses)

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#1150]
**Description:**

Arena team losses appear to be double, if not higher, then the normal values.

**Current behaviour:**

Losing in arena is resulting in a loss higher then normal. 
Example:
1500 TEAM A, with 1500 personal rating Vs 1650 Team B with 1650 personal rating.

Team A loses to Team B.

Team A loses 26 points, Team B wins 7 points.

**Expected behaviour:**

Team A should lose only at most 13 points to Team B. Most like 10-13. Not 25+

**Steps to reproduce the problem:**

Step 1. Be in an arena team and play a match.
Step 2. Lose a Match.
Step 3. Observer severe point loss.

 **rev. hash/commit:** 	

Team B was losing around 30 points per loss, nearly equivalent of Team A losing around 24-27 points. It seems the lower Team A got in rating, the more points they would lose each game, despite team B being higher and higher in rating.

Source below (relevant to tbc as it is pre-3.0) clearly states the elo system and how it calculates loss of points based on the two teams ratings, personal and team.

""""""""""""
https://wowwiki.fandom.com/wiki/Arena_PvP_system:

Arena rating calculation of each match is based on the Icon-wikipedia-22x22 ELO Rating System which is used by the international chess rating system.

The ELO system takes the score of two opponents and calculates a statistical chance of winning based off those scores. After the match it uses the difference between the calculated chance of winning and the actual results. The difference between the two probabilities is then applied to the maximum amount of points allowed per match. Having a maximum amount makes sure teams have to play a large number of matches instead of just getting lucky and beating one team with a high ranking score.

Example of a match rating calculation:

Team A's Current Score: 1500pt
Team B's Current Score: 1580pt
Team A's Chance of Winning: 1 / (1+10(1580 - 1500)/400) = 0.38686
Team B's Chance of Winning: 1 / (1+10(1500 - 1580)/400) = 0.61314
Now Let's say Team A won the battle then
Team A's New Score: 1500 + 32*(1 - 0.38686) = 1500 + 19.62 = 1519.62
Team B's New Score: 1580 + 32*(0 - 0.61314) = 1580 + (-19.62) = 1560.38
Now Let's say Team B won the battle then
Team A's New Score: 1500 + 32*(0 - 0.38686) = 1500 + (-12.38) = 1487.62
Team B's New Score: 1580 + 32*(1 - 0.61314) = 1580 + 12.38 = 1592.38

The K value used by Blizzard is 32. So each match, the maximum rating gain/loss will be 32pts. And if you play with a team with same rating, you will gain/lose exactly 16pts.

As you can see when a team with a higher ranking score wins a match against a lower ranking team, they receive fewer points than if the lower rank team won.

""""""""""""""""""""""""""""""""""""""

![WoWScrnShot_042119_165240](https://user-images.githubusercontent.com/47015256/56466467-e6483380-6455-11e9-8450-3036d493c67e.jpg)

**Comment by Cheelout** [comment]
Seems the net gain and loss is reversed.. Winning poitns is going down and losing points is going up

**Comment by emorelix** [comment]
winning is meant to go down as u vs teams lower rating then you

**Comment by emorelix** [comment]
*This was all tested in 2v2 bracket, have not tested 3v3/5v5**

**Comment by Cheelout** [comment]
3v3 is the same, assuming 5v5 is the same too

**Comment by Cheelout** [comment]
I believe that the WOTLK System is implemented for Season 6 and after. I believe this is the Calculation System for S1 - S5

Example of a match rating calculation:

Team A's Current Score: 1500pt
Team B's Current Score: 1580pt
Team A's Chance of Winning: 1 / (1+10(1580 - 1500)/400) = 0.38686
Team B's Chance of Winning: 1 / (1+10(1500 - 1580)/400) = 0.61314
Now Let's say Team A won the battle then
Team A's New Score: 1500 + 32*(1 - 0.38686) = 1500 + 19.62 = 1519.62
Team B's New Score: 1580 + 32*(0 - 0.61314) = 1580 + (-19.62) = 1560.38
Now Let's say Team B won the battle then
Team A's New Score: 1500 + 32*(0 - 0.38686) = 1500 + (-12.38) = 1487.62
Team B's New Score: 1580 + 32*(1 - 0.61314) = 1580 + 12.38 = 1592.38

The K value used by Blizzard is 32. So each match, the maximum rating gain/loss will be 32pts. And if you play with a team with same rating, you will gain/lose exactly 16pts.

As you can see when a team with a higher ranking score wins a match against a lower ranking team, they receive fewer points than if the lower rank team won.

**Comment by Cheelout** [comment]
Also this: https://wowwiki.fandom.com/wiki/Arena_team_rating

**Comment by kelno** [comment]
Fixed in 11124
