### ISSUE TITLE
Mage able to blink while garrote + cheapshot

### ISSUE THREAD

**Issue by dinkletron** [thebarrensissues/Issues#1151]
**Description:**
Mage is able to cast blink while cheap shot + garroted. Garrote should silence the mage.

**Current behaviour:**
Mage can blink while CS + Garroted, see video here: https://youtu.be/Yq8bpnhznKY
If mage is only garroted, he is silenced and can't blink.
If rogue follows up with a CS (so mage debuffs are garrote + cheap shot), he can successfully blink.

**Expected behaviour:**
Mage should remain silenced for the duration of garrote, even when stunned.

**Steps to reproduce the problem:**
1) Mage vs rogue duel
2) Have rogue garrote mage, then instantly cheap shot
3) Mage casts blink (while garrote still has ~1 second remaining) and cast will successfully go off

 **rev. hash/commit:** 	
![Serverinfo](https://user-images.githubusercontent.com/29308094/56466835-55c02200-645a-11e9-9417-de9816e3b3e6.JPG)

**Comment by Jerrythemagicdog** [comment]
Doesn't happen if the target is not stunned, with only Garrote on the Mage is silenced and can't Blink. Blink seems to only check for stun.

**Comment by woiwoz** [comment]
This problem is left to me to solve.
I already know how to copy it.
thanks @dinkletron

**Comment by kelno** [comment]
Fixed with 11101
