### ISSUE TITLE
[Mage] - Winter's Chill - Debuffs not stacking with other mages

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1152]
**Description:**

Winters chill from other mages is over riding the stacks already on the target, instead of adding a stack to the debuff

**Current behaviour:**

Winters chill from other mages is over riding the stacks already on the target, instead of adding a stack to the debuff

**Expected behaviour:**

https://tbc-twinhead.twinstar.cz/?spell=28595

Each mage who is specced into this talent is meant to add a stack not overwrite the other mages stacks

Might be related to the same issue as scorch? https://github.com/thebarrensissues/Issues/issues/654

**Steps to reproduce the problem:**

CHANGEME
1. Get 2 mages
2. Spec Winters Chill in Frost Tree
3. Frostbolt same target

Revision: 11053

**Comment by Jerrythemagicdog** [comment]
Fixed in 11054
