### ISSUE TITLE
[Shattered Halls] Warchief Kargath Bladefist summoned assassins are engaging immediately

### ISSUE THREAD

**Issue by Azytheoneandonly** [thebarrensissues/Issues#1153]
**Description:**

Currently Kargath is pulling the 4 Shattered Hand Assassins from around the stairs on either side whenever he does his Blade Dance.

**Current behaviour:**

When he does his Blade Dance it pulls the Shattered Hand Assassins and causes a wipe.
Demo here recorded on GM account while a group attempted it: https://streamable.com/cuica
I asked them to stand away from the entrances to prove that it was not them pulling them.

**Expected behaviour:**

For the Shattered Hand Assassins to only engage if someone is close to them.

**Steps to reproduce the problem:**

1. Fight Kargath and he does Blade Dance
2. Shattered Hand Assassins pull and own healer

Warchief Kargath Bladefist: http://db.hellfire-tbc.com/?npc=16808
Blade Dance: http://db.hellfire-tbc.com/?spell=30739
Shattered Hand Assassin: http://db.hellfire-tbc.com/?npc=17695

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/37324574/56469690-4a7fed00-6480-11e9-830f-9a46c94ac831.png)

**Comment by Jerrythemagicdog** [comment]
Thanks for the video!

**Comment by Harrock1** [comment]
In addition to this, it seems as if the blade dance is targeting people. As per [this 2007 video](https://www.youtube.com/watch?v=47Cu92Ugeng) you can see that the boss will randomly blade dance around the room then charge a player, causing them high amount of damage whilst getting others hit by the blade dance. Can confirm thats a 2007 vid, clicking and keyboard turning included. This strategy was only available to normal mode. 

Just tried a heroic version of it and it seems the blade dance charges between random members. Then on blade dance end, charges 1 random player for 3k. From the video you can see he charges during his blade dance, causing it to damage that person and anyone in 15 yards.

**Comment by SUN-Leekie** [comment]
#1174

**Comment by kelno** [comment]
Seems fixed

**Comment by kelno** [comment]
Related 732bc15bbeeb39cda2ad119433deb6cfd58cecce
