### ISSUE TITLE
[Karazhan] Prince Malchezaar deals more damage than he should (evidence provided)

### ISSUE THREAD

**Issue by LoshyFirestorm** [thebarrensissues/Issues#1155]
**Description:**

Prince Malchezaar is dealing between 4-5k melee auto's against a 14k AC tank specced, def capped paladin.

**Current behaviour:**

Prince is dealing more damage than he should be doing (evidence below in expected behaviour)

**Expected behaviour:**

According to https://www.youtube.com/watch?v=ziHZPDRS_NQ  a video posted in 2007, Princes auto attacks should be doing between 2-2.8k.  During Thrash, there can be seen hits for 4134 at roughly 5:47 and 3025 at 5:33 on the vid.  Now, with a paladin in like-gear, they would have had roughly 14k AC and during these hit times did not appear to have inspiration (or similar) effect.

14k AC is roughly 57% physical DR (13830 armour is 56.71%).  Paladins also get an additional 6% DR from Improved Righteous Fury (Talent).  This would put the damage reduced to roughly 60% (60.1126 according to the aforementioned armour value as Imp RF is a multplier of all damage rather than additional).

This would put Princes Phase 1 damage, against an enemy with 0 armour and no additonal DR at 5000-7000 and during P2 7585-10335 (with the values outlined above from the video).

**Steps to reproduce the problem:**

CHANGEME
1. Be T4 raid ready tank
2. Get smacked by Prince
3. Be sad when thrash instagibs ya

 **rev. hash/commit:** 	

 
![image](https://user-images.githubusercontent.com/43313533/56470345-70a98b00-6488-11e9-8031-872592735c5d.png)

**Comment by Cheelout** [comment]
Please see: https://www.youtube.com/watch?v=5hI-8RhwhGU

I don't know if you are factoring in abilities like Demo shout (Did you have a warrior using it), Was Curse of Recklessness up on the boss.
I understand the above video is from another private server, but the damage is very similar.

**Comment by Cheelout** [comment]
https://www.youtube.com/watch?v=HTdvWZDBThk

Can see hits range from 900-6k throughout the fight, and they are not just high thrash hits, it is very dependant on debuffs on boss and buffs on tank.

I think the damage is fine.

**Comment by Cheelout** [comment]
![image](https://user-images.githubusercontent.com/38281939/56476409-7af47500-64da-11e9-8b67-336111bed30e.png)

That is on a level 1 warrior with 1 mil HP for testing purposes.
