### ISSUE TITLE
[Hunter] Explosive Trap

### ISSUE THREAD

**Issue by Azytheoneandonly** [thebarrensissues/Issues#1156]
**Description:**

Hunters Explosive Trap initial explosion is currently hitting friendly targets and other things it should not.

**Current behaviour:**

When Explosive trap is Triggered by an enemy it hurts everything nearby as you will be able to see in the Two demos below.
Explosive Trap Effect hits Netherstorm NPC: https://streamable.com/8pu53
Explosive Trap Effect Friendly Fire: https://streamable.com/hcg3d

**Expected behaviour:**

To only Apply to Enemy targets.

**Steps to reproduce the problem:**

1. Drop Explosive Trap any rank (tested all 4)
2. Have enemy trigger it.

Rank 1: http://db.hellfire-tbc.com/?spell=13812
Rank 2: http://db.hellfire-tbc.com/?spell=14314
Rank 3: http://db.hellfire-tbc.com/?spell=14315
Rank 4: http://db.hellfire-tbc.com/?spell=27026

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/37324574/56474775-de25dd80-64c1-11e9-9765-d2282ceb68a7.png)

**Comment by kelno** [comment]
But that's how explosions work mate

**Comment by kelno** [comment]
Fixed with 11151
