### ISSUE TITLE
Shade of aran ability 'Flame Wreath'

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#1160]
**Description:**
Flame Wreath is triggering after expiring

NPC ID  = 16524
Possible spell IDS all named Flame Wreath
29946
29947
30004

**Current behaviour:**

Flame Wreath will count down until expiry as long as you are stationary and will explode at the end.

**Expected behaviour:**

Flame Wreath should only trigger from movement, it should not trigger on expiration.
Source: https://wow.gamepedia.com/Shade_of_Aran#Flame_Wreath

**Steps to reproduce the problem:**

CHANGEME
1. Engage Shade of Aran
2. Wait until he casts Flame Wreath
3. Do not move and wait until debuff expires
4. Watch Flame Wreath trigger anyway.

 **rev. hash/commit:** 	
![image](https://user-images.githubusercontent.com/35262513/56544059-6c798c80-65b2-11e9-946b-10945bf8f085.png)

**Comment by kelno** [comment]
Fixed with 11194
