### ISSUE TITLE
Thalassian Charger Blood Elf Paladin Mount Quest.

### ISSUE THREAD

**Issue by freakhoo** [thebarrensissues/Issues#1161]
**Description:**

This quest teaches a Blood Elf Paladin to summon a Thalassian Charger. This quest is offered by Knight Lord Bloodvalor at lvl 60. The Quest name is 'A Summons from Lord Solanar' (https://www.wowhead.com/quest=9721/a-summons-from-lord-solanar). This quest if I remember correctly was 'A Summons from Lady Liadrin' in TBC (http://cata-shoot.tauri.hu/?quest=9721).  However we are asked to talk to Lord Solanar(https://www.wowhead.com/npc=25223/lord-solanar-bloodwrath), which I think is an NPC added in 2.4.0.

**Current behaviour:**

After accepting the quest, and checking online, Lord Solanar  is supposed to be near Mu'ru in the Paladin Training hall in Silvermoon. However, he is not there. But Lady Liadrin and Magister Bloodsworn are present there.

**Expected behaviour:**

I think you may have added the wrong quest. I think it should be 'A Summons from Lady Liadrin' instead of the quest you currently have. Maybe that's why even when I went to check at lvl 60, the quest indicated it is a (low level) quest. 

**Steps to reproduce the problem:**

Get a lvl 60 Paladin and talk to Knight Lord Bloodvalor, accept the quest 'A Summons from Lord Solanar' and try finding him here Mu'ru.

 **rev. hash/commit:** 	

![screens](https://user-images.githubusercontent.com/49869401/56548661-fd0c9880-65c3-11e9-8ac5-b4596b038833.png)

**Comment by SUN-Leekie** [comment]
Fixed in 11187.
