### ISSUE TITLE
[Engineering] Rocket Boots Xtreme

### ISSUE THREAD

**Issue by Azytheoneandonly** [thebarrensissues/Issues#1162]
**Description:**

 Rocket Boots Xtreme currently apply the speed whenever equipped and you can keep swapping your boots to get the boost while it is on cooldown.

**Current behaviour:**

Equip Boots: Get speed boost.
Use them and get the boost and they go on cooldown like normal.
equip them again and back and you have boost for 3-4 seconds as if you used the cooldown repeat as needed to travel around.

**Expected behaviour:**

Should not Apply the speed boost when you put the boots on.

**Steps to reproduce the problem:**

1. Apply Boots.

Item: http://db.hellfire-tbc.com/?item=23824
Spell: http://db.hellfire-tbc.com/?spell=51582

 **rev. hash/commit:** 	
![image](https://user-images.githubusercontent.com/37324574/56554723-fedf5780-65d5-11e9-93d4-2190d5dfbfaa.png)

**Comment by Azytheoneandonly** [comment]
Seems to be fixed.

![image](https://user-images.githubusercontent.com/37324574/56897104-ef2daa80-6ad0-11e9-99ee-7ef26af4c76b.png)

**Comment by SUN-Leekie** [comment]
Seems fixed to me too.
