### ISSUE TITLE
Able to learn a 3rd Primary profession, despite having 2 already.

### ISSUE THREAD

**Issue by ItsMeOldmate** [thebarrensissues/Issues#1163]
**Description:**

I have a 300 enchanting and 258 leatherworking and went to learn jewelcrafting from the NPC Tatiana <Master Jewelcrafting Trainer> at Honor Hold in Hellfire Peninsula.  I was able to learn the profession despite having 2 already.

**Current behaviour:**

Able to learn 3rd profession

**Expected behaviour:**

I should only be able to have a maximum of 2 professions.

**Steps to reproduce the problem:**

Have 2 professions.  Learn 3rd from a trainer in Hellfire Peninsula.

 **rev. hash/commit:** 	
![Untitled](https://user-images.githubusercontent.com/49894674/56555911-a8741800-65d9-11e9-9e14-4718b6c0a4dc.jpg)

**Comment by kelno** [comment]
Fixed with 11130
