### ISSUE TITLE
[Quest] Whispers of the Raven God

### ISSUE THREAD

**Issue by zemfi** [thebarrensissues/Issues#1165]
**Description:**

Killing the required NPC's doesnt apply the buff required for the quest

**Current behaviour:**

Killing Grishna Arakkoa NPC's doesnt yeild the required buff. Killed over 20+

Buff: Understanding Ravenspeech (#37642 ; #37466)
NPC: Grishna Falconwing (#19988)

**Expected behaviour:**

Killing the above NPC should yeild the buff applied to you, and able to continue with the quest

**Steps to reproduce the problem:**

1. Get Quest
2. Kill the endless npc's, no buff :(
3. quest uncompleteable

More Info: https://www.wowhead.com/quest=10607/whispers-of-the-raven-god#comments:id=25791

 **rev. hash/commit:** 	

 .rev 11061

**Comment by dinkletron** [comment]
Can confirm this, been attempting it tonight. Thanks for the log zemph!

**Comment by SUN-Leekie** [comment]
Fixed in 11302.
