### ISSUE TITLE
Swamplord Musel'ek (3rd boss UB) doesn't drop loot in heroic

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#1170]
**Description:**

Swamplord Musel'ek (3rd boss UB) doesn't drop loot in heroic

**Current behaviour:**

Swamplord Musel'ek (3rd boss UB) doesn't drop loot in heroic

**Expected behaviour:**

He should drop loot

**Steps to reproduce the problem:**

CHANGEME
1. Kill the boss; loot it; note only badge on body

http://db.hellfire-tbc.com/?npc=20183
rev 11061

**Comment by Cheelout** [comment]
On PTR
![image](https://user-images.githubusercontent.com/38281939/56671986-f5024500-66f8-11e9-86d4-c9f8e2ae981b.png)

**Comment by Kaziner** [comment]
![image](https://user-images.githubusercontent.com/45530324/56672550-fc761e00-66f9-11e9-8346-8810e81001bb.png)

**Comment by Cheelout** [comment]
![image](https://user-images.githubusercontent.com/38281939/56700852-adeb7280-673f-11e9-959c-3824ddaca026.png)

**Comment by Cheelout** [comment]
Please rekill and let me know.

**Comment by Cheelout** [comment]
Still fucked. Need to check reference.

**Comment by Cheelout** [comment]
Fixed with SQL Update:
UPDATE `creature_loot_template` SET `patch_min`=0 WHERE `Entry`=20183 AND `Item`=43003;
