### ISSUE TITLE
threat reduction trinkets don't seem to work

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#1172]
**Description:**
trinkets such as 
https://tbc-twinhead.twinstar.cz/?item=29181
timelapse shard don't seem to work
**Current behaviour:**
use timelapse shard on a mob that u have threat on by 100, you do not drop threat, the trinket should be removing 901 threat.
side issue is any mob in 30 yards is hiddenly put in combat with you aswell, it won't attack you but until it dies you are in combat.
**Expected behaviour:**
threat is put lower, and in the situation where the threat difference for target swapping is reached the mob changes targets.
mobs aren't hiddenly put in combat with you
**Steps to reproduce the problem:**
1. get threat on a target 
2. get someone else to match your threat
3. use the trinket where more than 10% of your threat would be removed in comparison to your friends
serverinfo
![visual](https://user-images.githubusercontent.com/47352954/56735614-466a0d00-67a9-11e9-9242-6e434d082e25.png)

**Comment by SUN-Leekie** [comment]
Fixed in 11314.
