### ISSUE TITLE
Warchief Kargath Bladefist Blade dance cooldown

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#1174]
**Description:**

Warchief Kargath Bladefist's ability Blade Dance is being cast too frequently.

**Current behaviour:**

Blade dance is being cast too soon when engaging and too frequently during the fight. ~20 sec cd.

**Expected behaviour:**

Blade Dance should only be cast from 30 seconds from engagement and 30 seconds from the END of the last Blade Dance.
Source: https://wow.gamepedia.com/Warchief_Kargath_Bladefist#Basic_strategy
'Kargath's special ability is "Blade Dance". He will first use it 30 seconds after being engaged, and then every 30 seconds from the *end* of the previous Blade Dance.'

Video evidence: https://www.youtube.com/watch?v=UzQEPwf8eyY
Date: Oct 13, 2007

**Steps to reproduce the problem:**

CHANGEME
1. Engage Warchief Blade Dance and start timer
2. Watch as he Blade Dance's before 30 seconds
3. Watch as he Blade Dance's again far sooner than 30 seconds after he finishes previous Blade Dance

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/35262513/56745163-001caa00-67b9-11e9-8594-6872fa4064a2.png)

**Comment by Cheelout** [comment]
We have implemented a spell override to reduce the damage by ~35% on Heroic as it was 1 shotting most players.

**Comment by kelno** [comment]
The cooldown is currently 30s from the end of the last dance.
