### ISSUE TITLE
Unstuck while a Ghost causes you to die as a Ghost.

### ISSUE THREAD

**Issue by Azytheoneandonly** [thebarrensissues/Issues#1179]
**Description:**

Casting Auto-Unstuck while a ghost seems to port character to the GY as a ghost and unable to revive and requires assistance from a GM to revive.

**Current behaviour:**

As above.

**Expected behaviour:**

Should port you and your Corpse to the GY instead.

**Steps to reproduce the problem:**

1. Be ghost and unable to get to body and use unstuck.
2. Ported to GY as a ghost and .. be stuck dead as a ghost.

if you need a demo let me know i'll go make one.

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/37324574/56802114-8b05af00-6862-11e9-9c96-d9489b1ac10b.png)

**Comment by kelno** [comment]
Fixed with 11549
