### ISSUE TITLE
[Shaman] Healing Way

### ISSUE THREAD

**Issue by artieau** [thebarrensissues/Issues#1180]
**Description:**

The talent Healing Way 1/2/3 is providing the incorrect amount of bonus% to healing per stack/talent point spent.
Healing Way Talent 1/3 = Spell ID 29206
Healing Way Talent 2/3 = Spell ID 29205
Healing Way Talent 3/3 = Spell ID 29202
The above spell is to interact with Healing Wave - for example Spell ID 25396

**Current behaviour:**

Each stack of Healing Way is providing the full 3/3 stacks bonus, on EVERY stack.

- First heal on the target without any Healing Way buff = normal heal, lets say 1000 healing.

 - Second heal on the target who now has 1 stack of Healing Way (6% bonus) = 1180 healing 
(actually 18% bonus over initial heal)

 - Third heal on the target who now has 2 stacks of Healing Way (12% bonus) = 1392 healing 
(actually 39% bonus over initial heal)

 - Fourth heal on the target who now has 3 stacks of Healing Way (18% bonus) = 1643 healing (actually 64% bonus over the initial heal)

**Expected behaviour:**

Each stack should ONLY provide 6% bonus healing to Healing Wave, not 18% per stack.
It should be a total of 18% healing bonus at 3 stacks.
For example, initial heal of 1000 = a heal of 1180 on a target with 3 stacks.

**Steps to reproduce the problem:**

CHANGEME
1. see above, go fully naked on a resto spec shaman and heal with rank 12 healing wave
2. Heal with 1 stack
3. Heal with 2 stacks
etc

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/40563134/56815284-4e4aaf80-6884-11e9-817e-aa1c6b4e8899.png)

**Comment by artieau** [comment]
![image](https://user-images.githubusercontent.com/40563134/56815373-86ea8900-6884-11e9-8ad3-808e015dc5a8.png)
This shouldn't happen, especially in blue gear LOL

**Comment by Azytheoneandonly** [comment]
was that 12532 crit on a warlock with fel armor?

**Comment by artieau** [comment]
That example in the picture was on a warlock, a bad example to use for this ticket.
To make it clearer, remove all items from the character and do the above steps with Healing Wave rank 12.
First heal ~2400 with 0 gear or totems on a normal player.
Second heal should be ~2544 however it will land for ~2832
Third heal should be ~2688 however it will land for ~3341
Fourth heal should be ~2832 however it will land for ~3943
@Azytheoneandonly

**Comment by kelno** [comment]
Fixed with 11110
