### ISSUE TITLE
[Heroic Black Morass] Chrono-beacon

### ISSUE THREAD

**Issue by HueHueTBCTheBarrens** [thebarrensissues/Issues#1181]
**Description:**
[Chrono-Beacon](https://tbc-twinhead.twinstar.cz/?item=24289) (24289) 
![image](https://user-images.githubusercontent.com/29525708/56843106-24bf7180-68e0-11e9-8fdb-7dfdd3ec4da8.png)
Summons a hostile add. 

**Expected behaviour:**

shouldnt be hostile

 **rev. hash/commit:** 	
![image](https://user-images.githubusercontent.com/29525708/56843172-b0390280-68e0-11e9-80c8-e9e3c809574b.png)

**Comment by giveusmezpls** [comment]
confirmed.
![image](https://user-images.githubusercontent.com/49624667/56843243-90eea500-68e1-11e9-9ed3-65ccda71e9b0.png)

**Comment by artieau** [comment]
On normal mode, he beacon spawns a friendly dragon but it just stands there and does nothing

**Comment by giveusmezpls** [comment]
so it spawns an artie dragon

**Comment by kelno** [comment]
Fixed
