### ISSUE TITLE
Mindflay doesn't stack with multiple shadow priests

### ISSUE THREAD

**Issue by chickentango** [thebarrensissues/Issues#1182]
**Description:**

Mindflay doesn't stack with multiple shadow priests

**Current behaviour:**

The shadow priest with less SP gets a notification that a 'more powerful spell is active'

**Expected behaviour:**

All shadow priests should be able to case mind flay on a single target

**Steps to reproduce the problem:**

Mind Flay interrupts, Shadow weaving not stacking w/ multiple shadow priests #1148

The above bug wasn't fixed. I ran Gruul on Thursday with another SP and the other SP couldn't use mind flay.

**Comment by nafsepz** [comment]
Tested 28/04 (rev 11082) - confirm that mind flay still fails to stack on a target, however shadow weaving appears to be functioning correctly.

**Comment by Kaziner** [comment]
May be linked to the recent change where slows no longer stack and more impairing slows dispel less impairing slows (Eg crippling poison being applied to a target would remove hamstring from it)

**Comment by kelno** [comment]
Fixed with 11148
