### ISSUE TITLE
Shadowfiend doesn't attack

### ISSUE THREAD

**Issue by chickentango** [thebarrensissues/Issues#1183]
**Description:**

Shadowfiend doesn't attack

**Current behaviour:**

When a priest summons a shadow fiend it doesn't attack right away, instead sunning back to the priest as if it's passive. The priest needs to manually tell it to attack the target which works sometimes but others the priest needs to set it to passive then tell it to attack.

**Expected behaviour:**

The shadow fiend attacks the targeted mob upon summon

**Comment by Cheelout** [comment]
Also impacting Water Elemental SpellID=31687

**Comment by giveusmezpls** [comment]
it appears that shadow fiend after being summoned correctly behind the mob and attacking sometimes once or trying to attack is issued a defensive mode command and then returns to the priest. he is useless in the meanwhile.

**Comment by kelno** [comment]
Duplicate https://github.com/thebarrensissues/Issues/issues/1016 ?

**Comment by giveusmezpls** [comment]
@kelno yes they are the same issue(s).
