### ISSUE TITLE
Can see the opposing faction ghosts while dead

### ISSUE THREAD

**Issue by Tamosheik** [thebarrensissues/Issues#1185]
**Description:**
If two opposite-faction players are dead they are able to see each other while in ghost form.

**Expected behaviour:**
Players should not be able to see ghosts cross-faction

 **rev. hash/commit:** 	
rev 11082

**Comment by artieau** [comment]
Regression? See #882

**Comment by kelno** [comment]
Fixed with 11547

**Comment by kelno** [comment]
I think it was never fixed in the first place.
https://github.com/kelno/sunstrider/commit/88bf7ab7ecdd9159378f20aa6cef017c075b61b1
