### ISSUE TITLE
Murmur using anti-ranged ability incorrectly.

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#1186]
**Description:**

Murmur in Shadowlabs is currently using 'Resonance' [33657] incorrectly.

**Current behaviour:**

Resonance is being cast regardless of the range of players and whether there is someone in melee or not.

**Expected behaviour:**

Murmur should only cast Resonance if there is 0 targets within melee range.

**Steps to reproduce the problem:**

CHANGEME
1. Engage Murmur
2. Watch him cast Resonance even with melee next to him

 **rev. hash/commit:** 	
![image](https://user-images.githubusercontent.com/35262513/56857274-98c64c00-69aa-11e9-8e6d-aee90f98814e.png)

**Comment by giveusmezpls** [comment]
Added comments to Normal and Heroic Murmur issues #1137
suggest we close #1186 as duplicate to place all Murmur related issues into one location.
