### ISSUE TITLE
[Quest] Fel Reavers, No Thanks! 

### ISSUE THREAD

**Issue by Azytheoneandonly** [thebarrensissues/Issues#1190]
**Description:**

Fel Reavers, No Thanks! is currently giving you progress while in a group but because other characters did not complete the Inactive Fel Reaver quest it is unable to be handed in while saying it is complete.

![image](https://user-images.githubusercontent.com/37324574/56860403-a646fa80-69d9-11e9-8f06-4f9cf309b9d4.png)

![image](https://user-images.githubusercontent.com/37324574/56860411-c1b20580-69d9-11e9-9724-bd326fc9aa39.png)

**Current behaviour:**

As above.

**Expected behaviour:**

Either not give group credit or auto complete quest 10850 when someone in group completes while in range.

**Steps to reproduce the problem:**

1. Collect 5x Condensed Nether Gas(Quest item)
2. Talk to Inactive Fel Reaver
3. Group gets credit for quest but is unable to hand in.

Quest: http://db.hellfire-tbc.com/?quest=10855
Quest for Inactive Fel Reaver: http://db.hellfire-tbc.com/?quest=10850
Inactive Fel Reaver: http://db.hellfire-tbc.com/?npc=22293
Quest Item: http://db.hellfire-tbc.com/?item=31653

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/37324574/56860375-50725280-69d9-11e9-8c53-1cc60141cc03.png)

**Comment by zemfi** [comment]
Consolidated: #1204

**Comment by kelno** [comment]
Fixed with 11513
