### ISSUE TITLE
Creature not gaining UNIT_STATE_MELEE_ATTACKING if the victim is not within melee range at pull or aggro switch

### ISSUE THREAD

**Issue by SUN-Leekie** [thebarrensissues/Issues#1192]
**Description:**
Title

**Current behaviour:**
https://streamable.com/qpvan

**Expected behaviour:**
Unit should be ready to attack!

**Comment by Jerrythemagicdog** [comment]
https://github.com/thebarrensissues/Issues/issues/1128

**Comment by kelno** [comment]
DUPLICATE, CLOSING
