### ISSUE TITLE
[Dungeon] Escape From Durnholde

### ISSUE THREAD

**Issue by zemfi** [thebarrensissues/Issues#1193]
**Description:**

Probably a regression bug, after defeating the last boss, Thrall just stands there and doesnt proceed with the quest

**Current behaviour:**

As Above

**Expected behaviour:**

Should be able to continue and complete the quest.

**Steps to reproduce the problem:**

1. Start quest Escape From Durnholde (#10284)
2. Proceed through the quest and kill the last boss.
3. Thrall Just stands there, cant complete quest.

![thrall](https://user-images.githubusercontent.com/46832429/56898908-885ec000-6ad5-11e9-88ba-867892b94cbc.png)

 **rev. hash/commit:** 	

.rev 11098

**Comment by Jerrythemagicdog** [comment]
the dungeon is being reworked
