### ISSUE TITLE
[Quest] Evil Draws Near

### ISSUE THREAD

**Issue by zemfi** [thebarrensissues/Issues#1194]
//READ COMMENTS//

**Description:**

Unable to hand in quest: Evil Draws Near (#10923) after completion (days after).

**Current behaviour:**

Completed this quest in a group (one other), last week and forgot to hand it in, i assume he did, i went back today and unable to hand it in, with it being complete in the quest log (and still have the quest item).

**Expected behaviour:**

Should be able to hand in the quest to complete it.

**Steps to reproduce the problem:**

1. Accept quest, get a second player that is also on quest.
2. Other player gets the required items, you both kill the Summoned NPC
3. Cant Hand-in

Required Item: Dread Relic (#31811)
NPC To Kill: Teribus the Cursed (#22441)

![evildrawsnear](https://user-images.githubusercontent.com/46832429/56937540-95fd5f80-6b40-11e9-9fb3-5d9d21cdb131.jpg)

![evildrawsnear2](https://user-images.githubusercontent.com/46832429/56937569-b6c5b500-6b40-11e9-9825-3026a8e067ec.jpg)

 **rev. hash/commit:** 	

.rev 11098

**Comment by BarrensJerk** [comment]
If the other person in the group actually did the summoning it won’t complete for you. Every person in the group needs to collect 30 skulls and use the item. You don’t need to kill the bone dragon, just need to do the summon.

Not saying it isn’t bugged, just if you wanted to complete it before it gets fixed try that

**Comment by zemfi** [comment]
confirmed, thats whats happened here.

Speaks to a bigger issue that if players are in a grp and they do quests and some have requirements for quest objectives to complete, and not all players meet the requirements but still complete the quest objectives (marked complete in questlog), should be able to hand the quest in regardless.

**Comment by zemfi** [comment]
Consolidated: #1204

**Comment by kelno** [comment]
Fixed with 11516
