### ISSUE TITLE
[SSC ] - Fathom Lord Karathress - Fathom-Guard Tidalvess - Heal not uninterruptable

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1196]
**Description:**

Healing Wave on mob is currently immune to interrupt

**Current behaviour:**

Healing Wave on mob is currently immune to interrupt

**Expected behaviour:**

https://www.wowhead.com/npc=21964/fathom-guard-caribdis

https://www.wowhead.com/spell=38330/healing-wave

https://wowwiki.fandom.com/wiki/Fathom-Lord_Karathress

Healing Wave: Single target heal unrestricted by LoS or range, cast on any mob or herself, heals 20-30% of the target's total HP. Interruptible, 15s cooldown

**Steps to reproduce the problem:**

CHANGEME
1. Engage fight
2. Try and interrupt healing wave

11111

**Comment by SUN-Leekie** [comment]
It should be interruptable from spell_template data (13). It is a core issue.

**Comment by Cheelout** [comment]
This is now ignoring LoS

**Comment by kelno** [comment]
@SUN-Leekie Spells is interruptable when casted by other creatures

Caribdis has mechanic immune flag: 650854271
-> MECHANIC_INTERRUPT is in there

**Comment by Cheelout** [comment]
I believe the value needs to be 617,299,839‬

**Comment by Cheelout** [comment]
-- Remove MECHANIC_INTERRUPT
UPDATE `creature_template` SET `mechanic_immune_mask` = `mechanic_immune_mask` ~ &0x2000000‬ where `entry` = 21964;

**Comment by Kaziner** [comment]
This is confirmed fixed last night
