### ISSUE TITLE
[SSC] - The Lurker Below - Ranged are pulling threat when they should not be able too

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1197]
**Description:**

Ranged are pulling threat when they should not be able too

**Current behaviour:**

Ranged should not be able to be targeted by Lurker Below for melee attacks when at range, but this is happening. Lurker should only target highest threat in Melee range (Except for casting abilities on range targets IE Geyser)

**Expected behaviour:**

https://wow.gamepedia.com/The_Lurker_Below

The combat starts with the Lurker on the surface. It's rather straightforward tank and spank, except for Spout and Whirl. Aggro is hardly an issue—as long as there are targets in melee range, the Lurker does not attack ranged targets except for a random Geyser now and then. The Lurker can also be taunted. After two minutes, the Lurker submerges (which also removes all debuffs from him), adds turn up and Phase 2 starts. The Lurker re-emerges 60 seconds later and Phase 1 starts again.

**Steps to reproduce the problem:**

CHANGEME
1. Engage Lurker with Tank
2. Spam spells at range, observe him just target that character and do nothing

11111

**Comment by SUN-Leekie** [comment]
Fixed in 11327.

**Comment by Cheelout** [comment]
Now it seems like lurker is constantly dropping threat on the main tank.

**Comment by giveusmezpls** [comment]
all the melee took turns dying, felt like hateful strike lurker

**Comment by SUN-Leekie** [comment]
The tank *might* want to be the closest to the Lurker.

**Comment by Cheelout** [comment]
https://www.twitch.tv/videos/426899401?t=02h27m51shttps://www.twitch.tv/videos/426899401?t=02h27m51s

The tank is the closest to Lurker. Also, As long as the tank is in range of being hit being the closest is irrelevant.

**Comment by kelno** [comment]
Fixed recently
