### ISSUE TITLE
[SSC] - The Lurker Below - Spout - Hitting people in water

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1201]
**Description:**

Spout - Hitting people in water

**Current behaviour:**

The Spout ability is currently hitting people floating in water, it is not meant to hit them. Only when on platforms or higher

**Expected behaviour:**

Spout should not hit players floating in water.

https://wow.gamepedia.com/The_Lurker_Below

Spout
Spout is the main reason for wipes on this boss; the whole raid has to learn how to avoid it. Boss mods usually give a 3-second warning, and it's best to immediately jump in the water when the warning comes up. Ranged DPS and healers can continue to do their job while in the water by swimming a little deeper to gain line of sight. After the beam has passed, it's safe to return to the platforms. The tank and everybody close to him need to pay attention—the beam starts at the tank and rotates for a little more than 360°. Each spout is closely followed by a Whirl.

https://www.youtube.com/watch?v=jTegfdTJpEw&t=13s

**Steps to reproduce the problem:**

CHANGEME
1. Engage Lurker
2. Wait for spout
3. Hop in water and get hit by spout :(

 **rev. hash/commit:** 	

11111

**Comment by giveusmezpls** [comment]
This does not occur any longer since recent Lurker changes.
