### ISSUE TITLE
Shy-Rotam - Cannot be turned in

### ISSUE THREAD

**Issue by mattisamo** [thebarrensissues/Issues#1203]
**Description:**
Did the quest "Shy-Rotam" (https://the-barrens.org/armory/database/quest?id=5056) as part of a group. My other group member looted the required item, [Sacred Frostsaber Meat](https://vanilla-twinhead.twinstar.cz/?item=12733) and summoned the boss.
Upon defeating the boss, we both got credit and it says complete in the q-log, however only my friend could turn it in.
https://cdn.discordapp.com/attachments/557626093654376458/572480665413746709/unknown.png
https://cdn.discordapp.com/attachments/557626093654376458/572480736989544458/unknown.png
**Current behaviour:**

Gives credit, can't be turned in

**Expected behaviour:**

Able to turn in.

**Steps to reproduce the problem:**
1. Acquire quest
2. Have one member of the party loot the meat.
3. Summon boss, kill
4. ???
5. No profit

 **rev. hash/commit:** 
Sunstrider rev. 11111(61884a1e0187+) 2019-04-29 20:00 -0400 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by zemfi** [comment]
Consolidated: #1204

**Comment by zemfi** [comment]
To fix this issue, make sure each person has the required item, and summons it themselves, and you _should_ be able to hand it in.

**Comment by kelno** [comment]
Fixed with 11516
