### ISSUE TITLE
Quest Hand-Ins Not Working Properly In Groups (Expanded)

### ISSUE THREAD

**Issue by zemfi** [thebarrensissues/Issues#1204]
**Description:**

Seems to be a pattern where players in groups that do the same quest together, and all players having the quest marked completed, but some players not able to actually hand it in.

**Current behaviour:**

This issue seems to stem when not **every player** has the requirements to complete the  objective(s) for the quest, but one or more players that do, and the objective is met, and marked complete, but those players that didnt meat the requirements cant hand-in the quest, even though its complete.

eg. you need to collect x item, to summon y boss to kill, and y is the objective of the quest, and x is the requirement not every player obtained, but all of them participated in the kill of y and marked complete.

**Expected behaviour:**

Players should be able to hand-in marked completed quests.

**Steps to reproduce the problem:**

The following open issues have this problem:

#1203 #1194 #1190

 **rev. hash/commit:** 	

.rev 11111

**Comment by kelno** [comment]
Thanks for that

**Comment by giveusmezpls** [comment]
in addition if a player collects all and returns to bank/reacquire he should be able to turn them in.

**Comment by kelno** [comment]
Fixed with 11516.
Note that this is again a per quest issue so there might be other similar quests with issues. I fixed some more I found that were not listed here.
