### ISSUE TITLE
Pets's modifiers in creature_template are not being used (except mana & health)

### ISSUE THREAD

**Issue by SUN-Leekie** [thebarrensissues/Issues#1205]
**Description:**
Title

**Current behaviour:**
For example, Karathress's Guard, Fathom-Guard Sharkkis has 2 possible pets.
When he summons them, they hit for very low even though they should for ~2k according to their modifiers.

**Expected behaviour:**
Pets like this should have all of their data affected by modifiers.

See code in Pet.cpp @ 1197.
```cpp
CreatureBaseStats const* stats = sObjectMgr->GetCreatureBaseStats(petlevel, cinfo->unit_class);
SetCreateHealth(stats->BaseHealth[cinfo->expansion] * cinfo->ModHealth); //sun: added ModHealth and ModMana. Example spell 31476
SetCreateMana(stats->BaseMana * cinfo->ModMana);
```

Needs something like below with the function to calculate damage:
```cpp
if (owner->GetTypeId() == TYPEID_UNIT)
{
    const uint32 minDamage = (stats->AttackPower / 28.f + stats->BaseDamage[cinfo->expansion] * 2) * cinfo->ModDamage;
    const uint32 maxDamage = minDamage * (1.f + cinfo->BaseVariance);
    SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, minDamage);
    SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, maxDamage);
}
```
Not sure about the `if`, just put it as a safeguard.

**Comment by kelno** [comment]
Fixed with 11195
