### ISSUE TITLE
Quest: Uncatalogued Species

### ISSUE THREAD

**Issue by imtrollingu** [thebarrensissues/Issues#1206]
**Description:**

Quest: Uncatalogued Species. https://tbcdb.com/?quest=9875

**Current behaviour:**

Uncatalogued Species item doesn't allow you to accept the quest at Revered reputation.

**Expected behaviour:**

Item provides a quest to accept that you can hand in for reputation with Cenerion Expedition. https://tbcdb.com/?item=24407

**Steps to reproduce the problem:**

CHANGEME
Right clicked the item and accepted the quest. Removed WDB folder and restarted the game. Error: You don't meet the requirements for that quest

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

 **rev. hash/commit:** 	

 CHANGEME	
![WoWScrnShot_050119_190526](https://user-images.githubusercontent.com/42865804/57011294-486a1b00-6c44-11e9-9894-3db57d00141d.jpg)

**Comment by SUN-Leekie** [comment]
This quest is unavailable once you reach Revered as intented.
