### ISSUE TITLE
[Quest] You're Fired - ID 10821

### ISSUE THREAD

**Issue by dinkletron** [thebarrensissues/Issues#1208]
Description:

The required mob Doomcryer (NPC ID 19963) does not stay active long enough to kill. She despawns after roughly 10 seconds.

Current behaviour:

When you summon her with the 5 Camp Anger Keys, she appears as normal, once you engage her, it only takes her about 10 seconds to despawn.

**Expected behaviour:**

She should not despawn, and should be kite-able and have a decent leash range as well.

**Steps to reproduce the problem:**

1) Accept quest 'You're Fired!' - ID 10821
2) Obtain 5 x Camp Anger Keys (Item ID 31536) from Anger Guard (NPC ID 16952)
3) Click Obelisks relating to quest to start channeling and summoning boss NPC.
4) Engage Doomcryer (19963) and wait for despawn.

 **rev. hash/commit:** 	

 
![Capture](https://user-images.githubusercontent.com/29308094/57050282-29f53580-6cbf-11e9-9180-a2ffca798c46.JPG)

**Comment by SUN-Leekie** [comment]
Fixed in 11296.
