### ISSUE TITLE
[Paladin] Judgement of Command Higher Ranks do not work

### ISSUE THREAD

**Issue by flubbyguty** [thebarrensissues/Issues#1210]
**Description:**

Using any rank above rank 1 of Seal of Command and then casting judgement only does the damage of the rank 1 seal.

**Current behaviour:**

Rank 2-6 Seal of Command damage when casting Judgement only hits for the amount of Rank 1. 

**Expected behaviour:**

The damage done by the spell when judgement is cast should increase with spell rank.

**Steps to reproduce the problem:**

1. Be a paladin in retribution spec with a couple ranks of Seal of Command.
2. Apply Seal of Command highest rank, and then cast judgement on any enemy target.
3. Notice it only hits for Rank 1 numbers. 

SoC Rank 1 - https://tbcdb.com/?spell=20375
SoC Rank 6 - https://tbcdb.com/?spell=27170
Judgement - https://tbcdb.com/?spell=20271

Tested on mobs all around Outland. Mob type doesnt seem to effect it. 
![WoWScrnShot_050219_153536](https://user-images.githubusercontent.com/49171826/57061848-06e37980-6cf1-11e9-9b65-ac357ca38501.jpg)
![WoWScrnShot_050219_153544](https://user-images.githubusercontent.com/49171826/57061856-0e0a8780-6cf1-11e9-92cc-81ca56d556d6.jpg)

 **rev. hash/commit:** 	

![InkedWoWScrnShot_050219_153555_LI](https://user-images.githubusercontent.com/49171826/57061871-19f64980-6cf1-11e9-86ff-6096c17f942b.jpg)

**Comment by SUN-Leekie** [comment]
Fixed in 11291.
