### ISSUE TITLE
Gruul is Hurtful Striking inconsistently

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1211]
**Description:**

Gruul is Hurtful Striking inconsistently.

**Current behaviour:**

Gruul is Hurtful Striking inconsistently.

**Expected behaviour:**

https://wow.gamepedia.com/Gruul_the_Dragonkiller_(tactics)

Hurtful Strike: always hits the second highest aggro target within his melee range; therefore essential that any melee dps classes maintain their aggro level not only below that of the MT, but also below that of the OT. The base damage on Hurtful Strike is 12,350-13,650 (this, of course, is reduced by armor,  [Defensive Stance], etc.). A Hurtful Strike is performed on average every 20 seconds.

**Steps to reproduce the problem:**

CHANGEME
1. Engage Gruul
2. Observe how many Hurtfuls he does

 **rev. hash/commit:** 	

11118

**Comment by Cheelout** [comment]
By inconsistent I mean he can cast it twice per fight.. or 6 times.. or 20

**Comment by kelno** [comment]
Fixed with 11542

**Comment by kelno** [comment]
973e8faadd699ec154b57c5c7a4326b3a5d901a1
