### ISSUE TITLE
mount icons on your bars

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#1214]
**Description:**
mount icons on your action bars do not grey out when they are unusable
**Current behaviour:**
they stay lit up when inside
**Expected behaviour:**
they grey out when you cannot use them, ie indoors/in combat etc
rev. 11132

**Comment by kelno** [comment]
I'm almost sure there is no fix for that, the server does not tell the client this information but the client decides for himself when to grey out actions in bar.
