### ISSUE TITLE
Chair in Stormwind PvP area not functioning properly

### ISSUE THREAD

**Issue by giveusmezpls** [thebarrensissues/Issues#1216]
**Description:**

Chair not working well, perhaps contact IKEA ?

**Current behaviour:**

![image](https://user-images.githubusercontent.com/49624667/57136714-092cfd00-6df1-11e9-85d8-d209b9af1095.png)

**Expected behaviour:**

![image](https://user-images.githubusercontent.com/49624667/57136741-177b1900-6df1-11e9-96cf-eedef24e27dd.png)

**Steps to reproduce the problem:**

1. Go to Stormwind PvP area
2. Click chair
3. Whoops!

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/49624667/57136773-2bbf1600-6df1-11e9-840b-f0a0facafb08.png)

**Comment by Cheelout** [comment]
You are actually scum Jaysue.

**Comment by giveusmezpls** [comment]
All the chairs facing this way work. Guess that all chairs have the same programmed facing direction.

![image](https://user-images.githubusercontent.com/49624667/57136992-df280a80-6df1-11e9-9edf-6db8bc359845.png)

**Comment by kelno** [comment]
Fixed with 11252
