### ISSUE TITLE
Old Hillsbrad Thrall quest issue

### ISSUE THREAD

**Issue by Azibeel** [thebarrensissues/Issues#1217]
**Description:**

Cannot talk to Thrall after killing Captain Skarloc so can't start the second phase of Escape From Durnholde.

**Current behaviour:**

Killed Captain Skarloc and Thrall just stands looking towards the keep uninteractable

**Expected behaviour:**

After Captain Skarloc dies there should be a dialogue option with Thrall which makes him mount up and start moving towards Tarren Mill.

**Steps to reproduce the problem:**

Killed Captain Skarloc with a group consisting of Mage, Warrior, Priest, Shaman and Rogue. Not sure if it is unusual but Thrall was running from group to group on the way to the boss, it seemed faster than I recall.

 **rev. hash/commit:** 	

This was done approx 40 mins after bug.	
Sunstrider rev. 11132 (9ad389c8b78a+) 2019-05-02 17:04:02 +0200 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by zemfi** [comment]
Apparently the dungeon and that quest is being "re-worked" atm, heres my report of a similar issue a bit further on.. #1193

**Comment by giveusmezpls** [comment]
Re-tested after recent changes to dungeon does not occur any longer.
