### ISSUE TITLE
[Quest] The Infected Protectors: Wood Mites not spawning

### ISSUE THREAD

**Issue by ItsMeOldmate** [thebarrensissues/Issues#1220]
**Description:**

Wood Mites are meant to spawn after killing either Infested Root-Walker) or Rotting Forest-Ragers

**Current behaviour:**

Wood Mites do not spawn.

**Expected behaviour:**

Multiple Wood Mites (approx 4-6) should spawn upon the death of the relevent npcs.

**Steps to reproduce the problem:**

[https://wotlk-twinhead.twinstar.cz/?npc=22095](url)

NPCS
Wood Mite (#22419)
Infested Root-Walker  (#22095)
Rotting Forest-Rager (#22307)

Go to the outer edges of the Bone Wastes of Terokkar Forest and kill either an Infested Root-Walker or Rotting Forest Rager to spawn the Wood Mites.

I killed the npcs as a druid in cat form using both my abilities and melee swings as killing blows on the npcs.

 **rev. hash/commit:** 	

![Untitled](https://user-images.githubusercontent.com/49894674/57173061-9bbeb200-6e6c-11e9-9b08-4eccc5d6c603.png)

**Comment by giveusmezpls** [comment]
It looks like the wood mites do spawn but instantly despawn due to the master of the summoned created dying.

**Comment by SUN-Leekie** [comment]
Fixed in 11310.
