### ISSUE TITLE
[Crash] Server Crashes when Ability / Item breaks a "Fear" Spell

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1221]
**Description:**

Server is crashing anytime a player breaks fear using an ability or item.

**Current behaviour:**

If a player breaks a "fear" spell the server will crash. The server does not crash if the full duration ends.

Spell=8122 - Psychic Scream
Spell=11958 - Ice Block

Happens on Mob and Warlocks fears as well. Tested breaking with PVP Trinket and Beserker Rage too.

**Expected behaviour:**

Server should not crash.

May be related to heart beat resist change from last night

**Steps to reproduce the problem:**

CHANGEME
1. Get feared
2. Break with ability or item

 **rev. hash/commit:** 	
11145

**Comment by kelno** [comment]
https://i.imgur.com/0o22N5E.png

leaderGUID = 1019115

**Comment by kelno** [comment]
Fixed with 11146
