### ISSUE TITLE
[Item] Flame Cap - Proc is incorrectly scaling with Spell Power

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1225]
**Description:**

Flame cap is incorrectly scaling with Spell Power on the Melee Attack Proc

**Current behaviour:**

ItemID: 22788 - https://www.wowhead.com/item=22788/flame-cap
SpellID: 28714 - https://www.wowhead.com/spell=28714/flame-cap

**Expected behaviour:**

This item should not scale with spell power for the melee hit portion of the proc.

https://www.wowhead.com/spell=28714/flame-cap#comments

Extract Below:
By bogdan (6,370 – 5·34·117) on 2007/05/27 (Patch 2.1.0) 

Using this item gives you a one minute buff.

Unlike many other buffs available this is usable by every class somehow, and if you don't have a conjured consumable its some free added dps. It does indeed proc on wand cast.

Hits for ~40 and for me crit for ~65 on a wand hit.

Bored priest in Shattered Halls, for the win...

**Steps to reproduce the problem:**

CHANGEME
1. STack Spell Spower
2. Use Flame Cap
3. Auto and watch ridiculous proc numbers.

 **rev. hash/commit:**

11165

**Comment by giveusmezpls** [comment]
Oh now i found trip's github account since surely he is the one to log this bug.

**Comment by SUN-Leekie** [comment]
Fixed in 11184.
