### ISSUE TITLE
flametongue weapon incorrect spell scaling

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#1229]
**Description:**
flametongue weapon isn't scaling off a flat amount of 10% of your spell power
https://tbc-twinhead.twinstar.cz/?spell=25489
**Current behaviour:**
with my 1.3 speed daggers, when i place wrath of air totem which is 101 spell power, it only adds 5 damage per hit
**Expected behaviour:**
wrath of air adds 10.1 damage

this may be due to the attack speed scaling of the spell incorrectly affecting the spell power scaling, which it should not be doing
https://wowwiki.fandom.com/wiki/Flametongue_Weapon - patches explaining spell power in wotlk now being affected by speed
https://blue.mmo-champion.com/topic/18050-tbc-enhancement-shaman-faq/
post explaining it
"- Benefits from 10% of your spell damage per hit. This additional damage ignores weapon speed, so if you're elemental get the fastest dagger can you find. "
rev. 11165

**Comment by SUN-Leekie** [comment]
Fixed in 11180.
