### ISSUE TITLE
frostbrand weapon incorrect spellpower scaling

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#1230]
**Description:**
frostbrand weapon is scaling with 43% spell power instead of 10%
https://tbc-twinhead.twinstar.cz/?spell=25500
https://wowwiki.fandom.com/wiki/Frostbrand_Weapon
**Current behaviour:**
hit with 330 spell power, 200 base frostbrand damage= 350 damage to enemy
**Expected behaviour:**
hit with 330 spell power, 200 base frostbrand damage= 233 damage to enemy
rev. 11165

**Comment by SUN-Leekie** [comment]
Fixed in 11180.
