### ISSUE TITLE
[Tempest Keep ] - Void Reaver - Hitbox small

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1233]
**Description:**

Void Reaver's hitbox is too small causing issues for ranged when attacking. Ranged can only stack out to the circle, should be able to move further back.

**Current behaviour:**

Hitbox is smaller then normal

**Expected behaviour:**

https://www.wowhead.com/npc=19516/void-reaver
https://www.youtube.com/watch?v=jmwBZAl9EqY

Observe that the ranged in the above are a few steps if not more depending on class behind the circle allowing for more spread.

Melee should be able to stand a bit back from the boss as well

**Steps to reproduce the problem:**

CHANGEME
1. Engage VR in TK
2. Observe Max range as ranged and hitbox as melee

 **rev. hash/commit:** 	

11175

**Comment by kelno** [comment]
To dev:
His combatreach is only 2...
`SELECT * creature_model_info WHERE modelid = 18951;`
Dunno what the correct value is

**Comment by kelno** [comment]
Fixed with 11295
