### ISSUE TITLE
The spell Thrash which procs 2 melee attacks works with unlimited range

### ISSUE THREAD

**Issue by giveusmezpls** [thebarrensissues/Issues#1237]
**Description:**

The spell Thrash which procs 2 melee attacks works with unlimited range allowing for strange interaction when range have threat they can melee attack twice instantly regardless of distance.

**Current behaviour:**

The current behaviour allows the thrash spell (spell=3391) to be utilized beyond expected range, if you have 2 player (1 melee to engage with a HoT and 1 healer/range) you can engage the sleeping mobs at the end of the first hallway in shattered halls to reproduce this action.

**Expected behaviour:**

This spell should grant 2 melee attacks at the mobs normal melee range, not at unlimited range.

**Steps to reproduce the problem:**

if you have 2 player (1 melee to engage with a HoT and 1 healer/range) you can engage the sleeping mobs at the end of the first hallway in shattered halls to reproduce this action.

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/49624667/57562793-4f79f180-73d9-11e9-8a12-2c9a0c74be75.png)

**Comment by plutonium447** [comment]
https://github.com/thebarrensissues/Issues/issues/829
related issue, likely not fully resolved

**Comment by qoth** [comment]
Very nasty bug, can get healers 100->0 very easily with a moment of aggro loss.

**Comment by giveusmezpls** [comment]
Sorry I forgot NPCID.
16593

**Comment by kelno** [comment]
Fixed with 11231
