### ISSUE TITLE
Daze and increased defense

### ISSUE THREAD

**Issue by Paralol** [thebarrensissues/Issues#1238]
**Description:**

Daze is being applied incorrectly.

**Current behaviour:**

Currently all mobs seem to have a base chance to daze a player which is not modified in any way.

**Expected behaviour:**

Daze chance is modified by defense - which has no cap. Reference: https://wowwiki.fandom.com/wiki/Defense#Dazed

**Steps to reproduce the problem:**

Test against current level:
1. Create a level 70 character with 490 defense.
2. Turn your back to a level 70 mob
3. Get dazed

Test against low level:
1. Create a level 70 character
2. Turn your back to a level 1 mob
3. Get dazed

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/4516769/57572033-ecc83a80-7458-11e9-8c3b-9f0ed067007c.png)

**Comment by giveusmezpls** [comment]
I have confirmed this happening on live server, will test on PTR and report back.

**Comment by giveusmezpls** [comment]
On PTR I allowed al v6 mangy wolf to hit me almost 200 times.

![image](https://user-images.githubusercontent.com/49624667/57572806-12f2d800-7463-11e9-81b0-5e21f0462273.png)

In this process i was dazed one time, should it be impossible to be dazed? do you have any formulas I could use for testing?

**Comment by kelno** [comment]
The core does take into account defense and weapon skills

**Comment by Paralol** [comment]
No exact formulas I can find. Also am unable to find the post by Blizzard talking about crit immune tanks being immune to daze. There was a post regrading the skettis mounted bombing quest and how tanks can do it without getting knocked off their mount.

By the original post it states that a level 10 player vs a level 10 mob there is a 7% base daze chance.
Also following on that a defense capped tank is also immune to daze I would suggest the following.

`if PlayerLevel > 30 {
	DazeCalc = 20 + (0.16*(MobAttack-PlayerDefense))

if DazeCalc > 40
	DanceChance = 40
if DazeCalc < 0
	DanceChance = 0
else
	DanceChance = DazeCalc
}


if PlayerLevel < 30 {
	DazeCalc = 7 + (0.056*(MobAttack-PlayerDefense))
	
	if DazeCalc > 40
	DanceChance = 40
if DazeCalc < 0
	DanceChance = 0
else
	DanceChance = DazeCalc
}`

**Comment by Paralol** [comment]
> The core does take into account defense and weapon skills

It seems to be wrong though. As a tank over defense cap I am still getting dazed by level 15 mobs. I should be immune to daze by everything in the game.

**Comment by kelno** [comment]
I updated the formula (please include revision if you test)

**Comment by giveusmezpls** [comment]
![image](https://user-images.githubusercontent.com/49624667/57771516-416bfe00-7756-11e9-8270-599859143d41.png)
 using revision 11261 low level mobs are definately not dazing anymore and higher level mobs vs. prot pally not causing daze.
much improved / fixed.
