### ISSUE TITLE
[Priest] The Talent Holy Concentration not working correctly

### ISSUE THREAD

**Issue by giveusmezpls** [thebarrensissues/Issues#1239]
**Description:**

The talent Holy Concentration (per below image) should proc Clearcasting state (SpellID=34754) 6% of the time (2% per point).

![image](https://user-images.githubusercontent.com/49624667/57573754-4ee06a00-7470-11e9-8edf-ba054b8d284a.png)

**Current behaviour:**

Currently this talent only gives 2% chance even with 3 talent points, tested with almost 1000 cast on PTR using Procodile to track the SpellID proc. Priest was wearing Holy Bangle (also 2%) which recorded almost the exact same number of procs.

**Expected behaviour:**

It is expected to get 6% chance from this spell instead of 2% (increased with the investment).
Additionally this Clearcasting state seems to proc at a high rate when already proc.

**Steps to reproduce the problem:**

.batch cast 25213 10000

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/49624667/57573772-c7472b00-7470-11e9-9bd4-e32fda27f2dc.png)

**Comment by giveusmezpls** [comment]
I just realized i was testing with SPELL 2060 instead of 25213. It is possible downranked spells are affected differently in the code ?

**Comment by SUN-Leekie** [comment]
From our test framework:
It tests the proc chance from the 3 spells on thousands of casts.

> Tests results for input pattern: talents priest holy_concentration
>
> 1 | Total tests ran (388 ignored)
> 1 | Section successes
> 0 | Section failures (regressions: 0, known: 0)
>
> All tests passed \o/

**Comment by kelno** [comment]
Can you tell us how did you measured the proc chance here?
