### ISSUE TITLE
Find Weakness not being procced by Slice & Dice

### ISSUE THREAD

**Issue by Desparto** [thebarrensissues/Issues#1240]
**Description:**

As title states, find weakness talent in the Assassination tree isn't being procced by Slice and Dice. It should be procced by all finishing moves.

**Current behaviour:**

Find weakness talent not being procced by Slice and Dice

**Expected behaviour:**

Find weakness talent should proc when using Slice and Dice.

**Steps to reproduce the problem:**

CHANGEME
1. Step 1 Spec into Find Weakness 
2. Step 2 Use Slice and Dice
3. Step 3 See Find weakness doesn't proc (use rupture to see it proc for comparison)

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

 **rev. hash/commit:** 	11236

**Comment by SUN-Leekie** [comment]
Fixed in 11248.
