### ISSUE TITLE
special attacks are hitting more times than they should for proc purposes in some cases

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#1243]
**Description:**
when you use stormstrike as a shaman and execute as a warrior, they count as 1 more hit than they should, so for proc items and such calculations they will count for their hit +1.
**Current behaviour:**
use stormstrike on a target with flametongue weapon, 3 flametongue hits will occur if dualwielding, execute would make 2 flametongue hits. 
**Expected behaviour:**
use stormstrike on a target with flametongue weapon, only 1 flametongue hit per strike should occur, so 2 flametongue hits if dualwielding, and execute should only proc it once
**Steps to reproduce the problem:**
1. enchant a weapon with flametongue weapon as a shaman or use the totem, or equip items such as blazefury medallion/storm gauntlets that add a proc effect to attacks with 100% hit chance.
2. use abilities with that on and see if they are counting as more than the amount of hits they should.

this is an issue for stormstrike especially as with windfury weapon it will have a very high chance of proccing on the opener, as well as any on hit trinkets and the like.
if it's an issue for more than 1 ability it could be happening on more than those 2 abilities but i'm not sure and only have a warrior and shaman to test.

https://tbc-twinhead.twinstar.cz/?spell=17364 - stormstrike
https://tbc-twinhead.twinstar.cz/?spell=25236 - execute
https://tbc-twinhead.twinstar.cz/?spell=8024 - flametongue weapon
https://tbc-twinhead.twinstar.cz/?item=17111 - blazefury medallion
https://tbc-twinhead.twinstar.cz/?item=12632 - storm gauntlets
rev. 11246

**Comment by oj449** [comment]
tested other warrior abilities and only execute seems to have the +1 proc effect

**Comment by BrockSamson1** [comment]
MANY rogue abilities proc it. Including ones that don't even do damage like feint. Every special that counts as a melee hit procs it for rogues.

**Comment by kelno** [comment]
Thanks for the very detailed issue

**Comment by kelno** [comment]
Fixed with 11496.
Note that this is a per spell issue, so this is fixed for stormstrike and execution, but there might be other spell to fix with a similar issue.
