### ISSUE TITLE
Can't accept the quest "Imperial Plate Armor" from Myolor Sunderfury in Ironforge

### ISSUE THREAD

**Issue by Slamminn** [thebarrensissues/Issues#1244]
Can't accept the quest "Imperial Plate Armor" from Myolor Sunderfury in Ironforge

**Description:**

I have all of the requirements. (Character name: Edge). The requirements that are meant to be: Level 50, 265 Blacksmithing. I have both of these requirements, but I can't accept the quest.

**Current behaviour:**

There is no quest option given from the quest giver.

**Expected behaviour:**

I should be able to accept the quest "Imperial Plate Armor" from Myolor Sunderfury in Ironforge, but there is no prompt to do so.

**Steps to reproduce the problem:**

There are no steps, I can't accept the quest.
Some links for the outlined requirements:
https://tbcdb.com/?quest=10891
https://www.wowhead.com/quest=10891/imperial-plate-armor
https://tbc-twinhead.twinstar.cz/?quest=10891

 **rev. hash/commit:** 	

(see attached screenshot of the server info and showing that I have all of the requirements and can't accept the quest from him)

![Imperial Plate armor](https://user-images.githubusercontent.com/36665340/57599529-9575b780-7589-11e9-9b0a-18522500e018.png)
.

**Comment by SUN-Leekie** [comment]
Fixed in 11253.
