### ISSUE TITLE
T4 malorne 2 piece set bonus

### ISSUE THREAD

**Issue by Davethedruid** [thebarrensissues/Issues#1247]
T4 Malorne druid resto 2 piece set bonus does not appear to be working

When casting beneficial heal spells no procs have been detected.

Should proc for 120 mana return on beneficial spell cast on occasion.

1. Wearing T4 Malorne helm and gloves cast heals on self
2. watch for procs
3. repeat.

**Comment by giveusmezpls** [comment]
Hi Dave,
I have confirmation from another druid that it does proc, but the proc rate is low.
If you could do me a favor and find a source for the proc rate from wowhead or some such we can adjust the ticket to get the proc rate fixed if it is not correct.

**Comment by giveusmezpls** [comment]
I have proven this does proc on the PTR (in fact on my 2nd cast when testing).

![image](https://user-images.githubusercontent.com/49624667/57664972-83555100-763d-11e9-843e-14f93f857dfd.png)

**Comment by giveusmezpls** [comment]
Hi David, i've been working with an alliance druid to test this further. It appears that the fault might be that some spells are not proccing the t4 set bonus correctly such as lifebloom.

@SUN-Leekie  can you do a script test for the proc rate of the below, i've had the spellids and set bonus spellid listed.

Mana Restore (37288) 2p T4 set bonus (Restoration Druid)
Lifebloom (33763)
Rejuvenation (26982)
Regrowth (26980)
Healing Touch (26979)

**Comment by Davethedruid** [comment]
Sorry been working, i probably should have specified i was testing it with lifebloom not "heals"haha.

**Comment by SUN-Leekie** [comment]
Fixed in 11270.
@Davethedruid You were right, it only procced from direct heals, should now work with HoTs too!
Thanks @giveusmezpls for providing IDs :)
Proc rate is at 5% and seems working according to the test.
