### ISSUE TITLE
Leotheras the Blind casting Chaos bolt in Human form

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#1248]
**Description:**

Leotheras the Blind casting Chaos bolt in Human form sub 15%

**Current behaviour:**

At 15% hp Leo and his demon are splitting correctly, however the human form is casting Chaos Blast (37674, 37675) instead of Whirlwind (37641) 

See Clip:
https://clips.twitch.tv/OilyFlaccidTurtleRitzMitz

In the clip we see him begin casting a Chaos bolt almost immediately after changing back from Demon form. This could possibly be the cause of the bug and may not happen everytime unless this particular sequences of events transpires.

**Expected behaviour:**

Human form Leo should still cast Whirlwind(37641) not Chaos Blast (37674, 37675)

**Steps to reproduce the problem:**

CHANGEME
1. Engage Leo
2. Bring down to 15% during Demon form phase
3. Witness Human form behaviour after split

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/35262513/57613675-9f61df80-75b6-11e9-95c2-8a3be9183e74.png)

**Comment by SUN-Leekie** [comment]
Fixed in 11250.
