### ISSUE TITLE
Summon Infernal not working 

### ISSUE THREAD

**Issue by jcond23** [thebarrensissues/Issues#1251]
Summon Infernal is not under your control when it is summoned and it cannot be enslaved. 

**Expected behaviour:**

The infernal is supposed to be under the control of the caster for 5 minutes and be able to enslaved after that time period.

CHANGEME
1. Summon Infernal

Sunstrider rev. 11246 (39710c465a32+) 2019-05-12 01:08:01 +0200 (master branch) (Unix, RelWithDebInfo, Static).

**Comment by giveusmezpls** [comment]
There appears to be multiple versions of this spell and we appear to be using the WRATH version.

Patch 3.0.2 (14-Oct-2008): Cooldown reduced to 15 minutes, down from 1 hour. Duration reduced to 1 minute, down from 5 minutes+. Health increased by 30%, damage increased by 60%, and armor increased by 30%.

**Comment by jcond23** [comment]
its cooldown timer is still 1 hr and it appeared to stay there for 5 minutes after summoning it

**Comment by kelno** [comment]
Seems to work for me
https://i.imgur.com/qkzltLt.jpg
Can you tell me how to reproduce?

Also:
1. What level should it be?
2. How long should he stay? (supposing here he's supposed to stay for more than the enslave duration)

**Comment by kelno** [comment]
Updated with 11416
His level will now be the level of the caster + He will stay 10 minutes (dunno the correct value yet)
