### ISSUE TITLE
[Druid] Hibernate not consuming Nature's Swiftnes

### ISSUE THREAD

**Issue by Paralol** [thebarrensissues/Issues#1252]
**Description:**

Nature's Swiftness is making the druid spell Hibernate instant cast but is not consuming the Nature's Swiftness buff.

**Current behaviour:**

Nature's Swiftness is making the druid spell Hibernate instant cast but is not consuming the Nature's Swiftness buff.

**Expected behaviour:**

Nature's Swiftness should be used up after getting the benefit of the instant cast.

**Steps to reproduce the problem:**

1. Spec in to Nature's Swiftness
2. Find an animal
3. Cast Nature's Swiftness
4. Notice the cast is instant and you keep the Nature's Swiftness buff.

 **rev. hash/commit:** 	

11246

**Comment by giveusmezpls** [comment]
Confirmed on PTR to occur as per the description.

**Comment by SUN-Leekie** [comment]
Fixed in 11290.
