### ISSUE TITLE
[Quest] Electro-Shock Goodness!

### ISSUE THREAD

**Issue by zemfi** [thebarrensissues/Issues#1253]
**Description:**

Not able to complete/progress the quest due to the required npc's being instant-killed with the buff, and no globules spawn

**Current behaviour:**

As Above, you consume Navuud's Concoction (#29737), go to attack either Void Waste or Seeping Sludge, you insta-kill them and Void Waste Globule, Seeping Sludge Globule dont spawn to kill.

**Expected behaviour:**

NPC's Shouldnt be insta-killed and Globule should spawn.

**Steps to reproduce the problem:**

1. Accept Quest (#10411)
2. Consume Navuud's Concoction
3. Attack Void Waste (#20778) or Seeping Sludge (#20501) and see what happens.

 **rev. hash/commit:** 	

.rev 11246

**Comment by SUN-Leekie** [comment]
Fixed in 11309.
