### ISSUE TITLE
[SSC] - Lady Vashj - Toxic Spores Targetting All Raid Members

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1254]
**Description:**

Toxic Spores casted by Spore bats are incorrectly targeting all raid members when used instead of an individual player

**Current behaviour:**
Toxic Spores casted by Spore bats are incorrectly targeting all raid members when used instead of an individual player

https://www.twitch.tv/videos/424667481?t=02h40m46s

**Expected behaviour:**

https://www.wowhead.com/npc=22140/toxic-sporebat
https://www.wowhead.com/spell=38575/toxic-spores
https://wow.gamepedia.com/Lady_Vashj
Toxic spores should only target a single player

**Steps to reproduce the problem:**

CHANGEME
1. Engage Vashj
2. Get to P3
3. Watch ensuing green poo

 **rev. hash/commit:** 	

11246

**Comment by SUN-Leekie** [comment]
Fixed in 11262.
