### ISSUE TITLE
[Tempest Keep] - High Astromancer Solarian - Wrath of Astromancer is affecting the entire raid

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#1255]
**Description:**

 Wrath of Astromancer is affecting the entire raid instead of a single player

**Current behaviour:**

 Wrath of Astromancer is affecting the entire raid instead of a single player
https://www.twitch.tv/videos/424667481?t=03h04m28s
**Expected behaviour:**

The Wrath of the Astromancer debuff that deals a dot tick should only affect a single player

**Steps to reproduce the problem:**

CHANGEME
1. Engage Solarian
2. Wait for dot to be applied

 **rev. hash/commit:** 	

11246

**Comment by SUN-Leekie** [comment]
Fixed in 11262.
