### ISSUE TITLE
[SSC] - Lurker Below - Casting Whirl while in entry animation

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#1256]
**Description:**

Lurker below casts his Whirl attack while he is still in his entry animation (before he is attackable). It is cast approx when he hits the water after his dolphin like breach. 

The result of this is that spout at the same time he becomes attachable making it impossible to have the tank point him in the right direction on re-entry

**Current behaviour:**

Whirl is cast while in his entry animation

**Expected behaviour:**

He should complete his entry animation, become attackable, cast whirl right away then spout

**Steps to reproduce the problem:**

CHANGEME
1. Push lurker into P2 (where he swims down)
2. Wait until he comes up
3. Watch his attack sequence and notice he whirls while still in his entry animation

https://www.youtube.com/watch?v=eZJNTmHA7Cg - 4:35 shows the correct sequence 
https://www.twitch.tv/videos/423831678  2:16:30 - Shows whats happening on our server

**Comment by giveusmezpls** [comment]
I am closing this, will reopen after next lurker as Leekie has already applied some changes to Lurker timers which were not active during these attempts.
