### ISSUE TITLE
[SSC] - Lurker Below - Lurker re-surfaces at the start of P2 

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#1257]
**Description:**

Lurker re-surfaces at the start of P2 

**Current behaviour:**

Lurker re-surfaces at the start of P2 

**Expected behaviour:**

There should be a minimum timer for when Lurker will come back after he transitions to Phase 2 where all the adds come. He shouldn't instantly come back up while all the adds are up

**Steps to reproduce the problem:**

CHANGEME
1. Fight Lurker until he goes into phase 2
2. Watch him come back up way too early

https://www.twitch.tv/videos/424667481 - 1:26:55 - Shows the current behavior, he comes back almost instantly after submerging

**Comment by giveusmezpls** [comment]
I am closing this, will reopen after next lurker as Leekie has already applied some changes to Lurker timers which were not active during these attempts.
