### ISSUE TITLE
[Quest][Enchant] "Fiery Blaze Enchantments" scaling with spellpower

### ISSUE THREAD

**Issue by giveusmezpls** [thebarrensissues/Issues#1258]
**Description:**

Fiery Blaze Enchantment scaling with spellpower incorrectly (amongst other items)

**Expected behaviour:**

Another server has done a list with evidence to save us the trouble!
https://github.com/dalaranwow/dalaran-wow/issues/3938

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/49624667/57770048-c0f7ce00-7752-11e9-874f-1b6551b4151d.png)

**Comment by Jerrythemagicdog** [comment]
Fixed in 11263
https://github.com/kelno/sunstrider/commit/a451d9b8970e822d931700d24240bb7fd3a84907
