### ISSUE TITLE
Opera Event Big Bad Wolf not spawning

### ISSUE THREAD

**Issue by Calebizza** [thebarrensissues/Issues#1259]
**Description:**

After talking to the old lady in opera, the wolf does not spawn

**Current behaviour:**

After talking to the old lady in opera, the wolf does not spawn

**Expected behaviour:**

The old lady should despawn and the big bad wolf should spawn

**Steps to reproduce the problem:**

CHANGEME
1. enter Kara
2. Start Opera Event (ensure you get big bad wolf event)
3. Talk to the old Lady
4. get stuck on stage 

 **rev. hash/commit:** 	
![WoWScrnShot_051519_211313](https://user-images.githubusercontent.com/48810241/57771695-cf47e900-7756-11e9-9266-9cf479aef77e.jpg)

**Comment by kelno** [comment]
Fixed by woiwoz with 11295

**Comment by artieau** [comment]
Fixed
