### ISSUE TITLE
[Rogue] Distract causing Lightning Shield to proc and break Stealth

### ISSUE THREAD

**Issue by DaggerHand** [thebarrensissues/Issues#1263]
**Description:**

Currently on Storming Wind-Ripper NPC ID=22310
A Rogue using Distract Spell ID=1725
Causes the NPC's Lightning Shield Spell ID=12550 to proc and break Stealth

After a little bit of testing, it doesn't seem to be 100% of the time, but it was very much >80%

![distract](https://user-images.githubusercontent.com/50794581/57980468-581e9780-7a6b-11e9-97f5-a0ab478e0b12.png)

**Expected behaviour:**

Distract isn't supposed to proc a shield spell that breaks Stealth

**Steps to reproduce the problem:**

1. Step 1 Be a Rogue and using Stealth
2. Step 2 Use Distract on a Storming Wind-Ripper in Nagrand
3. Step 3 Stealth breaks from Lightning Shield proc damage

 **rev. hash/commit:** 	

![server info](https://user-images.githubusercontent.com/50794581/57980493-8c925380-7a6b-11e9-918f-fa77f920374f.png)

**Comment by kelno** [comment]
Fixed with 11546
