### ISSUE TITLE
Portal not working in stormwind

### ISSUE THREAD

**Issue by somedude321** [thebarrensissues/Issues#1266]
**Description:**

Stormwind teleporter in the mage port room don't work.

**Current behaviour:**

**I port to stormwind but can't get out of portal room**

**Expected behaviour:**

portal in room should port me to the bottom of the tower 

**Steps to reproduce the problem:**

CHANGEME
1. Step 1 player toon  
2. Step 2 portal
3. Step 3 portal

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)ss

 **rev. hash/commit:**

**Comment by Cheelout** [comment]
You are using the wrong one :)

**Comment by somedude321** [comment]
i tried both


On 21 May 2019, at 11:36 pm, Cheelout <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1266<https://github.com/thebarrensissues/Issues/issues/1266>.
