### ISSUE TITLE
void walker bug

### ISSUE THREAD

**Issue by somedude321** [thebarrensissues/Issues#1268]
**Description:**

voidwalker pet keeps casting consume shadows with the spell turned off
**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

not suppose to cast it with auto cast off

**Steps to reproduce the problem:**

CHANGEME
1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead-like page.  
2. Step 2
3. Step 3

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

 **rev. hash/commit:** 	

 CHANGEME	
Do a `.server info` in game and copy/screenshot the first line.  	
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by qoth** [comment]
Not enough info. Also consume shadows does not have an auto cast option.

**Comment by somedude321** [comment]
[cid:FBE43976-8A9A-42CA-B092-C5ADD20422BC]

On 23 May 2019, at 4:11 pm, qoth <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1268<https://github.com/thebarrensissues/Issues/issues/1268>.

**Comment by somedude321** [comment]
<img width="724" alt="Screen Shot 2019-05-23 at 10 40 53 pm" src="https://user-images.githubusercontent.com/47530588/58253745-760e3400-7dac-11e9-974c-164013a377eb.png">
