### ISSUE TITLE
execute is dropping rage to base rage cost

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#1270]
**Description:**
when you use execute above the base rage cost of 10 with the improved execute talent, not sure about without it, your rage stays at 10 after use- if you use it on 15 you go down to 5, 11 you go down to 1 etc
**Current behaviour:**
use execute at >10 rage, 10 rage leftover, may be >20, unsure server keeps crashing/busy atm, will test more soon
**Expected behaviour:**
use execute at >10 rage, puts you to zero rage after expending all of it for extra damage

rev.  11415

**Comment by kelno** [comment]
Error with a recent rewrite, fixed with 11421

**Comment by oj449** [comment]
back to the old execute bug now

**Comment by kelno** [comment]
This one? https://github.com/thebarrensissues/Issues/issues/1002

**Comment by oj449** [comment]
Yeah that one
