### ISSUE TITLE
[Item] Heroic Keys Not Available At Honored

### ISSUE THREAD

**Issue by zemfi** [thebarrensissues/Issues#1271]
**Description:**

_Apparently_ a known issue, but hopefully this can get some attention with an official report here.

**Current behaviour:**

Unable to attain Heroic Keys at Honored.

**Expected behaviour:**

Be able to attain Heroic Keys at Honored.

**Steps to reproduce the problem:**

1. Be patch 2.4
2. Have any honored rep of a particular faction's dungeon. eg. Lower City. Go to Nakodu (#21655)
3. Cant obtain Heroic Key (#30633)
4. Become an emotionally sad kitkat :(

 **rev. hash/commit:** 	

.rev 11422

**Comment by kelno** [comment]
Thanks! Always assume communication between staff and developers is very poor. And the reason to do so is because it is.

**Comment by Cheelout** [comment]
This was fixed last night. And was communicated in General that next restart it would apply

UPDATE `item_template` SET `RequiredReputationRank` = 5 where `entry` = 30633;
UPDATE `item_template` SET `RequiredReputationRank` = 5 where `entry` = 30623;
UPDATE `item_template` SET `RequiredReputationRank` = 5 where `entry` = 30622;
UPDATE `item_template` SET `RequiredReputationRank` = 5 where `entry` = 30634;
UPDATE `item_template` SET `RequiredReputationRank` = 5 where `entry` = 30635;

**Comment by zemfi** [comment]
Cant re-open this ticket again for some reason (probably shotty permissions), but Thrallmar rep key is missing (30637)

@Cheelout
