### ISSUE TITLE
Druid Swift Flight Form - QUEST Morthis Whisperwing (10955)

### ISSUE THREAD

**Issue by BarrensJerk** [thebarrensissues/Issues#1272]
**Description:**

Quest should be available from Logannar in Moonglade to start swift flight form questline

**Current behaviour:**

Quest not available from NPC

**Expected behaviour:**

Quest should be available in 2.4

 **rev. hash/commit:** 	

re. 11422

**Comment by Mediowow** [comment]
You need to have the artisan riding skill for druid trainers to point you to Logannar in Moonglade

**Comment by BarrensJerk** [comment]
That is right. At present, with 300/300 riding skill, no druid trainers will point a level 70 druid to Logannar for the swift flight form quest line. And Logannar himself has no quest to give.
![1](https://user-images.githubusercontent.com/44628946/58760005-bf613f00-8575-11e9-9a09-ca2802d03c2e.jpg)
![2](https://user-images.githubusercontent.com/44628946/58760008-c4be8980-8575-11e9-9173-d9627ea05ebf.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks for the report!
Fixed in 11493
