### ISSUE TITLE
Hungarfen mushrooms timer

### ISSUE THREAD

**Issue by MatthyusWoW** [thebarrensissues/Issues#1273]
Issues are for problem only, NOT for asking questions.
--->

**Description:**

Hungarfen 'Spore Cloud' activating as the Underbog Mushrooms grow or from Hungarfen himself

**Current behaviour:**

Hungarfen, 2nd boss in Underbog is currently spawning Underbog Mushrooms that are exploding almost instantly or Hungarfen is casting 'Spore Cloud'

**Expected behaviour:**

Underbog Mushrooms should slowly grow over 20 seconds and explode after that time, giving the debuff
https://wow.gamepedia.com/Hungarfen
https://wowwiki.fandom.com/wiki/Hungarfen

**Steps to reproduce the problem:**

Fight Hungarfen

 **rev. hash/commit:** 	

Unable to provide as this was before 2.4.3
Will attempt again and update with findings when able.

When logging this ticket - this one seems like it has been reported before
https://github.com/thebarrensissues/Issues/issues/965

**Comment by kelno** [comment]
Thanks. The old issue was related to a more general issue with time being wonky in instance so this is indeed a new one.

**Comment by kelno** [comment]
Fixed with 11480
