### ISSUE TITLE
[Mage] Dragon's Breath overrides slow effects of =< 50%

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#1274]
**Description:**
Dragon's Breath overrides slow effects such as Frostbolt.

**Expected behaviour:**

Slows should not be overriden by Dragon's Breath.

**Steps to reproduce the problem:**

1. Learn Dragon's Breath (31661)
2. Cast a Frostbolt on a target (maybe Permafrost talent required)
3. Dragon's Breath the target and notice that Frostbolt gets replaced.

 **rev. hash/commit:** 	
rev. 11483

**Comment by kelno** [comment]
(Decided invalid)
