### ISSUE TITLE
Cooking daily quest reward crate is empty

### ISSUE THREAD

**Issue by dreapon** [thebarrensissues/Issues#1276]
**Description:**

Cooking daily quest reward crate is empty.

**Current behaviour:**

When looting the cooking daily quest reward crate there is no loot.

**Expected behaviour:**

The cooking daily quest reward crate should have meat and possibly a cooking recipe.

**Steps to reproduce the problem:**

1. Accept cooking daily quest from The Rokk npc (ID: 24393) in Shattrath City
2. Complete cooking daily quest
3. Turn in quest to The Rokk
4. Select 'Crate of Meat' (ID: 33857) as quest reward
5. Open crate

 **rev. hash/commit:** 	

![fishingerrorrev](https://user-images.githubusercontent.com/46831677/58791769-280ff080-8636-11e9-8540-3e15555247c4.jpg)

**Note:**

Have tested for quests 'Revenge is Tasty' (ID: 11377) and 'Super Hot Stew' (ID: 11379)

**Comment by hufsa** [comment]
What happened here?
