### ISSUE TITLE
'Beginnings' quest item not dropping

### ISSUE THREAD

**Issue by antor85** [thebarrensissues/Issues#1277]
**Description:**

Quest items not dropping from Frostmane Novices.

**Current behaviour:**

'Feather Charm' quest items not dropping at all from Frostmane Novices in the Gnome starting area for the Gnome Warlock quest 'Beginnings', cant get the imp pet without it.

**Expected behaviour:**

Quest items 'Feather Charm' should be dropping (probably at 100%)

**Steps to reproduce the problem:**

1. https://www.wowhead.com/quest=1599/beginnings
2. Pickup quest as a new Gnome Warlock character 
3. Killed frostmane novices using combinations of Shadowbolt and corruption but They don't seem to be dropping the quest item 'Feather Charm' (killed over 20 of them)

 **rev. hash/commit:** 	

![stuff](https://user-images.githubusercontent.com/51326991/58805890-4edf1e80-8658-11e9-8ac8-ea094f34a5d7.png)

**Comment by Jerrythemagicdog** [comment]
Thanks for the report!
fixed in 11430

**Comment by antor85** [comment]
Hey there,
Cheers for the quick response! Just tried to complete the quest again though and after around 10 kills of Frostmane Novices still no Feather Charm item dropping. Also tried abandoning the quest and reacquiring it however no change.

**Comment by kelno** [comment]
When we give a revision (like in "fixed in 11430") it means it will be applied in a next update.
You can check the current server revision with the command ".server info"

**Comment by antor85** [comment]
I did check the server revision before replying about that, here is a screenshot of the ".server info" command when I attempted to complete the quest again:
![stuff2](https://user-images.githubusercontent.com/51326991/58855259-f5700180-86e2-11e9-9b6e-f4efb71476ee.png)
It definitely seems like its newer than the 11430 mentioned previously.

**Comment by Jerrythemagicdog** [comment]
Try with the next update, should be solved then.
