### ISSUE TITLE
Player Pet HP

### ISSUE THREAD

**Issue by Azytheoneandonly** [thebarrensissues/Issues#1278]
**Description:**

Player pets currently have extremely low hp. 

**Current behaviour:**

Examples below.
3 different pets of mine

![image](https://user-images.githubusercontent.com/37324574/58821112-b9ec1d80-8677-11e9-8bd9-46e4ca119d4b.png)

![image](https://user-images.githubusercontent.com/37324574/58821133-c5d7df80-8677-11e9-8b25-9ca0ceb9a164.png)

![image](https://user-images.githubusercontent.com/37324574/58821161-d1c3a180-8677-11e9-80b9-d94d98181168.png)

Another players voidwalker. 

![image](https://user-images.githubusercontent.com/37324574/58821267-08012100-8678-11e9-8743-9fa628c32416.png)

**Expected behaviour:**

For pets to have the correct HP.

**Steps to reproduce the problem:**

1. Log in and check pet hp.

 **rev. hash/commit:** 	

![image](https://user-images.githubusercontent.com/37324574/58821225-f586e780-8677-11e9-805e-0bf36d2735a9.png)

**Comment by kelno** [comment]
Fixed already, just need to update the server
