### ISSUE TITLE
[Rogue] Disarming a trap activates it and opens up a loot window.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#1279]
**Description:**
Disarm Trap (1842) activates the traps instead of despawning them. It also causes a loot window to open up. The issue can be easily reproduced with a hunter's Freezing Trap (14311) or a creature's trap such as Proximity Bomb (32784)

**Expected behaviour:**
Disarmed traps should despawn.

**Steps to reproduce the problem:**

1. .learn 1842 (Rogue spell)
2. .additem 5060
3. Cast any of the trap spells on another character (.cast 14311 for example)
4. Disarm the trap on a rogue
5. The trap activates and a loot window opens.

 **rev. hash/commit:** 	
rev. 11508

**Comment by kelno** [comment]
Fixed with 11515 by woiwoz

**Comment by Jerrythemagicdog** [comment]
Fixed
