### ISSUE TITLE
Undercity guards don't give directions to trainers / vendors / etc

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#130]
**Description:**

City guards either don't give directions to the trainers in question (Undercity Guards for example - no gossips) or the place that they are supposed to give you guidance to does not mark up on the map.

**Comment by kelno** [comment]
Guards ID: 5624

Some options are existing in broadcast_text table:
```
SELECT * 
FROM broadcast_text
WHERE MaleText LIKE "%archibald%"
```

**Comment by kelno** [comment]
Should the seekers such as 14404 also give directions?

**Comment by Jerrythemagicdog** [comment]
Can't find a source if they do anywhere.

**Comment by kelno** [comment]
Okay thanks

**Comment by SUN-Leekie** [comment]
Fixed in 11089.

**Comment by kelno** [comment]
741f4c967d717b8aa5629bebbfa5c068173b44cf
