### ISSUE TITLE
[Karazhan] Opera Event - Aggroed by ghosts in the next room 

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#136]
**Description:**

- After starting the Opera (theater) event the exit doors out of the stage do not have line of sight and NPCs are running through them (ghosts from the next room.)

The issue occurred before the boss fight started and we were standing in place waiting for the curtain to go up.

**Comment by kelno** [comment]
So while you're doing the opera event you get ghosts from the next room aggroing you?

**Comment by kelno** [comment]
So while you're doing the opera event you get ghosts from the next room aggroing you?

**Comment by Jerrythemagicdog** [comment]
Yes, when you start the event and get in position with your group, the mobs from the next room come through the closed doors.

**Comment by kelno** [comment]
Then isn't the main problem here that they aggro without a reason in the first place?

**Comment by kelno** [comment]
This run through door issue can't be fixed without very BIG changes I'm not willing to do considering the benefit. The first issue can be looked into though.

**Comment by Jerrythemagicdog** [comment]
This might be a result of the pack being linked to the boss somehow.

**Comment by SUN-Leekie** [comment]
Seems fixed.
