### ISSUE TITLE
[Warlock] Pet scaling values are incorrect.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#150]
**Description:**

Warlock pets scale with owner's stats a bit too much.

**Current behaviour:**

Pets have a bit too much hp compared to retail.
_Sunstrider_: https://imgur.com/a/2Nsvf3X
_Retail examples_: http://imgur.com/a/nKI97

**Expected behaviour:**

Pets should scale closer to retail values.

**Sources**: 

https://www.youtube.com/watch?v=LUCv1guR-zQ
https://www.youtube.com/watch?v=czV-xTY6NV0

**Comment by kelno** [comment]
Your example should compare the same mob though, since void walker is supposed to have more health

**Comment by Nqsty** [comment]
https://github.com/ValorenWoW/sunstrider-core/pull/164
