### ISSUE TITLE
[NPC] Marshal Marris paths underground

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#172]
**Description:**
Marshal Marris (guid: 6720) paths underground in Lakeshire.

**Expected behaviour:**

He should stand by the bridge (.go xyz -9284.030273, -2298.159912, 67.494423 0)

**Steps to reproduce the problem:**

1. .go crea 6720
2. He most likely won't be there but be somewhere to the north around the hills under the ground.

**rev. hash/commit:** 

Sunstrider rev. 10253 (3cfd54bedf9f) 2019-01-18 18:02:17 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by SUN-Leekie** [comment]
Fixed.
