### ISSUE TITLE
[Quest] 'Druid of the Claw' issues

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#177]
**Description:**
'Druid of the Claw' (2561) doesn't credit the player for killing the NPC (entry 7318, guid 46818) and the item required to finish the quest (Voodoo Charm - 8149) does not drop.
Here's a video: https://streamable.com/8eth0

**Expected behaviour:**

Player should be credited with killing the quest NPC and the item should drop
Video: https://www.youtube.com/watch?v=rV70Yt1BBeQ

**Steps to reproduce the problem:**

1. Pick up the quest
2. Try finishing it by killing Rageclaw
3. There is no credit and no item dropped.

**Comment by SUN-Leekie** [comment]
The item is given at the start of the quest and using it on the corpse completes the quest.
Seems fixed.
