### ISSUE TITLE
[Hunter] Freezing Trap duration on players is too long.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#185]
**Description:**

Currently Freezing Trap (14311 for example) lasts up to 26 seconds on a player (with Clever Traps 19245 skilled) and 20 without Clever Traps. They should last up to 13 seconds with Clever Traps skilled, and 10 seconds without.

**Sources**
13 seconds duration (can't see on target frame but can judge by time passed in the video)
https://youtu.be/7qQna7r5guk?t=193

https://youtu.be/7qQna7r5guk?t=227

https://youtu.be/sDcPvkDRWzk?t=130

All of the above have Clever Traps specced (which makes it 13 seconds)

**rev. hash/commit:** 

Sunstrider rev. 10283 (2e80439) 2019-01-22 18:43:47 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by emorelix** [comment]
*tested ingame in wsg on the 21st March, lasting 13 seconds on players*

**Comment by artieau** [comment]
I have had a trap last 18 seconds today 21st of March
Core version to be added to this comment, server offline

**Comment by emorelix** [comment]
Rev 10770

**Comment by kelno** [comment]
Fixed with 10812
