### ISSUE TITLE
[Item] Stormherald does not stormherald.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#186]
**Description:**

Stormherald does not stun people (4 seconds from its tooltip). It should apply spell 265280.
Unless I was extremely unlucky, the proc does not work.

**Expected behaviour:**
It should proc sometimes and stun the poor person on the receiving end.
I couldn't find any credible information, it is rumored to have 1% proc chance (https://www.mmo-champion.com/threads/601764-Mace-spec-nerf-and-PvP-class-balance?p=5517466&viewfull=1#post5517466)

**Steps to reproduce the problem:**

1. Equip Stormherald (28442)
2. Hit some target for some time
3. Stun does not trigger at all.

**rev. hash/commit:** 

Sunstrider rev. 10283 (2e80439) 2019-01-22 18:43:47 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by Hoochsex** [comment]
After testing both Deep Thunder (http://tbc.cavernoftime.com/item=28441) and Stormherald (http://tbc.cavernoftime.com/item=28442) for around 30 mins each spamming Hamstring on RT we noticed that the proc on Deep Thunder is working however Stormherald is not. Hope this helps :>

**Comment by SUN-Leekie** [comment]
Should proc on melee hit and all warriors spells (e.g. hamstring...).
Still bugged for both weapons.

**Comment by giveusmezpls** [comment]
still broken

**Comment by Jerrythemagicdog** [comment]
fixed in 11165
