### ISSUE TITLE
Bonfire spams damage

### ISSUE THREAD

**Issue by SUN-Leekie** [thebarrensissues/Issues#206]
https://streamable.com/ijp9n

**Comment by artieau** [comment]
Causes 2 x tick of fire again now, regression?
Rev. 10533
![image](https://user-images.githubusercontent.com/40563134/53279986-9a388580-3769-11e9-90e3-9b38df96067e.png)
@kelno

**Comment by artieau** [comment]
In this screenshot, Cooking Pot = 1 x fire damage proc
Bonfire = 2 x fire damage proc
![image](https://user-images.githubusercontent.com/40563134/53279996-bdfbcb80-3769-11e9-9175-1f180d7edaaf.png)

**Comment by kelno** [comment]
Can you
.gps
there ?

**Comment by artieau** [comment]
Character per screenshot above.
![image](https://user-images.githubusercontent.com/40563134/53287316-870bd100-37ce-11e9-8d51-1e2bde48737f.png)

**Comment by kelno** [comment]
Seems fixed?
