### ISSUE TITLE
[Hunter] Shot queueing mechanics

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#224]
**Description:**

The current way in which Steady Shot works overrides the auto shot timer which doesn't allow for the basic mechanics of the class to work (1:1 and 3:2 rotations. ) There are also rules for other hunter spells (like Aimed or Multi Shot) and which should have priority over which.

Here are similar issues and explanations: 
1. https://github.com/Schaka/TBC-research/issues/28
2. https://github.com/Atlantiss/NetherwingBugtracker/issues/2339

_Explanation by the same author (Zarant) in issue_ (https://github.com/Atlantiss/NetherwingBugtracker/issues/2339): 
I'll try to break down the auto shot mechanics and all its nuances as much as possible:

    1. Auto shot is a spell with a 0.5s cast time and its cooldown is the hunter's ranged attack speed minus 0.5
    2. Instant cast spells don't interact with auto shot in any way.
    3. Auto shot can only be cast if you're not currently casting any spell and only while standing still.
    4. Casting any spell with a cast time or moving should interrupt the 0.5s auto shot cast time.
    5. Steady shot and multi-shot are the only exceptions to rule number 4, both spells don't interrupt auto 
    shot.
    6. If you cast steady shot or multi-shot while an auto shot is mid cast, your next steady shot or multi-shot 
    should start casting as soon as the 0.5s auto shot cast time finishes.
    7. Whenever you finish casting an aimed shot, your auto shot cooldown is reset.

> 
> Now this next part is crucial to understand why the 3:2 rotation works the way it does:
> 
>     If you queue a steady shot or multi-shot during the auto shot wind up time, your GCD starts when the game client send the spell cast to the server.
>     Steady shot has a cast time shorter than a GCD, since ranged haste doesn't affect GCD.
>     Spell queuing should respect GCD limitations, meaning that you can't cast 2 spells back to back if both of them have a cast time shorter than a GCD.
>     If you cast a steady shot during the auto shot wind up time, the spell triggers a GCD before the spell cast begins, allowing you to cast 2 back to back steady shots.
>     You can't cast 2 back to back steady shots if auto shot is off cooldown by the time the first steady shot cast finishes. Auto shot should always take precedence over steady/multi shot.
>     You can't queue a multishot after a steady shot if auto shot is off cooldown by the time the first steady shot cast finishes.

3. Warmane bugtracker:

> Autoshot has 0.5s hidden cast. When this cast start, AS should "lock" itself and all other shot casts initiated during this lock should be delayed after it is unlocked again. This all works pretty much fine. Problem is with GCD triggering.
> 
> The Problem: When spell is initiated during 0.5 autoshot cast, GCD is not triggered at the initiation, but rather at spell cast start, which means, that GCD is also delayed.
> 
> How it should work: GCD should be triggered, when spell is initiated. By initiation is meant the moment, when server receive request from client to cast a spell, and it is decided, that this spell is available to be casted ( of GCD/CD and no other spell is beeing casted ).
> 
> How to reproduce:
> I tested this as BM hunter -> 20% haste from talents a 15% haste from ammo pouch and with gun of 2.7 base speed.
> 
> after haste effects:
> weapon speed: 2.7/1.15/1.2 = 1.96
> steady shot cast time: 1.5/1.15/1.2 = 1.09
> 
> now, what SHOULD happen, when you start casting autoshot and almost imidietly initiate steady shot casts
> 0.00 - autoshot cast starts
> 0.10 - steady shot initiated, GCD triggered
> 0.50 - autoshot casted, steady shot cast starts
> 1.59 - steady casted
> 1.60 - GCD ends, new spell can be started
> --- now we have 0.36s gap before new autoshot cast starts, where we could initiate next spell cast, which wont be deleayed - 0.36s is not a problem to hit
> 1.96 - new autoshot available
> 
> On warmane, it looks like this:
> 0.00 - autoshot cast starts
> 0.10 - steady shot initiated
> 0.50 - autoshot casted, steady shot cast starts, GCD triggered
> 1.59 - steady casted
> 1.96 - new autoshot available
> 2.00 - GCD ends, next spell can be casted
> You are not able to cast 2 steadies in a row with 2.7gun and BM talents.
> 
> We have a little improved 1:1 rotation instead of proper 3:2 rotation. Client side(= in game), GCD triggering looks fine, GCD timer on spell icon starts when spell is pushed, and spell cast starts after AS cast, but as my test showed, reality is different.
> 
> On more proof. Right now, Arcane shot is slighty bugged and if it is casted during autoshot 0.5s cast, Arcane is not delayed, but also does not interupt autoshot cast. This means, that when arcane is initiated, GCD is also triggered, which simulates proper GCD behaviour. When do the same test i did, but instead of steady, you start with Arcane (about 0.1s after autoshot starts), you can weave in one steady shot before next autoshot cast. 

4. http://wow.allakhazam.com/wiki/shot_rotation_(WoW)

**This is a gamebreaking issue that affects hunters and their playstyle greatly. I didn't get into too much detail because the referenced posts made it very clear as to what it should look like.**

rev: Sunstrider rev. 10353 (857762b7ebc2) 2019-02-01 17:28:52 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Fixed with 11498
