### ISSUE TITLE
Pet logic in regards to ranged spells and melee attacks.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#225]
**Description:**

Pets like Wind Serpent have a Lightning Breath ability that's a ranged spell. When left on auto-cast and issued an attack command (/petattack) the pet never goes in melee range of the target but keeps casting Lightning Breath from a distance. The /petattack should override that and make the pet go in melee range (with exceptions for pets whose only attack is their ranged attack - like Mage's Water Elemental. )
  
**Current behaviour:**

Pet stands at a distance only casting Lightning Breath / their ranged spell. Currently in order to get him to melee attack we have to disable autocast on that ability, do a /petfollow and issue a new /petattack on the target and re-enable autocast on that ability.

**Expected behaviour:**

The pet should be sent in melee range and keep casting the breath there. 

**Steps to reproduce the problem:**

1. Get a pet with a ranged spell (not Mage's Water Elemental) - I tested with a Wind Serpent
2. Issue an attack command
3. The pet will stay at a distance and cast his ranged ability until disabling the autocast, doing a /petfollow and issuing a new attack command.

**rev. hash/commit:** 

Sunstrider rev. 10353 (857762b7ebc2) 2019-02-01 17:28:52 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by Azytheoneandonly** [comment]
Currently the wind serpent is actually not even going into range to cast the lightning breath. stops short by 1-2 yards and stands there.
![image](https://user-images.githubusercontent.com/37324574/54469132-c3d05400-47df-11e9-93a8-ba199cbb741f.png)

**Comment by kelno** [comment]
Is the pet supposed to always go in melee range? Or should it stay at a distance and wait for a second attack order to go in melee?

**Comment by Azytheoneandonly** [comment]
Sorry for late reply. it should always go into melee range.

**Comment by kelno** [comment]
Fixed with 10903
