### ISSUE TITLE
Fear is breaking too easily

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#256]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Saturday Dec 08, 2018 at 01:03 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/22_

----

Patch:
2.4.3

Current behavior:
When a target is fully dotted fear always breaks after approx 2 seconds (even with no other damage being delt)

Expected behaviour:
Fear should sometimes break early and sometime last the full duration; even with dots up. 

https://forum.nostalrius.org/viewtopic.php?f=5&t=17424
(See bottom post of that first page for mechaics on fear in vanilla
http://wowwiki.wikia.com/wiki/Fear_effect
This shows patch changes of "fear effect' from vanilla

Steps to reproduce the problem:
Step 1: Cast dots on a mob; (UA, CoA Corr SL) 
Step 2: Cast fear on that mob; what it break in 1-2 seconds every time

**Comment by kelno** [comment]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kaziner](https://github.com/Kaziner)**
_Sunday Dec 16, 2018 at 13:50 GMT_

----

I provided all the research I had in the origional message; one way to consistantly see that its broken is to put CoA + SL + Corr up on mobs and get 3 of them fully dotted up then instant cast howl of terror.

They will all break after taking 2 steps at the same time, every time. Fear breaking is sopost to be a random effect but even when groups of mobs are being feared they all break on the same game tick

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Sunday Dec 16, 2018 at 14:03 GMT_

----

Yeah it's more for other devs if they want to check it, it's impossible to find a source that actually will give the correct formulas for this (How much damage for how much % of breaking, and other factors).
But others core might have researched it with more details before and done good approximations we can use.

**Comment by Kaziner** [comment]
Example of expected behavior 

https://www.youtube.com/watch?v=G51Ipz1d1Xc - 4:46 
https://www.youtube.com/watch?v=7k30ZBJ23MQ 2:42 & 4:36

**Comment by Cheelout** [comment]
I have noticed in PvP and watching warlocks do damage to mobs in fear this is no longer an issue. reopen if not the case.
