### ISSUE TITLE
When hitting "Complete Quest" button; quest window does not close

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#259]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Sunday Dec 09, 2018 at 10:40 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/27_

----

Patch:
2.4.3

Current behavior:
When I click "Complete Quest" button the quest window does not close (the quest does complete though). I need to manually hit the escape key to close the window to proceed.

Expected behaviour:
When I hit "Complete Quest" the window should close

Steps to reproduce the problem:
Step 1: Finish a quest and attempt to hand in

![report 009](https://user-images.githubusercontent.com/45530324/49696217-8f526800-fbf2-11e8-91a1-b5bdfae28ef1.JPG)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Dec 24, 2018 at 13:30 GMT_

----

Can't reproduce, has this been fixed by another patch?

**Comment by kelno** [comment]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kaziner](https://github.com/Kaziner)**
_Saturday Dec 29, 2018 at 05:36 GMT_

----

Its fixed; unsure of source of fix but its done

**Comment by kelno** [comment]
<a href="https://github.com/qoth"><img src="https://avatars2.githubusercontent.com/u/35262513?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [qoth](https://github.com/qoth)**
_Sunday Jan 13, 2019 at 23:06 GMT_

----

Issue is still present as of 14/1 and latest update. 

To replicate. 
Create new character, 
Accept the 58 pack option from the BETA NPC.
Accept quest 'Through the Dark Portal'
Go through portal and hand in quest.
Final Quest frame does not drop even though quest has indeed been completed.

**Comment by kelno** [comment]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [artieau](https://github.com/artieau)**
_Friday Feb 08, 2019 at 11:18 GMT_

----

Appears fixed now in rev: 10402

**Comment by emorelix** [comment]
Still Bugged. IE : nagrand ring of blood quest handins.

![wowscrnshot_022319_184030](https://user-images.githubusercontent.com/47015256/53284375-975c8580-37a7-11e9-8d35-408efe7fefc9.jpg)

**Comment by Cheelout** [comment]
This is fixed AFAIK.

**Comment by kelno** [comment]
Fixed with 11447
