### ISSUE TITLE
[#293] [Hellfire Ramparts] Vazruden the Herald

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#386]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Sunday Feb 10, 2019 at 11:02 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/293_

----

**Current behaviour:**

Starting the  encounter, boss flies down and dismounts -> then encounter resets

**Expected behaviour:**

Boss should dismount and mount fly back in the air shooting fire.

**Steps to reproduce the problem:**

1. Engage final boss
2. Boss flies down to ground
3. Boss dismounts then instantly re-mounts and resets.

**rev. hash/commit:** 

REV: 10421

**Comment by artieau** [comment]
Rev. 10533
Possible regression?
Engage boss
Boss flies down to ground and engages players
Once humanoid dies, Dragon flies down but resets whole encounter as it touches the ground.
@kelno

**Comment by kelno** [comment]
Fixed as of 10564

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider-scripts/commit/756d48641b7436b93a974271ab474da7aba110ae

**Comment by artieau** [comment]
Regression, not working again

**Comment by Jerrythemagicdog** [comment]
Can you provide reproduce steps? Can't reproduce locally. Thanks!

**Comment by artieau** [comment]
See #1021 for additional notes.
First time pull, damage of the dragon+boss is way too high.
IF you wipe, next attempt they both sit on the ground and have very fast cast speeds.
IF you kill one of the two NPC, it respawns and flies around. @Jerrythemagicdog

**Comment by kelno** [comment]
His melee damage was not up to date, this has been reduced. 
Also fixed an issue with the reset.
Fixed with 11389
