### ISSUE TITLE
[#12] Mobs are doing too much damage

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#410]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Thursday Dec 06, 2018 at 11:45 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/12_

----

Patch:
2.4.3

Current behaviour:
Enemy abilities (specifically Gnarlpine warrriors in starbeeze village are dealing too much damage with their normal melee attacks and special abilities. A crit and auto attack was enough to kill a level 5 druid (level 7 mob)

Expected behavior:
I suspect the mobs should be hitting for less damage then they currently are

Steps to reproduce the problem:
Step 1: Aggro a Gnarlpine Warrior, Let it hit you
![report 002](https://user-images.githubusercontent.com/45530324/49582288-460ada00-f9a0-11e8-886e-9db8939579ae.JPG)

**Comment by SUN-Leekie** [comment]
Fixed in 11089.

**Comment by kelno** [comment]
1ee7f023cd60fc7f941da4c3fbbcdf18ac0d816f
