### ISSUE TITLE
[#16] Warrior Rage Generation

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#412]
<a href="https://github.com/Harrock1"><img src="https://avatars2.githubusercontent.com/u/25610698?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Harrock1](https://github.com/Harrock1)**
_Thursday Dec 06, 2018 at 22:26 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/16_

----

**Patch:**
2.4.3

**Current behaviour:**
Mele swings are giving far too much rage, causing max rage from 2-3 mele swings. Unsure if its also generating rage on the yellow hits from Talents (Bloodthirst/shieldslam/rampage etc)

Linked at bottom are some screenshots of how many abilities I was able to use on one boar whilst only recording 6 extra rage from Unbridled wrath. Please note I do not have that talent on my Protection test warrior and it has the same result in excess rage.

**Expected behaviour:**
Rage generation should be relative to the white damage done and the damage recieved

**Steps to reproduce the problem:**
Step 1: White attack any mob
Step 2: Note the rate at which rage is batching up in large increments against the combat log

**IDs**
nil

**Source**
![rage](https://user-images.githubusercontent.com/25610698/49615558-0674da00-fa02-11e8-9300-0a29b4ad25b4.JPG)
![rageuse](https://user-images.githubusercontent.com/25610698/49615562-0d9be800-fa02-11e8-8fbf-22817807f1ab.JPG)

**Comment by kelno** [comment]
<a href="https://github.com/Harrock1"><img src="https://avatars2.githubusercontent.com/u/25610698?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Harrock1](https://github.com/Harrock1)**
_Thursday Dec 06, 2018 at 22:35 GMT_

----

I cant confirm, but it seems like misses and parries are generating rage

**Comment by dylbarrenstbc** [comment]
As best I can tell, this is also happening with feral druids

**Comment by Harrock1** [comment]
Seems now as of rev.10526 rage is not being generated for being hit (was getting 1 rage per block as per shield specialisation in prot tree)

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, are there any effects like .cheat god or similar used during the test? 
Seem to be getting rage normally (rev. 10530) when hit.

**Comment by Jerrythemagicdog** [comment]
After trying again and running the numbers with Rage formulas from wowwiki ( https://vanilla-wow.fandom.com/wiki/Rage ) it seems to add up to the Damage Taken considering it changes from level to level. Does not look like a bug.

**Comment by kelno** [comment]
Okay so, we found out that before blocking did prevent ALL damage so that was fucking with player rage generation.
Closing this until other problems are found.
