### ISSUE TITLE
[#26] Getting dismounted in shallow water

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#414]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kelno](https://github.com/kelno)**
_Sunday Dec 09, 2018 at 08:48 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/26_

----

blablabla

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Sunday Dec 09, 2018 at 09:11 GMT_

----

Should be fixed with 9927. (.server info to check current server version)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Sunday Dec 09, 2018 at 10:01 GMT_

----

https://github.com/ValorenWoW/sunstrider-core/commit/086883018a46a6cf7a66ad91e8d973cd01f8acc2
https://github.com/ValorenWoW/sunstrider-core/commit/f9469f112c08d0ed5e7c06b139fa9ceed05ef634

**Comment by kelno** [comment]
<a href="https://github.com/Nolin7777"><img src="https://avatars2.githubusercontent.com/u/20132236?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nolin7777](https://github.com/Nolin7777)**
_Sunday Dec 09, 2018 at 10:31 GMT_

----

Still too sensitive, checked with Draenei in Un'Goro
Maybe check if character would swim instead of a static height?

**Comment by kelno** [comment]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kaziner](https://github.com/Kaziner)**
_Sunday Dec 09, 2018 at 10:58 GMT_

----

Tested; appears to be still broken.

Further to the above; it seems to activate a speed hack where my toon moves as if its on a mount but I am in complete control of its actions (casting spells etc). Includes a faster running animation. (Tested in IF Pool, walk into pool, mount up inside of it, mount disappears but you gain the speed buff
![report 012](https://user-images.githubusercontent.com/45530324/49696397-26202400-fbf5-11e8-9d9a-d374b08caaa6.JPG)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Sunday Dec 09, 2018 at 15:21 GMT_

----

This is a different issue, can you create another one?

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Sunday Dec 09, 2018 at 15:58 GMT_

----

Okay my previous fix was not covering all cases. Should be fixed with 9929.

**Comment by kelno** [comment]
<a href="https://github.com/Nolin7777"><img src="https://avatars2.githubusercontent.com/u/20132236?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nolin7777](https://github.com/Nolin7777)**
_Sunday Dec 09, 2018 at 16:29 GMT_

----

Still too sensitive, checked with all classes.
Maybe check if character would swim instead of a static height?

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Dec 10, 2018 at 09:08 GMT_

----

Can you .gps me where you are checking Nolin?

I don't like checking swimming flag since it can be manipulated by client.

**Comment by kelno** [comment]
<a href="https://github.com/Nolin7777"><img src="https://avatars2.githubusercontent.com/u/20132236?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nolin7777](https://github.com/Nolin7777)**
_Saturday Jan 05, 2019 at 00:39 GMT_

----

Toons should be dismounted when they would start swimming.

**Comment by kelno** [comment]
The speed hack thing has been fixed last month I think. That was the worrying part of this issue for me.

**Comment by kelno** [comment]
Fixed with 10822

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider/commit/819e3fc730f86beee1ecde638e7b91b456dd78fc

**Comment by oj449** [comment]
i've still been having this issue, could be related to race mount size needing different depths for swimming, so that say a tauren will be dismounted before swimming because the dismount depth is set to human size mount? video of non swimmable water in shattrath dismounting:
[2019-04-05_22-59-42.zip](https://github.com/thebarrensissues/Issues/files/3047970/2019-04-05_22-59-42.zip)

**Comment by kelno** [comment]
Thanks for the video here

**Comment by kelno** [comment]
f187d2e23dadfb62e2809f3ed2923fa37a478d76 

Fixed with 10898
