### ISSUE TITLE
[#44] Gold Quest rewards don't align with turn-in screen at level 70

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#421]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Sunday Dec 16, 2018 at 12:43 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/44_

----

Current behavior:
I am received more gold for a quest turn-in then stated when turning in the quest

Expected behaviour:
They should match

Steps to reproduce the problem:

Step 1:Turn in a quest at level 70
![wowscrnshot_121618_224136](https://user-images.githubusercontent.com/45530324/50053607-e4a6f000-0183-11e9-8e83-04701e81bb64.jpg)
![wowscrnshot_121618_224143](https://user-images.githubusercontent.com/45530324/50053608-e4a6f000-0183-11e9-933b-1163b6a9f157.jpg)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Sunday Dec 16, 2018 at 13:51 GMT_

----

Thank you, $n. I'm not sure about that issue, when you're max level extra xp gets converted to money. Question is, is that supposed to be shown on the quest statement?

**Comment by Kaziner** [comment]
Invalid, please close
