### ISSUE TITLE
[#54] Dreghood Brutes and other NPC's who weild picks play the wrong sound when attacking

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#425]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Monday Dec 17, 2018 at 07:40 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/54_

----

Current behavior:
When this mob or other mobs with picks attack me they play the sound that plays when you mine ore; 

Expected behaviour:
Should be an attack sound

Steps to reproduce the problem:

Step 1: Let a Dreghood brute attack you
![wowscrnshot_121718_173846](https://user-images.githubusercontent.com/45530324/50072968-c80dc500-0222-11e9-99ef-1fd9b281865d.jpg)

**Comment by kelno** [comment]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kaziner](https://github.com/Kaziner)**
_Wednesday Dec 19, 2018 at 00:40 GMT_

----

https://www.wowdb.com/npcs/16938-dreghood-brute

**Comment by kelno** [comment]
Can't reproduce

**Comment by artieau** [comment]
fixed
