### ISSUE TITLE
[#61] Mobs not lootable in Blood Furnace after first boss 

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#428]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Monday Dec 17, 2018 at 11:05 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/61_

----

Current behavior:
Unable to loot mobs in hallways after first boss

Expected behavior:
I should be able to loot the boss

Step 1: Kill mobs in this hallway
Step 2: Attempt to loot mobs
![wowscrnshot_121718_203805](https://user-images.githubusercontent.com/45530324/50083432-7fb0d000-023f-11e9-9e8a-e2c6cf744be4.jpg)

**Comment by plutonium447** [comment]
me and some other testers have run this dungeon recently and we no longer had this issue
perhaps this was fixed?

**Comment by kelno** [comment]
Is this still happening?

**Comment by plutonium447** [comment]
Issue is most likely resolved.
I will attempt to confirm.
