### ISSUE TITLE
[#63] Tempest-Forge patroller pulling through the wall in Mech

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#429]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Monday Dec 17, 2018 at 12:33 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/63_

----

Current behavior:
Tempest-Forge patroller pull through the wall in Mech when you pull the middle mech at the start

Expected behavior:
They shouldn't aggro mobs through the wall

Step 1: Pull the middle mech that sits there at the start of mech

**Comment by kelno** [comment]
<a href="https://github.com/Kittnz"><img src="https://avatars2.githubusercontent.com/u/5845231?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kittnz](https://github.com/Kittnz)**
_Tuesday Dec 18, 2018 at 15:36 GMT_

----

vmaps, line of sight problem?

**Comment by kelno** [comment]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kaziner](https://github.com/Kaziner)**
_Wednesday Dec 19, 2018 at 00:37 GMT_

----

https://www.wowdb.com/npcs/19166-tempest-forge-patroller

**Comment by kelno** [comment]
Still happening? Maybe it was wrong vmap version on the test server

**Comment by artieau** [comment]
Appears fixed.
