### ISSUE TITLE
[#65] Visual bug in wall of mech above the elevator

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#430]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Monday Dec 17, 2018 at 12:36 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/65_

----

Current behavior:
Can see through the wall

Expected behavior:
Likely there is sopost to be something there?

Step 1: Go to mech at top of the elevator and look at the wall
![wowscrnshot_121718_215834](https://user-images.githubusercontent.com/45530324/50087561-28fdc300-024c-11e9-94bc-44acdb62bdbf.jpg)

**Comment by kelno** [comment]
<a href="https://github.com/Kittnz"><img src="https://avatars2.githubusercontent.com/u/5845231?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kittnz](https://github.com/Kittnz)**
_Monday Dec 17, 2018 at 12:37 GMT_

----

Well either it's a client bug or missing gob, i got no idea. can you give coordinates?

**Comment by kelno** [comment]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kaziner](https://github.com/Kaziner)**
_Monday Dec 17, 2018 at 12:38 GMT_

----

Its inside of the dungeon Mechanar (server crashed so can't go back inside) but based on my add-on in the pic i was at 70.6 69.7

**Comment by kelno** [comment]
<a href="https://github.com/Kittnz"><img src="https://avatars2.githubusercontent.com/u/5845231?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kittnz](https://github.com/Kittnz)**
_Monday Dec 17, 2018 at 13:07 GMT_

----

I checked, these are indeed missing gates. (Game objects) @kelno this should be fixed after importing all gobs from tc.

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Dec 17, 2018 at 13:18 GMT_

----

That's strange those were there before. Maybe not spawned in both normal and heroic.

**Comment by kelno** [comment]
<a href="https://github.com/Kittnz"><img src="https://avatars2.githubusercontent.com/u/5845231?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kittnz](https://github.com/Kittnz)**
_Monday Dec 17, 2018 at 13:20 GMT_

----

they are removed, a lot of area trigger teleports too

**Comment by Kaziner** [comment]
Confirmed fixed; please close
