### ISSUE TITLE
[#67] Quest not working as intended "Recharging the Batteries"

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#432]
<a href="https://github.com/kekrat"><img src="https://avatars0.githubusercontent.com/u/45924491?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kekrat](https://github.com/kekrat)**
_Wednesday Dec 19, 2018 at 00:46 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/67_

----

![wowscrnshot_121918_111225](https://user-images.githubusercontent.com/45924491/50191543-7c722d00-0382-11e9-872d-776084d6e1f5.jpg)

Current behaviour:
Using the quest item "Battery Recharging Blaster" on quest mobs "Phase Hunter" at low health when the emote "The Phase Hunter is very weak" appears as required by the quest caused;
- The mobs name to change to Drained Phase Hunter,
- The level up animation to occur, and 
- The mobs health to return to 100% HP.

Expected behaviour:
Using the quest item "Battery Recharging Blaster" on quest mobs "Phase Hunter" at low health when the emote "The Phase Hunter is very weak" appears as required by the quest to cause;
- The mobs name to change to Drained Phase Hunter,
- No level animation to occur, and 
- The mobs health to remain at the same level.

Steps to reproduce the problem:

1. Go to Netherstorm and talk to the questgiver NPC "Bot-Specialist Alley". 
2. Pick up the quest "Recharging the Batteries".
3. Go to location below in Netherstorm to find the quest mobs "Phase Hunter".
![image](https://user-images.githubusercontent.com/45924491/50191782-72046300-0383-11e9-8b88-a89e0b9aad1c.png)
4. Get a Phase Hunter to low health and wait for the "The Phase Hunter is very weak" emote to occur
5. Use the quest item "Battery Recharging Blaster" on the Phase Hunter
6. Watch the mob level up, and return to full health.

**When the mob is killed after "leveling up" and returning to full health quest credit is still given.**

IDs
[Item] Battery Recharging Blaster (28369)
[Quest] Recharging the Batteries (10190)
[NPC - Quest Giver] Bot-Specialist Alley (19578)
[NPC - Quest Mob] Phase Hunter (18879) and Drained Phase Hunter (19595)

Source
https://www.wowdb.com

**Comment by kelno** [comment]
<a href="https://github.com/Nolin7777"><img src="https://avatars2.githubusercontent.com/u/20132236?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nolin7777](https://github.com/Nolin7777)**
_Wednesday Dec 19, 2018 at 01:08 GMT_

----

Nice report

**Comment by Orcfootstool** [comment]
Picked up this quest recently and just wanted to add, the phase hunters are hitting way too hard.
![phasehunter](https://user-images.githubusercontent.com/48857734/56271463-e84f8100-613b-11e9-83f0-8fbd87c13fac.png)

**Comment by dinkletron** [comment]
Would also like to add since mob damage was updated this one broke.

NPC ID 18879.
According to http://db.hellfire-tbc.com/?npc=18879 melee should be hitting around 600.

**Comment by kelno** [comment]
Fixed
