### ISSUE TITLE
[#90] Spam shift-right clicking will cause you to re-mine a deposit without getting any ore

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#438]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Monday Dec 24, 2018 at 00:27 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/90_

----

Current behaviour:
When mining object 181556 I will shift + Right click to mining w/ auto loot, when I continue to spam right click the object, at the end of the channel the first channel will do nothing (no loot rec'd) and it will start the next channel. 

https://tbc-twinhead.twinstar.cz/?object=181556

Expected behaviour:
It should give me the ore from the first cast before starting the next cast

Steps to reproduce the problem:

Step 1. Mine object 181556
Step 2. Spam shift + right click on the ore and watch the first channel do nothing

**Comment by Kaziner** [comment]
Confirmed fixed; please close
