### ISSUE TITLE
[#143] [Server Crash] Rated Arena Finished and Server Crashed.

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#450]
<a href="https://github.com/Cheelout"><img src="https://avatars2.githubusercontent.com/u/38281939?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Cheelout](https://github.com/Cheelout)**
_Friday Jan 11, 2019 at 12:25 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/143_

----

Server crashed after completing a Rated Arena.. 2v2

Cant provide much more information then that.

**Comment by kelno** [comment]
<a href="https://github.com/Nolin7777"><img src="https://avatars2.githubusercontent.com/u/20132236?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Nolin7777](https://github.com/Nolin7777)**
_Friday Jan 11, 2019 at 13:01 GMT_

----

/home/tbc/server/src/server/game/Movement/MovementHandler.cpp:306 in HandleMovementOpcodes ASSERTION FAILED:
  control && control->GetSession() == this
Segmentation fault (core dumped)

0  0x0000000000dbe278 in Trinity::Assert (file=0xfc3c62 "/home/tbc/server/src/server/game/Movement/MovementHandler.cpp", line=306, function=0xfc3ed2 "HandleMovementOpcodes", debugInfo=...,
    message=0xfc3ee8 "control && control->GetSession() == this") at /home/tbc/server/src/common/Debugging/Errors.cpp:77

1  0x0000000000cfd450 in WorldSession::HandleMovementOpcodes (this=0x7fa2c4008000, recvData=...) at /home/tbc/server/src/server/game/Movement/MovementHandler.cpp:306

2  0x0000000000b4f4ef in WorldSession::Update (this=0x7fa2c4008000, diff=<optimized out>, updater=...) at /home/tbc/server/src/server/game/Server/WorldSession.cpp:358

3  0x0000000000ac7aa0 in Map::Update (this=0x4547eca0, t_diff=@0x7fa2cbffeddc: 30) at /home/tbc/server/src/server/game/Maps/Map.cpp:846

4  0x0000000000ac778a in Map::DoUpdate (this=0x4547eca0, maxDiff=100, minimumTimeSinceLastUpdate=<optimized out>) at /home/tbc/server/src/server/game/Maps/Map.cpp:813

5  0x0000000000afa96b in MapUpdateRequest::call (this=0x7fa1c41c37c0) at /home/tbc/server/src/server/game/Maps/MapUpdater.cpp:37

6  0x0000000000af9e39 in MapUpdater::LoopWorkerThread (this=0x1460bc0 <MapManager::instance()::instance+168>, enable_instance_updates_loop=0x1460d51 <MapManager::instance()::instance+569>)
    at /home/tbc/server/src/server/game/Maps/MapUpdater.cpp:152

7  0x00007fa2d8cd9e6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6

8  0x00007fa2d941a494 in start_thread (arg=0x7fa2cbfff700) at pthread_create.c:333

9  0x00007fa2d844eacf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

**Comment by Nolin7777** [comment]
Seems fixed somehow, will reopen if its still happening
