### ISSUE TITLE
[#151] [Hunter Pet] Attacks targets while player is mounted

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#456]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Saturday Jan 12, 2019 at 02:45 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/151_

----

When the Hunter is mounted (AND the Pet status is set to DEFENSIVE), the pet will  stop to attack targets who aggro onto the player as they are running.

The Hunter pet should automatically become 'PASSIVE' state while player is mounted, regardless of status set by player before being mounted.
It should then revert back to whatever status when  player dismounts

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Saturday Jan 12, 2019 at 09:22 GMT_

----

Can you source this exact behavior here?

**Comment by kelno** [comment]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [artieau](https://github.com/artieau)**
_Saturday Feb 02, 2019 at 13:24 GMT_

----

This would just need a video of a hunter running around in TBC while mounted and a pet out.
I am struggling to find such a video so far - anyone help!

**Comment by kelno** [comment]
Fixed in 10521

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider-core/commit/931cf5246783dcdc29d0ee43af52d896da0747a9

**Comment by artieau** [comment]
Regression, now broken again under server rev. 10660

**Comment by artieau** [comment]
Pets despawn when mounting, so this issue is no longer relevant
