### ISSUE TITLE
[#174] [NPC] Cursed Scarab (21306)

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#470]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Saturday Jan 26, 2019 at 13:44 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/174_

----

The mob Cursed Scarab (21306) spawns around NPC Apothecary Albreck (21279) after handing in quest Spinebreaker Post (10242).

The Scarabs have 6k health and do not despawn after 10-20 seconds as reported on wowhead. Their health should be a lot lower, and should despawn after a short period of time. Wowpedia has listed their health as 296, Wowhead has listed their health as 397.

**Comment by Jerrythemagicdog** [comment]
Fixed in 10932
