### ISSUE TITLE
[#191] [NPC] Bonechewer Raider + Riding Wolf Not Despawning

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#481]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Sunday Jan 27, 2019 at 08:04 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/191_

----

Engaging a Bonechewer Raider (#16925) spawns a Bonechewer Riding Wolf (#18706), As intended.

If you run away or die/leave combat, the spawned Bonechewer Riding Wolf (#18706) remains. 

Re-enaging the same Bonechewer Raider (#16925) again spawns another Bonechewer Riding Wolf (#18706), aswell as the original one being present.

They dont seem to de-spawn even after 5-10mins, and managed to spawn at least 5-6 Riding Wolfs, furthermore they dont evade properly, as in you can attack then when they go back to their 'reset' position.

Intended fix would be either despawn after combat and/or should not be able to spawn multiples. I have a video on request, if not heres some pics:

![tbc_bone1](https://user-images.githubusercontent.com/46832429/51798437-5041aa00-2266-11e9-9cd7-4f77ec6c874c.png) 
![tbc_bone2](https://user-images.githubusercontent.com/46832429/51798439-56d02180-2266-11e9-9001-f29d63cc1c68.png)

**Comment by kelno** [comment]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BrockSamson1](https://github.com/BrockSamson1)**
_Sunday Jan 27, 2019 at 09:01 GMT_

----

Confirming this interaction

**Comment by kelno** [comment]
I've done some rewrite here, need testing!

**Comment by artieau** [comment]
Working perfectly now
