### ISSUE TITLE
[#192] [Quest] The Path of Glory 

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#482]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Sunday Jan 27, 2019 at 08:38 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/192_

----

Requirements for the quest 'The Path of Glory' (#10047) is that you need to cleanse 'Cleanse Trampled Skeleton' (#182789).

Issue: Everytime you cleanse the 'Trampled Skeleton' (#182789); It does not despawn in the world for a good 5mins, unable to loot again, animation still going. ie. Nothing changing.

Intended: Despawn immediately after cleansing.

**Comment by kelno** [comment]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BrockSamson1](https://github.com/BrockSamson1)**
_Sunday Jan 27, 2019 at 09:01 GMT_

----

Can confirm this interaction

**Comment by Tamosheik** [comment]
Appears to despawn for other players viewing, but not the player that cleansed it. A similar effect appears to happen for collecting salvageable metal/wood.

**Comment by kelno** [comment]
Will put gamebreaking here as this probably affects all objects

**Comment by SUN-Leekie** [comment]
https://github.com/thebarrensissues/Issues/issues/18

**Comment by kelno** [comment]
Closing as duplicate
