### ISSUE TITLE
[#201] [Quest] A Spirit Guide (9410)

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#489]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Sunday Jan 27, 2019 at 13:26 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/201_

----

Current behaviour: Ancestral Spirit Wolf is summonable from quest item Ancestral Spirit Wolf Totem (23669) at the location of the corpse. The wolf doesn't move up to the Mag'har camp after spawning. It just sits passively, and follows you passively
 
Expected behaviour: Ancestral Spirit Wolf actively moves up to end NPC  Gorkan Bloodfist (16845) which triggers him to become interactable so the quest can be finished.

**Comment by kelno** [comment]
<a href="https://github.com/SUN-Leekie"><img src="https://avatars0.githubusercontent.com/u/18554785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SUN-Leekie](https://github.com/SUN-Leekie)**
_Sunday Jan 27, 2019 at 17:37 GMT_

----

The Wolf still has its script but its movement are override by the "guardian" effect.

**Comment by mrqiksta** [comment]
tested 2 days ago - now applies aura and follows script. Works ok and was able to hand in.
