### ISSUE TITLE
[#208] [QUEST] City of Light - Escort not working as intended

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#492]
<a href="https://github.com/dreapon"><img src="https://avatars1.githubusercontent.com/u/46831677?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dreapon](https://github.com/dreapon)**
_Monday Jan 28, 2019 at 03:00 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/208_

----

**Patch:**
2.4.3

**Server Version:**
10296

**Current behaviour:**
Escort NPC (Khadgar's Servant) that is spawned when accepting quest follows the player like a pet

**Expected behaviour:**
NPC should follow a set path around Shattrath

**Steps to reproduce the problem:**

1. Talk to Haggard War Veteran to get pre-quest 'A'dal'
2. Talk to A'dal and turn in quest
3. Talk to Khadgar and accept quest 'City of Light'
4. Move character and Khadgar's Servant will follow you around like a pet

![khadgarservantbug2](https://user-images.githubusercontent.com/46831677/51812108-db20b400-22fb-11e9-88f1-148bdd247f94.gif)

**IDs**
[Quest] City of Light (10211)
[Quest] A'dal (10210)
[NPC] Khadgar's Servant (19685)
[NPC] Khadgar (18166)
[NPC] A'dal (18481)
[NPC] Haggard War Veteran (19684)

**Source**
http://db.hellfire-tbc.com

**Comment by kelno** [comment]
<a href="https://github.com/SUN-Leekie"><img src="https://avatars0.githubusercontent.com/u/18554785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SUN-Leekie](https://github.com/SUN-Leekie)**
_Monday Jan 28, 2019 at 03:03 GMT_

----

Same issue as https://github.com/Nolin7777/TBC-Bugtracker/issues/201

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Jan 28, 2019 at 13:50 GMT_

----

Thank for you the video

**Comment by BarrensJerk** [comment]
Still broken on live now, really needs a fix, cannot select aldor / scryer without it

**Comment by kelno** [comment]
Fixed with 10814
