### ISSUE TITLE
[#215] [Talents] Rogue - Ruthlessness occasionally giving extra combo points

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#498]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BrockSamson1](https://github.com/BrockSamson1)**
_Monday Jan 28, 2019 at 05:22 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/215_

----

Patch:
2.4.3

Current behaviour:
Ruthlessness 3/3 ID: 14161, occasionally adds 2 or 3 combo points when a finishing move is used. 
Talent ppears to be a 20% chance at a combo point per talent point added.

Expected behaviour:
20/40/60% chance to add a **single** combo point.

Steps to reproduce the problem:
Have 3/3 ruthlessness rogue talent
Engage mob
Build combo points
Use finishing move
Observe combo points on target
Repeat until extra combo points are observed

**Comment by kelno** [comment]
<a href="https://github.com/Jerrythemagicdog"><img src="https://avatars1.githubusercontent.com/u/46463908?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Jerrythemagicdog](https://github.com/Jerrythemagicdog)**
_Monday Jan 28, 2019 at 17:13 GMT_

----

Tested, the most I can get is 2 though, not 3. Seems like it procs twice - it's not a visual bug I tried with Rupture to confirm (duration scales with combo points. )
What gear and other talents are you using during the test?

Test video: https://streamable.com/w029t

Duration is 16 seconds whenever used with 5 combo points.

rev: Sunstrider rev. 10304 (425c4ec03e75) 2019-01-27 16:42:07 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BrockSamson1](https://github.com/BrockSamson1)**
_Tuesday Jan 29, 2019 at 06:02 GMT_

----

Only gear i have that cause procs are the shadowcraft set 6 set bonus for extra energy proc, hand of justice and hearth of wyrmthalak trinkets.
None of my other talents cause combo point gain, only relentless strikes is a proc that causes energy gain. Basically was combat swords to 41 points, and assassination to ruthlessness.

I only have a vague recollection of seeing 3, usually only 2. My assumption was that .2*.2*.2 = 1/125 which is pretty rare. Whereas .2*.2 = 1/25 which is noticeable.

**Comment by emorelix** [comment]
As of 10962, this ability from talents is still often giving 2 combo points instead of 1.

**Comment by SUN-Leekie** [comment]
Fixed in 11247.

**Comment by HueHueTBCTheBarrens** [comment]
as of 11271, it doesn't proc at all.
