### ISSUE TITLE
[#219] Unable to loot Container items after interrupting/not looting (That is already being used error)

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#501]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Monday Jan 28, 2019 at 15:10 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/219_

----

Had this happen a few times now, but its a hard one to replicate all the time.

What Should happen: You attempt to retrieve an object for a quest or to loot, **and** it has a timer on it/process. You loot the item.

What is Happening: If you break the process while looting, and try again **and/or** you dont loot it initially, it becomes bugged with the error 'That is already being used'.

What is also Happening: The item is either not despawning, or taking a considerable long time, when the above happens.

Steps to reproduce: Found at least 2 items that had this issue thus far. Containers: Shredder Parts (#183934); Ravager Egg (#181385). 

1. Inside the container is requirements for quests (#9349) (#10236)
2. You loot the container
2.1. Either break the looting or loot without actually taking the item
3. Attempt to loot again
3.1. You loot the item! (ive found this intermittent)
3.2. You restart your client and it works (3.1)
4. Get the error: 'That is already being used.'
4. Unable to loot, and doesnt seem to despawn at all (check below)

What is intended to happen: You loot the item, container despawns.

Fix currently: Force Restarting/re-logging.

![tbc_quest_spawn11](https://user-images.githubusercontent.com/46832429/51844972-b0ba0f80-236a-11e9-9b26-2f47d2ebdc26.jpg)
![tbc_quest_spawn22](https://user-images.githubusercontent.com/46832429/51844978-b3b50000-236a-11e9-88a8-ec33c20583d6.jpg)

Note the times in the right hand corner before a force restart.

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Tuesday Jan 29, 2019 at 16:33 GMT_

----

Probably related to https://github.com/Nolin7777/TBC-Bugtracker/issues/90

**Comment by kelno** [comment]
<a href="https://github.com/SUN-Leekie"><img src="https://avatars0.githubusercontent.com/u/18554785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SUN-Leekie](https://github.com/SUN-Leekie)**
_Saturday Feb 02, 2019 at 23:02 GMT_

----

Does this still happen? I think it's fixed. 🤔

**Comment by kelno** [comment]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zemfi](https://github.com/zemfi)**
_Wednesday Feb 06, 2019 at 05:24 GMT_

----

still present in rev. 10357

just had it with Zepplin Debris (#183394)

![tbc_used_error](https://user-images.githubusercontent.com/46832429/52322043-a1525a80-2a2b-11e9-8a2e-eac6507d8361.jpg)

**Comment by artieau** [comment]
Fixed as of 10766
