### ISSUE TITLE
[#224] Stillpine Hold

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#504]
<a href="https://github.com/silumor"><img src="https://avatars2.githubusercontent.com/u/46830678?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [silumor](https://github.com/silumor)**
_Tuesday Jan 29, 2019 at 03:27 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/224_

----

Current behaviour: When i entered the back of this cave where "The Kurken" Spawns along with some Crazed Wildkin, the NPCs disappeared as soon as i entered combat with them. cannot complete Quest "The Kurken is Lurkin'" quest=9570

Expected behaviour: Mobs should engage in melee combat

Steps to reproduce the problem:

Cannot reproduce as mobs have disappeared and have no re spawned after 3-4 hours.

The Kurken npc=17447

Crazed Wildkin npc=17189

Stillpine Hold object=181777

quest=9570

**Comment by kelno** [comment]
<a href="https://github.com/silumor"><img src="https://avatars2.githubusercontent.com/u/46830678?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [silumor](https://github.com/silumor)**
_Tuesday Jan 29, 2019 at 08:32 GMT_

----

I've found the mobs, they have teleported to the same location, but above the cave if that makes sense.

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Wednesday Jan 30, 2019 at 21:53 GMT_

----

Yes, thanks

**Comment by kelno** [comment]
<a href="https://github.com/silumor"><img src="https://avatars2.githubusercontent.com/u/46830678?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [silumor](https://github.com/silumor)**
_Sunday Feb 03, 2019 at 01:39 GMT_

----

Crazed Wildkin npc=17189 still flying up to outside of cave

Sunstrider Rev. 10357 (a9a5f35b2353) 2019-02-02 00:25:39 -0500 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by kelno** [comment]
<a href="https://github.com/SUN-Leekie"><img src="https://avatars0.githubusercontent.com/u/18554785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SUN-Leekie](https://github.com/SUN-Leekie)**
_Monday Feb 04, 2019 at 03:09 GMT_

----

I don't see any Crazed Wildkin flying, can you give a GUID with `.npc guid` or a video?

**Comment by artieau** [comment]
Please re-check and re-open if  required with additional info.
