### ISSUE TITLE
[#230] mithril in durotar

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#509]
<a href="https://github.com/balunn"><img src="https://avatars2.githubusercontent.com/u/46829506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [balunn](https://github.com/balunn)**
_Tuesday Jan 29, 2019 at 08:38 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/230_

----

![image](https://user-images.githubusercontent.com/46829506/51894990-42725d00-23fd-11e9-8838-8b8b7569ccf1.png)
I don't think these are meant to be here. co ords are in the screen shot

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/46829506/51895067-6b92ed80-23fd-11e9-8b2d-cf5029c4683f.png)

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Monday Feb 11, 2019 at 18:35 GMT_

----

Can you `.gps` there? Its hard to see where you are

**Comment by artieau** [comment]
Please add info and re-open
