### ISSUE TITLE
[#239] Kil'sorrow ritualists seem stuck in place

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#516]
<a href="https://github.com/BrockSamson1"><img src="https://avatars3.githubusercontent.com/u/46757539?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BrockSamson1](https://github.com/BrockSamson1)**
_Thursday Jan 31, 2019 at 06:24 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/239_

----

**Current behaviour:**
Kil'sorrow ritualists ID: 18658 in lower part of Oshu'gun internal area do not move into line of sight to attack - Remain aggroed in position, fixated on player while maintaining combat status

**Expected behaviour:**

NPCs should try to engage the player in combat by moving towards a place where they are able to gain line of sight before they restart their usual programmed combat

**Steps to reproduce the problem:**

1. Body pull kil'sorrow ritualist
2. Move out of line of sight
3. Note unusual behaviour

**rev. hash/commit:** 

in screenshots

Casting in combat
![kil sorrow ritualist casting](https://user-images.githubusercontent.com/46757539/52034768-31505a00-257d-11e9-854f-daf1708eff85.jpg)

Not moving but still in combat
![kil sorrow ritualist not moving](https://user-images.githubusercontent.com/46757539/52034630-f1897280-257c-11e9-8391-4390c0bf071b.jpg)

**Comment by kelno** [comment]
<a href="https://github.com/SUN-Leekie"><img src="https://avatars0.githubusercontent.com/u/18554785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SUN-Leekie](https://github.com/SUN-Leekie)**
_Saturday Feb 02, 2019 at 03:51 GMT_

----

@kelno Seems like a core issue because the movements are really weird after running:
````sql
-- NPC 18658
SET @ENTRY = 18658;
UPDATE creature_template SET AIName='SmartAI', ScriptName='' WHERE entry = @ENTRY;
DELETE FROM smart_scripts WHERE entryorguid = @ENTRY AND source_type = 0;
INSERT IGNORE INTO smart_scripts (entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags, event_param1, event_param2, event_param3, event_param4, action_type, action_param1, action_param2, action_param3, action_param4, action_param5, action_param6, target_type, target_flags, target_param1, target_param2, target_param3, target_x, target_y, target_z, target_o, comment) VALUES 
(@ENTRY, 0, 1, 0, 37, 0, 100, 0, 0, 0, 0, 0, 58, 6, 9613, 3000, 3000, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Kil&#039;sorrow Ritualist - On AI Initialize - Install Caster SUN Template '),
(@ENTRY, 0, 2, 0, 0, 0, 100, 0, 5000, 8000, 35000, 45000, 11, 32063, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 'Kil&#039;sorrow Ritualist - In Combat - Cast "<a href="http://wowhead.com/spell=32063">Corruption</a>" '),
(@ENTRY, 0, 3, 0, 6, 0, 100, 0, 0, 0, 0, 0, 33, 21276, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 'Kil&#039;sorrow Ritualist - On Death - Quest Credit "<a href="http://wowhead.com/quest=21276">Kil"sorrow Agent</a>" ');
```

**Comment by SUN-Leekie** [comment]
Seems fixed.
