### ISSUE TITLE
[#241] [Quest] Off To Area 52 (10183)

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#518]
<a href="https://github.com/BarrensJerk"><img src="https://avatars0.githubusercontent.com/u/44628946?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BarrensJerk](https://github.com/BarrensJerk)**
_Thursday Jan 31, 2019 at 23:36 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/241_

----

**Current behaviour:**

Quest is not available from NPC 19569

**Expected behaviour:**

Quest should be available without any prerequisites from Netherologist Coppernickels (19569) as long as other breadcrumb quests aren't in questlog  (ExclusiveGroup 10183)

**Steps to reproduce the problem:**

1. Go to NPC 19569
2. Make sure none of the other breadcrumb quests have been completed or are in questlog
3. Quest not available

**rev. hash/commit:** 

10343 (8129e9d56781+)

**Comment by SUN-Leekie** [comment]
Fixed in 11257.
