### ISSUE TITLE
[#266] [NPC] Various Kneeling/laying NPC's dont change stance engaged

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#539]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Monday Feb 04, 2019 at 04:15 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/266_

----

**Current behaviour:** 

At least 3 different NPC's in Hellfire that kneel down, stay kneeled down when engaged but when moving/pathing they are in the correct stance (standing up) until stationary, back to kneeling.

**Expected behaviour:**

When engaging they should be standing up normally, not stuck in the kneeling/laying stance.

**Steps to reproduce the problem:**

NPC's effected (so far):
Debilitated Mag'har Grunt (#16847)
Mag'har Grunt (#16846)
Bleeding Hollow Necrolyte (#19422)

1. Find the above NPC's that are kneeling/laying down
2. Engage them, and notice they are stuck kneeling/laying down stationary (half their body is in motion)
3. With Bleeding Hollow Necrolyte; they seem to be completely bolted to the ground, even when oom, they will not move when they should.

![tbc_stance1](https://user-images.githubusercontent.com/46832429/52189892-8ea31e80-288f-11e9-883b-f19b4e8f796d.jpg)
![tbc_stance2](https://user-images.githubusercontent.com/46832429/52189897-92cf3c00-288f-11e9-987d-6ddcc0ecbe60.jpg)
![tbc_sleepattack](https://user-images.githubusercontent.com/46832429/52189900-95ca2c80-288f-11e9-9518-128a3a3d7c38.png)
![tbc_stance3-recap](https://user-images.githubusercontent.com/46832429/52189974-21dc5400-2890-11e9-94f3-fe768a169c8e.jpg)

.rev 10357

**Comment by kelno** [comment]
Working now?

**Comment by artieau** [comment]
Working now
