### ISSUE TITLE
[#274] Visual/Graphical Bug, Losing UI in Combat

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#544]
<a href="https://github.com/zemfi"><img src="https://avatars1.githubusercontent.com/u/46832429?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zemfi](https://github.com/zemfi)**
_Wednesday Feb 06, 2019 at 07:01 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/274_

----

This one is a weird one that has happened to me a randomly a few times, no idea why until now..

**Current behaviour:**

Getting into combat, going to your world map and back out again loses your UI/HUD.

**Expected behaviour:**

Going to your map while in combat and out again should not lose your UI.

**Steps to reproduce the problem:**

1. Either mount up or get into combat
2. Push M on the keyboard or world map, get back out
3. You lose your ui completely, unable to get it back until your out of combat and map again (similar to alt-z)

1. ![tbc_visual1](https://user-images.githubusercontent.com/46832429/52325432-1a0be380-2a39-11e9-9899-69f7e9c4f86b.jpg)
2. ![tbc_visual2](https://user-images.githubusercontent.com/46832429/52325434-1a0be380-2a39-11e9-906c-70e553adffe0.jpg)
3. ![tbc_visual3](https://user-images.githubusercontent.com/46832429/52325435-1a0be380-2a39-11e9-9fe9-035292de57a0.jpg)

.rev 10357

**Comment by kelno** [comment]
<a href="https://github.com/kelno"><img src="https://avatars2.githubusercontent.com/u/3866946?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kelno](https://github.com/kelno)**
_Wednesday Feb 06, 2019 at 20:24 GMT_

----

Congratulations, you won the strangest bug of the month contest.
Can you list the addons you're using here?

**Comment by artieau** [comment]
This is addon related, please  re-open if you find it again and list the addons in use.
