### ISSUE TITLE
[#291] [Kara] Curator

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#557]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Sunday Feb 10, 2019 at 10:18 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/291_

----

**Current behaviour:**

When killed, boss only provides 1 unique piece of loot (sometimes none).

**Expected behaviour:**

The boss should give 1 unique item and 1 T4 token.

**Steps to reproduce the problem:**

1. Using strong communication and team work, bring down the boss.
2. Hold each other and cry when only 1 item is rewarded.

**rev. hash/commit:** 

REV: 10421

**Comment by Cheelout** [comment]
This is fixed.
