### ISSUE TITLE
[#327] [Dungeon] Sethekk Halls - door doesn't open

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#571]
<a href="https://github.com/artieau"><img src="https://avatars0.githubusercontent.com/u/40563134?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artieau](https://github.com/artieau)**
_Wednesday Feb 13, 2019 at 11:44 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/327_

----

**Current behaviour:**

After killing the final boss of Sethekk Halls, Talon King Ikiss # 18473
The door between the boss room and instance entrance does not open

**Expected behaviour:**

The door should open when the boss # 18473 dies.

**Steps to reproduce the problem:**

1. Kill Talon King Ikiss
2. Run to door
3. Faceplant on door

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/52709459-e43ea000-2fe0-11e9-9ce4-d2a8e93c675f.png)

NOTES: 
- Please don't be shy on the details and context, screenshots and videos are VERY welcome
- Include the ID for game objects, npcs (creatures, pets, minions), spells, items, quests, instances, zones, skills related to this issue.

**Comment by SUN-Leekie** [comment]
Seems fixed.
