### ISSUE TITLE
[#328] Bogstroks in SP walk instead of running

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#572]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 12:20 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/328_

----

**Current behaviour:**

Bogstrok's walk while patrolling

**Expected behaviour:**

They should run; fairly fast; it should be difficult to try and avoid those packs but at their current speed its much easier

**Steps to reproduce the problem:**

1. Zone into Slave pens
2. Observe slow movement of Bogstriks

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/45530324/52711174-d7b84880-2fdc-11e9-9d24-0a990ec525a5.png)

https://db.excalibur.ws/?npc=17816

**Comment by kelno** [comment]
<a href="https://github.com/Jerrythemagicdog"><img src="https://avatars1.githubusercontent.com/u/46463908?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Jerrythemagicdog](https://github.com/Jerrythemagicdog)**
_Wednesday Feb 13, 2019 at 14:52 GMT_

----

Would love some sources

**Comment by Kaziner** [comment]
https://www.youtube.com/watch?v=AMhMcysXNjw - 10 seconds in

@Jerrythemagicdog

**Comment by Kaziner** [comment]
Confirmed fixed; please close
