### ISSUE TITLE
[#329] Wastewalker Captives become untargetable when their naga dies and continue to attack you

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#573]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 12:22 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/329_

----

**Current behaviour:**

Wastewalker Captives become untargetable when their naga dies and continue to attack you

**Expected behaviour:**

They should become neutral and run away

**Steps to reproduce the problem:**

1. Pull back of Wastewalker Captives and their naga at the start of slave pens
2. Kill the Naga
3. Observe them become untargetable and continue to attack you

![image](https://user-images.githubusercontent.com/45530324/52711495-ad1abf80-2fdd-11e9-845d-b3b3d130d7cc.png)

https://db.excalibur.ws/?npc=18206

**Comment by Kaziner** [comment]
Confirmed fixed; please close
