### ISSUE TITLE
[#336] The black stalk's Levitate spell doesnt work correctly

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#581]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 12:49 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/336_

----

**Current behaviour:**

The black stalk casts Levitate on a player and basically nothing happens

**Expected behaviour:**

They should get pushed up into the air when the spell is cast on a player

**Steps to reproduce the problem:**

1. Pull the black stalk
2. Let it cast Levitate on you
3. Observe it do nothing to you

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

![image](https://user-images.githubusercontent.com/45530324/52712796-629b4200-2fe1-11e9-8c75-f51c1db36621.png)

https://db.excalibur.ws/?npc=17882#controlled-abilities
https://db.excalibur.ws/?spell=31704

https://www.youtube.com/watch?v=qzynrfdTezk

Watch around the 55 second mark

**Comment by Kaziner** [comment]
Confirmed fixed; please close
