### ISSUE TITLE
[#340] Cache of the legion is in the wrong spot

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#585]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 13:05 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/340_

----

**Current behaviour:**

Cache of the legion is in the wrong spot

**Expected behaviour:**

It should be closer to the wall

**Steps to reproduce the problem:**

1. Look at it

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

![image](https://user-images.githubusercontent.com/45530324/52713455-15b86b00-2fe3-11e9-9d46-5ea7c6956259.png)

https://www.youtube.com/watch?v=zOCAa8--zyg

**Comment by Kaziner** [comment]
Confirmed fixed; please close
