### ISSUE TITLE
[#341] Pathaleon the Calculator not spawning adds

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#586]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 13:06 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/341_

----

**Current behaviour:**

Pathaleon the Calculator doesn't spawn adds

**Expected behaviour:**

He should spawn adds (I think at certain heal break-points not 100% sure tho)

**Steps to reproduce the problem:**

1. Fight Pathaleon the Calculator
2. Wait a while; do some damage; kill him; note no adds spawn

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

https://db.excalibur.ws/?npc=19220#drop

https://www.youtube.com/watch?v=ZWH17QjFrqo - 20s in

![image](https://user-images.githubusercontent.com/45530324/52713759-e22a1080-2fe3-11e9-9d14-4cb1d19e667d.png)

**Comment by Kaziner** [comment]
Confirmed fixed; please close
