### ISSUE TITLE
[#342] Tempest-Forge Patroller aggro's from miles away and paths through walls

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#587]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 13:09 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/342_

----

**Current behaviour:**

Tempest-Forge Patroller aggro's from miles away and paths through walls

**Expected behaviour:**

He should accept the world isn't perfect on his peace keeping mission and not aggro from miles away and phase through walls to come and apply peace to my face; should path normally

**Steps to reproduce the problem:**

1. Zone into Bot
2. Stand anywhere near this dude with a wall between you
3. Watch him aggro and come through walls to get you

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

https://db.excalibur.ws/?npc=21578

![image](https://user-images.githubusercontent.com/45530324/52713864-2e755080-2fe4-11e9-882d-05bc22b6ee3a.png)

**Comment by Kaziner** [comment]
Confirmed fixed; please close
