### ISSUE TITLE
[#345] Sunseeker channelers in Bot infront of Stayr boss don't patrol

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#590]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 13:24 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/345_

----

**Current behaviour:**

They just sit there

**Expected behaviour:**

They should walk to the middle of the demons; cast some weird magic shit for a bit then walk back to where they are closer to the boss

**Steps to reproduce the problem:**

1. Step 1 Watch a Sunseeker channeler in Bot

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

https://db.excalibur.ws/?npc=21571

![image](https://user-images.githubusercontent.com/45530324/52714681-41892000-2fe6-11e9-9796-6e404791bd9c.png)

**Comment by kelno** [comment]
<a href="https://github.com/Jerrythemagicdog"><img src="https://avatars1.githubusercontent.com/u/46463908?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Jerrythemagicdog](https://github.com/Jerrythemagicdog)**
_Wednesday Feb 13, 2019 at 14:29 GMT_

----

Would love a source on that one, the other video you provided unfortunately doesn't show that.
(https://youtu.be/UaC8ZY1C6ag?t=273)
Nothing in their spells either that would indicate that, wowhead comments and wowwiki also helpless.

**Comment by kelno** [comment]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kaziner](https://github.com/Kaziner)**
_Thursday Feb 14, 2019 at 02:22 GMT_

----

What sources would you limit research to?

I understand youtube vids of retail tbc or original comments are gold but if I can provide several P-server videos all showing how something is sopost to work would that be enough evidence? 

Not asking specifically for this issue but has a general question; I have tried to find original vids and original guides/forums etc for alot of this stuff but its really hard; alot more content is available for P-server stuff; so hoping if I can show 2+ p servers behave in a certain way that would be enough evidence (as long as it aligns with my memory of how something is sopost to work as well)

**Comment by kelno** [comment]
<a href="https://github.com/SUN-Leekie"><img src="https://avatars0.githubusercontent.com/u/18554785?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SUN-Leekie](https://github.com/SUN-Leekie)**
_Thursday Feb 14, 2019 at 14:27 GMT_

----

We hardly take other private server as evidence. You can probably find a retail video running the dungeon. These kind of animations rarely change over the years.

**Comment by Kaziner** [comment]
https://www.youtube.com/watch?v=aY9vfmEFAqI - 24:06 - 24:22; channels drops channeling the crystal; goes to the middle of the demons and does some magic shit

I understand this video is WOLK but struggling to find a full run from TBC on youtube. It does very clearly show the expected behavior for this mob

![image](https://user-images.githubusercontent.com/45530324/52864904-ff4b1480-3186-11e9-9a29-8c11f2da9fe4.png)

**Comment by Kaziner** [comment]
Confirmed fixed; please close

**Comment by kelno** [comment]
Thanks
