### ISSUE TITLE
[#356] When pulling Blackheart the inciter the entire room of mobs should get aggro'd if they are alive

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#599]
<a href="https://github.com/Kaziner"><img src="https://avatars2.githubusercontent.com/u/45530324?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kaziner](https://github.com/Kaziner)**
_Wednesday Feb 13, 2019 at 13:48 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/356_

----

**Current behaviour:**

When you aggro blackheart the inciter only the boss aggros; nothing else

**Expected behaviour:**

When pulling Blackheart the inciter the entire room of mobs should get aggro'd if they are alive

**Steps to reproduce the problem:**

1. Aggro blackheart the incienter

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

This is in place to force teams to clear the entire room

![image](https://user-images.githubusercontent.com/45530324/52716111-c7f33100-2fe9-11e9-8cac-1c1d5fa44375.png)

https://db.excalibur.ws/?npc=18667

**Comment by SUN-Leekie** [comment]
Fixed in 11293.
