### ISSUE TITLE
[#364] [Black Morass] Medivh Shield Event

### ISSUE THREAD

**Issue by kelno** [thebarrensissues/Issues#607]
<a href="https://github.com/Paralol"><img src="https://avatars3.githubusercontent.com/u/4516769?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Paralol](https://github.com/Paralol)**
_Thursday Feb 14, 2019 at 11:07 GMT_
_Originally opened as https://github.com/Nolin7777/TBC-Bugtracker/issues/364_

----

**Current behaviour:**

Medivh starts losing shield before as soon as the event starts and before any portals open.

![image](https://user-images.githubusercontent.com/4516769/52783039-558f5900-309c-11e9-867b-53aece7d9cad.png)

**Expected behaviour:**

Shield should only be lost if an add spawned from a portal walks close to Medivh and casts a spell.

**Steps to reproduce the problem:**

1. .tele blackm
2. Walked up to Medivh to start the event
3. Cry as you lose shield before anything spawns

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/4516769/52783071-70fa6400-309c-11e9-8b71-91626080a058.png)

**Comment by giveusmezpls** [comment]
it appears that until the first portal is complete, the shield starts dropping.
once the first portal is done the shield only drops when adds are alive (doesn't count elites).

**Comment by Harrock1** [comment]
Now the final 3 portals appear within 20 seconds of eachother, causing 3x waves of adds + end boss going to medivh

**Comment by artieau** [comment]
Fixed as of 11323
