### ISSUE TITLE
Rarespawn Duke Ragereaver outside Stratholme

### ISSUE THREAD

**Issue by kakarotkaruma** [thebarrensissues/Issues#617]
**Description:**

Found a level 45 rarespawn "Duke Ragereaver" outside of the Stratholme instance. Had 219912 HP but did very little damage. Not sure if health is overtuned so reporting just in case. Also did not drop any loot when killed.

**Current behaviour:**

Very beefy boiybut soloable by a level 58 prot warrior (took about 15 minutes)

**Expected behaviour:**

Not sure if should be so beefy.

**Comment by kelno** [comment]
https://www.wowhead.com/npc=10820/duke-ragereaver

**Comment by Cheelout** [comment]
Fixed with CALL DeleteCreature(74033)
