### ISSUE TITLE
[Game Object] Deer riding a goat on the path to Western Plaguelands

### ISSUE THREAD

**Issue by drak41** [thebarrensissues/Issues#643]
Saw a Deer riding a goat on my way to Western Plaguelands, coming from Alterac Mountain's

Deer should not be able to ride anything.

see above

Deer should be on the ground maybe walking beside the goat but not riding it.

**Expected behaviour:**

**Steps to reproduce the problem:**
![image](https://user-images.githubusercontent.com/47776284/53081809-b234bd00-354f-11e9-81f6-589645c093a7.png)
Location:
![image](https://user-images.githubusercontent.com/47776284/53081893-d8f2f380-354f-11e9-9f90-9d3031201d79.png)

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`
![image](https://user-images.githubusercontent.com/47776284/53082177-6f271980-3550-11e9-81f0-d49ebe8cb65e.png)

**Comment by kelno** [comment]
She got better 

![](https://i.imgur.com/x4xTXZc.jpg)
