### ISSUE TITLE
[Shadow Labyrinth] Murmur fight event

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#646]
**Description:**

When entering the Murmur room (last boss of Shadow Labyrinth) the players should see the NPCs fight Murmur in an epic battle for survival like here: https://youtu.be/9aLlWZdHa74?t=1321

**Current behaviour:**

Currently everyone is just standing there in a standoff. 

**rev. hash/commit:** 
Sunstrider rev. 10526

**Comment by kelno** [comment]
2681ff7decdd77a131b06141609be6b02b1beb47
