### ISSUE TITLE
Druid Swift flight form - Quest not available 

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#648]
**Description:**

No swift flight form

**Current behaviour:**

Swift flight form not learnt from 70 boost, also no quest available, despite having the riding training to unlock quest.

**Expected behaviour:**

druid quest meant for swift flight form meant to be picked up from druid trainer once you have the riding skill for it. 

Evidence of quest:
https://wowwiki.fandom.com/wiki/Swift_Flight_Form_quest_chain

Quest:
https://tbc-twinhead.twinstar.cz/?quest=11001

![wowscrnshot_022219_113430](https://user-images.githubusercontent.com/47015256/53211594-d7334800-3695-11e9-8dfb-30077d5451ca.jpg)

**Comment by BarrensJerk** [comment]
Wasn't in the game in 2.0x

**Comment by BarrensJerk** [comment]
https://wowwiki.fandom.com/wiki/Patch_2.1.0

**Comment by Tamosheik** [comment]
Chain not patch appropriate, please reopen ticket if not available on patch 2.1.0 release
