### ISSUE TITLE
[NPC] Talon King Ikiss (18473)

### ISSUE THREAD

**Issue by BarrensJerk** [thebarrensissues/Issues#658]
**Description:**

Talon King Ikiss on normal mode intermittently casts Arcane Explosion (38197)
The cast should take 5 seconds, and his cast bar displays a 5 second cast, but the spell is completing early at ~3.5 seconds, without his cast bar completing.

**Steps to reproduce the problem:**

1. Go into normal Sethekk Halls
2. Fight last boss
3. Get destroyed by Arcane Blast which completes long before the cast bar completes

**rev. hash/commit:** 
Sunstrider rev. 10531 (1dce6855d2c0)

**Comment by soup1234** [comment]
Confirming this with #660
Same issue with spell casting speeds from player and mobs/bosses

**Comment by SUN-Leekie** [comment]
Seems fixed.
