### ISSUE TITLE
Casting speeds/cast bars possibly 30% or higher, faster.

### ISSUE THREAD

**Issue by DotDotGoose** [thebarrensissues/Issues#660]
**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**
Mobs and player casting and attack speeds are easily over 30% faster AFTER heroism/ or possibly drums of battle are used.

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected 
Normal casting and attack speed on both mob and player.

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**
Possibly caused by heroism or drums, but doing raid/dungeons after heroism was popped everyone speed was significantly sped up.

Could be reversed on restart, but will continue to be a problem if not handled.

CHANGEME
1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead-like page.  
2. Step 2
3. Step 3

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by artieau** [comment]
Please give examples
Please share steps
Please post rev screenshot

**Comment by artieau** [comment]
From my experience though, there is something incorrect with certain channel or longer cast spells.
Resurrect spells end their cast at 3 seconds remaining on the cast
Windfury buff on weapon ends at 3sec remaining on buff

**Comment by Desparto** [comment]
I think slice and dice was dropping off with a few seconds remaining last night also but will look into this further

**Comment by artieau** [comment]
Just tested on a Priest and RENEW  expires with 3 seconds remaining on player

**Comment by soup1234** [comment]
Tested: 
vampiric touch 15 second dot, ticks to 12 seconds
Mindflay: 3 sec channeled cast to 1.75 seconds 
SW:P haven’t checked
Mindblast: 1.5 sec cast to 1.1
Most 30 second cooldowns are also sped up atleast 3 seconds quicker

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, seems like some weird interaction, please try to provide reproduce steps.

**Comment by artieau** [comment]
@soup1234 @Desparto Were these tested in a dungeon? Had your toon been affected by Heroism/Bloodlust prior (not even during test) ?
My tests were all in dungeons

**Comment by Jerrythemagicdog** [comment]
Seems to happen only at The Barrens PTR and all casts, buffs and debuffs are affected. Can't reproduce locally or on EU PTR.

**Comment by soup1234** [comment]
This happened after the raid we had the other night, the speed of the heroism continued after it ended, then did a few dungeons and the speed was still there but still not 100% sure if it’s the heroism that caused it. We need to setup a group and try it out.

**Comment by Desparto** [comment]
@artieau this was during Gruul testing the other night. My SnD was dropping with seconds still remaining on it. I would say I'd been affected by Bloodlust yes

**Comment by artieau** [comment]
Still happens, we reproduced a few weeks/month back with Jerry on Kelno PTR.
Randomly appears still, not sure how to force reproduce.
Relog clears it.
@Jerrythemagicdog

**Comment by artieau** [comment]
Kelno band-aid has cleared this issue - please re-open if anything new is observed.
