### ISSUE TITLE
[Professions] Can Currently learn all professions

### ISSUE THREAD

**Issue by Hoochsex** [thebarrensissues/Issues#662]
Description:

Can currently learn more then 2 Professions from trainers

Current behaviour:

![image] https://user-images.githubusercontent.com/45529944/53274296-8299d680-3742-11e9-9cd0-ccf5a987d040.png

Expected behaviour:

Should only be able to learn a max of 2 professions from trainers

Steps to reproduce the problem:

Step 1 Create fresh Character
Step 2 try learn as many professions from trainers 

rev. hash/commit:

CHANGEME

![image](https://user-images.githubusercontent.com/45529944/53274427-f20fc600-3742-11e9-84d5-602476f99bfd.png)

**Comment by plutonium447** [comment]
***Update***
This issue still occurs in rev. 10697

**Comment by plutonium447** [comment]
![WoWScrnShot_032019_091100](https://user-images.githubusercontent.com/40911527/54648576-8f67db00-4af2-11e9-81dc-c515d79509be.jpg)
![WoWScrnShot_032019_092054](https://user-images.githubusercontent.com/40911527/54648580-9262cb80-4af2-11e9-975b-565ec22d0a69.jpg)

**Comment by kelno** [comment]
Should be fixed at next update

**Comment by artieau** [comment]
https://cdn.discordapp.com/attachments/557626093654376458/561707645644439562/4_profs.jpg
Regression, can now learn more than 2 profession again
Rev. 10808

**Comment by kelno** [comment]
Not a regression, but some cases were not covered apparently

**Comment by kelno** [comment]
Fixed with 10811
