### ISSUE TITLE
Resurrect spells on released players

### ISSUE THREAD

**Issue by artieau** [thebarrensissues/Issues#663]
**Description:**

Res spells do not work when used on players who have released spirit.
Cast completes, mana spent but player does not receive a res.

**Current behaviour:**

Using a Res spell on a player who has released spirit, does not grant the player the option to accept any Res.
Example used - Spell ID 25590

**Expected behaviour:**

Targetted player should receive a Res to accept/decline.

**Steps to reproduce the problem:**

CHANGEME
1. /point /laugh at your dead friend. They then cry and release spirit
2. Use a res spell on them (such as 25590)
3. ?? No res granted to targetted player

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/53274572-d0ffa300-374b-11e9-80f9-4fd76a62cf3e.png)

**Comment by woiwoz** [comment]
After testing, no problems were found.
rev.10565

**Comment by artieau** [comment]
Thanks - will retest when our PTR updates to 10565 then

**Comment by artieau** [comment]
@woiwoz 
Re-tested now.
Res works in same zone so if the dead player releases in open world and their ghost remains in the same zone, Res will work.
If player dies in dungeon and releases, their ghost is outside dungeon and res will not work inside the dungeon.
It seems that it depend where the dead player ghost is, which map/instance compared to the ressing player.

**Comment by woiwoz** [comment]
okay,Thank you for confirming the question. Check quickly

**Comment by kelno** [comment]
Fixed with 10780

**Comment by artieau** [comment]
Not working still.
1 time out of 100 it works randomly. @kelno

**Comment by zemfi** [comment]
Confirmed not working with Rebirth (Rank 6) (#26994) on a player that had released.

.rev 11118

**Comment by kelno** [comment]
Okay, so the first issue was indeed resolved but apparently the line of sight check was likely to fail in many case.
Fixed with 11517.
