### ISSUE TITLE
[Hunter] Pet training points

### ISSUE THREAD

**Issue by artieau** [thebarrensissues/Issues#664]
**Description:**

Pet skills taught via Beast Training (SPELL ID 5149) do not check how many points the player has to use. Just lets the player learn anything without restriction

**Current behaviour:**

Beast Training allows the player to teach any number of skills to their pet without restriction

**Expected behaviour:**

Beast Training lists a number of remaining training points and should limit the player to those points only. Can not go past that number.

**Steps to reproduce the problem:**

CHANGEME
1. OPen Beast Training and teach  skills to pet.
2. Teach skills until the remaining points becomes near 0
3. Keep teach skills forever as the game never stops you

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/53275246-6439d800-374e-11e9-8bee-866938fe2dbc.png)

**Comment by artieau** [comment]
![image](https://user-images.githubusercontent.com/40563134/53281348-e213d880-377a-11e9-8ea9-d76aa2f11b0b.png)
Number of current points available to spend after training...

**Comment by kelno** [comment]
Fixed with 10752.
This probably won't fix players having already abused this, those needs to be reset.

**Comment by kelno** [comment]
Should fix it but needs to be tested:
```
DELETE ps
FROM characters  c
JOIN character_pet cp ON c.guid = cp.owner
JOIN pet_spell ps ON ps.guid = cp.id
WHERE c.class = 3
```
