### ISSUE TITLE
[Shaman] Sentry Totem - Server crash

### ISSUE THREAD

**Issue by artieau** [thebarrensissues/Issues#667]
**Description:**

Sentry Totem (Spell 6495) can cause the server to crash.
Either on use/right click OR from Totemic Call (Spell 36936)

**Current behaviour:**

Sometimes when using Totemic Call (While having Sentry Totem out), the server can crash.

**Expected behaviour:**

The server should not crash.

**Steps to reproduce the problem:**

1. Place Sentry Totem
2. Right click the player buff to attempt changing sight position between player and totem
3. Use Totemic Call

I cant make this happen 100% of the time, but I spam it a few times in a row and eventually it crashes.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/53279110-f1d2f300-3761-11e9-9903-dfa3368005ee.png)

**Comment by kelno** [comment]
Can't crash my server with that, still happening for you?

**Comment by kelno** [comment]
Closed until news of this.
