### ISSUE TITLE
Vanilla Dire Maul boss lost in Outland.

### ISSUE THREAD

**Issue by soup1234** [thebarrensissues/Issues#675]
**Description:**
Illyanna Ravenoak, npc at the Arena of blood in Blade's edge mountains.

**Current behaviour:**
She drops her normal dungeon loot when killed in the arena.
She is misplaced in the world.

**Expected behaviour:**
She needs to go back home.

![ill2](https://user-images.githubusercontent.com/46829458/53281600-741de000-377f-11e9-9179-164c372fdf47.jpg)
![lsotpn](https://user-images.githubusercontent.com/46829458/53281612-a0396100-377f-11e9-8a29-9a60e4d5c785.jpg)

**Comment by Kittnz** [comment]
seems a lot of npcs there should be removed
