### ISSUE TITLE
[SHAMAN] Talent: Healing Way

### ISSUE THREAD

**Issue by Deatherapy** [thebarrensissues/Issues#682]
**Description:**

The Shaman 'Healing Way' talent in the Restoration tree is adding an additional % healing to the spell Healing Wave after the 3 stack buff has been applied.

**Current behaviour:**

After the 3 stacks of Healing Way has been applied, the fourth Healing Wave spell (and any additional Healing Wave spells) will receive an additional healing % greater than the 18% as specified in the talent description

![image](https://user-images.githubusercontent.com/45929803/53297198-9d259a00-387f-11e9-8ce0-88a36f4ce2a5.png)

**Expected behaviour:**

This talent should only buff Healing Wave by 18% once 3 stacks of Healing way have been achieved. If we assume the first healing wave in the screenshot as a baseline, then 3 stacks of healing way should increase this by 18% to roughly 3050-3250 for all consecutive healing waves there after.

Rank 8 Healing Wave with +1651 healing was used for this test.

https://tbc-twinhead.twinstar.cz/?spell=29202

**Steps to reproduce the problem:**

1. Spec into the Restoration tree and put 3 points into Healing Way 
2. Cast 3 Healing Waves on self to proc 3 Healing Way buffs
3. Cast the 4th Healing Wave.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/45929803/53297245-584e3300-3880-11e9-95a8-c9305a3977ce.png)

**Comment by Cheelout** [comment]
Fixed.
