### ISSUE TITLE
[Rogue] Mace Specialization stun can proc on the Rogue

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#684]
**Description:**
Mace Specialization (13803 for max rank) can proc on the Rogue who has the talent specced and stun him. Should only proc on enemies.

**rev. hash/commit:** 

rev. 10543

**Comment by woiwoz** [comment]
I tested no problem rev: 10614

**Comment by kelno** [comment]
Should have been fixed somewhere last week.

**Comment by Nolin7777** [comment]
confirm fixed
