### ISSUE TITLE
[Mechanic] Stronger slow effects should override lesser effects

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#687]
**Description:**

Stronger slow effects should override lesser effects. Currently many slow effects can be present at the same time on the target meaning we can stack them and once one expires the other one will take over.
It should follow more or less the "more powerful spell is already active" logic with some exceptions. 

**Current behaviour:**
Currently there can be many different slow effects of varying effect strength on the target
https://imgur.com/a/rKkC3OS

**Expected behaviour:**

> Player1 applies crippling poison(70% slow) to Mob. Player2 casts frostbolt (40% slow) on Mob. Frostbolt does damage but no debuff is applied because there is already a stronger effect in place

> Player2 casts frostbolt (40% slow, 8 sec duration) on Mob, debuff is applied. Player1 applies crippling poison (70% slow, 2 sec duration), debuff is applied and frostbolt is removed.

> Debuffs with a secondary effect should stay as a debuff even if there are more powerful spells, but the effects themselves should not stack, some examples:
> Frost Armor (Slows movement and attack speed)
> Curse of Exhaustion (slows movement and has a hidden secondary effect, warlocks drain life (talented) heals more depending on warlock debuffs on the target) applied along with Crippling Poison here: https://www.youtube.com/watch?v=t8iiLNszJpU&feature=youtu.be&t=175

**Some sources**:

https://youtu.be/8mNaTUiowTk?t=2m17s
2:17 Crippling poison removes Hamstring

https://www.youtube.com/watch?v=a3yTchRq8Ls
1:56 Cone of cold removes Frostbolt debuff
7:55 Crippling poison removes Frostbolt debuff

**rev. hash/commit:** 
rev. 10543

**Comment by kelno** [comment]
Updated, need to be tested!

**Comment by kelno** [comment]
Still worked on

**Comment by kelno** [comment]
Fixed with 11020

**Comment by DotDotGoose** [comment]
Add mindflay to this list, Cannot cast it on mobs/enemy players with hamstring crippling etc says there's currently a stronger spell on it

**Comment by kelno** [comment]
It should be fixed by now
