### ISSUE TITLE
'Coilfang Resevoir Waterfall' Game object is clickable (184212)

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#690]
**Description:**

 The waterfall that acts as the gate to Serpentshrine Cavern is clickable (184212)

**Current behaviour:**

Currently able to click and mouse over the object 'Coilfang Resevoir Waterfall' (184212)

**Expected behaviour:**

Waterfall should not be clickable nor should you see the objects name. The waterfall should simply disappear when approached with key in bags.

**Steps to reproduce the problem:**

Visit Serpentshrine cavern and mouse over the waterfall.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/53308443-4ce72000-38f1-11e9-8fb2-37b047f35f41.png)

**Comment by Jerrythemagicdog** [comment]
Fixed some commits ago, now uses the correct quest.
