### ISSUE TITLE
Skar'this the Heretic has no cage NPC ID (22421)

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#691]
**Description:**

In heroic Slave pens, Skar'this the Heretic has spawned, however he should be contained within a cage

**Current behaviour:**

Skar'this the Heretic is simply standing there with no cage
![image](https://user-images.githubusercontent.com/35262513/53308827-30001c00-38f4-11e9-9c45-58af146fd43a.png)

**Expected behaviour:**

He should be in a cage
![image](https://user-images.githubusercontent.com/35262513/53308954-c8969c00-38f4-11e9-93b0-2421b3209a9d.png)

(image is from a 2007 video https://youtu.be/5Y1fbjDH2-0?t=49)
**Steps to reproduce the problem:**

1. Set dungeon mode to Heroic
2. Proceed through dungeon until you reach Skar'this the Heretic

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/53309002-27f4ac00-38f5-11e9-893d-355694f5795e.png)

**Comment by kelno** [comment]
FIXED. Somewhere recently.

**Comment by hufsa** [comment]
We even hired a construction worker to install this prison.
