### ISSUE TITLE
[SSC] Hydross adds are not immune to frost/nature damage

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#692]
**Description:**

Both types of adds on Hydross should be immune to BOTH nature and frost.
Tainted Water Elemental (21253)
Purified Water Elemental (21260)

**Current behaviour:**

Currently you can hit either add with both schools of nature and frost
![image](https://user-images.githubusercontent.com/35262513/53309396-773bdc00-38f7-11e9-9c85-5805c4fd1995.png)

**Expected behaviour:**

Adds should be immune
Source: https://wow.gamepedia.com/Hydross_the_Unstable#Abilities

**Steps to reproduce the problem:**

CHANGEME
1. Target either type of add
2. Cast a nature or frost spell
3. It will damage even though it should be immune

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/53309292-fbda2a80-38f6-11e9-8cc1-048aaf119913.png)

**Comment by kelno** [comment]
Fixed with 10565

**Comment by Jerrythemagicdog** [comment]
This is not a big deal, but the water one should be immune to frost, the nature should be immune to nature.
From your source: 
https://wow.gamepedia.com/Hydross_the_Unstable#Abilities
and
https://wow.gamepedia.com/Pure_Spawn_of_Hydross
> Pure Spawn of Hydross are water elementals, which means you can't use frost trap/frost nova to CC
> Damage: ~6K Frost/Nature base melee damage 
> Immune to nature/frost damage
That means it should be either of those for the respective elementals.

**Comment by kelno** [comment]
Fixed with 8da8302de4c1596efa73315a013914b7a235a599
