### ISSUE TITLE
[SSC] - Morogrim Tidewalker - Water Globules do not move around

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#707]
**Description:**

At 25% Morogrim Tidewalker stops casting Watery Grave but begins summoning Watery Globules. These are meant to move towards players but are not

**Current behaviour:**

At 25% Morogrim Tidewalker stops casting Watery Grave but begins summoning Watery Globules. These are meant to move towards players but are not

**Expected behaviour:**

At 25% Morogrim Tidewalker stops casting Watery Grave but begins summoning Watery Globules. He summons 4, one from each grave spot, they move slowly towards a fixed player and explodes for 4000-6000 damage on impact.

**Steps to reproduce the problem:**

CHANGEME
1. Engage Morogrim Tidewalker
2. Get to 25%
3. Watch globules spawn but not move

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

Sunstrider Rev: 10564 (213cb03e6b11)

**Comment by SUN-Leekie** [comment]
Seems fixed.
https://www.twitch.tv/videos/418363463?t=37m20s
