### ISSUE TITLE
[SSC] - Underbog Colossus - Only performing one on death act

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#711]
**Description:**

Underbog colossus not using more then 1 on death trigger.

**Current behaviour:**

Underbog Colossus (NPC ID: 21251) is meant to have multiple on death triggers but is only using the single one (Toxic Pool)

**Expected behaviour:**

https://wow.gamepedia.com/Underbog_Colossus

On Death
There will also be a choice of abilities he might use as he dies:

Toxic Pool - When the colossus dies, it turns the ground bright green in a huge area, which does ~2k nature damage a tick if you stand in it. Just run out of the bright green ground and wait for it to fade out.
Two Colossus Lurker - Tank + spank
Many small adds - Lots of HP so AOE isn't easy. Best practice we found was have the tanks gather them together in a pile, and leave 1 tank in the raid to pickup loose ones.
Refreshing mist - blue mushrooms with regenerative properties. Stand in them and be refreshed. (Regenerates 9-11 health and mana every 2 seconds, and some pet happiness).
Nothing!

List of abilities found here: https://www.wowhead.com/npc=21251/underbog-colossus#abilities

**Steps to reproduce the problem:**

1. Got to SSC and Kill a bunch of them, they will only use Toxic Pool

Sunstrider Rev: 10564 (213cb03e6b11)

**Comment by SUN-Leekie** [comment]
Fixed in 11093.
