### ISSUE TITLE
[SSC] - Lady Vashj - Coilfang Beast-Tamer Spawned around platform (8-10)

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#714]
**Description:**

When running up to Vashj the first time there are 8-10 Coilfang Beast-Tamer's (NPC ID: 21221) around the platform which should not be there

https://www.wowhead.com/npc=21221/coilfang-beast-tamer

**Current behaviour:**

Coilfang Beast-Tamer's surrounding platform.

**Expected behaviour:**

No Coilfang Beast-Tamer's

**Steps to reproduce the problem:**

CHANGEME
1. Zone into SSC and Port to Lady Vashj's platform

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

Sunstrider Rev: 10564 (213cb03e6b11)

**Comment by Cheelout** [comment]
93900,93901,93902,93903,93904,93905,93906,93907,93908,93909 - Spawn ID's

Will remove from DB with:
DELETE FROM `creature_entry` where `spawnID` IN(93900,93901,93902,93903,93904,93905,93906,93907,93908,93909)

Not sure how to stop them spawning is it done via script?

**Comment by Jerrythemagicdog** [comment]
Fixed in 11112
