### ISSUE TITLE
[SSC]- Lady Vashj Bridge console is not clickable

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#715]
**Description:**

Players not able to interract with the game object that raises the Bridge to Lady Vashj. It highlights as yellow cog but not worky.

**Current behaviour:**

Players not able to interract with the game object that raises the Bridge to Lady Vashj. It highlights as yellow cog but not worky.

**Expected behaviour:**

Should be able to click and raise the bridge.

**Steps to reproduce the problem:**

CHANGEME
1. Zone into SSC and go to Bridge Console, try and click.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

Sunstrider Rev: 10564 (213cb03e6b11)

**Comment by Cheelout** [comment]
https://github.com/TrinityCore/TrinityCore/issues/2624

May be helpful

**Comment by Cheelout** [comment]
Clickabe.

**Comment by artieau** [comment]
This is now clickable without any bosses being dead, nor platforms being cleared.
Changed in 2.4 per https://wowwiki.fandom.com/wiki/Patch_2.4.0
It should be possible to visit Vashj once the platforms are cleared at that stage.
However for Endless perhaps wish to keep 2.0-2.3 version where all bosses must be dead before being able to proceed @kelno @Jerrythemagicdog

**Comment by Jerrythemagicdog** [comment]
There is a switch in the core that checks if the server version is set to 2.4 and then allows you to click it. Since it's 2.4 then you are able to click it. Thanks though!
