### ISSUE TITLE
[SSC] - Lady Vashj - Toxic Spores do no damage in Phase 3

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#716]
**Description:**

The Toxic Spores (Spell ID: 38575) spawned by Toxic Sporebats (NPC ID: 22140) in Phase 3 spawn and : show visual, even give a debuff, but do no damage

**Current behaviour:**

The Toxic Spores spawned by bats in Phase 3 spawn and show visual, even give a debuff, but do no damage

**Expected behaviour:**

https://www.wowhead.com/npc=22140/toxic-sporebat
https://www.wowhead.com/spell=38575/toxic-spores
https://wow.gamepedia.com/Lady_Vashj

Toxic Spore Bats
During phase 3, these bats spawn. At first they're few, but their number steadily increases.

6,900 HP
Toxic Spores — Poison cloud AoE 1,500 nature damage per second

**Steps to reproduce the problem:**

CHANGEME
1. Enage Vashj to Phase 3
2. Let spore bats spawn and spit the AOE on the ground.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

Sunstrider Rev: 10564 (213cb03e6b11)

**Comment by Kaziner** [comment]
Tested on 10570 and I took damage from the poison

**Comment by Cheelout** [comment]
Still not receiving damage.

**Comment by Cheelout** [comment]
11071

**Comment by kelno** [comment]
Fixed with 11197
