### ISSUE TITLE
[General] Transports are not displaying other players correctly.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#717]
**Description:**
Transports like lifts (in SSC, Thunder Bluff, Freewind Post) don't display the player's position correctly to other players after jumping up. The player appears to be stuck in the air until the transport reaches its destination.

**Steps to reproduce the problem:**

1. Go on an elevator with another player
2. Jump up on one of them
3. He will disappear

**rev. hash/commit:** 

rev. 10568

**Comment by kelno** [comment]
Fixed with 10795
