### ISSUE TITLE
[Tempest Keep] - High Astromancer Solarian - Void Phase - Boss is too large

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#719]
**Description:**

During Phase 2 when she changes into a void walker, it is taking up most of the room.

**Current behaviour:**

Void Form is way to large

**Expected behaviour:**

Void Form should be smaller
https://youtu.be/8-8iV4_5opw?t=270

**Steps to reproduce the problem:**

CHANGEME
1. Engage High Astromancer Solarian
2. Get her to 20%

**rev. hash/commit:** 
10570 (2eecf786f40e)

**Comment by artieau** [comment]
https://cdn.discordapp.com/attachments/499911508759805973/550599383096360970/unknown.png

**Comment by Jerrythemagicdog** [comment]
https://www.youtube.com/watch?v=EEA33bAXyNM

**Comment by SUN-Leekie** [comment]
Fixed.
