### ISSUE TITLE
[SSC] Purified water elementals not patrolling correctly or respawning infront of Hydro

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#733]
**Description:**

Purified water elementals not patrolling correctly or respawning infront of Hydro

**Current behaviour:**

At present they are moving is a really weird and random way

**Expected behaviour:**

The poisoned elementals should spawn on the far right hand side to Hydros; move in an assembly line format to infront of hydro; be cleansed then continue from right to left to the other side of the platform to despawn

**Steps to reproduce the problem:**

CHANGEME
1. Go to hydros and watch them move around

rev 10570

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`
![wowscrnshot_030119_194730](https://user-images.githubusercontent.com/45530324/53689651-0b99b900-3da6-11e9-8321-f8e9d605c524.jpg)

https://db.excalibur.ws/?npc=21260
https://db.excalibur.ws/?npc=21216

https://www.youtube.com/watch?v=AUcragI8Gr8 - expected behavior

**Comment by SUN-Leekie** [comment]
Fixed in 11093.
