### ISSUE TITLE
[SSC] Almost all the pack of trash are wrong between Leo and Morgrim if you go the long way

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#734]
**Description:**

Almost all the pack of trash are wrong between Leo and Morgrim if you go the long way

**Current behaviour:**

Come packs have too many mobs; others have too few; others have the wrong mobs

**Expected behaviour:**

The reverse of the above

**Steps to reproduce the problem:**

CHANGEME
1. Observe the above

rev 10570
![wowscrnshot_030119_195815](https://user-images.githubusercontent.com/45530324/53689739-03db1400-3da8-11e9-89bf-1818f5d81fab.jpg)

![wowscrnshot_030119_195839](https://user-images.githubusercontent.com/45530324/53689883-6681df00-3dab-11e9-92d8-72f7ad10e997.jpg)
![wowscrnshot_030119_195938](https://user-images.githubusercontent.com/45530324/53689884-6c77c000-3dab-11e9-8b4e-0519af6db087.jpg)

I don't have a full clear video from 2008 so all my reference material for evidence is P-servers which will not be accepted as evidence therefore I have no proof to offer.

Basic logic suggests that its 100% fucked; some packs have 3 elites and others have like 8 elites. Would strongly recommend you reconsider views on p-servers as they look balanced and correct and are all in sync with eachother. No matter if its authentic to retail TBC  or not is irrelevant as its alot better then what we have at the moment with no way to provide in either case

**Comment by Kaziner** [comment]
Edit: even the short way between them is pretty sketchy

**Comment by Cheelout** [comment]
This was fine on our first night
