### ISSUE TITLE
[Loot] Mark of the Illidari dropping in SSC (Shouldn't start dropping until TK)

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#736]
**Description:**

Mark of the Illidari dropping in SSC (Shouldn't start dropping until TK)

**Current behaviour:**

Mark of the Illidari dropping in SSC (Shouldn't start dropping until TK)

**Expected behaviour:**

Should not drop in SSC

**Steps to reproduce the problem:**

1. Kill a greyheart tidecaller (or most random trash in SSC) 
2. Loot it
3. repeat until a mark of the illidari drops

rev 10570

![wowscrnshot_030119_200959](https://user-images.githubusercontent.com/45530324/53689945-a85f5500-3dac-11e9-8f6f-7c94d2749f38.jpg)

https://db.excalibur.ws/?item=32897#dropped-by:0-8+1
https://db.excalibur.ws/?npc=21229

**Comment by Cheelout** [comment]
https://wow.gamepedia.com/Mark_of_the_Illidari

This item drops from trash mobs in World of Warcraft: The Burning Crusade raid instances: Serpentshrine Cavern, Tempest Keep, Black Temple, Battle of Mount Hyjal and Sunwell Plateau.

Set to only drop in 2.1
