### ISSUE TITLE
[SSC] Greyheart shield-bearer's aren't throwing sheilds cap America style

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#737]
**Description:**

Greyheart shield-bearer's arn't throwing sheilds cap America style

**Current behaviour:**

Greyheart shield-bearer's arn't throwing sheilds cap America style

**Expected behaviour:**

They should throw sheilds cap America style

**Steps to reproduce the problem:**

1. Fight a greyheart shield-bearer
2. Note it doesn't fling its shield

rev 10570

![wowscrnshot_030119_201020](https://user-images.githubusercontent.com/45530324/53689953-db094d80-3dac-11e9-8a3f-6784dc304c4d.jpg)

https://db.excalibur.ws/?npc=21231#abilities
https://db.excalibur.ws/?spell=38631

**Comment by Cheelout** [comment]
Fixed
