### ISSUE TITLE
[SSC] Leotheras doesn't leash

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#738]
**Description:**

Leotheras doesn't leash

**Current behaviour:**

Leotheras doesn't leash

**Expected behaviour:**

Leotheras should leash

**Steps to reproduce the problem:**

CHANGEME
1. Pull Leo,
2. Run down the west tunnel
3. Note he doesnt leash

rev 10570

![wowscrnshot_030119_201440](https://user-images.githubusercontent.com/45530324/53689982-831f1680-3dad-11e9-87c4-c4c23d614fb5.jpg)

wowhead comment:

you can reset him by running out to the tunnel at the west side.
https://www.wowhead.com/npc=21215/leotheras-the-blind#comments:id=131451:reply=14231

**Comment by SUN-Leekie** [comment]
@Kaziner Not sure what you want to say with the wowhead comment.
I think this is the first time I see the word "leash" used in this context, so just to be sure, you mean reset, right? :D
Will look into it.
