### ISSUE TITLE
[Loot] Void Reaver isn't dropping Tier 5 tokens

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#747]
**Description:**

Void Reaver isn't dropping Tier 5 tokens

**Current behaviour:**

Void Reaver isn't dropping Tier 5 tokens

**Expected behaviour:**

Should drop 2 sholder tokens

**Steps to reproduce the problem:**

CHANGEME
1. Kill void reaver
2. Loot him

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

rev 10570

![wowscrnshot_030219_220553](https://user-images.githubusercontent.com/45530324/53690321-dac08080-3db3-11e9-9ea6-9a83f0f0689f.jpg)

**Comment by Kaziner** [comment]
Same issue with kael

![wowscrnshot_030219_221357](https://user-images.githubusercontent.com/45530324/53690419-d5643580-3db5-11e9-9066-8175c940c2c1.jpg)

https://db.excalibur.ws/?npc=19622#drop

**Comment by Cheelout** [comment]
Fixed with DB Update.
