### ISSUE TITLE
[Loot] Bosses that drop Tier 5 tokens are dropping 1 of each token; every time (3 pcs all different types)

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#748]
**Description:**

Bosses that drop Tier 5 tokens are dropping 1 of each token; every time (3 pcs all different types)

**Current behaviour:**

Bosses that drop Tier 5 tokens are dropping 1 of each token; every time (3 pcs all different types)

(Leo, Vash, Voidreaver etc)

**Expected behaviour:**

They should drop 2 tokens; and they should be random (could be 2 of the same token)

**Steps to reproduce the problem:**

CHANGEME
1. Kill any of these bosses (vash for example).
2. Loot the body

rev 10570

https://db.excalibur.ws/?npc=21212
https://db.excalibur.ws/?item=30242
https://db.excalibur.ws/?item=30243
https://db.excalibur.ws/?item=30244

**Comment by Cheelout** [comment]
Fixed with DB Update.
