### ISSUE TITLE
Remote Toy from Master engineer is a buff instead of debuff (can click it off)

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#750]
**Description:**

Remote Toy from Master engineer is a buff instead of debuff (can click it off)

**Current behaviour:**

Remote Toy from Master engineer is a buff instead of debuff (can click it off)

**Expected behaviour:**

It should be a debuff

**Steps to reproduce the problem:**

CHANGEME
1. Do the Kael fight; up to the master engineer
2. Let him cast remote toy on you

rev 10570

![wowscrnshot_030219_220553](https://user-images.githubusercontent.com/45530324/53690369-1445bb80-3db5-11e9-8eeb-97b7c1cb7701.jpg)
![wowscrnshot_030219_220559](https://user-images.githubusercontent.com/45530324/53690373-1f005080-3db5-11e9-8a7e-a653399018c8.jpg)

https://db.excalibur.ws/?npc=20063

**Comment by Jerrythemagicdog** [comment]
Fixed in 10916. Closed in https://github.com/thebarrensissues/Issues/issues/750
