### ISSUE TITLE
Netherstand longbow doesnt have a model

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#751]
**Description:**

Netherstand longbow doesnt have a model

**Current behaviour:**

Netherstand longbow doesnt have a model - currently invis (but targetable)

**Expected behaviour:**

It should have a model

**Steps to reproduce the problem:**

CHANGEME
1. Do Kael fight
2. Get it to spawn - look at it

rev 10570

![wowscrnshot_030219_220643](https://user-images.githubusercontent.com/45530324/53690385-4fe08580-3db5-11e9-8e8d-965d9ceae1eb.jpg)

https://db.excalibur.ws/?npc=21268

**Comment by SUN-Leekie** [comment]
Seems fixed.
