### ISSUE TITLE
Unable to loot legendary weapons from Kael fight

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#752]
**Description:**

Unable to loot legendary weapons from Kael fight

**Current behaviour:**

It lets you open the loot window but returns an error as if I already have one in my inventory

**Expected behaviour:**

It should let me loot it

**Steps to reproduce the problem:**

CHANGEME
1. Kill the weapons in the Kael fight
2. Try to loot the weapons (tested for all weapons and all have the same issue)

rev 10570

![wowscrnshot_030219_220803](https://user-images.githubusercontent.com/45530324/53690401-9504b780-3db5-11e9-8536-f2206363fa67.jpg)

https://db.excalibur.ws/?item=30316
https://db.excalibur.ws/?npc=21269

**Comment by SUN-Leekie** [comment]
Seems fixed.
