### ISSUE TITLE
High Astromancer Solarian is not casting arcane missles enough

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#753]
**Description:**

High Astromancer Solarian is not casting arcane missles enough

**Current behaviour:**

High Astromancer Solarian is not casting arcane missles enough

**Expected behaviour:**

She should cast arcane missles non-stop; she should studder step towards her new target between her casts. If a melee is ontop of her she should slap them before the next missles but there is no way she should run after people and melee several times between casts

**Steps to reproduce the problem:**

CHANGEME
1. fight High Astromancer Solarian
2. Watch he melee alot

rev 10570

https://db.excalibur.ws/?npc=18805

https://www.wowhead.com/npc=18805/high-astromancer-solarian#comments
"Solarian will occasionally attempt to melee whoever is highest on threat. Basically how it works is she will randomly choose a target for arcane missiles, however in the split second between casts, she will attempt to melee whoever would normally have aggro. In the event that this is a caster, she will move a little bit."

**Comment by Cheelout** [comment]
This is no longer occurring. Arcane Missiles was very often on our attempt last night.
