### ISSUE TITLE
Wrath of the Astromancer (from High astromancer) is a buff instead of a debuff

### ISSUE THREAD

**Issue by Kaziner** [thebarrensissues/Issues#754]
**Description:**

Wrath of the Astromancer (from High astromancer) is a buff instead of a debuff

**Current behaviour:**

Wrath of the Astromancer (from High astromancer) is a buff instead of a debuff

**Expected behaviour:**

Should be a debuff

**Steps to reproduce the problem:**

CHANGEME
1. Get high astromancer to cast wrath of the astromancer on you

rev 10570

![wowscrnshot_030219_215540](https://user-images.githubusercontent.com/45530324/53690566-dc407780-3db8-11e9-8c6b-a27c4caf7a85.jpg)

**Comment by kelno** [comment]
Fixed
