### ISSUE TITLE
[Rogue] Shadowstep - character orientation is incorrect after using it

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#757]
**Description:**
After using Shadowstep our character's orientation is incorrect which results in a weird camera angle as well. 
Here's how it looks: 
https://streamable.com/xpqns
We can see it's for some reason not exactly behind the target facing the same way.

**Expected behaviour:**
Here's how it should look:
https://streamable.com/ji2l5

**Steps to reproduce the problem:**

1. Use Shadowstep on a static target
2. See that the orientation and camera angle end up weird.

**rev. hash/commit:** 

rev. 10603

**Comment by kelno** [comment]
Apparently fixed
