### ISSUE TITLE
[Druid] Scaling on Entangling Roots (Rank 1) 

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#771]
**Description:**
With around 800 spell damage Rank 1 Entangling Roots (339) does 169 damage per tick, while max rank (26989) ticks for 218. The damage seems too high for rank 1.

**How it should work**:
According to sources Entangling Roots has a 10% spell damage coefficient on top of the tooltip damage.

**Spell power coeffs for BC:** 
https://wowwiki.fandom.com/wiki/Spell_power_coefficient?oldid=1285321

**rev. hash/commit:** 
rev. 10603

**Comment by SUN-Leekie** [comment]
Fixed in 11237.
