### ISSUE TITLE
[Arathi Basin] - Spirit Guide missing from certain graveyards

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#777]
**Description:**

Alliance Spirit guide (13116) missing from: Lumber Mill / Blacksmith
Horde Spirit Guide (13117) missing from: Blacksmith

**Current behaviour:**

Alliance Spirit guide (13116) missing from: Lumber Mill / Blacksmith
Horde Spirit Guide (13117) missing from: Blacksmith

**Expected behaviour:**

Spirit Guides should be at each graveyard

**Steps to reproduce the problem:**

1. Start Arathi Basin
2. Cap the relevant point
3. Die

![image](https://user-images.githubusercontent.com/38281939/54467249-fe35f300-47d7-11e9-85a0-38f54ca8aa02.png)

**Comment by kelno** [comment]
Fixed with 10702

**Comment by Cheelout** [comment]
Issue reoccured 11132

**Comment by giveusmezpls** [comment]
can you link an npcid cheelout ?

**Comment by Cheelout** [comment]
@kelno These are not present in AB on the PTR Either.

**Comment by Cheelout** [comment]
They exist in main base only

**Comment by kelno** [comment]
Fixed with 11145
