### ISSUE TITLE
[Alterac Valley] - Warmaster / Marshal HP Buff not working

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#779]
**Description:**

When a Warmaster or Marshall is active in the General Fortress, it applies a 25% HP and Damage buff, This buff is not applying the 25% portion

**Current behaviour:**

Each mob has the active buff, but the 25% HP is applying to the mobs, 25% Damage is.
NPCS:
https://vanilla-twinhead.twinstar.cz/?npc=14772
https://vanilla-twinhead.twinstar.cz/?npc=14773
https://vanilla-twinhead.twinstar.cz/?npc=14776
https://vanilla-twinhead.twinstar.cz/?npc=14777
https://vanilla-twinhead.twinstar.cz/?npc=14762
https://vanilla-twinhead.twinstar.cz/?npc=14763
https://vanilla-twinhead.twinstar.cz/?npc=14764
https://vanilla-twinhead.twinstar.cz/?npc=14765

**Expected behaviour:**

Mob health should increase by 25% per buff.

**Steps to reproduce the problem:**

CHANGEME
1. Zone into AB
2. Go to Drek'thar / Vanns Room
3.Look at HP of Warmasters / Marshall and General
4. Capp all 4 towers
5. Review health again.

![image](https://user-images.githubusercontent.com/38281939/54468743-f11f0100-47e3-11e9-91b0-c54def38f824.png)

**Comment by kelno** [comment]
Fixed somewhere recently, just need to update the server.
