### ISSUE TITLE
[Alterac Valley] - Mob Health is incorrect

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#781]
**Description:**

All mobs in Alterac Valley appear to have Vanilla health values. (Graveyard guards have 1HP..)

**Current behaviour:**

**Expected behaviour:**
As examples: The health needs to be corrected
Captain Galvangar
Vanilla Ref: https://vanilla-twinhead.twinstar.cz/?npc=11947
Active AV: ![image](https://user-images.githubusercontent.com/38281939/54468823-d436fd80-47e4-11e9-9eda-346d450519dc.png)

Warmasters and Marshals
https://vanilla-twinhead.twinstar.cz/?npc=14772
https://vanilla-twinhead.twinstar.cz/?npc=14773
https://vanilla-twinhead.twinstar.cz/?npc=14776
https://vanilla-twinhead.twinstar.cz/?npc=14777
https://vanilla-twinhead.twinstar.cz/?npc=14762
https://vanilla-twinhead.twinstar.cz/?npc=14763
https://vanilla-twinhead.twinstar.cz/?npc=14764
https://vanilla-twinhead.twinstar.cz/?npc=14765
![image](https://user-images.githubusercontent.com/38281939/54468859-1f511080-47e5-11e9-8fd5-35ee024efb78.png)

Drek'Thar

Vanilla Ref: https://vanilla-twinhead.twinstar.cz/?npc=11946
Active AV: ![image](https://user-images.githubusercontent.com/38281939/54468879-3b54b200-47e5-11e9-847f-a79a1e6a969f.png)

Frostwolf Guardian:

Vanilla Ref: https://vanilla-twinhead.twinstar.cz/?npc=12053
Active AV: 
![image](https://user-images.githubusercontent.com/38281939/54468926-a7371a80-47e5-11e9-9ce9-d41caaa18bca.png)

**Steps to reproduce the problem:**

CHANGEME
1. Zone into AV and look at mob health

![image](https://user-images.githubusercontent.com/38281939/54468948-f715e180-47e5-11e9-8bec-3453e821f920.png)

**Comment by kelno** [comment]
We need the retail values here

**Comment by kelno** [comment]
Fixed health of many mobs here.

**Comment by Cheelout** [comment]
Fixed by Kboo
