### ISSUE TITLE
Shadow of Doom

### ISSUE THREAD

**Issue by artieau** [thebarrensissues/Issues#782]
**Description:**

Shadow of Doom (NPC # 16143) are alive around Azeroth.
This is tied to Naxx release and WOTLK release events only.
![image](https://user-images.githubusercontent.com/40563134/54469441-1f084380-47ec-11e9-9a45-d9d0b25a310d.png)

**Current behaviour:**

NPC is alive across Azeroth.

**Expected behaviour:**

Should not be spawned, it is tied to NAxx and wotlk events
http://db.hellfire-tbc.com/?npc=16143
http://db.hellfire-tbc.com/?quest=9085

**Steps to reproduce the problem:**

CHANGEME
1. Leveling in Burning Steppes
2. Agro Level 60 elite Shadow  of Doom
3. Cry whyyyyyyyyyyy

Perhaps we can review all live events running on the core as some are obviously incorrect.

Known locations: 
Blasted Lands - 63:30, 57:36, 62:24, 47:39, 52:28, 46:20
Burning Steppes - 79:28, 67:35, 73:48, 25:52, 24:69, 34:71
Eastern Plaguelands - 18:75, 24:72, 22:83, 70:57, 66:71, 76:70
Winterspting - 49:11, 55:16, 50:16, 42:37, 46:36, 44:42, 63:47, 67:52, 62:52
Azshara - 17:53, 18:66, 45:58
Tanaris - 30:57, 36:57, 35:64, 48:30, 55:31, 51:37, 52:49, 58:64, 52:56

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/54469438-0ef06400-47ec-11e9-969f-15c135c9332c.png)

**Comment by woiwoz** [comment]
This is the summon of a technician in naxx. This monster should not appear directly in the world.

**Comment by woiwoz** [comment]
summon from spell:31315

**Comment by Jerrythemagicdog** [comment]
Fixed in 10915.
