### ISSUE TITLE
Mining/Herb Fails are Instant

### ISSUE THREAD

**Issue by Azytheoneandonly** [thebarrensissues/Issues#786]
**Description:**
Mining fails happen instantly.
Tested Herbing. same issue.

**Current behaviour:**

Mining fails happen instantly rather than at the end of the cast.
You can just keep spamming the button till it starts to cast and it doesn't seem to fail from that point.
Tested Herbing as well. 300 skill picking felweed failed a few times and could just click instantly before it worked.

**Expected behaviour:**

Mining Fails should happen after the full attempt.
Herbing Fails should happen after the full attempt.

**Steps to reproduce the problem:**

1. Mine Orange Skilled Node and when it fails it happens instantly. (tested on fel iron/felweed anyway) 
2. spam button till it casts gather and enjoy your loot

**rev. hash/commit:** 
![Server Version Sat 16 12pm](https://user-images.githubusercontent.com/37324574/54470772-85479300-47f9-11e9-92fa-ac035ca1c55a.PNG)

**Comment by kelno** [comment]
Fixed by Nolin, with 10742
