### ISSUE TITLE
NO LONGER AN ISSUE:Quest: Glyph Chasing (ID: 8309)

### ISSUE THREAD

**Issue by kakarotkaruma** [thebarrensissues/Issues#804]
**Description:**

Basic quest rundown is to head into 3 of the Silithus Hives and obtain a rubbing from inside.
Hive'Ashi and Hive'Zora crystals open a dialogue box when interacted with, and instantly produce a rubbing for the player. Hive'Regal stone doesn't appear to exist, or if it does, is not in the right location.

**Current behaviour:**
Hive'Ashi and Hive'Zora crystals open a dialogue box when interacted with, and instantly produce a rubbing for the player. Hive'Regal crystal doesn't appear to exist, or if it does, is not in the right location. Server went down before I could acquire screenshots.

**Expected behaviour:**
There should be a cast-time to produce the rubbing, and there should not be a dialogue box from the crystal ["Greetings, playername"]

CHANGEME Tell us what should happen instead.
Hive'Regal crystal location (55,90)
Crystals should require a Geologist's Transcription Kit (this is given during the quest) to initiate a cast-time and produce a rubbing. Should not initiate a dialogue box with the crystal when interacted with.

Hive'Ashi Glyphed Crystal Object ID: 180454
Hive'Zora Glyphed Crystal Object ID: 180455
Hive'Regal Glyphed Crystal Object ID: 180453

Hive'Ashi Rubbing item ID: 20455
Hive'Zora Rubbing item ID: 20454
Hive'Regal Rubbing item ID: 20456
**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by Nolin7777** [comment]
Can you please add the item IDs

**Comment by kakarotkaruma** [comment]
> Can you please add the item IDs

Done
