### ISSUE TITLE
random fall damage

### ISSUE THREAD

**Issue by jinbe88** [thebarrensissues/Issues#812]
**Description:**

left freewind post via mount, used the lift, didn't fall, traveled a fair distance from freeewind post before dying from fall damage

**Current behaviour:**

randomly take fall damage
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

not take fall damage randomly

**Steps to reproduce the problem:**

CHANGEME
1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead-like page.  
2. Step 2
3. Step 3

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by plutonium447** [comment]
Issue referenced in: https://github.com/thebarrensissues/Issues/issues/848
issue is described in greater detail there.
