### ISSUE TITLE
[Druid] Improved Leader of the Pack not working

### ISSUE THREAD

**Issue by LoshyFirestorm** [thebarrensissues/Issues#816]
**Description:**

Improved Leader of the Pack does not provide healing on a melee or ranged critical strike like it should.

**Current behaviour:**

Improved Leader of the Pack does not provide healing on a melee or ranged critical strike based on your maximum health (2/4% based on allocated talent points)

**Expected behaviour:**

On a melee or ranged critical strike, Improved Leader of the Pack should grant a heal based on your maximum health based on the talent points invested (2/4%).  This healing effect cannot occur more than once every 6 seconds, 

**Steps to reproduce the problem:**

CHANGEME
1. Be a Druid and talent into Leader of the Pack (prerequisite talent) and Improved Leader of the Pack.
2. Get injured by a monster, and melee at it until you critically strike (must be in bear, dire bear or cat form for leader of the pack to be active)
3. Double check combat log for no note of receiving a heal nor seeing any healing received.

**rev. hash/commit:** 

CHANGEME

The server is currently down, so I cannot get the .server info, but will update issue with it asap.
Date is 21/03/2019, 7:01pm (GMT+10, no daylight savings) - Just for date and time information.

**Comment by LoshyFirestorm** [comment]
![ServerInfo](https://user-images.githubusercontent.com/43313533/54797093-8a478f00-4c9e-11e9-972e-f9e1b2c6af40.png)
For the server info

**Comment by Zeuaireus** [comment]
Can confirm this issue is still present for druids on recent server build.

![image](https://user-images.githubusercontent.com/49328610/55664250-0b398580-585e-11e9-8c99-54e6ac84778b.png)

**Comment by kelno** [comment]
Fixed with 11037
