### ISSUE TITLE
Force Reactive Disk (ID: 18168)

### ISSUE THREAD

**Issue by kakarotkaruma** [thebarrensissues/Issues#817]
**Description:**

The Force Reactive Disc seems to have an inordinately high proc rate. Also procs when changing stances as a warrior - this shouldn't happen.

**Current behaviour:**

Shield effect (22620) seems to be proccing almost 100% of the time, and procs when changing stances as a warrior.

**Expected behaviour:**

According to item description, should only proc when the shield blocks. Should not proc on stance changes.

CHANGEME
http://db.hellfire-tbc.com/?item=18168

**Comment by Jerrythemagicdog** [comment]
Fixed in Fixed in 10725
