### ISSUE TITLE
frost bolts with different permafrost ranks clashing

### ISSUE THREAD

**Issue by vblongneck** [thebarrensissues/Issues#819]
**Description:**

Whilst in WSG when another allied mage cast frost bolt on an enemy player i could not cast frost bolt(rank11) on that same target until their frost bolts slow effect expired. I have been told by the mage that they used the talent 3/3 permafrost. I am talented 0/3.

**Current behaviour:**

"A more powerful spell is already active" error message would continue while trying to cast on the target until the slow expired. 3/3 permafrost preventing my untalented mage to cast frost bolt on same target.

**Expected behaviour:**

the ability for 3/3 permafrost talented mages to not prevent mages without the talent from casting frost bolt on the same target.

**Steps to reproduce the problem:**

1. allied mage casts frost bolt with the permafrost 3/3 talent (12571)  on enemy player.
2. try to cast my frost bolt(25304) with 0/3 permafrost only to be prevented from casting due to "A more powerful spell is already active".
3. required to wait until allied mages frost bolt debuff expires until i can cast my frost bolt on that target.

(server us currently offline and i am unable to .server info if required)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by kelno** [comment]
Fixed with 10733
