### ISSUE TITLE
Can't use the moonwell in Temple of the Moon, Darnassus 

### ISSUE THREAD

**Issue by Heydownthere** [thebarrensissues/Issues#821]
Can't make mooncloth in TotM

steps
1. I teleported from Silithus to TotM, Darnassus
2. walked straight to the moonwell
3. attempted to make but said "Requires Moonwell" 

works in Silithus 

sorry if this is too vague can't really describe it any better

**Comment by kelno** [comment]
Misses a gameobject spell focus there

**Comment by Jerrythemagicdog** [comment]
Fixed in 10725
