### ISSUE TITLE
Can't hand in druid "Body and Heart" quest (Druid bear form quest)

### ISSUE THREAD

**Issue by Heydownthere** [thebarrensissues/Issues#822]
Description-

I am a LvL 15 Tauren Druid trying to do the "Body and Heart" quest it says i've done it but i can't hand it in to the person im supposed to hand it in to.

**Current behaviour:**
in the Elders Rise, Thunderbluff the NPC Turak Runetotem (who is a druid trainer) gives a quest called Body and Heart. He gives you lunardust and tells you to go to a moonkin stone roughly 
42, 61 around Camp Taurajo in the Barrens.
when you get there and use the dust on the stone instead of one Lunaclaw spawning it spawns 2, these Lunaclaws seem to have a massive melee range, i hit them with wrath at roughly max range 
(30 yards) and they were somehow hitting me

**Expected behaviour:**
Only one Lunarclaw spawning, it doesn't have an extreme melee range and i'm meant to hand it in to Taurak Runetotem rather than it being blank

**Steps to reproduce the problem:**

CHANGEME
1. get the quest from Taruak  
2. go to 42, 61 in the barrens
3. use lunardust on moonkin stone
4. after you've kill 1 it says its done but i killed the 2 in case it being alive caused it (didn't fix)
5. attempt to hand in but the dialog he give you is blank

![image](https://user-images.githubusercontent.com/48792458/54771198-e38ccf80-4c58-11e9-898a-59e475e4652f.png)

![image](https://user-images.githubusercontent.com/48792458/54771250-fb645380-4c58-11e9-9234-1bb1a3e259ac.png)

**Comment by Jerrythemagicdog** [comment]
To dev:
Database info in `creature_questender` is correct, the correct NPC is listed with the correct quest ID.
The dust indeed spawns two moonkins and they do have very long attack range (basically ranged. )

**Comment by kelno** [comment]
Fixed with 10792.
You may need to empty your game cache if you already took the quest before
