### ISSUE TITLE
Light's Grace talent isn't consumed by the next holy light cast 

### ISSUE THREAD

**Issue by vblongneck** [thebarrensissues/Issues#824]
**Description:**

The holy paladin talent Light's Grace (spell=31833) is not being consumed by the next holy light cast, allowing a permanent 0.5 second cast speed reduction for the entirety of the 15 seconds. working with all ranks of holy light. bug is found with 1/3 talents, untested with higher talent ranks. 

**Current behaviour:**

The holy paladin talent Light's Grace (spell=31833) is not being consumed by the next holy light cast

**Expected behaviour:**

for Holy light to consume the Light's Grace effect

**Steps to reproduce the problem:**

1. cast any rank of holy light until Light's Grace procs.
2. cast any rank of holy light continuously with a 0.5 cast time reduction without consuming the Light's Grace effect.

**rev. hash/commit:** 

![lights grace](https://user-images.githubusercontent.com/48788674/54795312-9aec0b00-4c86-11e9-88f3-1c1732bb847a.png)

**Comment by kelno** [comment]
Thanks for the spell ids!

**Comment by kelno** [comment]
Fixed 10770
