### ISSUE TITLE
[NPC] Fardel Dabyrie Ranged Melee swing

### ISSUE THREAD

**Issue by Kekass** [thebarrensissues/Issues#825]
**Description:**
Fardel Dabyrie in Arathi Highlands 56.7, 38.4 seams to be melee swinging from more than melee range

https://www.youtube.com/watch?v=qeMoBgjEPGo

**Current behaviour:**

when is slowed feared frozen or even out of range 36yrds (frostbolt) he'll melee swing and hit you 

**Expected behaviour:**

to only melee swing when in melee range only

**Steps to reproduce the problem:**

start combat with [Fardel Dabyrie](https://classicdb.ch/?npc=4479) and slow him fear him or root him and stand at more than 5 - 10 yards away. He will also melee swing while being feared.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

Sunstrider rev. 10713 (c5f6127c4072) 2019-03-21 17:29:11 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by kelno** [comment]
Big thanks for the video!

**Comment by kelno** [comment]
To dev: SmartAI script seems correct, something with visually incorrect position?

**Comment by Kekass** [comment]
Hey I'm not sure if you want me to make another ticket so I'll just post it here seeing it's the same issue. I found another mob that melee attacks from range.

https://www.youtube.com/watch?v=g7ft1LJv2Os

[Slavering Ghoul](https://wowwiki.fandom.com/wiki/Slavering_Ghoul)
These mobs are located in Western Plagelands at 51,77 ( near uther's tomb ) 
seams fairly similar bug, but unlike Fardel the Ghoul's Cast Thrash.

**Comment by plutonium447** [comment]
This npc also has Thrash (https://classicdb.ch/?npc=4479#abilities) (https://classicdb.ch/?spell=3391)
Related issue: https://github.com/thebarrensissues/Issues/issues/829

**Comment by kelno** [comment]
Fixed with 10770
