### ISSUE TITLE
Rogue - Preperation - Not resetting some abilities.

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#827]
**Description:**

Preperation doesn't reset sprint/vanish/evasion 100% of the time.

**Current behaviour:**

Preperation does not always reset the cooldowns on sprint, evasion, vanish, when they are already on cooldown.

**Expected behaviour:**

Preperation should reset the rogues 

When activated, this ability immediately finishes the cooldown on your Evasion, Sprint, Vanish, Cold Blood, Shadowstep and Premeditation abilities.

**Steps to reproduce the problem:**

1.Have Vanish / Evasion / Sprint on cooldown.
2.Pop Preperation.
3.Sometimes one of those abilities wont have the cooldown reset.

**rev. hash/commit:** 
(unsure as to what causes the abilties to not be reset, seems to be random)

Preperation [spell=14185]

sprint spell=11305
evasion spell=26669
vanish spell=1857

**Comment by kelno** [comment]
I fixed an issue with vanish cooldown reset. 
I didn't manage to reproduce the others yet.

**Comment by kelno** [comment]
Are we 100% sure it also happens with sprint and evasion?

**Comment by emorelix** [comment]
> Are we 100% sure it also happens with sprint and evasion?

It has happened in the past when vanish was not resetting, but have not seen it occur recently, will need to test it more, but for now i think it is just vanish.

**Comment by kelno** [comment]
Thanks!
I'll close this for now then. As usual, if this is still happening we can re open this one.
