### ISSUE TITLE
Incorrect level requirements for dungeons

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#828]
**Description:**

Some dungeons have level requirements that are well beyond what the dungeon requires

**Current behaviour:**

Entering specific dungeons gives an error that a higher level is needed which is incorrect.

**Expected behaviour:**

All dungeons should be able to be entered from level 1

**Steps to reproduce the problem:**

Full list of dungeons affected

Blackfathom Deeps = Level 65
Deadmines = level 55
Razorfen Kraul = Level 70
Shadowfang Keep = level 65
The Stockades = level 55
Wailing caverns = level 55

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/54802031-7eb59180-4cb9-11e9-830e-51594feb26d7.png)

**Comment by Tamosheik** [comment]
https://wow.gamepedia.com/World_of_Warcraft_instances_by_level lists the level requirements as the following:
Deadmines - 10 (10)
Stockades - 15 (15)
WC - 10 (10)
BFD - 15 (10)
SFK - 11 (10)
RFK - 25 (15)

These values in brackets are the current values in world.access_requirement.level_min for these instances.

**Comment by kelno** [comment]
Fixed with 10727
