### ISSUE TITLE
[npc] Skeletal Flayer can use Thrash at range

### ISSUE THREAD

**Issue by plutonium447** [thebarrensissues/Issues#829]
**Description:**
When attacking the skeletal flayer mob it is possible for the mob to attack the player while out of melee range. This may be due to its [Thrash] ability, enabling it to attack at range.
After some testing this appears to be occuring up to 25-30yrds from the player, and potentially further.
Whenever the mob attacked, i was hit several times, indicating that it is most likely the [Thrash] ability causing the issue.

**Current behaviour:**
Skeletal Flayer can use its [Thrash] ability at ranges greater than melee range.

**Expected behaviour:**
Skeletal Flayer should only be able to attack within melee range with its [Thrash] ability.

**Steps to reproduce the problem:**

1. Go to WPL @ ~ 46.7,78.2 , near Uther's Tomb.
2. Mount up.
3. Aggro 1 skeletal flayer and run large circles around it.
4. notice you are being hit at range, sometimes even being dazed.

rev. hash/commit:** 
**10713**

**ids**
[npc] Skeletal Flayer (1783)
[spell] Thrash (3391)

**Comment by plutonium447** [comment]
This issue is related to: https://github.com/thebarrensissues/Issues/issues/825
Both affected npcs use Thrash as an ability.

**Comment by kelno** [comment]
Fixed with 10770
