### ISSUE TITLE
Warlock player summoning not working

### ISSUE THREAD

**Issue by Harrock1** [thebarrensissues/Issues#830]
**Description:**

Warlock Summon portals do not currently work

**Current behaviour:**

Upon completing the Ritual of Summoning cast, a portal appears inside the body of the warlock and the casting warlock ceases to channel into the portal. Others can click the portal (including the warlock who made the portal) but the summon does not complete. The Portal object remains where it was cast and the target is not summoned.

![WoWScrnShot_032219_182554](https://user-images.githubusercontent.com/25610698/54816038-652b3e80-4ce7-11e9-9467-5565ed5cec68.jpg)

**Expected behaviour:**

The casting warlock should remain channelling the spell (for 10 mins) and 2 other people in the group should be able to click the portal for it to complete the summon. The player targeted by the warlock should receive a dialog to accept or decline the summon.

**Steps to reproduce the problem:**

1. Step 1 create a party of 4 with a warlock 
2. Step 2 have a warlock summon one of the members with the other 2 clicking the portal
3. Step 3 have summoned party member accept the dialog box and appear where the portal was cast

**rev. hash/commit:** 

[21:13] Sunstrider rev. 10713 (c5f6127c4072) 2019-03-21 17:29:11 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by kelno** [comment]
Fixed with 10815
