### ISSUE TITLE
Auto logged out when dead, logged in alive.

### ISSUE THREAD

**Issue by seanlol88** [thebarrensissues/Issues#832]
Log out, log in res'd me

CHANGEME Description of the problem or issue here.

I went afk as i was running back to my body as a ghost i was autologged. When i logged back in i was alive and in the same spot as i logged out.

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

CHANGEME
1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead-like page.  
2. Step 2
3. Step 3

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by Cheelout** [comment]
Still occuring and is currently being abused in PvP situations.

**Comment by kelno** [comment]
Fixed with 10998
