### ISSUE TITLE
Auction deposit Fees very high!.

### ISSUE THREAD

**Issue by cryptochiefy** [thebarrensissues/Issues#834]
Auction deposit fees are insanely high. 22g deposit fees on purple items. seems like deposit fees are like triple the vendoring price of an item.

**Comment by kelno** [comment]
Is the server set on crossfaction AH?

**Comment by Cheelout** [comment]
XFaction is enabled Kelno

**Comment by Azytheoneandonly** [comment]
just confirming this is a display issue. actual gold taken when you post items is actually around 20-25% of the displayed price.

**Comment by Cheelout** [comment]
I used the AH the other night and it was correctly showing my AH Deposit price.

**Comment by giveusmezpls** [comment]
This issue has cropped up again, it looks like it is taking the Xfaction cost amount (3x higher).

**Comment by zemfi** [comment]
Can we get this bumped to gamebreaking/high priority? This issue has pretty much decimated the AH on the server, given its a tiny pop server, the economy too. Players cant afford the high fees, especially new.

Still broken as of .rev 11262

**Comment by giveusmezpls** [comment]
Can you give me an example of deposit vs. vendor cost for a 48 hr auction @zemfi

**Comment by kelno** [comment]
Mode should have fixed it with server config
