### ISSUE TITLE
Auction house clearing on crash/reset

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#836]
**Description:**

Auction house is clearing on crash/restart

**Current behaviour:**

Auction house is finishing all auctions and returning items to their owners whenever there is a crash or reset
**Expected behaviour:**

Auctions should last their full duration

**Steps to reproduce the problem:**

1. Post something on AH
2. Wait for crash
3. Item will be mailed back to you regardless of how long was left.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/54860452-1d013000-4d6a-11e9-9874-c892856780a7.png)

**Comment by kelno** [comment]
Still waiting for step 2 here, annoying reproduce steps

**Comment by kelno** [comment]
Fixed with 10746
