### ISSUE TITLE
Rogue poisons reset 

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#838]
**Description:**

Rogue Poisons in Skills is reset and constantly resets.

**Current behaviour:**

Whenever you swap instance or relog the rogue poisons skill resets back to 1/300.

**Expected behaviour:**

Poison skill shouldn't reset.

**Steps to reproduce the problem:**

1. have maxed out poisons or any level really.
2. (One case) enter a battleground.
3. Leave or finish battleground
4. Enter azeroth
5. Poisons skill is back to 1/300

**rev. hash/commit:** 
spell=2842 - poisons

**Comment by kelno** [comment]
Fixed with 10782
