### ISSUE TITLE
Warrior Mace Stun self on Stance Change

### ISSUE THREAD

**Issue by willaged** [thebarrensissues/Issues#839]
**Description:**

When changing stance as a warrior, I am able to Mace Stun Effect myself.
I believe its possible it also procs trinkets on attack as well, but I can't confirm this myself

**Current behaviour:**

When changing stance, I have a % chance to stun myself due to the Mace talent in the arms tree for warrior

**Expected behaviour:**

Mace stun should only proc on melee swing
**Steps to reproduce the problem:**

CHANGEME
1. Step 1 Be warrior -> Have mace - > Spec Mace Specialization  
2. Step 2 Change stance repeatedly until proc happens to yourself
3. Step 3 Be stunned 

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

Sunstrider rev. 10718 (7f942c34c69d) 2019-03-22 14:51:21 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by emorelix** [comment]
Also applying to rogue mace spec.

**Comment by Harrock1** [comment]
Weapon effects seem to be applying to the player weilding them under certain scenarios (stance changes/stealth).

[MSA](http://db.hellfire-tbc.com/?item=23221) procs onto my warrior all the time

**Comment by Jerrythemagicdog** [comment]
Fixed in 10725
