### ISSUE TITLE
Guild bank not allowing item deposits

### ISSUE THREAD

**Issue by kakarotkaruma** [thebarrensissues/Issues#840]
**Description:**

Unable to deposit items into the guild bank regardless of guild control permissions. It is possible to deposit gold, just not items.

**Current behaviour:**
Can't deposit items into guild bank

**Expected behaviour:**
Should be able to deposit items into guild bank with permissions (determined by guild rank, set in guild control)
CHANGEME Tell us what should happen instead.
With permissions set via guild control, guild members should be able to deposit items into the guild bank.
**Steps to reproduce the problem:**
1) open guild bank
2) try to deposit an item

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by Cheelout** [comment]
This was not an issue first few days. It is recent.
Confirmed issue is present as GM and lesser ranks

**Comment by Azytheoneandonly** [comment]
Odd. just made a guild and bank is working fine other than not being able to right click out items (might be addon issue?)
https://streamable.com/0u1ru

**Comment by Cheelout** [comment]
Tried with no addons as well

**Comment by kelno** [comment]
Fixed with 10732
