### ISSUE TITLE
Warlocks Pets do not spawn with You in BG's

### ISSUE THREAD

**Issue by Harrock1** [thebarrensissues/Issues#845]
**Description:**

Warlock pets are not automatically spawned when resurecting in a BG

**Current behaviour:**

Pets are despawned on death in bg's

**Expected behaviour:**

The pet that was with the warlock on death should spawn with the warlock on resurrecting. If the pet was killed this does not apply

**Steps to reproduce the problem:**

1. Que a bg
2. Play a warlock
3. Die, or find the nearest enemy physical dps
4. Accept res at bg spirit

**rev. hash/commit:** 

Sunstrider rev. 10718 (7f942c34c69d) 2019-03-22 14:51:21 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Harrock1** [comment]
"Unlike Spirit Healers found in the rest of the world, players resurrected by Spirit Guides are restored to full health and mana, as are any pets or minions" - [Gamepedia](https://wow.gamepedia.com/Battleground)

This follows in line with the preparation buff. Meaning if a hunter has Spirit Bond or a Warlock has Demonic Knowledge talents, they recieve these buffs when respawning with their pet (due to them being persistant buffs)

**Comment by artieau** [comment]
Confirmed not working for Hunters either currently

**Comment by kelno** [comment]
Fixed with 10766

**Comment by Nolin7777** [comment]
confirm fixed
