### ISSUE TITLE
[Arathi Basin] - Druids unable to take flags in prowl

### ISSUE THREAD

**Issue by zemfi** [thebarrensissues/Issues#846]
**Description:**

As stated in title.

**Current behaviour:**

Be druid, stealthed in cat, attempt to grab a flag, and comes up with 'Failed Attempt' over and over in red. Have to remove Prowl to be able to attempt to capture or defend.

**Expected behaviour:**

You should be able to capture while in prowl/stealthed (the action brings you out of stealth).

**rev. hash/commit:** 

rev 10718

**Comment by emorelix** [comment]
effects all stealth, rogues cant initiate flag cap too from stealth

**Comment by woiwoz** [comment]
fixd 10753
