### ISSUE TITLE
Warlock Paranoia too strong

### ISSUE THREAD

**Issue by Harrock1** [thebarrensissues/Issues#847]
**Description:**

With fel puppy out, am able to see stealthed targets at 15-20 yds (only in frontal cone)

**Current behaviour:**

Paranoia allowing warlock to see much further than we should be for stealthed targets. Rogues are easier to see than druids.

For reference, I was able to see a rogue stealthed on the top platform of WSG base from the flag pickup point.

**Expected behaviour:**

Paranoia should allow some distance, but not at medium range. Should be closer to 8 yds in distance

**Steps to reproduce the problem:**

1. Have warlock with Fel hunter out
2. Have enemy rogue or druid stay stealthed infront of caster
3. Walk rogue away until it cannot be seen
4. Have stealther move outside of the frontal 30 degree cone to see the effectiveness

**rev. hash/commit:** 

Sunstrider rev. 10718 (7f942c34c69d) 2019-03-22 14:51:21 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Harrock1** [comment]
[Crap quality 2006 vid of warlock with paranoia unable to see stealthed druid until just as he gets jumped](https://youtu.be/aDGtKZ-xRuo?t=429)

[More noticeable/less potato version where rogue can see stealthed druid from short range with the paranoia buff](https://youtu.be/KZwcjq82NH4?t=361)

Should be +30 stealth detection - same as hunter ["Track Hidden"](https://wowwiki.fandom.com/wiki/Track_Hidden) as it is the same tooltip of "Greatly increases stealth detection.

[More Info](https://wowwiki.fandom.com/wiki/Stealth_(mechanic))

**Comment by Tamosheik** [comment]
spell=19480

**Comment by Jerrythemagicdog** [comment]
What are the talents the rogue has? 
Does he have Master of Deception? 
Does the druid have Feral Instinct? 
Thanks for the details!

**Comment by Harrock1** [comment]
I have confirmed with at least one rogue that he had 5/5 Master of deception. This same player was visible from around 20 yards ingame (the one I could see from the flag point at the top of WSG room). The feral druid I am not 100% confident had feral instincts, however I do think that is part of the feral druid talent choice for pvp,
