### ISSUE TITLE
Frost/Fire Ward reflecting while untalented

### ISSUE THREAD

**Issue by vblongneck** [thebarrensissues/Issues#851]
**Description:**

Frost Ward(spell=32796) is reflecting frost spells without the Frost Warding(spell=11189) talent.
Fire Ward(spell=27128) is reflecting fire spells without the Molten Shields(spell=11094) talent.

The combat log states that the spells are reflected and an animation of the reflect is triggered but no damage is transferred(See screenshot). However an enemy mage with a higher rank Permafrost(spell=12571) talent than I had their frost bolts slow effect reflected by my Frost Ward and triggered the "A more powerful spell is already active" error(1) and refused to let me cast my frost bolt on them.

(1) Permafrost issue reference  https://github.com/thebarrensissues/Issues/issues/819

**Current behaviour:**

Frost Ward is reflecting frost spells without being talented to do so.
Fire Ward is reflecting fire spells without being talented to do so. 

Damage is not reflected but some spell effects linked to the spells appear to reflect.

**Expected behaviour:**

To not reflect with wards unless having points in the related talents.

**Steps to reproduce the problem:**

1.  Cast Frost Ward without reflect talent
2. Enemy mages frost bolt with permafrost 3/3 is reflected by my ward returning 0 damage but reflecting their slow effect back onto them.
3. "A more powerful spell is already active" is triggered and I am unable to cast my frost bolt on them until the slow expires.

**rev. hash/commit:** 

![el reflecto](https://user-images.githubusercontent.com/48788674/54870825-9ccce000-4de6-11e9-8d28-1e8aed730a2c.jpg)
![reflect2](https://user-images.githubusercontent.com/48788674/54870832-c38b1680-4de6-11e9-8936-1d4dca85764f.png)

**Comment by kelno** [comment]
I could not reproduce it so far

**Comment by artieau** [comment]
has your mage ever specced into those talents before? 
Can you also please re-test now that we are in TBC? @vblongneck

**Comment by Cheelout** [comment]
Probably from the Migration. A lot of players had talents they had on Migration and requires a respec to remove (Hunters had spirit bond with no talent points spent for example)
I have not been able to reproduce this on live.
