### ISSUE TITLE
Deeprun Tram movement bugged. Trams moving through walls/other Trams

### ISSUE THREAD

**Issue by plutonium447** [thebarrensissues/Issues#852]
**Description:**
The movement of the Deeprun Trams is bugged, causing trams to disappear into walls or fly through other trams before disappearing into walls.
This will cause players to be flung into walls and dropped to the ground.

![Screenshot from 2019-03-24 07-34-15](https://user-images.githubusercontent.com/40911527/54871969-6607c180-4e08-11e9-90ad-e32aa9e78b03.png)

Fig1. _map of stormwind side tram station. trams numbered._

**Current behaviour:**
Please refer to Fig1.
Trams 1,2,4,5 all have correct movement and behaviour.
Tram 3 will move to the **west** when on the ironforge side, causing it to move into a wall.
Tram 6 will move to the **east** when on the stormwind side, causing it to clip through trams 4 and 5 before moving into a wall.

Tram 3 will not be present on the stormwind side station.
Tram 6 will not be present on the ironforge side station.

![Screenshot from 2019-03-24 07-41-19](https://user-images.githubusercontent.com/40911527/54872003-06f67c80-4e09-11e9-95bd-039ac47674f9.png)

![Screenshot from 2019-03-24 07-44-44](https://user-images.githubusercontent.com/40911527/54872009-2392b480-4e09-11e9-968b-112a255b92f9.png)

**Expected behaviour:**
All trams should not intercept each other nor move into walls.

**Steps to reproduce the problem:**

1. Go to the Deeprun tram, either at ironforge or stormwind
2. Observe the northern-most tram (1,2,3)
3. Observe the southern-most tram (4,5,6)
4. notice how trams 3 and 6 are bugged

**rev. hash/commit:** 
**rev. 10725**

**Comment by kelno** [comment]
Fixed with 10796

**Comment by kelno** [comment]
Rev 34342 we actually fixed it for real
