### ISSUE TITLE
[Item] Wolfshead Helm 

### ISSUE THREAD

**Issue by Smudgee** [thebarrensissues/Issues#853]
**Description:**
Wolfshead Helm equip bonus not working

**Current behaviour:**

Wolfshead Helm item 8345 is supposed to add 5 rage (bear) and 40 energy (cat) upon shapeshift. Bear form is correct. Cat does not add energy. 
note; This was tested with the 5/5 Furor Talent.

**Expected behaviour:**
with 5/5 furor and Wolfshead Helm worn. Shapeshifting into Cat should begin with 60 energy, first tick to 80. 

**Steps to reproduce the problem:**
.additem 8345 
equip and shapeshift. 

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/45928493/54872994-7a0bed00-4e21-11e9-86c0-349ef283b3f2.png)

**Comment by Jerrythemagicdog** [comment]
Fixed in 10768
