### ISSUE TITLE
Cheatdeath buff is not reducing incoming damage

### ISSUE THREAD

**Issue by nichanderson** [thebarrensissues/Issues#855]
**Description:**

Cheat death's secondary effect (proc reduces incoming damage by 90%) is not working.

**Current behaviour:**

Incoming damage is not reduced by the effect, screenshot attached.

![CheatDeathProc](https://user-images.githubusercontent.com/21208563/54873497-15ea2880-4e23-11e9-83ab-987931e2f41c.png)

**Expected behaviour:**

Incoming damage should be reduced to 90%.

**Steps to reproduce the problem:**

Spec a rogue 3/3 into cheat death, duel another player and compare damage without vs with cheat death activated.

**rev. hash/commit:** 

Sunstrider rev. 10725 (6796dce0c7c7+) 2019-03-23 17:24:35 +0000 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Jerrythemagicdog** [comment]
The effect scales with resilience. 
https://wowwiki.fandom.com/wiki/Cheat_Death_(rogue_talent)?oldid=1521550
I suppose since you right now don't have any, it's not reduced at all.

**Comment by Desparto** [comment]
What Jerry said. The damage reduction was changed in 2.4.3 to be affected by resilience. 
From 2.4.3 patch notes: 
Cheat Death: This talent has been rebalanced significantly. Killing blows are no longer 100% absorbed. If the Rogue is below 10% health, the killing blow is still completely absorbed; if the Rogue is over 10% health, enough damage will be absorbed to reduce the Rogue’s health down to 10%. For the following 3 seconds, damage is not always reduced by 90%; it is now reduced by a maximum of 90%, depending on how much resilience the Rogue has. The damage reduction will be four times the damage reduction resilience causes against critical strikes.
