### ISSUE TITLE
Hearthstone not setting in 'Neutral' inns

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#856]
**Description:**

Hearthstone is not currently changing inn when requested at a Neutral inn.

**Current behaviour:**

Hearthstone is not currently changing inn when requested at a Neutral inn.

**Expected behaviour:**

Hearthstone should update regardless of which inn is used.

**Steps to reproduce the problem:**

CHANGEME
1. Request via innkeeper to set new hearthstone in a netural inn. i.e. Gadgetzan or Everlook
2. Hearthstone will not update

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/54875832-ca04a700-4e55-11e9-8316-cde10e2a68a0.png)

**Comment by kelno** [comment]
Fixed with 10761
