### ISSUE TITLE
All player Res spells are too fast

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#857]
Ressurection cast on players is 2 seconds too quick.

**Current behaviour:**

Whenever a resurrection spell is used on a player, the cast stops 2 seconds too soon and the spell is cast.

**Expected behaviour:**

Resurrection spells on players should be a 10 second cast, not 8.

**Steps to reproduce the problem:**

1. Player dies.
2. Cast resurrection on a player.
3. Resurrection ends at 8 seconds and the player is res'd.

**rev. hash/commit:** 

CHANGEME

![WoWScrnShot_032419_173032](https://user-images.githubusercontent.com/47015256/54875901-2ddd9e80-4e5b-11e9-9f76-0804a86a7104.jpg)

**Comment by emorelix** [comment]
spell=20770 
is one example, this effects all res's though

**Comment by kelno** [comment]
Duplicate https://github.com/thebarrensissues/Issues/issues/835
