### ISSUE TITLE
Stun effects changing mob direction

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#859]
**Description:**

Stuns from cheapshot and kidneyshot appear to sometimes make a mob turn around or not face the direction of their model.

**Current behaviour:**

Mobs face the opposite direction, or not where their model is facing when stunned by cs or ks.
trying to backstab a mob from behind after a stun sometimes requires to move around to where the mob's model is facing.

**Expected behaviour:**

Mobs should have their hitbox orientated to where their model is facing.

**Steps to reproduce the problem:**

1. open on mob with
2. stun mob with cheap shot or kidney shot
3. mob is not facing where their model shows them to be facing.

**rev. hash/commit:** 

kidney - spell=8643
cs - spell=1833

This appears to happen to any mob in the game.

![WoWScrnShot_032419_173032](https://user-images.githubusercontent.com/47015256/54876536-c11bd180-4e65-11e9-8a0d-22075d11e229.jpg)

**Comment by kelno** [comment]
Is still still happening?

If so, need reproduce steps

**Comment by emorelix** [comment]
Appears to be fixed now somehow.

**Comment by kelno** [comment]
Thanks.
Closed for now then!
