### ISSUE TITLE
Quest item not dropping

### ISSUE THREAD

**Issue by mrqiksta** [thebarrensissues/Issues#861]
**Description:**

item=5867 not dropping from npc=4054 for quest 1195

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

item=5867 should drop from npc=4054

**Steps to reproduce the problem:**

CHANGEME
1. Killed a large number of npc=4054. Drop rate should be 100%

**rev. hash/commit:** 

Sunstrider rev. 10725 (6796dce0c7c7+) 2019-03-23 17:24:35 +0000 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Jerrythemagicdog** [comment]
Fixed in 10768
