### ISSUE TITLE
Alliance Receiving Blood Shard

### ISSUE THREAD

**Issue by pewpewlaserz** [thebarrensissues/Issues#864]
**Description:**

When mining in Eastern Kingdoms (untested for Kalimdor) as Alliance on Copper / Tin Nodes receive Blood Shard (item id: 5075) a Horde repeatable quest item (http://db.hellfire-tbc.com/?item=5075#objective-of).

**Current behaviour:**

When mining copper or tin, receiving Blood Shard occasionally (1 in 5).

**Expected behaviour:**

When mining as Alliance you should not receive Blood Shard.

**Steps to reproduce the problem:**

1. Mine Copper or Tin Ore as Alliance - tested in Eastern Kingdoms currently.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/48882366/54879467-fedc2280-4e84-11e9-852e-dce6f0e453b8.png)

Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by Jerrythemagicdog** [comment]
Fixed in 10846
