### ISSUE TITLE
#865

### ISSUE THREAD

**Issue by Bizo1** [thebarrensissues/Issues#865]
Dual weilding mobs proc a triple attack in one swing.

When in combat with a dual wielding mob, there is a chance that an attack will proc a triple hit in one swing.

CHANGEME Tell us what happens.

- Enter combat with dual wield mob (ie tested on Deadwind Brute)
- Mob will hit as normal, then sometimes proc a triple attack in one swing.

**Expected behavior:**

- Enter combat with mob.
- Mob should hit once per weapon at specified speed etc.

**Steps to reproduce the problem:**

Can be tested on - Deadwind Pass > The Vice > Deadwind Brute
Enter melee combat and observe.
Player does not trigger this, nor can it be stopped. Action is completely internal to the core coding.

At 21.30 in following link it is briefly explained on Prince Malchazzar in Karazhan (yes, raid bosses can proc this to my understanding)

https://www.youtube.com/watch?v=SRCySAL0YF4

Screenshot from in-game

![1](https://user-images.githubusercontent.com/48882435/54879475-72822d80-4e8d-11e9-8ff5-5d5559ccabe6.png)

![2](https://user-images.githubusercontent.com/48882435/54879476-7746e180-4e8d-11e9-91c0-0de98c4099d5.png)

**rev. hash/commit:** 

Sunstrider rev. 10725 (6796dce0c7c7+) 2019-03-23 17:24:35 +0000 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by plutonium447** [comment]
This npc has [Thrash] allowing the mob to attack more than once per swing. Im assuming it will hit three times with a duel weapon setup.
http://db.hellfire-tbc.com/?npc=7369#abilities
