### ISSUE TITLE
[Guild Bank] Unable to withdraw items

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#866]
**Description:**

Unable to withdraw items from guild bank

**Current behaviour:**

Unable to withdraw items from guild bank

**Expected behaviour:**

Should be able to withdraw items
Character Guid: 633 (Modelol)
Guild ID: 8

**Steps to reproduce the problem:**

CHANGEME
1. Deposit item to guild bank
2. Try and withdraw it

![image](https://user-images.githubusercontent.com/38281939/54885636-97e55a80-4ed2-11e9-8251-e2fade1d6372.png)

**Comment by kelno** [comment]
Can't reproduce on my side for now

**Comment by Cheelout** [comment]
We can drag and drop items but can't "Right-click" to withdraw

**Comment by kelno** [comment]
Fixed with 10955
