### ISSUE TITLE
[SHAMAN] Elemental Shields Stacking (Regression)

### ISSUE THREAD

**Issue by Deatherapy** [thebarrensissues/Issues#867]
This is a regression back to a previously logged issue with similar mechanics https://github.com/thebarrensissues/Issues/issues/326

**Current behaviour:**
Player is able to self cast both Earth Shield and Lightening shield on self. 
![image](https://user-images.githubusercontent.com/45929803/54886106-046b5400-4ee9-11e9-999f-235b2778ef29.png)

**Expected behaviour:**
Only one elemental shield should be active on the player shaman. The shield should override the other if cast on self.

**Steps to reproduce the problem:**

1. Spec into resto shaman talent tree and get Earth Shield
2. Cast Lightening Shield then Earth Shield on self

**Include sources for the expected behaviour**
https://tbc-twinhead.twinstar.cz/?spell=974 Earth Shield
https://tbc-twinhead.twinstar.cz/?spell=324 Lightening Shield

**NOTE:** Cannot re-test Water Shield as do not have access to it currently

rev. hash/commit:
![image](https://user-images.githubusercontent.com/45929803/54886097-f0bfed80-4ee8-11e9-8a19-28904d9b2399.png)

**Comment by Jerrythemagicdog** [comment]
Only affects Lightning Shield(25472) and Earth Shield (974) (Water Shield correctly removes other shields present.)

**Comment by Jerrythemagicdog** [comment]
Fixed in 10754
