### ISSUE TITLE
[Warlock] Unholy Power

### ISSUE THREAD

**Issue by Azytheoneandonly** [thebarrensissues/Issues#869]
**Description:**

Whenever you spec into Unholy Power it seems to modify pet damage into negative? causing it to miss every attack.

**Current behaviour:**

Whenever any points spent into Unholy Power. Directly after until either you change gear, level up or get a talent which modifies stats in some way. your pet will miss.

**Expected behaviour:**

For Pet to not miss.

**Steps to reproduce the problem:**

1. Spec into Unholy Power Send in pet and watch it miss.
2. Call pet back and change 1 bit of gear and send pet back in to see its fixed.

1-5 points reference below.
http://db.hellfire-tbc.com/?spell=18769
http://db.hellfire-tbc.com/?spell=18770
http://db.hellfire-tbc.com/?spell=18771
http://db.hellfire-tbc.com/?spell=18772
http://db.hellfire-tbc.com/?spell=18773

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/37324574/54889095-7abe8500-4eee-11e9-9e8d-84db0996515e.png)

**Comment by kelno** [comment]
Fixed a while ago
