### ISSUE TITLE
Druid's energy doesn't set to 0 when shapeshifting into cat form

### ISSUE THREAD

**Issue by Korblo** [thebarrensissues/Issues#870]
**Current behaviour:**

Whenever druids use "Cat Form" (Spell#768, also passive spell possibly related: spell#3025) their energy bar ~~is set to 100%.~~ doesn't set to 0. Energy seems to keep ticking up while you're in other forms but if you spend all of your energy and then quickly shift out of cat form and back into it, you'll still be at the same low value as before.

Interestingly, if the druid gets even a single point in the "Furor" talent (Spell#17056) then the functionality of Cat Form becomes its expected behaviour.

**Expected behaviour:**

Druids in cat form usually start with 0% energy, though with some talents and items adding an additional value to this.

**Steps to reproduce the problem:**

1. Be a druid that has learned Cat Form and has no points in the Furor talent.
2. Use the Cat Form spell and enjoy your 100% energy

**Comment by kelno** [comment]
Fixed with 10760
