### ISSUE TITLE
[Druid] Energy when Shapeshifting into Cat Form is set to "background" Energy Levels

### ISSUE THREAD

**Issue by pewpewlaserz** [thebarrensissues/Issues#872]
**Description:**

Currently when shape shifting into cat form at any level you are given your current "background energy".

**Current behaviour:**

Shape shifting into cat form will set you at 100/100 energy based on your "background ticks" when you do a few attacks and reduce your energy to 0/100 then immediately shift out / shift back into cat form you will then only have 20/100 energy. Bug appears to be in relation to druid energy constantly ticking in the background.

Fix maybe in relation to how...
line 2298 in player.cpp

case POWER_ENERGY;
SetFullPower(POWER_ENERGY);
break;

Have it set energy to 0 when Cat Form is cast? Or maybe there's a way to turn off energy tick regen when not in Cat form without it affecting rogues?

**Expected behaviour:**

When shape shifting into cat form you should have 0 energy and it should start ticking, *important* ensure that "powershifting" from wolfshead helm / furor still works + tigers fury.

**Steps to reproduce the problem:**

CHANGEME
1. Shift into cat form from "idle"
2. Do a few attacks to get to 0/100 energy
3. Shift to human form
4. Shift to cat form 0 should have 20 or 40/100 energy

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/48882366/54893021-a433dc80-4eff-11e9-8a24-93be4eaa998c.png)

**Comment by kelno** [comment]
Thanks for the details! That's great that you're using the legacy repo here.

**Comment by kelno** [comment]
Fixed with 10760
