### ISSUE TITLE
Cancelling trades causes items and trade function to become unusable

### ISSUE THREAD

**Issue by kakarotkaruma** [thebarrensissues/Issues#873]
**Description:**

When trading with another player, if you put items into the "To be traded" window, and then have the trade closed, the items become greyed out and no longer useable without re-logging. It also makes a player unable to open trade windows without re-logging.

**Current behaviour:**
 Exiting a trade window with items in trade slots causes the items and the trade function itself to become unusable.

**Expected behaviour:**
Should be able to cancel trades without it affecting items or the trade function.

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by kelno** [comment]
Fixed with 10956
