### ISSUE TITLE
[Weapon Skill] Not skilling up on grey mobs / particularly slow

### ISSUE THREAD

**Issue by pewpewlaserz** [thebarrensissues/Issues#874]
**Description:**
Creating an issue based on the info Fanatic and I put in the game issues discord.

Weapon skill ups are occurring rarely, particularly so for classes other then rogue/warrior, additionally no skill ups occur vs "grey" mobs.

**Current behaviour:**

When fighting mobs that are grey, no skill ups occur. When fighting green or above mobs, skill ups occur but are much rarer then expected/in 1.12.

Anecdotal: it took Fanatic 6 hours to level 2 different weapons from 1 to 290 as a Paladin.

**Expected behaviour:**

Skill ups should be possible vs grey mobs and should occur more frequently then is currently happening.

We think what is in the red box is possibly what is stopping you from getting skill ups vs grey mobs.

What is underlined in red is why rogues/warriors are getting a much higher chance to gain a skill up, perhaps this could be applied to all classes as an interim?

Its also unclear if intellect is affecting the skill up chance of classes outside of warrior/rogue, no reference to GetStat being made in what we can see.

![image](https://user-images.githubusercontent.com/48882366/54897138-e6b2e480-4f12-11e9-93a1-54c67e85e775.png)

**Steps to reproduce the problem:**

1. As a rogue equip a single dagger, fight vs grey/green mobs and observe no skill ups vs grey but skill ups vs the green mob.
2. As a paladin equip a 1h mace, fight vs grey/green mobs and observe no skill ups vs grey and less frequent skill ups vs the green mob compared to rogues.

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/48882366/54897244-5628d400-4f13-11e9-9761-30e210bd6bd9.png)

**Comment by FanaticTBC** [comment]
[weaponskill chance.xlsx](https://github.com/thebarrensissues/Issues/files/3002237/weaponskill.chance.xlsx)
Calcs show the difference in chance to gain rogue/warriors have compared to other classes, and why it is so much slower.

**Comment by kelno** [comment]
Fixed with 10751. I've reimplemented a rule that  should be identical to the behavior you had on the LH core.
