### ISSUE TITLE
[NPC/Mob] Servants in Blasted Lands are killable outside of quest

### ISSUE THREAD

**Issue by Deatherapy** [thebarrensissues/Issues#876]
**Current behaviour:**

The Servants of Servine, Grol, Razelikh, Allistarj in Blasted Lands are killable without destroying their crystal

**Expected behaviour:**

These NPC's should not be killable without destroying their crystal first. They should be effectively immortal unless on quest https://vanilla-twinhead.twinstar.cz/?quest=2681

**Steps to reproduce the problem:**

1. Go to Blasted Lands and kill one of the servants near a crystal without destroying it

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/45929803/54898880-b67b3e00-4f32-11e9-869f-5278761bddb7.png)

**Comment by zemfi** [comment]
dupe: #530

**Comment by artieau** [comment]
Closing as duplicate
