### ISSUE TITLE
[NPC/MOB] Dreadmaul Mauler - Blasted Lands

### ISSUE THREAD

**Issue by Deatherapy** [thebarrensissues/Issues#878]
**Current behaviour:**

Mob will randomly attack 3 times in quick succession

![image](https://user-images.githubusercontent.com/45929803/54899896-45d62080-4f36-11e9-9377-9feec3d19ee3.png)

My melee weapon is Fang of Venoxis which has a 1.3 sec attack speed for reference.

**Expected behaviour:**

This mob does not have any abilities to suggest it can attack 3 times instantly (similar to how windfury hits but with out the vortex animation) 

https://classic.wowhead.com/npc=5977/dreadmaul-mauler#abilities

**Steps to reproduce the problem:**

1. Allow mob to attack you.

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/45929803/54900038-b2e9b600-4f36-11e9-808e-f532c97a0eed.png)

**Comment by plutonium447** [comment]
http://db.hellfire-tbc.com/?npc=5977#abilities
Using a tbc database, this npc has Thrash, which can proc multiple attacks in one swing
