### ISSUE TITLE
[Arena] Bug when zoning in while flying

### ISSUE THREAD

**Issue by artieau** [thebarrensissues/Issues#879]
**Description:**

When a player accepts an Arena battle while flying via flight master, they DC after zoning in.
Once they log back in, they become unfriendly with their own team and can attack them.

**Current behaviour:**

When a player accepts an Arena battle while flying via flight master, they DC after zoning in.
Once they log back in, they become unfriendly with their own team and can attack them.

**Expected behaviour:**

Player should not disconnect when zoning in, the same as zoning in while grounded.
Player should not become hostile to their own team.

**Steps to reproduce the problem:**

1. Queue for an Arena
2. While waiting, fly somewhere via Flight Master
3. Accept Arena battle while still flying
4. After zoning in, take one step and DC.
5. Log back in, now hostile with your team

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/54901145-b4f94800-4f29-11e9-82aa-1db3255f8dbb.png)

**Comment by kelno** [comment]
To me:
Unit::ValidateMovementInfo: A violation has been detected (mi->HasMovementFlag(MOVEMENTFLAG_PLAYER_FLYING) && !mi->HasMovementFlag(MOVEMENTFLAG_CAN_FLY)) for player Warriorr (lowguid: 10660) moving unit Warriorr (GUID: GUID Full: 0x00000000000029a4 Type: Player Low: 10660). The player will be kicked. Data from client: MovementFlags: 33554432, MovementFlags2: 0. Data in the server: MovementFlags: 33554432, MovementFlags2: 0.
S->C: [Player: Adlo (Guid: 10733, Account: 3)] [MSG_MOVE_SET_FACING 0x00DA (218)]
Unit::ValidateMovementInfo: A violation has been detected (mi->HasMovementFlag(MOVEMENTFLAG_PLAYER_FLYING) && !mi->HasMovementFlag(MOVEMENTFLAG_CAN_FLY)) for player Warriorr (lowguid: 10660) moving unit Warriorr (GUID: GUID Full: 0x00000000000029a4 Type: Player Low: 10660). The player will be kicked. Data from client: MovementFlags: 33554432, MovementFlags2: 0. Data in the server: MovementFlags: 33554432, MovementFlags2: 0.
S->C: [Player: Adlo (Guid: 10733, Account: 3)] [MSG_MOVE_SET_PITCH 0x00DB (219)]
Unit::ValidateMovementInfo: A violation has been detected (mi->HasMovementFlag(MOVEMENTFLAG_PLAYER_FLYING) && !mi->HasMovementFlag(MOVEMENTFLAG_CAN_FLY)) for player Warriorr (lowguid: 10660) moving unit Warriorr (GUID: GUID Full: 0x00000000000029a4 Type: Player Low: 10660). The player will be kicked. Data from client: MovementFlags: 33554433, MovementFlags2: 0. Data in the server: MovementFlags: 33554432, MovementFlags2: 0.

**Comment by kelno** [comment]
Seems fixed now
