### ISSUE TITLE
[Shaman] Totems despawning

### ISSUE THREAD

**Issue by artieau** [thebarrensissues/Issues#880]
**Description:**

Certain totem types cause other specific totem types to despawn when killed.

**Current behaviour:**

kill Air totem = other 3 totems die
kill Water totem = Earth and Fire totems die
kill Earth totem = Fire totem dies
kill Fire totem = normal behaviour

**Expected behaviour:**

Killing a totem should only kill that totem, none should be linked in any way.

**Steps to reproduce the problem:**

1. Shaman places down 4 x different type totems. For example: Frost Resistance Totem  (Fire), Strength of Earth Totem (Earth), Fire Resistance Totem (Water) and Windfury Totem (Air).
2. Enemy player melee hits the Windfury (Air) totem
3. All 4 totems die instantly.
See above Current Behaviour for how the other totems interact on death too.

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/54901662-474e1b80-4f2b-11e9-9298-98a3e9002fae.png)

**Comment by kelno** [comment]
Fixed with 10749
