### ISSUE TITLE
[Profession] Fishing in regular water fishes incorrect fish

### ISSUE THREAD

**Issue by LoshyFirestorm** [thebarrensissues/Issues#881]
**Description:**

Fishing in the wild almost always grants raw brilliant smallfish or raw longjaw mud snapper regardless of the area.  For example, using the addon fishing buddy to keep a log of what I have fished, at Felpaw Village in NE Felwood, out of 71 catches 41 were Raw Brilliant Smallfish, 30 were Raw Longjaw Mud Snappers.

**Current behaviour:**

Fishing in higher level zones nets raw brilliant smallfish and raw longjaw mud snapper.  

**Expected behaviour:**

Higher level area's should have different fish.  https://legacy-wow.com/fishing-guide-valuable-fish/  has some notables as to where certain fish are fishable outside of schools of fish during vanilla.

**Steps to reproduce the problem:**

1. Get high enough fishing for higher level zones
2. Go fish

**rev. hash/commit:** 

![ServaInfo](https://user-images.githubusercontent.com/43313533/54901560-904da200-4f22-11e9-9571-790312495ae1.png)

**Comment by pewpewlaserz** [comment]
https://wowwiki.fandom.com/wiki/Fishing_items?oldid=1715867
that wiki version is just before wotlk info comes out and has all the fish

https://wowwiki.fandom.com/wiki/Fishing_locations?oldid=1799567
this version shows what fish can be caught in each zone, vanilla/tbc is the same as previous history version, this one is just better formatted and happens to include northrend

unable to find drop/catch chance anywhere =[


http://kmdguild.forumotion.com/t1-fishing-leveling-guide-1-375
(references the lvl req for each zone)

**Comment by kelno** [comment]
Thanks for all the details

**Comment by kelno** [comment]
Mostly fixed with 10835. We have all the same fish loots as TC. That also includes the day/night event.

I noticed that Nost/LHCore have some added loots as well but it's such a mess in their DB, I don't know how to import that neatly.
To dev if you want to check it later:
``` 
SELECT *
FROM lh_world.fishing_loot_template f
LEFT JOIN trinityworld.fishing_loot_template tc_f ON f.entry = tc_f.Entry
LEFT JOIN trinityworld.fishing_loot_template tc_f2 ON f.entry = tc_f2.Entry AND f.item = tc_f2.Item
LEFT JOIN trinityworld.reference_loot_template tc_r ON tc_f.Reference = tc_r.Entry AND tc_r.Item = f.item
WHERE tc_r.Entry IS NULL AND tc_f2.Entry IS NULL
```
