### ISSUE TITLE
Seeing opposite faction's spirits while dead

### ISSUE THREAD

**Issue by emorelix** [thebarrensissues/Issues#882]
**Description:**

Can see opposite's spirits faction while dead.

**Current behaviour:**

If you die and run around in spirit form, you can see members of the opposite faction who are ALSO in spirit form (dead).

**Expected behaviour:**

You should only be able to see members of your faction whilst in spirit form (dead).

**Steps to reproduce the problem:**

1 Die
2 Stand in an area with players of the opposite faction who are also dead.
3 You can now see the opposite factions in spirit form.

**rev. hash/commit:** 

![WoWScrnShot_032519_183123](https://user-images.githubusercontent.com/47015256/54902062-6ac59600-4f2c-11e9-9f94-77156152b40b.jpg)
![WoWScrnShot_032519_180455](https://user-images.githubusercontent.com/47015256/54902065-6e591d00-4f2c-11e9-88ea-ffee07afddea.jpg)
![WoWScrnShot_032119_162550](https://user-images.githubusercontent.com/47015256/54902066-6e591d00-4f2c-11e9-9151-0392a277d0d2.jpg)

**Comment by kelno** [comment]
Probably fixed with 11030
(https://github.com/thebarrensissues/Issues/issues/1126)

**Comment by Cheelout** [comment]
Confirmed all good Kelno :)
