### ISSUE TITLE
[NPC] Ian Strom (ID 1411) Teaching Rogue Abilities without Level Requirement

### ISSUE THREAD

**Issue by pewpewlaserz** [thebarrensissues/Issues#887]
**Description:**

Ian Strom is an Rogue Trainer NPC in Booty Bay (loc 26.8, 77.1)

**Current behaviour:**

Currently you are able to learn rogue skills above your level, you are also then able to use them and it is updated in your spellbook. (NPC is not showing level requirements on skills, only gold).

![image](https://user-images.githubusercontent.com/48882366/54925355-e12cbd00-4f59-11e9-9d22-4e143ea7b543.png)

Spell ID 11300 (Eviscerate Rank 8) learned at level 39.

Screenshot demonstrates the increased damage, is not just a ui bug "saying" its rank 8 but using rank 5.
![image](https://user-images.githubusercontent.com/48882366/54925540-3537a180-4f5a-11e9-9723-fb24daf8cf2a.png)
Images showing the damage of each rank.
![image](https://user-images.githubusercontent.com/48882366/54925634-64e6a980-4f5a-11e9-82d0-57ac0b0a9f90.png)
![image](https://user-images.githubusercontent.com/48882366/54925669-7760e300-4f5a-11e9-8aad-d4eb7b659500.png)

**Expected behaviour:**

To only be able to learn skills appropriate for your level.

**Steps to reproduce the problem:**

1. Be a rogue (tested with a lvl 39 rogue currently)
2. Go to NPC Ian Strom (ID 1411) in Booty Bay
3. Learn skills above your level
4. Fight mobs with these skills.

**Comment by Jerrythemagicdog** [comment]
Fixed in 10916
