### ISSUE TITLE
Damage overflowing when using high mitigation

### ISSUE THREAD

**Issue by plutonium447** [thebarrensissues/Issues#888]
**Description:**
It is possible to be hit for billions of damage by low level mobs with very weak attacks.

**Current behaviour:**
When a high damage mitigation geared player is hit by a low level mob with very weak attacks, it is possible for the attack to be mitigated so much that it becomes less than 1, causing an 'overflow' and the damage value to become a very large number.

![Screenshot from 2019-03-26 08-02-02](https://user-images.githubusercontent.com/40911527/54959227-237aec00-4fa4-11e9-9b6e-a886930d84fb.png)

**Expected behaviour:**
Regardless of all mitigation, a mobs attack should not be reduced past 1.

**Steps to reproduce the problem:**

1. Be Warrior/Paladin
2. Equip T3/T4/ etc
3. Go to Razerfen Downs
4. Turn left, encounter Freezing Spirit
5. Attack
6. wait until player is hit for billions of damage

Freezing Spirit is the only mob i have encountered to reliably trigger this bug.

**rev. hash/commit:** 
rev. **10755**

**id's**
[npc] Freezing Spirit (7353)

edit: ids

**Comment by kelno** [comment]
Fixed with 10759
