### ISSUE TITLE
Druid - Shifting to cat form enables "Track Humanoids"

### ISSUE THREAD

**Issue by mrqiksta** [thebarrensissues/Issues#889]
Current behaviour:

Druid: shifting to Cat form enables "track Humanoids", switching to any other form clears tracking to "track nothing"

Expected behaviour:

Shifting to cat form should not change what the druid is tracking on the minimap

Steps to reproduce the problem:

    Shift to catform, check minimap tracking has changed
    Shift out of catform, check minimap tracking is "nothing"

BE VERY SPECIFIC HERE. Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

rev. hash/commit:

CHANGEME
Do a .server info in game and copy/screenshot the first line.

Sunstrider rev. 10725 (6796dce0c7c7+) 2019-03-23 17:24:35 +0000 (master branch) (Unix, RelWithDebInfo, Static)

NOTES:

    Please don't be shy on the details and context, screenshots and videos are VERY welcome
    Include the ID for game objects, npcs (creatures, pets, minions), spells, items, quests, instances, zones, skills related to this issue.

**Comment by zemfi** [comment]
Looks like it is something intended.

https://www.wowhead.com/spell=5225/track-humanoids#comments

Note the comments, worth doing some research on it first

**Comment by mrqiksta** [comment]
I see, this source is unclear if shifting back to humanoid or other forms would clear any previous tracking option set, like we're seeing though.

**Comment by kelno** [comment]
Fixed with 10768. 
More precisely, it will still erase some tracking such as Food & Drink or innkeepers, but won't erase Minerals tracking or Beast Tracking.
I think we can't do better here, the client does not even notify the server if he switch to innkeeper for example, that's fully local on the client so we can't change the server behavior based on that.
