### ISSUE TITLE
Quest mob "King Bangalash" missing in-game

### ISSUE THREAD

**Issue by mrqiksta** [thebarrensissues/Issues#891]
**Description:**

https://classicdb.ch/?npc=731 is missing from his usual location, 

**Current behaviour:**

https://classicdb.ch/?npc=731 is not in usual location

**Expected behaviour:**

Should be at Coordinates: 38.2, 35.6, unable to locate him nearby.

**Steps to reproduce the problem:**

1. Tele to Coordinates: 38.2, 35.6 in STV
2. /tar king
3. no result. Could be misplaced or missing. Mob is not a stealthed creature, waited >15 mins in case he had been killed. Mob is not summoned.

**rev. hash/commit:** 

Sunstrider rev. 10748 (4c8418973318) 2019-03-25 08:40:16 +0100 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Jerrythemagicdog** [comment]
He's spawned here:
https://imgur.com/a/EMgL3p2
(Exact coords: -12679.003906, -220.677689, 37.586880, 3.510748)
with a 30 minute respawn timer.
