### ISSUE TITLE
[GM] Forced Rename Issue.

### ISSUE THREAD

**Issue by Azytheoneandonly** [thebarrensissues/Issues#894]
**Description:**

Can't pick new name after Forced Rename.

**Current behaviour:**

Currently if you are force renamed using the Game Master command it doesn't let you Pick a new name.
This is the error you receive: Character Rename Failed

Demo Here: https://streamable.com/bj14w
 
**Expected behaviour:**

Should allow a rename based on available names and restrictions.

**Steps to reproduce the problem:**

1. Have Game Master rename your character
2. Run into error trying to rename character.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/37324574/54968856-d3158580-4fc7-11e9-82c9-237f90776af9.png)

**Comment by Jerrythemagicdog** [comment]
Have you tried with other characters? This one in particular is flagged as your "main character" by our website GM system connected to the PTR, which should prevent changes to that character.

**Comment by Azytheoneandonly** [comment]
Also happens on other characters
![image](https://user-images.githubusercontent.com/37324574/55015717-1c51ed80-5039-11e9-9c40-c0e2071c2781.png)

**Comment by kelno** [comment]
This has already been fixed recently, the server just needs to be updated to last revision.
