### ISSUE TITLE
Dukes in silithus permanently spawned.

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#895]
**Description:**

The summonable Dukes in silithus are permanently spawned and respawning within a minute

**Current behaviour:**

Dukes are permanently up and respawning. 

**Expected behaviour:**

Dukes should not be in the world permanently and only should spawn when summoned via the Wind Stones.

**Steps to reproduce the problem:**

ID's of mobs.
15211 - Azure Templar
15212 - Hoary Templar
15220 - The Duke of Zephyrs
15206 - The Duke of Cynders

1. Visit a twilight camp in silithus
2. Witness all dukes spawned
3. Kill one and watch it respawn

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/54973937-06fda480-4fe2-11e9-98e9-e05841c31c73.png)

**Comment by kelno** [comment]
Fixed by Nolin in 10762
