### ISSUE TITLE
[NPC - Deadmines] Goblin Engineer (ID 622) is not casting Spell (ID 3605) correctly

### ISSUE THREAD

**Issue by pewpewlaserz** [thebarrensissues/Issues#899]
**Description:**
[NPC - Deadmines] Goblin Engineer (ID 622) is not casting Spell (ID 3605) correctly

**Current behaviour:**

Goblin Engineer (ID 622) is casting Spell "Summon Remote-Controlled Golem" (ID 3605) when spawning or at some point prior to being engaged in combat by the player.
![image](https://user-images.githubusercontent.com/48882366/54990224-f101db00-5005-11e9-9015-a628126309a5.png)

**Expected behaviour:**

Goblin Engineer (ID 622) casts Spell "Summon Remote-Controlled Golem" (ID 3605) after engaging in combat with players. Remote Controlled Golem (NPC ID 2520) 

CHANGEME
1. Zone into Deadmines
2. Observe NPC Goblin Engineer in Foundry Area with pre-summoned Remote Controlled Golem (NPC ID 2520).

**Comment by Jerrythemagicdog** [comment]
Fixed in 10762
