### ISSUE TITLE
X-Faction Mail is not enabled

### ISSUE THREAD

**Issue by plutonium447** [thebarrensissues/Issues#904]
**Description:**
As part of the many changes to the Barrens server that differs it to Blizzard, one of them is the ability to deliver mail to opposing members of each faction. This is not currently enabled.

**Current behaviour:**
Players of opposing factions cannot send mail between each other.

![Screenshot from 2019-03-27 14-01-52](https://user-images.githubusercontent.com/40911527/55049687-f3614500-5098-11e9-9381-b124cf544a35.jpg)

**Expected behaviour:**
Players of opposing factions should be able to send mail between each other, as per the behaviour seen on the vanilla core.

**Steps to reproduce the problem:**

1. Be any faction member
2. Go to mailbox
3. Attempt to send mail to known enemy player

**rev. hash/commit:** 
rev. **10762**

**Comment by kelno** [comment]
To dev: That's `AllowTwoSide.Interaction.Mail` in config.
