### ISSUE TITLE
Food buffs stacking

### ISSUE THREAD

**Issue by Septimush** [thebarrensissues/Issues#906]
**Description:**

Windblossom Berries (10 Stamina) Blessed Sunfruit Juice (10 Spirit) are stacking when both consumed. 

**Current behaviour:**

Receive both Stamina and Spirit buff once food consumed.

**Expected behaviour:**

Normally buffs didn't stack with one another/one would cancel the other when consumed after the other.

**Steps to reproduce the problem:**

1. Consume http://db.hellfire-tbc.com/?item=11950 and http://db.hellfire-tbc.com/?item=13813
2. Receive both buffs as shown here https://i.imgur.com/SS7sNJz.png

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

https://i.imgur.com/q4EjZq1.png

**Comment by Jerrythemagicdog** [comment]
Could you provide some credible research showing they shouldn't stack? Thanks!

**Comment by Septimush** [comment]
I've no reference evidence I can provide other than in Vanilla food/well fed buffs did not stack and would cancel out if one was consumed after the other, sorry! :(

**Comment by Jerrythemagicdog** [comment]
Fixed in 10766

**Comment by cryptochiefy** [comment]
Windblossom is meant to stack with food buff. Not sure in tbc but rumsey rums used to stack with food buff aswell but now they dont :(
