### ISSUE TITLE
Argent Medic (NPC ID: 16284) dialogue options

### ISSUE THREAD

**Issue by kakarotkaruma** [thebarrensissues/Issues#908]
**Description:**

Argent Medics are offering teleportation services in their dialogue boxes.

**Current behaviour:**
Interacting with Argent Medics opens the dialogue option:
"I've got too much to do and not enough time to do it, [faction]! Please, get out of my way.
If you're infected with the maggot slime or ghoul rot, I might be able to help you."

- Take me to Singing Ridge
- Take me to Razaan's Landing
- Take me to Ruuan Weald

While these areas are not currently available, this could cause issues post-portal opening.

**Expected behaviour:**

They should not offer these services
**Steps to reproduce the problem:**

CHANGEME
1. Find an Argent Medic in EPL (coords: 47.0, 43.4)
2. Talk to it
3. Look at options
![Argent Medics dial options](https://user-images.githubusercontent.com/47651637/55068031-c6308900-50d0-11e9-9dc8-faec7b57129a.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks, this is just a wrong dialogue assigned to the wrong NPC. NPC 21461 (Rally Zapnabber) should have it.

**Comment by Jerrythemagicdog** [comment]
Fixed in 10767
