### ISSUE TITLE
Pvp title earned with HKs

### ISSUE THREAD

**Issue by johnboy1989** [thebarrensissues/Issues#909]
Gaining 1000 liftime kills has earned the title 'Private'

Description of the problem or issue here.
Killed qoth in game, got a reputation-like ding effect with title earned.

Tell us what happens
See photos below

Tell us what should happen instead.
Are the titles supposed to be earned via lifetime kills?

1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead-like page.  
2. Step 2
3. Step 3

By Blued (5,274 – 1·18·36) on 2010/10/24 (Patch 4.0.1) |   |  
-- | -- | --
Pre-lvl 60..
In the old PvP Honor System, players could earn ranks that gave them access to better items. 

With Patch 2.0, the old system has been replaced with the new PvP Honor System and the PvP Arena System. 

The Arena System still rewards players with new titles, but the new Honor System does not. 

The old title and rank system has become obsolete, but players who earned ranks prior to Patch 2.0 can still display their lifetime highest rank.

Via: http://www.worldofwarcraft.com/pvp/ranks.html

![titlebug](https://user-images.githubusercontent.com/39358344/55073520-08ae9180-50e2-11e9-845e-ec09be3ed987.jpg)

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/39358344/55073467-ec125980-50e1-11e9-882a-660a792db073.png)

**Comment by Nolin7777** [comment]
https://github.com/kelno/sunstrider/blob/master/src/server/game/Entities/Player/Player.cpp#L6774

**Comment by kelno** [comment]
Fixed with 10767
kelno/sunstrider/8824baa2686057ef9f3500bbefc8f39ff4ad93b5
