### ISSUE TITLE
Gordock Bushwhacker outside of DM

### ISSUE THREAD

**Issue by kakarotkaruma** [thebarrensissues/Issues#914]
**Description:**
There are two Godock Bushwhacker (NPC ID: 14351) outside the courtyard inside Dire Maul zone.

**Current behaviour:**
As above.

**Expected behaviour:**

To my knowledge these NPCs should only be spawned when removing tannin from the basket inside Dire Maul North.

**Steps to reproduce the problem:**

1. Enter the Dire Maul zone
2. Make your way to courtyard
3. See the two NPCs

![Bushwhacker DM](https://user-images.githubusercontent.com/47651637/55117235-fa8c5f80-5139-11e9-81ae-39085accc778.jpg)

**Comment by kelno** [comment]
Fixed by Nolin in 10793
