### ISSUE TITLE
[ITEM] Metal Buckler (ID 17189) Being sold for 0s and No Level Req

### ISSUE THREAD

**Issue by pewpewlaserz** [thebarrensissues/Issues#916]
**Description:**

Item Database error 

**Current behaviour:**
Metal Buckler (ID 17189) is being sold by these vendors at no cost (http://db.hellfire-tbc.com/?item=17189)

**Expected behaviour:**
Vendors should sell the item for 1g 30s 54c
Vendors should buy the item for 26s 10c
Item requires level 29 to equip

**Steps to reproduce the problem:**
CHANGEME
1. Go to vendor Osric Strang (ID 1323)
2. Purchase Metal Buckler for free - be able to equip at any level and be unable to vendor the item.

**Comment by kelno** [comment]
Fixed by Nolin in 10794
