### ISSUE TITLE
Araj's Scarab quest

### ISSUE THREAD

**Issue by imtrollingu** [thebarrensissues/Issues#917]
**Description:**

Araj's Scarab quest. http://db.hellfire-tbc.com/?quest=5804

**Current behaviour:**

When Araj is killed the item drops and sparkles but you can't loot it.

If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

Loot dropped item. http://db.hellfire-tbc.com/?item=14610

**Steps to reproduce the problem:**

Killed Araj twice and the item dropped but couldn't loot it

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 
rev. **10770**

**Comment by Jerrythemagicdog** [comment]
fixed in past update.
