### ISSUE TITLE
[Druid] Bear form can gain windfury procs

### ISSUE THREAD

**Issue by plutonium447** [thebarrensissues/Issues#919]
**Description:**
When shapeshifted into Bear form, druids are able to benefit from windfury totem and gain extra attacks as per behaviour of windfury.

**Current behaviour:**
Druids in bear form can gain extra attacks from windfury.

![unknown](https://user-images.githubusercontent.com/40911527/55155856-23e1d580-51a4-11e9-80c2-09220c138ed1.png)

![unknown 2](https://user-images.githubusercontent.com/40911527/55155859-25ab9900-51a4-11e9-9929-6a9c2f049334.png)

**Expected behaviour:**
Druids in bear form should **not** gain any benefit from windfury totem.

**Steps to reproduce the problem:**

1. Be Druid.
2. Shapeshift into bear form
3. Have a shaman.
4. Shaman casts windfury totem
5. Druid attacks target.
6. magic
7. Druid gains windfury procs

**rev. hash/commit:** 
rev. **10770**

**id's**
[spell] Bear Form (5487)
[spell] Windfury Totem (8512)

**Comment by kelno** [comment]
Fixed with 11040

**Comment by Jerrythemagicdog** [comment]
> [11:51 PM] Jaysue: hey guys the fix for windfury in druid forms has a 'workaround'
> [11:52 PM] Jaysue: if you power shift you can get it on your weapon then it will be used in forms

**Comment by kelno** [comment]
Closed with 11388
