### ISSUE TITLE
[Rogue] Combo points don't clear on creatures after leaving combat.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#921]
**Description:**
Combo points should be cleared when creature enters evade mode. Should **not** apply to players, combo points should persist.

**rev. hash/commit:** 

Sunstrider rev. 10766 (c83db2abbc50) 2019-03-26 22:26:10 +0100 (master branch)

**Comment by kelno** [comment]
Fixed with 10979
