### ISSUE TITLE
Minor trade bug

### ISSUE THREAD

**Issue by cryptochiefy** [thebarrensissues/Issues#922]
Not sure how to reproduce this but trading bugs 50% of the time. Seems to happen more after trading someone atleast once/twice.

**Comment by cryptochiefy** [comment]
Relogging fixes it.

**Comment by Cheelout** [comment]
@kelno I believe you fixed this a few days ago.. Confirm?

**Comment by kelno** [comment]
Yes there was another issue for this

**Comment by giveusmezpls** [comment]
have not experienced any trade bugs since the last fix.
