### ISSUE TITLE
Server kicks players after logging out and logging on another character

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#929]
**Description:**
Server kicks people logging out and logging on another character. Pretty easy to reproduce:
1. Log out on a character
2. Enter world on another character
3. Get disconnected.

**Comment by Jerrythemagicdog** [comment]
Closed in https://github.com/kelno/sunstrider/commit/86610ad851788b2595141ef5f7870b01e9217baf

**Comment by kelno** [comment]
https://github.com/kelno/sunstrider/commit/78ab459513daf6a5bf16aab6a05b6694c5fd1cc7
