### ISSUE TITLE
[NPC] Hostile NPC's Spawned by Script Can be Multiplied 

### ISSUE THREAD

**Issue by zemfi** [thebarrensissues/Issues#931]
**Description:**

Enemies that are spawned or enabled by scripted events can be multiplied from evading/running away (ie. reseting) and does not reset or despawn, or does, but after a **significant amount of time**. Extension of #481 effecting most mobs.

**Expected behaviour:**

You should be able to run/out of range to reset a mob, and their spawns should despawn, or at least within a reasonable time, without it being abusable (spawn multiples)

**Steps to reproduce the problem:**

CHANGEME
1. Engage hostile mobs that spawn extra hostile npc's per script, then run out of range so they reset, the spawned extra ad remains. do this over and over.
2. Tested this out with a non-tbc spawn and got the same result:

![tbc_overandover](https://user-images.githubusercontent.com/46832429/55273612-d4291880-5321-11e9-9113-dbd32d355509.jpg)

**rev. hash/commit:** 
probably a known issue, but heres a report about it..
.rev 10800

**Comment by SUN-Leekie** [comment]
Fixed is the past weeks.
