### ISSUE TITLE
Flightmaster in alliance honor hold on roof

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#932]
**Description:**

Flightmaster Krill Bitterhue [16822] bugs out sometimes and ends up on the roof of the stables. Likely related to the infernal invasion event that happens often in Honor Hold.
![image](https://user-images.githubusercontent.com/35262513/55273892-3fbeb600-5321-11e9-89e3-6ddbb49eb5e2.png)

**Expected behaviour:**

Flightmaster Krill Bitterhue should return to her normal spot in front of the parked gryphons when event is over.

**Steps to reproduce the problem:**

1. Visit honor hold
2. See Flightmaster doing parkour on the roof

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/35262513/55273897-52d18600-5321-11e9-8637-ef53614810a4.png)

**Comment by kelno** [comment]
To dev: probably happens after the infernal rain fear

**Comment by Jerrythemagicdog** [comment]
Fixed in 10915
