### ISSUE TITLE
[Quest] City of Light (10211)

### ISSUE THREAD

**Issue by BarrensJerk** [thebarrensissues/Issues#933]
As per #492 

City of Light is not completable. NPC follows rather than gives the tour. 

Need the quest working to progress to Aldor / Scryer selection

Rev. 10800

**Comment by kelno** [comment]
High priority because I expect this to affect a lot of other quest npcs

**Comment by SUN-Leekie** [comment]
#492

**Comment by kelno** [comment]
Fixed with 10814
