### ISSUE TITLE
[Quest] Who are They? Speaking does give progress

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#938]
**Description:**

When speaking to Shadowy Initiate / Laborer / Advisor it does not give quest credit

**Current behaviour:**

When speaking to Shadowy Initiate / Laborer / Advisor it does not give quest credit

**Expected behaviour:**

quest=10040
npc=26464
npc=26465
npc=26466
Speaking to each mob should grant quest progress

**Steps to reproduce the problem:**

CHANGEME
1. Pickup quest
2. Talk to mobs

![image](https://user-images.githubusercontent.com/38281939/55282550-daf37200-5399-11e9-91be-4c9e73226286.png)

**Comment by mrqiksta** [comment]
When picking up the quest, a 'disguise' is cast on the player making some of these NPCs friendly instead of hostile. They are correctly appearing friendly and have some gossip but the player gets no quest credit after clicking their speech option when speaking with them.

**Comment by Jerrythemagicdog** [comment]
fixed.
