### ISSUE TITLE
[Quest] By Any Means Necessary - Empoor not engable

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#939]
**Description:**

When you locate Empoor you are meant to engage in combat to persuade him, you can't engage him in combat or there is no text to engage.

**Current behaviour:**

When you locate Empoor you are meant to engage in combat to persuade him, you can't engage him in combat or there is no text to engage.

**Expected behaviour:**

Quest=9978
https://www.wowhead.com/quest=10040/who-are-they
When you find Empoor you are meant to fight him

**Steps to reproduce the problem:**

CHANGEME
1. Pickup quest
2. Locate Empoor
3. Speak to - No option to fight

![image](https://user-images.githubusercontent.com/38281939/55282573-7be22d00-539a-11e9-8291-a8aa4627368e.png)

**Comment by mrqiksta** [comment]
confirmed as horde

**Comment by Jerrythemagicdog** [comment]
fixed in 11154
