### ISSUE TITLE
[Quest] Help! - Corki does nothing after letting him out of the cage with key

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#940]
**Description:**

Corki does nothing after letting him out of the cage with key

**Current behaviour:**

Corki does nothing after letting him out of the cage with key

**Expected behaviour:**

https://www.wowhead.com/quest=9923/help

Should offer https://www.wowhead.com/quest=9924/corkis-gone-missing-again after being freed

**Steps to reproduce the problem:**

CHANGEME
1. Accept quest
2. Free Corki

![image](https://user-images.githubusercontent.com/38281939/55282979-febbb580-53a3-11e9-8615-262a89d8dba6.png)

**Comment by Tamosheik** [comment]
Corki - NPC ID#18445

**Comment by Jerrythemagicdog** [comment]
Fixed in 11154

**Comment by giveusmezpls** [comment]
Tested today on this revision 11165, cage works and NPC released however no credit for quest is given.
Will test on PTR to confirm.

**Comment by Orcfootstool** [comment]
> 
> 
> Tested today on this revision 11165, cage works and NPC released however no credit for quest is given.
> Will test on PTR to confirm.

This is what is occurring for me too.

**Comment by Jerrythemagicdog** [comment]
fixed with https://github.com/kelno/sunstrider-scripts/commit/5fb61ca836d5699546d8523c79c0a74f6ca53983
