### ISSUE TITLE
[Quest] - Diplomatic Measure - Blademaster gossip doesnt work to complete listening to his tale

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#941]
**Description:**

Blademaster gossip doesnt work to complete listening to his tale

**Current behaviour:**

You can't complete listening to Blademasters tale

**Expected behaviour:**

https://www.wowhead.com/quest=10107/diplomatic-measures

Listen to tale -> Quest completes

**Steps to reproduce the problem:**

CHANGEME
1. Accept quest
2. Listen to tale - Click through gossips

![image](https://user-images.githubusercontent.com/38281939/55283018-f152fb00-53a4-11e9-9e28-79dd5026512d.png)

**Comment by Tamosheik** [comment]
Also Quest ID#10108 (Alliance)

**Comment by Jerrythemagicdog** [comment]
Fixed in 11154
