### ISSUE TITLE
[Quest] - Talbuk Mastery - Bach'lor is missing

### ISSUE THREAD

**Issue by Cheelout** [thebarrensissues/Issues#942]
**Description:**

Bach'lor is missing, can't be located

**Current behaviour:**

Bach'lor is missing, can't be located

**Expected behaviour:**

Bach'lor should patrol a certain area of Nagrand
https://www.wowhead.com/quest=9859/talbuk-mastery

**Steps to reproduce the problem:**

CHANGEME
1. Pick up quest
2. Try and locate Bach'lor

![image](https://user-images.githubusercontent.com/38281939/55283079-3deb0600-53a6-11e9-9703-6822bf60a788.png)

**Comment by Jerrythemagicdog** [comment]
After many hours of exhausting searching I have finally managed to locate Bach'lor
![image](https://user-images.githubusercontent.com/46463908/55284712-d87e2180-5373-11e9-90e9-2578c9805a2b.png)
Respawn time: 4 min
