### ISSUE TITLE
Quest: Ishanah [10554] not able to hand in

### ISSUE THREAD

**Issue by qoth** [thebarrensissues/Issues#943]
**Description:**

Unable to complete the quest 'Ishanah' ID [10554]

**Current behaviour:**

You can accept quest 'Ishanah' [10554] but not hand it in.

**Expected behaviour:**
 
Quest should be available to hand in at the npc of the same name NPCID[18538]

**Steps to reproduce the problem:**

CHANGEME
1. Accept quest Ishanah [10554] from Khagdar[18166] in the middle of Shattrath
2. Visit NPC Ishanah [18538] and attemp to hand in quest Ishanah [10554]
3. NPC Ishanah will not have a question mark over her heard, nor any gossip options.

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/35262513/55284165-b65ac280-53b8-11e9-86d2-07b18e39da73.png)

**Comment by Jerrythemagicdog** [comment]
Fixed in 10827
