### ISSUE TITLE
[Quest] 9397 Birds of a feather (Can't handin quest)

### ISSUE THREAD

**Issue by Kekass** [thebarrensissues/Issues#944]
**Description:**

The Quest " Birds of a Feather " once completed is _unable_ to be handed in.

**Current behaviour:**

One you complete the quest and go to the [NPC 16790 Falconer Drenna Riverwind ](http://db.hellfire-tbc.com/?npc=16790) she doesn't have a question mark above her head and you cannot interact with her.

**Expected behaviour:**

Once you get a [23486 Caged Female Kaliri Hatchling](http://db.hellfire-tbc.com/?item=23486) you should be able to interact with Dreanna and hand in the quest

**Steps to reproduce the problem:**

1. pick up the quest [9397 Birds of a Feather](http://db.hellfire-tbc.com/?quest=9397) 
2. go click nests and get a female Kaliri Hatchling to spawn
3. use the quest item [23485 Empty Birdcage ](http://db.hellfire-tbc.com/?item=23485) on female bird.
4. go to quest giver and get ignored like you don't even exist :'( 

**rev. hash/commit:** 

 In Screenshot

![Wow_oTYkdJqhuB](https://user-images.githubusercontent.com/35077310/55284300-603b4e80-53bb-11e9-9d66-97c9a42567f3.jpg)

**Comment by kelno** [comment]
Fixed with 10822
