### ISSUE TITLE
Sanctity Aura canceled by trinket

### ISSUE THREAD

**Issue by jinbe88** [thebarrensissues/Issues#952]
**Description:**

Sanctity Aura is canceled

**Current behaviour:**

When Sanctity Aura is active and I use Ancient Crystal Talisman it cancels Sanctity Aura.
Tested multiple times, maybe it has something to do with them both sharing the same icon.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

Sanctity Aura should stay active until canceled manually

**Steps to reproduce the problem:**

CHANGEME
http://db.hellfire-tbc.com/?spell=20218
http://db.hellfire-tbc.com/?item=25620
2. Step 2
3. Step 3

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by kelno** [comment]
Fixed with 3596fe2f4dc69f4164720141cbfa8889a0112d62 already
