### ISSUE TITLE
[Quest] The Ata'mal Terrace

### ISSUE THREAD

**Issue by Azytheoneandonly** [thebarrensissues/Issues#954]
**Description:**

The Ata'mal Terrace Quest cannot be completed as Shadowlord Deathwail doesn't come down so you can attack.

**Current behaviour:**

NPC: Shadowmoon Soulstealer currently stand still and don't even melee

**Expected behaviour:**

After you kill the 3 Shadowmoon Soulstealer it should cause NPC: Shadowlord Deathwail to land to attack.

**Steps to reproduce the problem:**

1. Attempt to kill Shadowmoon Soulstealer to make Shadowlord Deathwail come attack you.

Quest: http://db.hellfire-tbc.com/?quest=10707
Shadowmoon Soulstealer: http://db.hellfire-tbc.com/?npc=22061
Shadowlord Deathwail: http://db.hellfire-tbc.com/?npc=22006

**rev. hash/commit:** 
  
![Screen Shot 03-31-19 at 03 48 PM](https://user-images.githubusercontent.com/37324574/55288103-191e7f00-53f6-11e9-9f93-18f170435ca2.JPG)

**Comment by Jerrythemagicdog** [comment]
Video of the whole event: https://www.youtube.com/watch?v=iS6FtMSw5-4

**Comment by Jerrythemagicdog** [comment]
Fixed in 11154
