### ISSUE TITLE
K. Lee Smallfry offers already learned engineering

### ISSUE THREAD

**Issue by Tamosheik** [thebarrensissues/Issues#956]
**Description:**

The NPC K. Lee Smallfry (ID #17634) offers apprentice engineering (ID#4036) even when it has already been learned.

**Current behaviour:**

![image](https://user-images.githubusercontent.com/40758487/55289067-a49f0c80-5404-11e9-80e5-2333f1ca2724.png)

**Expected behaviour:**

Already learned spells should not be available from the trainer.

**Steps to reproduce the problem:**

1. Have Engineering
2. Talk to the engineering trainer K. Lee Smallfry
3. See screenshot

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 
![image](https://user-images.githubusercontent.com/40758487/55289092-08293a00-5405-11e9-9e16-954bda67e5cf.png)

**Comment by kelno** [comment]
This one could be related to the character port process, does this also happen to a fresh character?

**Comment by Korblo** [comment]
As someone that leveled 1-70 after the portal opened, I can confirm that does not seem to be an issue for me.
![kleecheck](https://user-images.githubusercontent.com/48878430/56325720-2c7b6980-61ae-11e9-92a2-e6d31ec22fdf.jpg)

Sunstrider rev. 11015 (13b9ba922417+) 2019-04-17 19:32:40 +0200 (master branch) (Unix, RelWithDebInfo, Static)
