### ISSUE TITLE
[NPC] Aldor Rise - Extreme amount of spawns

### ISSUE THREAD

**Issue by LoshyFirestorm** [thebarrensissues/Issues#958]
**Description:**

Aldor Rise in Shattrath city has an extreme number of spawns.

**Current behaviour:**

An extreme number of spawns, as can be seen in this screenshot with nameplates shown and location:

![WoWScrnShot_033119_235837](https://user-images.githubusercontent.com/43313533/55290027-3ad92f80-5411-11e9-885b-b9f9313fa2de.jpg)

![WoWScrnShot_040119_000118](https://user-images.githubusercontent.com/43313533/55290038-5ba18500-5411-11e9-938a-8d1cf57c889f.jpg)

**Expected behaviour:**

There should only be one of each NPC spawned, but there appears to be around six spawns of each.

**Steps to reproduce the problem:**

CHANGEME
1. Go to Aldor Rise in Shattrath City
2. Turn on allied nameplates
3. Approach the center of Aldor Rise (as outlined by above screenshot)

**rev. hash/commit:** 

![ServerInfo310319](https://user-images.githubusercontent.com/43313533/55290064-96a3b880-5411-11e9-9b1d-61bf4e879dea.png)

**Comment by kelno** [comment]
Anyone knows which quest (if that's indeed a quest) spawn them?

**Comment by kelno** [comment]
Fixed with 10829
