### ISSUE TITLE
Pathfinding near water or in water doesn't always provide a path

### ISSUE THREAD

**Issue by Jerrythemagicdog** [thebarrensissues/Issues#960]
**Current behaviour:**

Sometimes unable to get a path when attempting to charge through a pool of water like here
![image](https://user-images.githubusercontent.com/46463908/55301441-92d55d80-5434-11e9-92b8-4ab60f590707.png)
and getting pathed around it, through more shallow water.

**Expected behaviour:**

Should find a path.

**Steps to reproduce the problem:**

1. .go xyz 389.862030 7687.499512 18.562681 (in Zangarmarsh)
2. try to charge someone on the other side
3. get pathed around or not at all

**rev. hash/commit:** 
Sunstrider rev. 10821 (ea0ac048d8df+) 2019-04-01 04:04:09 +0200 (master branch)

**Comment by Tamosheik** [comment]
This also appears to affect pets. They can move through water while OOC, but get stuck if in combat.

**Comment by kelno** [comment]
Will be fixed soonish on The Barrens server

**Comment by artieau** [comment]
Issue is still screwy as of today.
Mobs will evade with no path through water that is SO SMALL a gnome can stand up in it even.
Sometimes the mob still 'swimming animation through it' even if player can still walk.
etc

**Comment by kelno** [comment]
Need a location here, the one in this issue is working perfectly for me
