### ISSUE TITLE
Hunter pet FOLLOW command does not recall pet

### ISSUE THREAD

**Issue by Tamosheik** [thebarrensissues/Issues#963]
**Description:**

The hunter pet action fails to recall the summoned pet back to the hunter

**Current Behaviour **
When attacking an enemy, the follow command has nil effect on pet behavior. Outside of combat the command works as intended.

**Expected behaviour:**
Using the follow command should recall the pet back to the hunter

**Steps to reproduce the problem:**
1. Target an enemy that is some distance away
2. Issue the Pet "Attack" command
3. Issue the Pet "Follow" command
4. The pet does not recall to the player.

For clarification this occurs at all times. The pet is **not** under the effects of Bestial Wrath.

**rev. hash/commit:** 
rev. 108020

**Comment by kelno** [comment]
Fixed with 10837
