### ISSUE TITLE
[Quest] The Earthbinder

### ISSUE THREAD

**Issue by dinkletron** [thebarrensissues/Issues#964]
**Description:**

You cannot turn in this quest to Earthbinder Galandria Nightbreeze, similar to the 'Birds of a Feather' quest which is also bugged. She doesn't allow you to right click her.

**Current behaviour:**

You can't turn the quest/quest item into the relevant NPC.

**Expected behaviour:**

You should be able to turn in the Crimson Crystal Shard (ID 29477) to Earthbinder Galandria Nightbreeze.

**Steps to reproduce the problem:**

CHANGEME
1. Complete quest as seen here: http://db.hellfire-tbc.com/?quest=10349
2. Attempt to turn in to final NPC Earthbinder Galandria Nightbreeze.

**rev. hash/commit:** 

CHANGEME
`Sunstrider rev. 10820 (683517a2bf22+) 2019-04-01 02:53:07 +0200 (master branch) (Unix, RelWithDebInfo, Static)

**Comment by Jerrythemagicdog** [comment]
Does it happen after someone else turns in the same quest? There is a small RP event with a colossus spawning, but then she goes back to her spot and we can interact with her again.

**Comment by Jerrythemagicdog** [comment]
Possibly fixed in 10822

**Comment by dinkletron** [comment]
There was no event happening when I went to turn it in, waited around for 5 minutes. I will test again this morning now that Birds of a Feather has been fixed!

**Comment by dinkletron** [comment]
Can confirm this has been fixed in 10822.

**Comment by Jerrythemagicdog** [comment]
Thanks!

**Comment by stevietje** [comment]
Same issues happened with me. Accepted the quest from "Tola'thion" and get /w "look over here on the hill". Simply nothing happens. Can't right click the NPC.

**Comment by zemfi** [comment]
Similar to another previously bugged quest, this is now complete-able as of 10914 again, just finished it.

**Comment by Tamosheik** [comment]
Successfully completed Quest. Closing.

**Comment by woiwoz** [comment]
1、This problem reappeared in my PTR, but I did a good job of testing myself. So it's not clear what caused BUG.
2、I have a suggestion that when the NPC returns to its point, we can force it to disappear and reproduce. This can circumvent the problem.
