### ISSUE TITLE
Hungarfen spores

### ISSUE THREAD

**Issue by Calebizza** [thebarrensissues/Issues#965]
**Description:**

Hungarfen's Foul Spores are exploding too quickly

**Current behaviour:**

Hungarfen, 2nd boss in Underbog is currently spawning Foul Spores that are exploding almost instantly

**Expected behaviour:**

They should slowly grow over 20 seconds and explode after that time, giving the debuff

**Steps to reproduce the problem:**

-Fight Hungarfen

**rev. hash/commit:** 

![WoWScrnShot_040119_210847](https://user-images.githubusercontent.com/48810241/55320291-71bb4e00-54c2-11e9-938d-74344ad70381.jpg)

**Comment by Jerrythemagicdog** [comment]
Can't reproduce locally, shrooms take a very long time to explode and they grow two - three times before that.

**Comment by kelno** [comment]
Maybe https://github.com/thebarrensissues/Issues/issues/835
