### ISSUE TITLE
Knockback drops threat

### ISSUE THREAD

**Issue by Calebizza** [thebarrensissues/Issues#966]
**Description:**

Any ability that knocks back another player drops threat also

**Current behaviour:**

when you get knocked back by abilities (eg: Ghaz'an's tail sweep)

**Expected behaviour:**

these knockbacks should not drop threat

**Steps to reproduce the problem:**

fight any mob that uses knockback abilities
Lose all threat

**rev. hash/commit:** 

![WoWScrnShot_040119_210847](https://user-images.githubusercontent.com/48810241/55323570-248faa00-54cb-11e9-8fc2-122f7f5e9838.jpg)

**Comment by kelno** [comment]
Threat isn't changed at all on Ghaz'an when I get tail sweeped, can you describe more what happens here for you to come to that conclusion?
