### ISSUE TITLE
[Quest] Dimensius the All-Devouring

### ISSUE THREAD

**Issue by Paralol** [thebarrensissues/Issues#967]
**Description:**

Unable to complete quest

**Current behaviour:**

When talking to NPC Captain Saeed to start the event he will get stuck pathing back and forth.

**Expected behaviour:**

Captain Saeed should lead an attack up in to Manaforge Ultris and spawn the boss Dimensius the All-Devouring to complete the quest.

**Steps to reproduce the problem:**

1. Accept quest Dimensius the All-Devouring
2. Talk to Caprain Saeed
3. Watch him run back and forth

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/4516769/55323757-513fc380-54c3-11e9-836d-0fce83c60710.png)

**Comment by Jerrythemagicdog** [comment]
Fixed in 11154
