### ISSUE TITLE
Ghaz'an knockback not just applied to tail

### ISSUE THREAD

**Issue by Calebizza** [thebarrensissues/Issues#968]
**Description:**

Ghaz'an's knockback is casting infront of him 

**Current behaviour:**

Ghaz'an's knockback is currently affecting any random player, including tank

**Expected behaviour:**

This knockback ability should only affect players behind him like onyxia's tail swipe

**Steps to reproduce the problem:**

-tank Ghaz'an
-get knocked back 

**rev. hash/commit:** 

![WoWScrnShot_040119_210847](https://user-images.githubusercontent.com/48810241/55323878-13936880-54cc-11e9-889c-d492c19344f3.jpg)

**Comment by Jerrythemagicdog** [comment]
Couldn't reproduce, could you provide reproduce steps? Does it only happen if someone behind gets knocked back and it chains to the tank? Thanks!
