### ISSUE TITLE
[quest] "Arcane Disturbances" Underground Pond Reading not completable

### ISSUE THREAD

**Issue by plutonium447** [thebarrensissues/Issues#976]
**Description:**
It is impossible to finish the quest "Arcane Disturbances" because the Underground Pond Reading objective cannot be completed.

**Current behaviour:**
Attempting to use the quest item "Violet Scrying Crystal" in the correct location for the quest objective results in the error "Requires Underground Water Source".

![Screenshot from 2019-04-02 11-42-32](https://user-images.githubusercontent.com/40911527/55370054-6f95d580-553c-11e9-98f3-6aa772709d57.png)

**Expected behaviour:**
Using the quest item in the correct quest location should result in the quest objective being completed.

**Steps to reproduce the problem:**

Reference Video
https://www.youtube.com/watch?v=CZz7hYB1bd0

1. Accept "Arcane Disturbances" from NPC Archmage Alturus in front of Karazhan entrance
2. Go to 42.9, 77.9, underground in a cave (follow the video guide)
3. Go to correct quest location
4. Attempt to use the quest item
5. fail
6. cry

This issue does not affect the "Underground Well Reading" objective.

**rev. hash/commit:** 
rev. **10826**

**id's**
[quest] Arcane Disturbances (9824)
[npc] Archmage Alturus (17613)
[item] Violet Scrying Crystal (24474)
[marker] Underground Pond Credit Marker (18162)

**Comment by Jerrythemagicdog** [comment]
![image](https://user-images.githubusercontent.com/46463908/55370513-9e875980-54f2-11e9-8d4b-e2142dbf9730.png)

**Comment by qoth** [comment]
![image](https://user-images.githubusercontent.com/35262513/55370493-306a8300-5542-11e9-8c65-9769646c9d32.png)

Tested with Palladium and found it is a very small area where the quest item can be used. Should be more generous than the area it currently is.

![image](https://user-images.githubusercontent.com/35262513/55370550-5d1e9a80-5542-11e9-9bc5-722ed9af8747.png)

**Comment by qoth** [comment]
https://www.youtube.com/watch?v=CZz7hYB1bd0

**Comment by Jerrythemagicdog** [comment]
Fixed in 10829
