### ISSUE TITLE
[Quest] To Legion Hold (10563)

### ISSUE THREAD

**Issue by LoshyFirestorm** [thebarrensissues/Issues#979]
**Description:**

Quest To Legion Hold does not grant credit after discovering the plans.

**Current behaviour:**

Using the Box o' Tricks works, so does the event, but credit is not given after watching the small scripted event.

**Expected behaviour:**

Grant completion upon watching the small scripted event while under the buff Box o' Tricks.

**Steps to reproduce the problem:**

CHANGEME
1. Pick up the quest and head to the quest area
2. Use Box o' Tricks to start the small scripted event
3. Don't receive credit after the scripted event ends and the buff drops.

**rev. hash/commit:** 

![ServerInfo20419](https://user-images.githubusercontent.com/43313533/55388290-590c7000-5576-11e9-8a0b-44521f889dd7.png)

**Comment by kelno** [comment]
Fixed with 10847
