### ISSUE TITLE
[Dungeon] Old Hillsbrad - Thrall is too fast

### ISSUE THREAD

**Issue by BarrensJerk** [thebarrensissues/Issues#981]
**Description:**

After talking to Thrall to begin his escort leaving the cell, he runs very very quickly, not leaving enough time to drink, resurrect, or anything else in between his pulls.

**Current behaviour:**

His movement speed is too high, not leaving enough time between pulls.

**Expected behaviour:**

He should walk 

**Steps to reproduce the problem:**

Do the dungeon. Start the escort from his dungeon. 

**rev. hash/commit:** 

10826

**Comment by kelno** [comment]
Maybe related to https://github.com/thebarrensissues/Issues/issues/835 as well

**Comment by Calebizza** [comment]
Have also noticed that all orc mobs seem to have a high movement speed (eg when running away)
This could be related?

**Comment by Cheelout** [comment]
This is fixed.

**Comment by kelno** [comment]
@Calebizza Not related to orc but there is an issue with all fleeing running speed
