### ISSUE TITLE
[Alchemy] Mad Alchemist Potion

### ISSUE THREAD

**Issue by Deatherapy** [thebarrensissues/Issues#988]
Current behaviour:

None of the master alchemists are able to teach Mad Alchemist Potion

Expected behaviour:

It is one of the main recipes that can be taught via trainer

http://db.hellfire-tbc.com/?spell=45061 Recipe
http://db.hellfire-tbc.com/?npc=19052#starts Lorokeem
http://db.hellfire-tbc.com/?npc=18802 Alchemist Gribble
http://db.hellfire-tbc.com/?npc=16588 Apothercary Antonivich

Steps to reproduce the problem:

Be 300 Alchemist and speak to one of the outland master alchemists

rev. hash/commit:

rev 10843

**Comment by Deatherapy** [comment]
Never mind, this is added in 2.3

**Comment by Jerrythemagicdog** [comment]
Indeed, that's what it's currently set to.
