### ISSUE TITLE
[Quest] Trial of the Naaru: Magtheridon

### ISSUE THREAD

**Issue by artieau** [thebarrensissues/Issues#989]
**Description:**

The quest Trial of the Naaru: Magtheridon is part of a long chain and should be available once player has progressed through that chain only.

**Current behaviour:**

The quest is available at A'dal without completing any prior chain requirement.
http://db.hellfire-tbc.com/?quest=10888

**Expected behaviour:**

Part of a long chain and should be only be available once prior long chain is complete.

**Steps to reproduce the problem:**

1. Visit A'dal in Shatt
2. Accept quest

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/40563134/55439202-92cd8d00-55ef-11e9-9aa9-057f9ce7fef5.png)

**Comment by Jerrythemagicdog** [comment]
Fixed in 10844
