### ISSUE TITLE
[Quest] A Not So Modest proposal (10270)

### ISSUE THREAD

**Issue by BarrensJerk** [thebarrensissues/Issues#990]
**Description:**

Quest cannot be completed

**Current behaviour:**

After picking up quest item, cannot activate teleporter with the quest item in bags. You get a cast bar on the teleporter, but no gossip item to activate it once cast interaction bar completes

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

There should be a gossip option to make the image of Wind Trader Marid (20518) appear. You can then hand the quest into him.

**rev. hash/commit:** 

10843

**Comment by Jerrythemagicdog** [comment]
Fixed in 10844
