### ISSUE TITLE
Botanica

### ISSUE THREAD

**Issue by Paralol** [thebarrensissues/Issues#991]
**Description:**

Multiple issues

**Current behaviour:**

1.  All trash is hitting excessively hard.
2. Large groups of trash are respawning in a matter of minutes.
3. High Botanist Freywinn, Frayer Protectors are spawning and moving way too fast and instantly killing the healer. https://www.youtube.com/watch?v=C_qoQ4ghpL4 @ 10:20 The adds should appear and be inactive for 1 second before acquiring a target and attacking.

**Expected behaviour:**

None of the above

**Steps to reproduce the problem:**

1. Run the instance

**rev. hash/commit:** 

![image](https://user-images.githubusercontent.com/4516769/55448947-1b0e5b00-560d-11e9-87a2-e171085895d2.png)

**Comment by plutonium447** [comment]
Could not replicate behaviour 1. and 3., in a recent run on the same revision.
High Botanist Freywinn appears to work correctly and trash damage appears halfway correctly tuned.

Some types of mobs do appear to respawn on a 5m timer however, like:

Bloodwarder Mender (19633) http://db.hellfire-tbc.com/?npc=19633
Bloodwarder Protector (17993) http://db.hellfire-tbc.com/?npc=17993
Sunseeker Botantist (18422) http://db.hellfire-tbc.com/?npc=18422

there may be others but those are the ones i remember

**Comment by Jerrythemagicdog** [comment]
Can't reproduce 1, 2 is fixed in 10851, 3 is an inactivity timer yet to be implemented (https://github.com/thebarrensissues/Issues/issues/57). 
Thanks for all the missing info Palladium!

**Comment by kelno** [comment]
Fixed
