### ISSUE TITLE
Warchief Kargath Bladefist OP

### ISSUE THREAD

**Issue by jinbe88** [thebarrensissues/Issues#992]
**Description:**

seems to be too many adds spawning with the boss on normal difficulty, either extra ones that aren't meant to spawn at all and/or extra 

**Current behaviour:**

about 10 mobs spawn from the stairs about 30 seconds into the fight
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

im guessing that only 2 are meant to spawn at a time

**Steps to reproduce the problem:**

CHANGEME
1. Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead-like page.  
2. Step 2
3. Step 3

Be very specific here! Even if the problem seems general, do tell which spells did you use, on what creature, in which conditions. (Very often the problem is only happening in a specific context)

**rev. hash/commit:** 

CHANGEME
Do a `.server info` in game and copy/screenshot the first line.  
For example: `Sunstrider rev. 10455 2019-01-09 11:31:41 +0100 (my branch) (Win64, RelWithDebInfo, Static) (worldserver)`

**Comment by Jerrythemagicdog** [comment]
https://wow.gamepedia.com/Warchief_Kargath_Bladefist

> At the start of the fight, pairs of stealthed elite assassins (identical to the ones that attack you in the last hallway) spawn near the bottom of the stairs on both sides of his cage. These assassins will not aggro unless a player gets too close to the bottom of the stairs. Thus, it is very important for all members of the party to stay no more than two steps from the cage. 

And the Guards mentioned in there as well.

**Comment by Jerrythemagicdog** [comment]
Maybe related https://github.com/thebarrensissues/Issues/issues/835

**Comment by Jerrythemagicdog** [comment]
Please retest after the "3 seconds bug" is gone.
