### ISSUE TITLE
[Quest] Finding the Survivors

### ISSUE THREAD

**Issue by dinkletron** [thebarrensissues/Issues#996]
**Description:**

Upon releasing the Mag'har Prisoner's from their cage, the player doesn't receive credit.

**Current behaviour:**

Upon releasing the Mag'har Prisoner's from their cage, the player doesn't receive credit.

**Expected behaviour:**

The player should receive credit for releasing the prisoner - some cages have more than others in them.

**Steps to reproduce the problem:**

1) Get key from surrounding Ogres.
2) Open cage

**rev. hash/commit:** 

10843

**id's**
[quest] Finding the Survivors (9948) http://db.hellfire-tbc.com/?quest=9948
[npc] Mag'har Prisoner (18428) http://db.hellfire-tbc.com/?npc=18428

**Comment by plutonium447** [comment]
added id's and links

**Comment by kelno** [comment]
Fixed with 11145 (by woiwoz)
