### ISSUE TITLE
Normal mode Exarch Maladaar incorrect health and level values.

### ISSUE THREAD

**Issue by giveusmez** [thebarrensissues/Issues#998]
**Description:**
Normal mode Auchenai Crypts last boss Exarch Maladaar has incorrect health and level values.

**Current behaviour:**
Exarch Maladaar has the health and level of his heroic counterpart.
![unknown](https://user-images.githubusercontent.com/40911527/55484654-3fe5eb00-566c-11e9-9721-12f15020e6c2.png)
**Current values seen**
Health values seen: **131,637**
NPC Level seen: **72**

**Expected behaviour:**
Exarch Maladaar has normal mode health and level in normal mode Auchenai Crypts.

The normal mode version of this boss should only have **83,490** HP and be level **68**.
The heroic mode version of this boss should have **131,489** HP and be level **72**

**Steps to reproduce the problem:**
Go to Auchenai Crypts with the difficulty set to normal and walk to last boss room.

**id's**
[npc] Exarch Maladaar (18373) (Normal Mode) http://db.hellfire-tbc.com/?npc=18373
[npc] Exarch Maladaar (20306) (Heroic Mode) http://db.hellfire-tbc.com/?npc=20306

rev. **10843**

**Comment by plutonium447** [comment]
Edited op's post to have more detail

**Comment by kelno** [comment]
Thanks Pala

**Comment by Jerrythemagicdog** [comment]
Fixed in 10845
