### ISSUE TITLE
unbridled wrath no rage from abilities

### ISSUE THREAD

**Issue by oj449** [thebarrensissues/Issues#999]
**Description:**
unbridled wrath bug - no rage from abilities
**Current behaviour:**
when you deal damage with an ability as a warrior you don't get rage from the talent unbridled wrath

**Expected behaviour:**
any melee damage dealt should have a chance of giving 1 rage, not just white autos, as the tooltip states
**Steps to reproduce the problem:**
1. attack with abilities and watch rage gain, pref use a slow weapon as it has a higher proc rate, and try using melee damaging abilities that don't give rage to see it correctly.

http://db.hellfire-tbc.com/?spell=13002

rev. **10843**

**Comment by plutonium447** [comment]
added revision and link
